Repository pingcap/tidb-operator, pull requests merged in 2019-09, with the labels that each got.

#791 add kind cluster create script
  docs/CONTRIBUTING.md
  hack/kind-cluster-build.sh
Labels: CI

#830 pkg/manager/member: Fix setting StatefulSet partition bug
  pkg/manager/member/pd_upgrader.go
  pkg/manager/member/pd_upgrader_test.go
  pkg/manager/member/tidb_upgrader.go
  pkg/manager/member/tidb_upgrader_test.go
  pkg/manager/member/tikv_upgrader.go
  pkg/manager/member/tikv_upgrader_test.go
Labels: needs-cherry-pick-1.0

#750 Add basic TLS support for TiDB cluster
  charts/tidb-cluster/templates/_helpers.tpl
  charts/tidb-cluster/templates/discovery-deployment.yaml
  charts/tidb-cluster/templates/scripts/_start_pd.sh.tpl
  charts/tidb-cluster/templates/scripts/_start_tikv.sh.tpl
  charts/tidb-cluster/templates/tidb-cluster.yaml
  charts/tidb-cluster/values.yaml
  charts/tidb-operator/templates/controller-manager-deployment.yaml
  pkg/apis/pingcap.com/v1alpha1/tidbcluster.go
  pkg/apis/pingcap.com/v1alpha1/types.go
  pkg/controller/pd_control.go
  pkg/controller/pod_control.go
  pkg/controller/tidb_control.go
  pkg/discovery/discovery.go
  pkg/httputil/httputil.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tikv_member_manager.go
  pkg/manager/member/tikv_upgrader.go
  pkg/pdapi/pdapi.go
  pkg/pdapi/pdapi_test.go
  tests/actions.go
  tests/failover.go
  tests/pkg/webhook/pods.go
Labels: enhancement

#878 fix some orphan pods cleaner bugs
  cmd/controller-manager/main.go
  pkg/controller/backup/backup_controller.go
  pkg/controller/backupschedule/backup_schedule_controller.go
  pkg/controller/pod_control.go
  pkg/controller/restore/restore_controller.go
  pkg/controller/tidbcluster/tidb_cluster_controller.go
  pkg/manager/member/orphan_pods_cleaner.go
  pkg/manager/member/orphan_pods_cleaner_test.go
Labels: needs-cherry-pick-1.0

#886 fix the problem that admission controller can't get tidbcluster correctly
  pkg/controller/controller_utils.go
  pkg/controller/controller_utils_test.go
  pkg/webhook/statefulset/statefulset.go
Labels: needs-cherry-pick-1.0

#803 Add stability test for multiple drainers and reparo restore
  charts/tidb-drainer/values.yaml
  go.mod
  tests/actions.go
  tests/backup.go
  tests/cluster_info.go
  tests/cmd/e2e/main.go
  tests/cmd/stability/main.go
  tests/config.go
  tests/drainer_info.go
  tests/pkg/util/db.go
  tests/util.go
Labels: stability-tests

#779 add tidb permit host option
  charts/tidb-cluster/templates/scripts/_initialize_tidb_users.py.tpl
  charts/tidb-cluster/templates/tidb-initializer-job.yaml
  charts/tidb-cluster/values.yaml
Labels: needs-cherry-pick-1.0

#790 Clean pod schedule annotation
  pkg/controller/tidbcluster/tidb_cluster_control.go
  pkg/controller/tidbcluster/tidb_cluster_control_test.go
  pkg/controller/tidbcluster/tidb_cluster_controller.go
  pkg/controller/tidbcluster/tidb_cluster_controller_test.go
  pkg/manager/member/pvc_cleaner.go
  pkg/manager/member/pvc_cleaner_test.go
  pkg/scheduler/predicates/ha.go
  tests/actions.go
Labels: needs-cherry-pick-1.0

#907 by default, don't give montior any cross-namespace access
  charts/tidb-cluster/templates/config/_prometheus-config.tpl
  charts/tidb-cluster/templates/monitor-rbac.yaml
  charts/tidb-cluster/values.yaml
Labels: type/1.1 cherry-pick

#787 release v1.0.1
  CHANGELOG.md
  charts/tidb-cluster/values.yaml
  charts/tidb-operator/values.yaml
  deploy/aliyun/variables.tf
  deploy/aws/variables.tf
  deploy/gcp/variables.tf
  deploy/modules/aliyun/tidb-cluster/variable.tf
  deploy/modules/aliyun/tidb-operator/variables.tf
  deploy/modules/aws/tidb-cluster/variables.tf
  deploy/modules/aws/tidb-operator/variables.tf
  deploy/modules/gcp/tidb-cluster/variables.tf
  deploy/modules/gcp/tidb-operator/variables.tf
  deploy/modules/share/tidb-cluster-release/variables.tf
  tests/manifests/stability/stability.yaml
Labels: needs-cherry-pick-1.0

#926 add provider and module versions for aws
  deploy/aws/aws-tutorial.tfvars
  deploy/aws/versions.tf
  deploy/modules/aws/tidb-operator/main.tf
Labels: needs-cherry-pick-1.0

#939 Fix drainer misconfiguration
  charts/tidb-cluster/values.yaml
  tests/actions.go
Labels: needs-cherry-pick-1.0

#947 Set the default externalTrafficPolicy to be Local for TiDB service
  deploy/modules/aliyun/tidb-cluster/values/default.yaml
  deploy/modules/aws/tidb-cluster/values/default.yaml
  deploy/modules/gcp/tidb-cluster/values/default.yaml
Labels: needs-cherry-pick-1.0

#911 chart: Add note about setting pv reclaim policy to retain
  charts/tidb-cluster/values.yaml
Labels: needs-cherry-pick-1.0

#964 Fix backup restore
  cmd/backup-manager/app/backup/backup.go
  cmd/backup-manager/app/backup/manager.go
  cmd/backup-manager/app/restore/manager.go
  cmd/backup-manager/app/restore/restore.go
  manifests/backup/backup.yaml
  manifests/backup/restore.yaml
  pkg/apis/pingcap.com/v1alpha1/types.go
  pkg/backup/backup/backup_manager.go
  pkg/backup/restore/restore_manager.go
  pkg/backup/util/util.go
Labels: type/1.1 cherry-pick

#959 Add provider versions constraint for GCP and Aliyun and support values file customization for tidb-operator and tidb-cluster
  deploy/aliyun/versions.tf
  deploy/gcp/main.tf
  deploy/gcp/tidbclusters.tf
  deploy/gcp/variables.tf
  deploy/gcp/versions.tf
Labels: bug, needs-cherry-pick-1.0

#912 fix tidb-operator crash when user modify sts upgrade strategy improperly
  pkg/manager/member/pd_scaler_test.go
  pkg/manager/member/pd_upgrader.go
  pkg/manager/member/pd_upgrader_test.go
  pkg/manager/member/tidb_upgrader.go
  pkg/manager/member/tidb_upgrader_test.go
  pkg/manager/member/tikv_scaler_test.go
  pkg/manager/member/tikv_upgrader.go
  pkg/manager/member/tikv_upgrader_test.go
Labels: needs-cherry-pick-1.0

#885 Monitoring: Add Node & Pod info in TiDB Grafana
  charts/tidb-cluster/templates/config/_grafana-datasource.tpl
  charts/tidb-cluster/templates/monitor-configmap.yaml
  charts/tidb-cluster/templates/monitor-deployment.yaml
  charts/tidb-cluster/values.yaml
  tests/actions.go
Labels: type/1.1 cherry-pick

#965 add maxFailoverCount limit to TiKV
  charts/tidb-cluster/templates/tidb-cluster.yaml
  charts/tidb-cluster/values.yaml
  go.mod
  go.sum
  images/tidb-operator-e2e/tidb-cluster-values.yaml
  pkg/apis/pingcap.com/v1alpha1/types.go
  pkg/manager/member/tidb_failover.go
  pkg/manager/member/tikv_failover.go
  pkg/manager/member/tikv_failover_test.go
Labels: bug, needs-cherry-pick-1.0
