Repository pingcap/tidb-operator, pull requests merged in 2019-12, with the labels that each got.

#1251 Add recommended affinity setting for tidb and pump in note
  charts/tidb-cluster/values.yaml
Labels: status/LGTM2

#1250 Simplify the params for pod webhook
  pkg/webhook/pod/pd_deleter.go
  pkg/webhook/pod/pd_deleter_test.go
  pkg/webhook/pod/pods.go
  pkg/webhook/pod/tikv_deleter.go
  pkg/webhook/pod/tikv_deleter_test.go
  pkg/webhook/pod/util.go
Labels: area/webhook

#1287 [host network] keep backward compatibility in release-1.0
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tikv_member_manager.go
Labels: status/LGTM1

#1265 Fixed a bug that changed tikv-gc-time during full backup
  cmd/backup-manager/app/backup/manager.go
  cmd/backup-manager/app/constants/constants.go
Labels: area/backup

#1295 release v1.0.5
  CHANGELOG.md
  charts/tidb-cluster/values.yaml
  charts/tidb-operator/values.yaml
  deploy/aliyun/variables.tf
  deploy/aws/variables.tf
  deploy/gcp/variables.tf
  deploy/modules/aliyun/tidb-cluster/variables.tf
  deploy/modules/aliyun/tidb-operator/variables.tf
  deploy/modules/aws/tidb-cluster/variables.tf
  deploy/modules/aws/tidb-operator/variables.tf
  deploy/modules/gcp/tidb-cluster/variables.tf
  deploy/modules/gcp/tidb-operator/variables.tf
  deploy/modules/share/tidb-cluster-release/variables.tf
  tests/manifests/stability/stability.yaml
Labels: status/PTAL

#1288 Make webhook as apiservice server
  Makefile
  cmd/admission-controller/main.go
  cmd/admission-webhook/main.go
  go.mod
  go.sum
  images/tidb-operator/Dockerfile
  manifests/create-cert.sh
  manifests/patch-ca.sh
  manifests/patch-e2e.sh
  manifests/webhook.yaml
  pkg/webhook/pod/pd_deleter.go
  pkg/webhook/pod/pd_deleter_test.go
  pkg/webhook/pod/pods.go
  pkg/webhook/pod/pods_test.go
  pkg/webhook/pod/tikv_creater.go
  pkg/webhook/pod/tikv_deleter.go
  pkg/webhook/pod/tikv_deleter_test.go
  pkg/webhook/pod_admission_hooks.go
  pkg/webhook/route.go
  pkg/webhook/statefulset/statefulset.go
  pkg/webhook/statefulset_admission_hooks.go
  pkg/webhook/util/util.go
  pkg/webhook/webhook.go
  tests/actions.go
Labels: area/webhook, status/LGTM1

#1291 sync tidb configmap in controller
  cmd/controller-manager/main.go
  go.mod
  go.sum
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/controller/configmap_control.go
  pkg/controller/configmap_control_test.go
  pkg/controller/controller_utils.go
  pkg/controller/generic_control.go
  pkg/controller/generic_control_test.go
  pkg/controller/tidbcluster/tidb_cluster_controller.go
  pkg/controller/tidbcluster/tidb_cluster_controller_test.go
  pkg/manager/member/pump_member_manager.go
  pkg/manager/member/pump_member_manager_test.go
  pkg/manager/member/template.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tidb_member_manager_test.go
  pkg/manager/member/utils.go
  pkg/manager/member/utils_test.go
  pkg/scheme/scheme.go
  pkg/util/util.go
  pkg/util/utils_test.go
  tests/e2e/tidbcluster/tidbcluster.go
Labels: status/PTAL, type/refactor

#1319 CI: remove github actions
  .github/workflows/ci.yaml
Labels: test/ci

#1304 e2e: run process outside of the cluster
  Makefile
  hack/e2e.sh
  hack/run-e2e.sh
  pkg/controller/tidb_control.go
  pkg/pdapi/pdapi.go
  pkg/pdapi/pdapi_test.go
  tests/actions.go
  tests/backup.go
  tests/cmd/blockwriter/main.go
  tests/cmd/stability/main.go
  tests/cmd/webhook/main.go
  tests/config.go
  tests/e2e/config/config.go
  tests/e2e/config/restclientgetter.go
  tests/e2e/e2e.go
  tests/e2e/tidbcluster/tidbcluster.go
  tests/e2e/tidbcluster/util.go
  tests/e2e/util/portforward/helper.go
  tests/e2e/util/portforward/portforward.go
  tests/e2e/util/proxiedpdclient/proxiedpdclient.go
  tests/e2e/util/proxiedtidbclient/proxiedtidbclient.go
  tests/failover.go
  tests/images/e2e/Dockerfile
  tests/manifests/e2e/e2e.yaml
  tests/pkg/webhook/webhook.go
Labels: CanMerge

#1345 revise apiservice webhook
  cmd/admission-webhook/main.go
  manifests/patch-e2e.sh
  manifests/webhook.yaml
  pkg/webhook/admission_hooks.go
  pkg/webhook/pod/pd_deleter.go
  pkg/webhook/pod/pd_deleter_test.go
  pkg/webhook/pod/pods.go
  pkg/webhook/pod/pods_test.go
  pkg/webhook/pod/tikv_deleter.go
  pkg/webhook/pod/tikv_deleter_test.go
  pkg/webhook/pod/tikv_util.go
  pkg/webhook/pod/util.go
  pkg/webhook/statefulset_admission_hooks.go
  tests/actions.go
Labels: area/webhook, status/PTAL

#1354 Add apiserver admission webhook template
  charts/tidb-operator/templates/admission/admission-webhook-deployment.yaml
  charts/tidb-operator/templates/admission/admission-webhook-rbac.yaml
  charts/tidb-operator/templates/admission/admission-webhook-registration.yaml
  charts/tidb-operator/templates/admission/admission-webhook-secret.yaml
  charts/tidb-operator/templates/admission/admission-webhook-service.yaml
  charts/tidb-operator/templates/admission/certManager/certificate.yaml
  charts/tidb-operator/templates/admission/certManager/issuer.yaml
  charts/tidb-operator/templates/admission/jobPatch/pre-install-secret-job.yaml
  charts/tidb-operator/templates/admission/jobPatch/rbac.yaml
  charts/tidb-operator/values.yaml
Labels: status/PTAL

#1377 Using admission server in e2e test instead of applying `webhook.yaml`
  charts/tidb-operator/templates/admission/admission-webhook-deployment.yaml
  charts/tidb-operator/templates/admission/admission-webhook-rbac.yaml
  charts/tidb-operator/templates/admission/admission-webhook-registration.yaml
  charts/tidb-operator/templates/admission/admission-webhook-secret.yaml
  charts/tidb-operator/templates/admission/admission-webhook-service.yaml
  charts/tidb-operator/values.yaml
  manifests/patch-e2e.sh
  manifests/webhook.yaml
  tests/actions.go
  tests/cmd/stability/main.go
  tests/e2e/config/config.go
  tests/e2e/tidbcluster/tidbcluster.go
  tests/webhook.go
Labels: area/webhook, status/PTAL, test/e2e

#1388 Add missing TiKV config
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tikv_config.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
Labels: CanMerge, area/api

#1386 add ephemeral-storage resources and make QOS guaranteed
  ci/pingcap_tidb_operator_build_kind.groovy
Labels: CanMerge

#1292 Sync pump status to tidb-cluster.
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/tidbcluster/tidb_cluster_controller.go
  pkg/manager/member/pump_member_manager.go
  pkg/manager/member/pump_member_manager_test.go
Labels: CanMerge, contribution

#1355 binding clusterrole system:kube-scheduler to sa tidb-scheduler
  charts/tidb-operator/templates/scheduler-rbac.yaml
Labels: contribution

#1394 config: add openapi-gen in tikv cofigurations
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tikv_config.go
Labels: CanMerge

#1385 Automated cherry pick of #885: Monitoring: add node and pod information in tidb cluster
  charts/tidb-cluster/templates/config/_grafana-datasource.tpl
  charts/tidb-cluster/templates/monitor-configmap.yaml
  charts/tidb-cluster/templates/monitor-deployment.yaml
  charts/tidb-cluster/values.yaml
  tests/actions.go
Labels: CanMerge

#1373 scheduler: refine scheduler error message
  pkg/scheduler/predicates/ha.go
  pkg/scheduler/predicates/ha_test.go
  pkg/scheduler/predicates/stable_scheduling.go
  pkg/scheduler/predicates/stable_scheduling_test.go
  pkg/scheduler/predicates/test_helper.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
Labels: CanMerge, status/LGTM1, status/PTAL

#1284 Expose and set default terraform aliyun ACK version.
  deploy/modules/aliyun/tidb-operator/main.tf
  deploy/modules/aliyun/tidb-operator/variables.tf
Labels: CanMerge, area/terraform

#1383 Automated cherry pick of #898: Monitoring: change rules persistence
  charts/tidb-cluster/templates/monitor-deployment.yaml
  charts/tidb-cluster/values.yaml
Labels: CanMerge

#1396 e2e case of operating tidb-cluster without helm
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tikv_config.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/controller_utils.go
  pkg/manager/member/tikv_member_manager_test.go
  tests/actions.go
  tests/e2e/tidbcluster/tidbcluster.go
  tests/pkg/fixture/fixture.go
Labels: CanMerge

#1389 Add webhook switch for tidb-controller-manager
  charts/tidb-operator/templates/admission/pre-delete-job.yaml
  charts/tidb-operator/templates/controller-manager-deployment.yaml
  charts/tidb-operator/values.yaml
  cmd/controller-manager/main.go
  pkg/controller/controller_utils.go
  pkg/manager/member/pd_scaler.go
  pkg/manager/member/pd_upgrader.go
  pkg/manager/member/tikv_scaler.go
  pkg/manager/member/tikv_upgrader.go
  tests/e2e/tidbcluster/serial.go
Labels: CanMerge, area/controller, area/webhook, status/PTAL, test/e2e

#1415 fix error importer config
  charts/tidb-cluster/values.yaml
Labels: CanMerge, type/bug

#1410 ci: add k8s v1.17 support
  charts/tidb-operator/templates/scheduler-rbac.yaml
  ci/pingcap_tidb_operator_build_kind.groovy
  hack/e2e.sh
Labels: CanMerge

#1401 fix stability test blockwriter image
  tests/config.go
Labels: contribution

#1403 add controller for tidb initializer
  cmd/controller-manager/main.go
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/register.go
  pkg/apis/pingcap/v1alpha1/tidbinitializer.go
  pkg/apis/pingcap/v1alpha1/tidbinitializer_types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/controller_utils.go
  pkg/controller/generic_control.go
  pkg/controller/tidbinitializer/tidb_initializer_control.go
  pkg/controller/tidbinitializer/tidb_initializer_controller.go
  pkg/label/label.go
  pkg/manager/member/template.go
  pkg/manager/member/tidb_init_manager.go
Labels: CanMerge

#1423 Automated cherry pick of #1355: binding clusterrole system:kube-scheduler to sa
  charts/tidb-operator/templates/scheduler-rbac.yaml
Labels: CanMerge, contribution

#1419 make controller logic independable with certain tidbcluster label
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/manager/member/orphan_pods_cleaner.go
  pkg/manager/member/orphan_pods_cleaner_test.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/pd_member_manager_test.go
  pkg/manager/member/pump_member_manager.go
  pkg/manager/member/pump_member_manager_test.go
  pkg/manager/member/pvc_cleaner.go
  pkg/manager/member/pvc_cleaner_test.go
  pkg/manager/member/tidb_discovery_manager.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tidb_member_manager_test.go
  pkg/manager/member/tikv_member_manager.go
  pkg/manager/member/tikv_member_manager_test.go
  pkg/manager/meta/meta_manager.go
  pkg/manager/meta/meta_manager_test.go
  pkg/manager/meta/reclaim_policy_manager.go
Labels: CanMerge

#1382 replace corev1.Services type with ServiceType and rm useless code
  charts/tidb-cluster/templates/tidb-cluster.yaml
  charts/tidb-cluster/values.yaml
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/pd_member_manager_test.go
  pkg/manager/member/tidb_member_manager.go
Labels: CanMerge, contribution

#1411 Add default behavior in config field description
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/pd_config.go
  pkg/apis/pingcap/v1alpha1/tidb_config.go
  pkg/apis/pingcap/v1alpha1/tidb_config_test.go
  pkg/apis/pingcap/v1alpha1/tikv_config.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tidb_member_manager_test.go
  tests/pkg/fixture/fixture.go
Labels: CanMerge

#1412 check newline at end of file
  Makefile
  charts/tidb-drainer/templates/NOTES.txt
  deploy/aliyun/my-cluster.yaml
  deploy/aws/.gitignore
  deploy/aws/default-cluster.yaml
  deploy/gcp/prod.tfvars
  deploy/gcp/small.tfvars
  deploy/modules/aliyun/bastion/bastion-userdata
  deploy/modules/aliyun/bastion/bastion.tf
  deploy/modules/aliyun/tidb-cluster/local.tf
  deploy/modules/aliyun/tidb-cluster/outputs.tf
  deploy/modules/aliyun/tidb-cluster/values/default.yaml
  deploy/modules/aliyun/tidb-cluster/workers.tf
  deploy/modules/aliyun/tidb-operator/templates/local-volume-provisioner.yaml.tpl
  deploy/modules/aws/tidb-cluster/pre_userdata
  deploy/modules/aws/tidb-operator/outputs.tf
  hack/check-EOF.sh
  misc/images/debug-launcher/entry-point.sh
  misc/images/tidb-debug/Dockerfile
  misc/images/tidb-debug/run_flamegraph.sh
  tests/manifests/fault-trigger/fault-trigger.service
Labels: CanMerge, contribution

#1436 remove GO111MODULEON=off in codegen.sh
  hack/codegen.sh
Labels: CanMerge

#1361 able to scale in/out with delete slots feature
  charts/tidb-operator/templates/advanced-statefulset-rbac.yaml
  charts/tidb-operator/values.yaml
  cmd/controller-manager/main.go
  go.mod
  go.sum
  manifests/advanced-statefulset-crd.v1.yaml
  manifests/advanced-statefulset-crd.v1beta1.yaml
  pkg/apis/pingcap/v1alpha1/validation/validation.go
  pkg/apis/pingcap/v1alpha1/validation/validation_test.go
  pkg/controller/tidb_control.go
  pkg/controller/tidbcluster/tidb_cluster_control.go
  pkg/features/features.go
  pkg/label/label.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/pd_member_manager_test.go
  pkg/manager/member/pd_scaler.go
  pkg/manager/member/scaler.go
  pkg/manager/member/scaler_test.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tidb_member_manager_test.go
  pkg/manager/member/tikv_member_manager.go
  pkg/manager/member/tikv_member_manager_test.go
  pkg/manager/member/tikv_scaler.go
  pkg/manager/member/tikv_upgrader.go
  pkg/manager/member/utils.go
  pkg/manager/member/utils_test.go
  pkg/util/util.go
  pkg/util/utils_test.go
  pkg/webhook/admission_hooks.go
  pkg/webhook/pod/pd_deleter.go
  pkg/webhook/pod/tikv_deleter.go
  pkg/webhook/statefulset/statefulset.go
  tests/actions.go
  tests/e2e/tidbcluster/serial.go
  tests/e2e/util/discovery/discovery.go
  tests/e2e/util/proxiedtidbclient/proxiedtidbclient.go
  tests/e2e/util/statefulset/statefulset.go
Labels: CanMerge

#1425 Add TidbMonitor Controller
  cmd/controller-manager/main.go
  pkg/apis/pingcap/v1alpha1/register.go
  pkg/controller/controller_utils.go
  pkg/controller/generic_control.go
  pkg/controller/tidbmonitor/tidb_monitor_control.go
  pkg/controller/tidbmonitor/tidb_monitor_controller.go
  pkg/label/label.go
  pkg/monitor/monitor.go
  pkg/monitor/monitor/monitor_manager.go
  pkg/monitor/monitor/template.go
  pkg/monitor/monitor/util.go
Labels: CanMerge, area/controller, status/PTAL

#1435 update docs/CONTRIBUTING.md and more help information
  docs/CONTRIBUTING.md
  hack/e2e.sh
  hack/run-e2e.sh
  hack/run-in-container.sh
  tests/e2e/e2e.go
Labels: CanMerge

#1429 add basic defaulting and validating for tidbcluster
  charts/tidb-operator/templates/admission/admission-webhook-rbac.yaml
  charts/tidb-operator/templates/admission/admission-webhook-registration.yaml
  charts/tidb-operator/values.yaml
  go.mod
  go.sum
  pkg/apis/pingcap/v1alpha1/defaulting/tidbcluster.go
  pkg/apis/pingcap/v1alpha1/validation/validation.go
  pkg/apis/pingcap/v1alpha1/validation/validation_test.go
  pkg/controller/controller_utils.go
  pkg/controller/tidbcluster/tidb_cluster_control_test.go
  pkg/registry/registry.go
  pkg/registry/strategy.go
  pkg/registry/tidbcluster_strategy.go
  pkg/webhook/admission_hooks.go
  pkg/webhook/strategy/registry.go
  pkg/webhook/strategy/webhook.go
  pkg/webhook/strategy/webhook_test.go
  pkg/webhook/util/util.go
  tests/actions.go
  tests/cmd/stability/main.go
  tests/e2e/config/config.go
  tests/e2e/tidbcluster/serial.go
  tests/util.go
Labels: CanMerge, status/PTAL

#1446 fix tidb-controller rbac bug
  charts/tidb-operator/templates/controller-manager-rbac.yaml
  pkg/monitor/monitor/monitor_manager.go
  pkg/monitor/monitor/util.go
Labels: CanMerge

#1414 avoid trigger rolling-update when template is actually not changed
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/pd_upgrader.go
  pkg/manager/member/pd_upgrader_test.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tidb_upgrader.go
  pkg/manager/member/tidb_upgrader_test.go
  pkg/manager/member/tikv_member_manager.go
  pkg/manager/member/tikv_upgrader.go
  pkg/manager/member/tikv_upgrader_test.go
  pkg/manager/member/utils.go
Labels: CanMerge

#1409 refactor the tidbcluster type definition in favor of defaulting
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/apis/pingcap/v1alpha1/tidbcluster_component.go
  pkg/apis/pingcap/v1alpha1/tidbcluster_test.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/validation/validation_test.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/pd_control.go
  pkg/controller/pod_control.go
  pkg/controller/tidb_control.go
  pkg/controller/tidbcluster/tidb_cluster_control_test.go
  pkg/discovery/discovery.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/pd_member_manager_test.go
  pkg/manager/member/pd_upgrader_test.go
  pkg/manager/member/pump_member_manager.go
  pkg/manager/member/pump_member_manager_test.go
  pkg/manager/member/pvc_cleaner.go
  pkg/manager/member/tidb_failover.go
  pkg/manager/member/tidb_failover_test.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tidb_member_manager_test.go
  pkg/manager/member/tidb_upgrader_test.go
  pkg/manager/member/tikv_failover.go
  pkg/manager/member/tikv_failover_test.go
  pkg/manager/member/tikv_member_manager.go
  pkg/manager/member/tikv_member_manager_test.go
  pkg/manager/member/tikv_upgrader.go
  pkg/manager/member/tikv_upgrader_test.go
  pkg/manager/meta/reclaim_policy_manager.go
  pkg/manager/meta/reclaim_policy_manager_test.go
  pkg/monitor/monitor/util.go
  pkg/tkctl/cmd/info/info.go
  pkg/tkctl/cmd/upinfo/upinfo.go
  pkg/webhook/pod/pods.go
  pkg/webhook/pod/pods_test.go
  tests/actions.go
  tests/e2e/tidbcluster/serial.go
  tests/e2e/tidbcluster/tidbcluster.go
  tests/e2e/util/proxiedpdclient/proxiedpdclient.go
  tests/e2e/util/proxiedtidbclient/proxiedtidbclient.go
  tests/failover.go
  tests/pkg/fixture/fixture.go
  tests/pkg/webhook/pods.go
Labels: CanMerge

#1454 fix pd client tls and use table driven tests to cover tls case
  go.mod
  pkg/httputil/httputil.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/tidb_member_manager.go
  pkg/pdapi/pdapi.go
  tests/actions.go
  tests/e2e/tidbcluster/tidbcluster.go
  tests/e2e/util/proxiedpdclient/proxiedpdclient.go
  tests/e2e/util/proxiedtidbclient/proxiedtidbclient.go
Labels: CanMerge
