Repository pingcap/tidb-operator, pull requests merged in 2019-07, with the labels that each got.

#610 separate slow log with tidb server log by default
  charts/tidb-cluster/values.yaml
Labels: deploy

#616 Multiple clusters management in EKS
  deploy/aws/.gitignore
  deploy/aws/README.md
  deploy/aws/aws-key-pair/main.tf
  deploy/aws/aws-key-pair/outputs.tf
  deploy/aws/aws-key-pair/variables.tf
  deploy/aws/aws-key-pair/versions.tf
  deploy/aws/aws-tutorial.tfvars
  deploy/aws/bastion.tf
  deploy/aws/charts/tidb-cluster
  deploy/aws/charts/tidb-operator
  deploy/aws/clusters.tf
  deploy/aws/data.tf
  deploy/aws/default-cluster.yaml
  deploy/aws/main.tf
  deploy/aws/manifests/crd.yaml
  deploy/aws/manifests/tiller-rbac.yaml
  deploy/aws/outputs.tf
  deploy/aws/pd-userdata.sh
  deploy/aws/templates/tidb-cluster-values.yaml.tpl
  deploy/aws/tidb-cluster/README.md
  deploy/aws/tidb-cluster/cluster.tf
  deploy/aws/tidb-cluster/data.tf
  deploy/aws/tidb-cluster/local.tf
  deploy/aws/tidb-cluster/outputs.tf
  deploy/aws/tidb-cluster/pre_userdata
  deploy/aws/tidb-cluster/templates/userdata.sh.tpl
  deploy/aws/tidb-cluster/values/default.yaml
  deploy/aws/tidb-cluster/variables.tf
  deploy/aws/tidb-cluster/workers.tf
  deploy/aws/tidb-cluster/workers_launch_template.tf
  deploy/aws/tidb-operator/README.md
  deploy/aws/tidb-operator/main.tf
  deploy/aws/tidb-operator/manifests/gp2-storageclass.yaml
  deploy/aws/tidb-operator/manifests/local-volume-provisioner.yaml
  deploy/aws/tidb-operator/outputs.tf
  deploy/aws/tidb-operator/variables.tf
  deploy/aws/tikv-userdata.sh
  deploy/aws/variables.tf
Labels: area/terraform, deploy, doc

#631 support force upgrade when pd cluster is unavailable
  pkg/label/label.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/pd_member_manager_test.go
  pkg/manager/member/pd_upgrader.go
  pkg/manager/member/pd_upgrader_test.go
  pkg/manager/member/utils.go
Labels: bug, doc

#638 change the way to config tidb/tikv/pd in charts
  charts/tidb-cluster/templates/_helpers.tpl
  charts/tidb-cluster/templates/config/_pd-config.tpl
  charts/tidb-cluster/templates/config/_tidb-config.tpl
  charts/tidb-cluster/templates/config/_tikv-config.tpl
  charts/tidb-cluster/values.yaml
  deploy/aws/README.md
  deploy/modules/aws/tidb-cluster/values/default.yaml
  tests/actions.go
  tests/cluster_info.go
  tests/cmd/e2e/main.go
  tests/cmd/stability/stability.go
  tests/util.go
Labels: doc, enhancement

#686 Enable nlb cross zone load balancing by default
  deploy/modules/aws/tidb-cluster/values/default.yaml
Labels: tinyfix

#665 Stability cases: stop kubelet and etcd
  tests/actions.go
  tests/cmd/stability/main.go
  tests/failover.go
  tests/fault.go
Labels: stability-tests

#705 Update documents in favor of consistency
  README.md
  deploy/aliyun/variables.tf
  deploy/gcp/README.md
  deploy/modules/aliyun/tidb-cluster/variable.tf
  deploy/modules/aliyun/tidb-operator/variables.tf
  deploy/modules/aws/tidb-cluster/variables.tf
  deploy/modules/share/tidb-cluster-release/variables.tf
  docs/aliyun-tutorial.md
  docs/aws-eks-tutorial.md
  docs/backup-restore.md
  docs/cli-manual.md
  docs/google-kubernetes-tutorial.md
  docs/local-dind-tutorial.md
  docs/minikube-tutorial.md
  docs/operation-guide.md
  docs/references/tidb-backup-configuration.md
  docs/setup.md
  docs/troubleshooting.md
  docs/user-guide.md
  static/tidb-operator-overview.png
Labels: needs-cherry-pick-1.0, needs-cherry-pick-1.1

#709 changelog: update wording and fix format for v1.0.0
  CHANGELOG.md
Labels: needs-cherry-pick-1.0, needs-cherry-pick-1.1
