Repository pingcap/tidb-operator, pull requests merged in 2020-06, with the labels that each got.

#2588 Update serial case to 1.1.0 from 1.0.6
  tests/e2e/tidbcluster/serial.go
Labels: CanMerge, needs-cherry-pick-1.1

#2434 UCP: support setting discovery resources
  docs/api-references/docs.md
  examples/basic/tidb-cluster.yaml
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/member/tidb_discovery_manager.go
  pkg/manager/member/tidb_discovery_manager_test.go
  tests/e2e/tidbcluster/tidbcluster.go
Labels: contribution, needs-cherry-pick-1.1

#2545 Directly use CRD in e2e test instead of helm
  tests/crd_test_util.go
  tests/e2e/tidbcluster/tidbcluster.go
  tests/pkg/fixture/fixture.go
Labels: CanMerge, needs-cherry-pick-1.1

#2605 reduce resource requests of e2e pods
  ci/e2e_kind.groovy
  ci/pingcap_tidb_operator_build_kind.groovy
Labels: needs-cherry-pick-1.1

#2593 Fix TiKV Config Incompatibility error
  pkg/manager/member/tikv_member_manager.go
  pkg/manager/member/tikv_member_manager_test.go
Labels: CanMerge, needs-cherry-pick-1.1

#2613 e2e: clean eks/gke if job is unsuccessful
  ci/e2e_eks.groovy
  ci/e2e_gke.groovy
Labels: needs-cherry-pick-1.1

#2615 Bump dm version to v2.0.0-beta.1
  manifests/dm/master/dm-master.yaml
  manifests/dm/worker/base/dm-worker.yaml
Labels: CanMerge, needs-cherry-pick-1.1

#2616 Enrich unit tests and add comment for pd failover
  pkg/manager/member/pd_failover.go
  pkg/manager/member/pd_member_manager_test.go
Labels: CanMerge, needs-cherry-pick-1.1

#2625 use v4.0.0 in CDC e2e
  tests/e2e/tidbcluster/tidbcluster.go
  tests/e2e/util/image/image.go
Labels: needs-cherry-pick-1.1

#2628 Remove unnecessary e2e job
  ci/pingcap_tidb_operator_build_kind.groovy
Labels: needs-cherry-pick-1.1, test/e2e

#2610 UCP:Support Service LoadBalancerSourceRanges
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/validation/validation.go
  pkg/apis/pingcap/v1alpha1/validation/validation_test.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tidb_member_manager_test.go
  pkg/monitor/monitor/util.go
  pkg/monitor/monitor/util_test.go
Labels: contribution, needs-cherry-pick-1.1

#2636 Fix tidb monitor panic
  pkg/monitor/monitor/monitor_manager.go
Labels: CanMerge, needs-cherry-pick-1.1

#2607 Fix stability PD Failover check
  tests/failover.go
Labels: CanMerge, needs-cherry-pick-1.1

#2624 add detailed TiDBCluster example
  examples/advanced/tidb-cluster.yaml
Labels: CanMerge, enhancement, needs-cherry-pick-1.1

#2651 Revise Tidbmonitor e2e case
  tests/e2e/tidbcluster/tidbcluster.go
Labels: CanMerge, needs-cherry-pick-1.1

#2641 pirint the errors while failed to sync ticdc status
  pkg/manager/member/ticdc_member_manager.go
Labels: CanMerge, needs-cherry-pick-1.1

#2647 optionally set resources and priorityclass
  charts/tidb-operator/templates/controller-manager-deployment.yaml
  charts/tidb-operator/values.yaml
Labels: CanMerge, needs-cherry-pick-1.1

#2646 Fixed scheduling errors when based on zone scheduling
  pkg/scheduler/predicates/ha.go
  pkg/scheduler/predicates/ha_test.go
  pkg/scheduler/predicates/test_helper.go
Labels: CanMerge, area/scheduler, contribution

#2633 E2e CI job use memory storage for etcd
  ci/pingcap_tidb_operator_build_kind.groovy
  hack/e2e.sh
Labels: CanMerge, contribution, needs-cherry-pick-1.1

#2652 Hide datasource information for backup job
  cmd/backup-manager/app/util/util.go
Labels: CanMerge, needs-cherry-pick-1.1

#2539 Support DynamicConfiguration in feature gate
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/member/template.go
  pkg/manager/member/tikv_member_manager.go
  pkg/manager/member/tikv_member_manager_test.go
Labels: CanMerge, needs-cherry-pick-1.1

#2671 revise log for auto-scaling e2e case
  tests/e2e/tidbcluster/serial.go
Labels: CanMerge, needs-cherry-pick-1.1

#2669 Backup: fix remote file not clean when job is failed
  cmd/backup-manager/app/backup/backup.go
  cmd/backup-manager/app/backup/manager.go
  cmd/backup-manager/app/util/remote.go
  cmd/backup-manager/app/util/util.go
  pkg/apis/pingcap/v1alpha1/types.go
Labels: CanMerge

#2587 Emit an event if failed to sync labels to tikv stores
  pkg/controller/tidbcluster/tidb_cluster_controller.go
  pkg/manager/member/failover.go
  pkg/manager/member/tikv_member_manager.go
  pkg/manager/member/tikv_member_manager_test.go
Labels: CanMerge, contribution, needs-cherry-pick-1.1

#2664 Make StsWebhook and PodWebhook work
  pkg/manager/member/pd_upgrader.go
  pkg/manager/member/tikv_upgrader.go
  tests/e2e/tidbcluster/serial.go
Labels: CanMerge, needs-cherry-pick-1.1

#2661 add docs for tidb cluster pause feature
  docs/design-proposals/2020-03-23-pause-tidb-cluster.md
Labels: CanMerge

#2677 fix ha filter test is not stable
  pkg/scheduler/predicates/ha_test.go
Labels: CanMerge, contribution, needs-cherry-pick-1.1

#2658 add docs for tidbcluster conditions
  docs/design-proposals/2020-04-13-record-conditions-in-tidbcluster-status.md
Labels: CanMerge

#2679 Add imagePullSecrets attribute to all components
  charts/tidb-drainer/templates/drainer-statefulset.yaml
  charts/tidb-drainer/values.yaml
  charts/tidb-lightning/templates/job.yaml
  charts/tidb-lightning/values.yaml
  charts/tidb-operator/templates/admission/admission-webhook-deployment.yaml
  charts/tidb-operator/templates/admission/pre-delete-job.yaml
  charts/tidb-operator/templates/advanced-statefulset-deployment.yaml
  charts/tidb-operator/templates/apiserver-deployment.yaml
  charts/tidb-operator/templates/controller-manager-deployment.yaml
  charts/tidb-operator/templates/scheduler-deployment.yaml
  charts/tidb-operator/values.yaml
  charts/tikv-importer/templates/tikv-importer-statefulset.yaml
  charts/tikv-importer/values.yaml
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbcluster_component.go
  pkg/apis/pingcap/v1alpha1/tidbinitializer_types.go
  pkg/apis/pingcap/v1alpha1/tidbmonitor_types.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/backup/backup/backup_cleaner.go
  pkg/backup/backup/backup_manager.go
  pkg/backup/backupschedule/backup_schedule_manager.go
  pkg/backup/restore/restore_manager.go
  pkg/manager/member/tidb_discovery_manager.go
  pkg/manager/member/tidb_init_manager.go
  pkg/monitor/monitor/util.go
Labels: CanMerge, needs-cherry-pick-1.1

#2680 apis: add raft message config for TiKV
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tikv_config.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
Labels: CanMerge, needs-cherry-pick-1.1

#2682 Able to specify subdirectory within the volume to store TiKV data
  docs/api-references/docs.md
  examples/advanced/tidb-cluster.yaml
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/validation/validation.go
  pkg/apis/pingcap/v1alpha1/validation/validation_test.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/template.go
  pkg/manager/member/template_test.go
  pkg/manager/member/tikv_member_manager.go
  pkg/manager/member/tikv_member_manager_test.go
  tests/e2e/tidbcluster/tidbcluster.go
Labels: CanMerge, needs-cherry-pick-1.1

#2684 Add proxy server for Dashboard
  cmd/discovery/main.go
  pkg/discovery/server/proxy.go
  pkg/manager/member/tidb_discovery_manager.go
Labels: needs-cherry-pick-1.1

#2688 Explicitly avoid broken aws 2.65.0 terraform provider
  deploy/aws/versions.tf
Labels: CanMerge, needs-cherry-pick-1.1

#2701 Change tidb-discovery strategy type to `Recreate`
  charts/tidb-cluster/templates/discovery-deployment.yaml
  pkg/manager/member/tidb_discovery_manager.go
Labels: CanMerge, needs-cherry-pick-1.1

#2702 Update Configuration to v4.0.1
  docs/api-references/docs.md
  pkg/apis/pingcap/v1alpha1/pd_config.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
Labels: CanMerge, needs-cherry-pick-1.1

#2706 update binaries in backup-manager image
  images/tidb-backup-manager/Dockerfile
Labels: needs-cherry-pick-1.1

#2707 Fix labelselector error in reclaimPolicyManager
  pkg/manager/meta/reclaim_policy_manager.go
Labels: CanMerge, needs-cherry-pick-1.1

#2713 Add switch to control the Dashboard Proxy
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/member/pd_member_manager.go
Labels: CanMerge, needs-cherry-pick-1.1

#2718 Fix TidbMonitor e2e check error
  tests/monitor.go
Labels: CanMerge, needs-cherry-pick-1.1

#2714 add configurations for demo and product deployment on eks
  deploy/aws/demo.tfvars
  deploy/aws/prod.tfvars
Labels: CanMerge, needs-cherry-pick-1.1

#2717 Fix missing openapi configuration
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/pd_config.go
Labels: CanMerge, needs-cherry-pick-1.1

#2709 use the latest version object in deletion request
  pkg/controller/tidbcluster/tidb_cluster_control.go
  pkg/manager/member/orphan_pods_cleaner.go
  pkg/manager/member/orphan_pods_cleaner_test.go
  pkg/manager/member/pvc_cleaner.go
Labels: CanMerge, needs-cherry-pick-1.1

#2654 add label to identify individual services
  pkg/label/label.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/pd_member_manager_test.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tidb_member_manager_test.go
  pkg/manager/member/tiflash_member_manager_test.go
  pkg/manager/member/tikv_member_manager.go
  pkg/manager/member/tikv_member_manager_test.go
  pkg/monitor/monitor/util.go
  pkg/monitor/monitor/util_test.go
Labels: CanMerge, needs-cherry-pick-1.1, status/PTAL

#2715 Fix alert rules lost after rolling upgrade
  charts/tidb-cluster/templates/monitor-deployment.yaml
  charts/tidb-cluster/values.yaml
Labels: CanMerge, needs-cherry-pick-1.0, needs-cherry-pick-1.1

#2696 Add Heterogeneous Design Proposal
  docs/design-proposals/2020-06-12-heterogeneous-design-for-tidb-cluister.md
Labels: CanMerge, area/heterogeneous

#2727 Fix e2e auto-scaling test case
  tests/e2e/tidbcluster/serial.go
Labels: CanMerge, needs-cherry-pick-1.1

#2736 Add design proposal template
  docs/design-proposals/template.md
Labels: CanMerge

#2730 Revise e2e backup restore case
  tests/backup.go
  tests/e2e/tidbcluster/tidbcluster.go
Labels: CanMerge, needs-cherry-pick-1.1

#2738 fix following steps of install tidb-operator
  charts/tidb-operator/templates/NOTES.txt
Labels: CanMerge, needs-cherry-pick-1.1

#2744 Add alertMangerAlertVersion option to TidbMonitor
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbmonitor_types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/monitor/monitor/util.go
Labels: CanMerge, needs-cherry-pick-1.1

#2629 Use crd to manage tidbcluster in stability
  tests/actions.go
  tests/cmd/stability/main.go
  tests/crd_test_util.go
  tests/e2e/tidbcluster/serial.go
  tests/e2e/tidbcluster/tidbcluster.go
  tests/failover.go
  tests/pkg/fixture/fixture.go
  tests/pkg/ops/tikv.go
Labels: CanMerge, needs-cherry-pick-1.1

#2747 fix lightning log
  charts/tidb-lightning/templates/scripts/_start_lightning.sh.tpl
Labels: CanMerge, needs-cherry-pick-1.1

#2743 Use minimum resource requirements in basic examples
  examples/basic/tidb-cluster.yaml
Labels: CanMerge, needs-cherry-pick-1.1

#2600 Bumped image versions to v4.0.0
  charts/tidb-cluster/values.yaml
  charts/tidb-drainer/values.yaml
  charts/tidb-lightning/values.yaml
  charts/tikv-importer/values.yaml
  deploy/aliyun/manifests/db-monitor.yaml.example
  deploy/aliyun/manifests/db.yaml.example
  deploy/aliyun/variables.tf
  deploy/aws/manifests/db-monitor.yaml.example
  deploy/aws/manifests/db.yaml.example
  deploy/aws/variables.tf
  deploy/gcp/manifests/db-monitor.yaml.example
  deploy/gcp/manifests/db.yaml.example
  deploy/gcp/variables.tf
  deploy/modules/aliyun/tidb-cluster/variables.tf
  deploy/modules/aws/tidb-cluster/variables.tf
  deploy/modules/gcp/tidb-cluster/variables.tf
  deploy/modules/share/tidb-cluster-release/variables.tf
  examples/advanced-statefulset/tidb-cluster-scaled.yaml
  examples/advanced-statefulset/tidb-cluster.yaml
  examples/auto-scale/tidb-cluster.yaml
  examples/auto-scale/tidb-monitor.yaml
  examples/basic/tidb-cluster.yaml
  examples/basic/tidb-monitor.yaml
  examples/initialize/tidb-cluster.yaml
  examples/monitor-with-externalConfigMap/tidb-monitor.yaml
  examples/selfsigned-tls/tidb-cluster.yaml
  hack/e2e.sh
  manifests/monitor/tidb-monitor.yaml
  tests/actions.go
  tests/e2e/tidbcluster/tidbcluster.go
  tests/e2e/util/image/image.go
Labels: CanMerge, needs-cherry-pick-1.1

#2762 revert tidb v3 version change
  tests/e2e/util/image/image.go
Labels: needs-cherry-pick-1.1

#2746 Fix TidbMonitor ClusterRef missing error in prometheus rule
  pkg/monitor/monitor/monitor_manager.go
  pkg/monitor/monitor/util.go
Labels: CanMerge, area/monitor, needs-cherry-pick-1.1

#2712 apis: Add some missing tikv configuration
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tikv_config.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
Labels: CanMerge, needs-cherry-pick-1.1

#2705 do not scale or upgrade tikv at the same time
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/pd_member_manager_test.go
  pkg/manager/member/pd_upgrader.go
  pkg/manager/member/pd_upgrader_test.go
  pkg/manager/member/tikv_member_manager.go
  pkg/manager/member/tikv_member_manager_test.go
  pkg/manager/member/tikv_scaler.go
  pkg/manager/member/tikv_upgrader.go
  pkg/manager/member/tikv_upgrader_test.go
Labels: CanMerge, needs-cherry-pick-1.1

#2763 Move compatible filterLeaderEvictScheduler in pdapi
  pkg/pdapi/pdapi.go
  pkg/webhook/pod/tikv_creater.go
  tests/e2e/util/image/image.go
Labels: CanMerge, needs-cherry-pick-1.1

#2754 add a example that uses images in China
  examples/basic-cn/tidb-cluster.yaml
  examples/basic-cn/tidb-monitor.yaml
  tests/examples/003-basic-cn.sh
Labels: CanMerge, needs-cherry-pick-1.1

#2229 Support additional containers and volumes in TiDB cluster
  Makefile
  docs/api-references/docs.md
  hack/update-crd-groups.sh
  hack/update-openapi-spec.sh
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbcluster_component.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/pd_member_manager_test.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tidb_member_manager_test.go
  pkg/manager/member/tiflash_member_manager.go
  pkg/manager/member/tikv_member_manager.go
  pkg/manager/member/tikv_member_manager_test.go
Labels: CanMerge, contribution, needs-cherry-pick-1.1

#2772 add humanreadable backup size
  cmd/backup-manager/app/backup/manager.go
  cmd/backup-manager/app/export/manager.go
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/util/crdutil.go
Labels: CanMerge, needs-cherry-pick-1.1

#2750 Support tidb-binlog metrics scraping for TidbMonitor
  pkg/monitor/monitor/template.go
  pkg/monitor/monitor/template_test.go
  tests/monitor.go
Labels: CanMerge, area/monitor, needs-cherry-pick-1.1

#2769 Fix pv patch continuously problem
  pkg/apis/pingcap/v1alpha1/defaulting/tidbcluster.go
  pkg/apis/pingcap/v1alpha1/tidbmonitor_types.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/controller_utils_test.go
  pkg/controller/pv_control_test.go
  pkg/label/label.go
  pkg/manager/meta/reclaim_policy_manager.go
  pkg/manager/meta/reclaim_policy_manager_test.go
  pkg/monitor/monitor/util.go
  tests/actions.go
  tests/e2e/tidbcluster/tidbcluster.go
  tests/pkg/fixture/fixture.go
Labels: CanMerge, area/monitor, needs-cherry-pick-1.1

#2781 add v1.1.1 release notes
  CHANGELOG-1.1.md
  charts/tidb-cluster/values.yaml
  charts/tidb-operator/values.yaml
  deploy/aliyun/variables.tf
  deploy/aws/variables.tf
  deploy/gcp/variables.tf
Labels: needs-cherry-pick-1.1

#2691 Add CRD and Controller for TiKVGroup/TiDBGroup
  cmd/controller-manager/main.go
  docs/api-references/docs.md
  hack/update-crd-groups.sh
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/crd_kinds.go
  pkg/apis/pingcap/v1alpha1/group_types.go
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/register.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/pingcap/v1alpha1/fake/fake_pingcap_client.go
  pkg/client/clientset/versioned/typed/pingcap/v1alpha1/fake/fake_tidbgroup.go
  pkg/client/clientset/versioned/typed/pingcap/v1alpha1/fake/fake_tikvgroup.go
  pkg/client/clientset/versioned/typed/pingcap/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/pingcap/v1alpha1/pingcap_client.go
  pkg/client/clientset/versioned/typed/pingcap/v1alpha1/tidbgroup.go
  pkg/client/clientset/versioned/typed/pingcap/v1alpha1/tikvgroup.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/pingcap/v1alpha1/interface.go
  pkg/client/informers/externalversions/pingcap/v1alpha1/tidbgroup.go
  pkg/client/informers/externalversions/pingcap/v1alpha1/tikvgroup.go
  pkg/client/listers/pingcap/v1alpha1/expansion_generated.go
  pkg/client/listers/pingcap/v1alpha1/tidbgroup.go
  pkg/client/listers/pingcap/v1alpha1/tikvgroup.go
  pkg/controller/tidbgroup/tidb_group_control.go
  pkg/controller/tidbgroup/tidb_group_controller.go
  pkg/controller/tikvgroup/tikv_group_control.go
  pkg/controller/tikvgroup/tikv_group_controller.go
  pkg/util/crdutil.go
Labels: CanMerge, area/heterogeneous, status/PTAL

#2792 use controller.GuaranteedUpdate to update TidbCluster CR in e2e
  tests/e2e/tidbcluster/serial.go
  tests/e2e/tidbcluster/tidbcluster.go
Labels: CanMerge, needs-cherry-pick-1.1

#2716 optimize prometheus operator example
  examples/prometheus-operator/pd-serviceMonitor.yaml
  examples/prometheus-operator/tidb-serviceMonitor.yaml
  examples/prometheus-operator/tikv-serviceMonitor.yaml
Labels: CanMerge, contribution, needs-cherry-pick-1.1

#2791 Add AutoScalerRef in TidbCluster Status
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbclusterautoscaler_types.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/autoscaler/autoscaler/autoscaler_manager.go
  pkg/autoscaler/autoscaler/tikv_autoscaler.go
  pkg/autoscaler/autoscaler/util.go
  pkg/autoscaler/autoscaler/util_test.go
  pkg/controller/autoscaler/tidbcluster_autoscaler_controller.go
  pkg/controller/tidbcluster/tidb_cluster_controller.go
  pkg/label/label.go
  pkg/manager/member/tidbcluster_status_manager.go
  pkg/manager/member/tidbcluster_status_manager_test.go
  pkg/manager/member/tiflash_util_test.go
  tests/e2e/tidbcluster/serial.go
Labels: CanMerge, area/auto-scaling, needs-cherry-pick-1.1

#2793 Strict condition for PD Scale-In
  pkg/manager/member/pd_scaler.go
  pkg/manager/member/pd_scaler_test.go
Labels: CanMerge, needs-cherry-pick-1.1

#2723 UCP: support sidecar in tidbmonitor
  docs/api-references/docs.md
  examples/monitor-with-thanos/tidb-monitor.yaml
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbmonitor_types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/monitor/monitor/util.go
Labels: CanMerge, contribution, needs-cherry-pick-1.1

#2794 fix the tiflash multi path and the doc issue
  docs/api-references/config.json
  docs/api-references/docs.md
  pkg/apis/pingcap/v1alpha1/tiflash_config.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/member/tiflash_member_manager.go
  pkg/manager/member/tiflash_util.go
  pkg/manager/member/tiflash_util_test.go
Labels: needs-cherry-pick-1.1

#2809 update PD config API schema and use evictSchedulerLeader config API
  pkg/pdapi/pd_config.go
  pkg/pdapi/pdapi.go
Labels: needs-cherry-pick-1.1, release-note-action-required

#2812 use the pingcap forked mydumper
  images/tidb-backup-manager/Dockerfile
Labels: CanMerge, needs-cherry-pick-1.1, status/LGTM1

#2820 Revise interface for the native api in the controller package
  pkg/controller/pod_control.go
  pkg/controller/pvc_control.go
  pkg/controller/service_control.go
  pkg/controller/stateful_set_control.go
Labels: CanMerge, needs-cherry-pick-1.1

#2825 Skip duplicated e2e case
  tests/e2e/tidbcluster/serial.go
Labels: CanMerge, needs-cherry-pick-1.1, test/e2e

#2828 update pd/tidb/tikv config to v4.0.2
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/pd_config.go
  pkg/apis/pingcap/v1alpha1/tidb_config.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
Labels: CanMerge, needs-cherry-pick-1.1

#2801 Add TIKVGroup controller syncing logic
  cmd/controller-manager/main.go
  docs/api-references/docs.md
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/tidbcluster/tidb_cluster_controller.go
  pkg/controller/tidbgroup/tidb_group_control.go
  pkg/controller/tidbgroup/tidb_group_controller.go
  pkg/controller/tidbgroup_control.go
  pkg/controller/tikvgroup/tikv_group_control.go
  pkg/controller/tikvgroup/tikv_group_controller.go
  pkg/controller/tikvgroup_control.go
  pkg/manager/manager.go
  pkg/manager/member/tidbcluster_status_manager.go
  pkg/manager/member/tidbcluster_status_manager_test.go
  pkg/manager/member/tikv_group_member_manager.go
Labels: CanMerge, area/heterogeneous

#2830 Automated cherry pick of #2828: update pd/tidb/tikv config to v4.0.2
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/pd_config.go
  pkg/apis/pingcap/v1alpha1/tidb_config.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
Labels: CanMerge

#2807 Revise Auto-scaling updating method
  pkg/apis/pingcap/v1alpha1/tidbclusterautoscaler_types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/autoscaler/autoscaler/autoscaler_manager.go
  pkg/autoscaler/autoscaler/tidb_autoscaler.go
  pkg/autoscaler/autoscaler/tikv_autoscaler.go
  pkg/controller/tidbcluster_control.go
  tests/e2e/tidbcluster/serial.go
Labels: CanMerge, area/auto-scaling, needs-cherry-pick-1.1

#2827 Get rid of sensitive words
  charts/tidb-cluster/values.yaml
  hack/kind-cluster-build.sh
  tests/actions.go
  tests/pkg/webhook/pods.go
Labels: CanMerge, needs-cherry-pick-1.1

#2831 Add TiKVGroup statefulset templates and status
  pkg/apis/pingcap/v1alpha1/group_component.go
  pkg/controller/controller_utils.go
  pkg/controller/tikvgroup/tikv_group_controller.go
  pkg/label/label.go
  pkg/manager/member/tikv_group_member_manager.go
  pkg/manager/member/tikv_member_manager.go
  pkg/manager/member/utils.go
Labels: CanMerge, area/heterogeneous

#2835 Collect metrics for cdc, lightning and importer
  pkg/monitor/monitor/template.go
  pkg/monitor/monitor/template_test.go
Labels: CanMerge, area/monitor, needs-cherry-pick-1.1
