Repository pingcap/tidb-operator, pull requests merged in 2020-07, with the labels that each got.

#2840 Added instructions to DM README.md
  manifests/dm/README.md
Labels: CanMerge

#2837 add TiDBScaling function
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tidb_member_manager_test.go
Labels: CanMerge, needs-cherry-pick-1.1

#2841 Replace controller.Int32Ptr with k8s.io/utils/pointer.Int32Ptr
  pkg/backup/backup/backup_cleaner.go
  pkg/backup/backup/backup_manager.go
  pkg/backup/restore/restore_manager.go
  pkg/controller/backupschedule/backup_schedule_controller_test.go
  pkg/controller/controller_utils.go
  pkg/controller/generic_control_test.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/pd_scaler_test.go
  pkg/manager/member/pd_upgrader_test.go
  pkg/manager/member/scaler_test.go
  pkg/manager/member/ticdc_member_manager.go
  pkg/manager/member/tidb_discovery_manager.go
  pkg/manager/member/tidb_init_manager.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tidb_upgrader_test.go
  pkg/manager/member/tiflash_member_manager.go
  pkg/manager/member/tikv_group_member_manager.go
  pkg/manager/member/tikv_member_manager.go
  pkg/manager/member/tikv_scaler_test.go
  pkg/manager/member/tikv_upgrader_test.go
Labels: CanMerge, needs-cherry-pick-1.1, status/PTAL

#2810 Add support to stop TiDB gracefully
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/member/tidb_member_manager.go
Labels: needs-cherry-pick-1.1

#2852 disable reserve-space in basic examples
  examples/basic-cn/tidb-cluster.yaml
  examples/basic/tidb-cluster.yaml
Labels: needs-cherry-pick-1.1

#2854 fix a bug in PR 2852
  examples/basic-cn/tidb-cluster.yaml
Labels: needs-cherry-pick-1.1

#2861 move lifecycle out of componentSpec
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbcluster_component.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/member/tidb_member_manager.go
Labels: needs-cherry-pick-1.1

#2856 update pvReclaimPolicy to retain in advanced tidbcluster configuration
  examples/advanced/tidb-cluster.yaml
Labels: CanMerge, needs-cherry-pick-1.1

#2865 update lightning&br version to v4.0.2
  hack/local-up-operator.sh
  images/tidb-backup-manager/Dockerfile
Labels: needs-cherry-pick-1.1, status/PTAL

#2862 Refactor TiKV auto-scaling
  docs/api-references/docs.md
  go.mod
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbclusterautoscaler_types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/autoscaler/autoscaler/calculate/util.go
  pkg/autoscaler/autoscaler/tidb_autoscaler.go
  pkg/autoscaler/autoscaler/tikv_autoscaler.go
  pkg/autoscaler/autoscaler/util.go
  pkg/autoscaler/autoscaler/util_test.go
  tests/e2e/tidbcluster/serial.go
Labels: CanMerge, area/auto-scaling, needs-cherry-pick-1.1, status/LGTM2, status/can-merge

#2846 Make pod webhook able to manage tikv group pod
  charts/tidb-operator/templates/admission/admission-webhook-rbac.yaml
  charts/tidb-operator/templates/admission/admission-webhook-registration.yaml
  cmd/admission-webhook/main.go
  pkg/controller/periodicity/periodicity_controller.go
  pkg/label/label.go
  pkg/manager/member/utils.go
  pkg/webhook/admission_hooks.go
  pkg/webhook/pod/pd_deleter.go
  pkg/webhook/pod/pd_deleter_test.go
  pkg/webhook/pod/pods.go
  pkg/webhook/pod/tikv_creater.go
  pkg/webhook/pod/tikv_deleter.go
  pkg/webhook/pod/tikv_deleter_test.go
  pkg/webhook/pod/tikv_util.go
  pkg/webhook/pod/util.go
  pkg/webhook/pod/util_test.go
Labels: area/heterogeneous, area/webhook, status/LGTM1, status/LGTM2, status/can-merge

#2844 don't dump StatefulSet spec on update event
  pkg/controller/tidbcluster/tidb_cluster_controller.go
Labels: needs-cherry-pick-1.1

#2869 Fixed syntax for "and" conditions
  charts/tidb-cluster/templates/monitor-secret.yaml
Labels: contribution

#2851 add more error info for controllers
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tiflash_member_manager.go
  pkg/manager/member/tikv_member_manager.go
Labels: needs-cherry-pick-1.1, status/PTAL

#2880 readme: remove stale ROADMAP and add Community section, etc.
  README.md
  ROADMAP.md
Labels: needs-cherry-pick-1.1

#2876 remove old Jenkins file which is replaced by ci/pull_e2e_kind.groovy
  ci/pingcap_tidb_operator_build_kind.groovy
Labels: needs-cherry-pick-1.1

#2885 add more error information for controller
  pkg/manager/member/orphan_pods_cleaner.go
  pkg/manager/member/pd_failover.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/pd_scaler.go
  pkg/manager/member/pd_upgrader.go
  pkg/manager/member/pod_restarter.go
  pkg/manager/member/pump_member_manager.go
  pkg/manager/member/ticdc_member_manager.go
  pkg/manager/member/tidb_failover.go
  pkg/manager/member/tidb_init_manager.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tidb_upgrader.go
  pkg/manager/member/tidbcluster_status_manager.go
  pkg/manager/member/tiflash_member_manager.go
  pkg/manager/member/tiflash_scaler.go
  pkg/manager/member/tikv_group_member_manager.go
  pkg/manager/member/tikv_member_manager.go
  pkg/manager/member/tikv_scaler.go
  pkg/manager/member/tikv_upgrader.go
  pkg/manager/meta/meta_manager.go
  pkg/manager/meta/reclaim_policy_manager.go
Labels: needs-cherry-pick-1.1

#2878 Fixed a bug where TidbMonitor resource could not be set
  docs/api-references/docs.md
  pkg/apis/pingcap/v1alpha1/tidbmonitor_types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/monitor/monitor/util.go
  tests/pkg/fixture/fixture.go
Labels: area/monitor, needs-cherry-pick-1.1

#2886 tikv scaling takes precedence over upgrading
  pkg/manager/member/tikv_member_manager.go
  pkg/manager/member/tikv_scaler.go
  pkg/manager/member/tikv_scaler_test.go
  tests/e2e/tidbcluster/stability.go
Labels: needs-cherry-pick-1.1

#2891 use CentOS 7 in OpenShift E2E and fix an incompatibility issue
  charts/tidb-operator/templates/_helpers.tpl
  charts/tidb-operator/templates/scheduler-deployment.yaml
  ci/run-in-vm.sh
  hack/e2e-openshift.sh
Labels: needs-cherry-pick-1.1

#2893 use different image tag in different jobs
  ci/pull_e2e_kind.groovy
Labels: needs-cherry-pick-1.1, status/LGT1

#2870 Replace mydumper with dumpling in tidbBackupManager
  cmd/backup-manager/app/constants/constants.go
  cmd/backup-manager/app/export/export.go
  cmd/backup-manager/app/export/manager.go
  cmd/backup-manager/app/util/util.go
  cmd/backup-manager/app/util/util_test.go
  docs/api-references/docs.md
  images/tidb-backup-manager/Dockerfile
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
Labels: needs-cherry-pick-1.1, release-note-action-required, status/LGT1

#2894 check pvc size before running
  pkg/backup/backup/backup_manager.go
  pkg/backup/restore/restore_manager.go
Labels: needs-cherry-pick-1.1, status/LGT2, status/PTAL

#2905 update tls config for eks and ack
  deploy/aliyun/manifests/db.yaml.example
  deploy/aws/manifests/db.yaml.example
Labels: needs-cherry-pick-1.1, status/LGT1

#2892 Make remove backup data optional
  docs/api-references/docs.md
  manifests/backup/backup-aws-s3-br.yaml
  manifests/backup/backup-gcs-br.yaml
  manifests/backup/backup-gcs.yaml
  manifests/backup/backup-s3-br.yaml
  manifests/backup/backup-s3.yaml
  manifests/backup/backup-schedule-aws-s3-br.yaml
  manifests/backup/backup-schedule-gcs-br.yaml
  manifests/backup/backup-schedule-gcs.yaml
  manifests/backup/backup-schedule-s3-br.yaml
  manifests/backup/backup-schedule-s3.yaml
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/backup/backup/backup_cleaner.go
  pkg/controller/backup/backup_control.go
  pkg/controller/backup/backup_controller_test.go
  tests/pkg/fixture/fixture.go
Labels: needs-cherry-pick-1.1, release-note-action-required, status/LGT2, status/PTAL

#2884 Support TiKV auto scaling-out by Storage
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbclusterautoscaler_types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/autoscaler/autoscaler/autoscaler_manager.go
  pkg/autoscaler/autoscaler/calculate/calculate.go
  pkg/autoscaler/autoscaler/calculate/cpu.go
  pkg/autoscaler/autoscaler/calculate/storage.go
  pkg/autoscaler/autoscaler/calculate/util.go
  pkg/autoscaler/autoscaler/tidb_autoscaler.go
  pkg/autoscaler/autoscaler/tikv_autoscaler.go
  pkg/autoscaler/autoscaler/tikv_autoscaler_test.go
  pkg/autoscaler/autoscaler/util.go
  pkg/autoscaler/autoscaler/util_test.go
  pkg/label/label.go
  tests/e2e/tidbcluster/serial.go
  tests/pkg/mock/monitor.go
  tests/pkg/mock/util.go
Labels: CanMerge, area/auto-scaling, needs-cherry-pick-1.1, status/LGT2, status/PTAL

#2912 pass correct StatefulSet getter to CrdTestUtil
  tests/actions.go
  tests/cmd/stability/main.go
  tests/crd_test_util.go
  tests/e2e/tidbcluster/tidbcluster.go
Labels: status/LGT2

#2908 Use k8s.gcr.io vanity domain
  manifests/local-dind/kubernetes-dashboard.yaml
Labels: needs-cherry-pick-1.1, status/LGT1

#2897 remove temp data in pv for backup
  cmd/backup-manager/app/export/manager.go
Labels: needs-cherry-pick-1.1, status/LGT2, status/PTAL

#2916 refine export cleaner
  cmd/backup-manager/app/clean/clean.go
Labels: needs-cherry-pick-1.1, status/LGT2

#2899 Add commit ts to restore status
  cmd/backup-manager/app/backup/backup.go
  cmd/backup-manager/app/backup/manager.go
  cmd/backup-manager/app/clean/clean.go
  cmd/backup-manager/app/export/export.go
  cmd/backup-manager/app/export/manager.go
  cmd/backup-manager/app/import/manager.go
  cmd/backup-manager/app/restore/manager.go
  cmd/backup-manager/app/util/remote.go
  cmd/backup-manager/app/util/util.go
  cmd/backup-manager/app/util/util_test.go
  docs/api-references/docs.md
  pkg/apis/pingcap/v1alpha1/types.go
Labels: needs-cherry-pick-1.1, status/LGT2, status/PTAL

#2923 update grafana version to v6.1.6
  charts/tidb-cluster/values.yaml
  deploy/aliyun/manifests/db-monitor.yaml.example
  deploy/aws/manifests/db-monitor.yaml.example
  deploy/gcp/manifests/db-monitor.yaml.example
  examples/auto-scale/tidb-monitor.yaml
  examples/basic-cn/tidb-monitor.yaml
  examples/basic/tidb-monitor.yaml
  examples/monitor-with-externalConfigMap/tidb-monitor.yaml
  examples/monitor-with-thanos/tidb-monitor.yaml
  examples/tiflash/tidb-monitor.yaml
  manifests/monitor/tidb-monitor.yaml
  tests/e2e/util/image/image.go
Labels: needs-cherry-pick-1.1, status/LGT2, status/PTAL

#2931 update kubetest2 release repo
  hack/lib.sh
Labels: needs-cherry-pick-1.1

#2913 Support TiKVGroup Upgrading and Scaling
  pkg/apis/pingcap/v1alpha1/group_component.go
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/controller/tikvgroup/tikv_group_control.go
  pkg/controller/tikvgroup/tikv_group_controller.go
  pkg/manager/manager.go
  pkg/manager/member/scaler.go
  pkg/manager/member/tikv_group_member_manager.go
  pkg/manager/member/tikv_group_upgrader.go
  pkg/manager/member/tikv_member_manager.go
  pkg/manager/member/tikv_scaler.go
  pkg/manager/member/tikv_scaler_test.go
  pkg/manager/member/tikv_upgrader.go
  pkg/manager/member/tikv_upgrader_test.go
  pkg/manager/meta/reclaim_policy_manager.go
  tests/actions.go
  tests/crd_test_util.go
  tests/e2e/tidbcluster/serial.go
  tests/pkg/fixture/fixture.go
Labels: area/heterogeneous, status/LGT1

#2918 Fix externalendpoint judgement in tikv auto-scaling
  pkg/autoscaler/autoscaler/tikv_autoscaler.go
Labels: CanMerge, area/auto-scaling, contribution, needs-cherry-pick-1.1, status/LGT2

#2947 cherry-pick #2861 to release-1.1(move lifecycle out of componentSpec)
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbcluster_component.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/member/tidb_member_manager.go
Labels: status/LGT1

#2948 fix link error for kubernetes reference
  docs/api-references/config.json
  docs/api-references/docs.md
Labels: needs-cherry-pick-1.1, status/LGT2

#2942 reporting test coverage for PRs
  .github/.codecov.yml
  .github/workflows/ci.yaml
Labels: CanMerge, needs-cherry-pick-1.1, status/LGT2

#2926 add commitTS in column for restore
  cmd/backup-manager/app/backup/manager.go
  cmd/backup-manager/app/export/manager.go
  cmd/backup-manager/app/restore/manager.go
  manifests/crd.yaml
  pkg/util/crdutil.go
Labels: needs-cherry-pick-1.1, status/LGT2, status/PTAL

#2976 test cmd/backup-manager/app
  Makefile
  cmd/backup-manager/app/util/util_test.go
Labels: needs-cherry-pick-1.1, status/LGT1

#2964 adapt tidb/pd/tikv arguments for v4.0.3
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/pd_config.go
  pkg/apis/pingcap/v1alpha1/tikv_config.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/member/tikv_member_manager_test.go
Labels: needs-cherry-pick-1.1, status/LGT2, status/PTAL

#2857 fix drainer initialCommitTs issue
  charts/tidb-drainer/templates/scripts/_start_drainer.sh.tpl
  charts/tidb-drainer/values.yaml
Labels: needs-cherry-pick-1.0, needs-cherry-pick-1.1, status/LGT1

#2941 support mysqlNodePort and statusNodePort
  docs/api-references/docs.md
  examples/advanced/tidb-cluster.yaml
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/member/tidb_member_manager.go
  pkg/util/util.go
Labels: needs-cherry-pick-1.1, status/LGT2, status/PTAL

#2965 Add more tests for upgrade/features pkgs
  .codecov.yml
  .github/workflows/ci.yaml
  pkg/features/features.go
  pkg/features/features_test.go
  pkg/upgrader/upgrader.go
  pkg/upgrader/upgrader_test.go
Labels: CanMerge, needs-cherry-pick-1.1, status/LGT2

#2988 use a generic way to test methods of PD Client
  pkg/controller/tidb_control.go
  pkg/pdapi/fake_pdapi.go
  pkg/pdapi/pd_control.go
  pkg/pdapi/pdapi.go
  pkg/pdapi/pdapi_test.go
  pkg/util/http/httputil.go
  tests/e2e/util/proxiedtidbclient/proxiedtidbclient.go
Labels: CanMerge, needs-cherry-pick-1.1, status/LGT2

#2991 add UTs for discovery
  cmd/discovery/main.go
  pkg/discovery/discovery.go
  pkg/discovery/discovery_test.go
  pkg/discovery/server/interface.go
  pkg/discovery/server/proxy.go
  pkg/discovery/server/proxy_test.go
  pkg/discovery/server/server.go
  pkg/discovery/server/server_test.go
Labels: CanMerge, needs-cherry-pick-1.1, status/LGT2

#2993 add tls support between drainer and downstream database server
  charts/tidb-drainer/templates/_helpers.tpl
  charts/tidb-drainer/templates/drainer-statefulset.yaml
  charts/tidb-drainer/values.yaml
Labels: needs-cherry-pick-1.1, status/LGT2, status/PTAL

#2997 check the StatefulSet in the incoming request and add UTs
  pkg/webhook/statefulset/statefulset.go
  pkg/webhook/statefulset/statefulset_test.go
  pkg/webhook/util/scheme.go
Labels: CanMerge, needs-cherry-pick-1.1, status/LGT2

#3006 fix typos
  pkg/autoscaler/autoscaler/calculate/calculate.go
  pkg/autoscaler/autoscaler/tidb_autoscaler.go
  pkg/autoscaler/autoscaler/tikv_autoscaler.go
Labels: CanMerge, contribution, needs-cherry-pick-1.1, status/LGT2

#3011 TLS support for TiCDC
  pkg/backup/backup/backup_manager.go
  pkg/backup/restore/restore_manager.go
  pkg/controller/http_client.go
  pkg/controller/ticdc_control.go
  pkg/controller/tidb_control.go
  pkg/manager/member/ticdc_member_manager.go
  pkg/monitor/monitor/util.go
  pkg/util/util.go
Labels: needs-cherry-pick-1.1, status/LGT2

#3002 support cleanPolicy for backup CR
  cmd/backup-manager/app/backup/manager.go
  cmd/backup-manager/app/clean/clean.go
  cmd/backup-manager/app/export/manager.go
  docs/api-references/docs.md
  manifests/backup/backup-aws-s3-br.yaml
  manifests/backup/backup-gcs-br.yaml
  manifests/backup/backup-gcs.yaml
  manifests/backup/backup-s3-br.yaml
  manifests/backup/backup-s3.yaml
  manifests/backup/backup-schedule-aws-s3-br.yaml
  manifests/backup/backup-schedule-gcs-br.yaml
  manifests/backup/backup-schedule-gcs.yaml
  manifests/backup/backup-schedule-s3-br.yaml
  manifests/backup/backup-schedule-s3.yaml
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/backup.go
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/backup/backup/backup_cleaner.go
  pkg/controller/backup/backup_control.go
  pkg/controller/backup/backup_controller_test.go
  tests/pkg/fixture/fixture.go
Labels: needs-cherry-pick-1.1, status/LGT2, status/PTAL

#3019 update tools in backup manager to v4.0.3
  images/tidb-backup-manager/Dockerfile
Labels: needs-cherry-pick-1.1, status/LGT2, status/PTAL

#3022 v1.1.3 release notes
  CHANGELOG-1.1.md
  charts/tidb-cluster/values.yaml
  charts/tidb-operator/values.yaml
  deploy/aliyun/variables.tf
  deploy/aws/variables.tf
  deploy/gcp/variables.tf
Labels: needs-cherry-pick-1.1, status/LGT1

#3009 Make the spec.pd, spec.tidb, spec.tikv and spec.discovery, optional in the TidbCluster CR
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/defaulting/tidbcluster.go
  pkg/apis/pingcap/v1alpha1/defaulting/tidbcluster_test.go
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/apis/pingcap/v1alpha1/tidbcluster_test.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/validation/validation.go
  pkg/apis/pingcap/v1alpha1/validation/validation_test.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/controller_utils_test.go
  pkg/controller/tidb_control_test.go
  pkg/controller/tidbcluster/tidb_cluster_condition_updater_test.go
  pkg/controller/tidbcluster/tidb_cluster_control_test.go
  pkg/controller/tidbcluster/tidb_cluster_controller_test.go
  pkg/discovery/discovery_test.go
  pkg/discovery/server/server_test.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/pd_member_manager_test.go
  pkg/manager/member/pd_upgrader_test.go
  pkg/manager/member/pump_member_manager_test.go
  pkg/manager/member/tidb_discovery_manager.go
  pkg/manager/member/tidb_failover_test.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tidb_member_manager_test.go
  pkg/manager/member/tidb_upgrader_test.go
  pkg/manager/member/tiflash_member_manager_test.go
  pkg/manager/member/tiflash_util_test.go
  pkg/manager/member/tikv_member_manager.go
  pkg/manager/member/tikv_member_manager_test.go
  pkg/manager/member/tikv_upgrader_test.go
  pkg/scheduler/predicates/ha_test.go
  pkg/util/utils_test.go
  pkg/webhook/pod/pods_test.go
  tests/e2e/tidbcluster/serial.go
  tests/pkg/fixture/fixture.go
Labels: contribution, status/LGT2

#3021 fix flakiness in "TLS for MySQL Client and TLS between TiDB components"
  charts/tidb-cluster/templates/scripts/_start_drainer.sh.tpl
  charts/tidb-drainer/templates/scripts/_start_drainer.sh.tpl
  pkg/autoscaler/autoscaler/query/external.go
  pkg/pdapi/pd_control.go
  pkg/pdapi/pdapi.go
  pkg/util/crypto/certs.go
  tests/actions.go
  tests/backup.go
  tests/e2e/tidbcluster/serial.go
  tests/e2e/tidbcluster/stability.go
  tests/e2e/tidbcluster/tidbcluster.go
  tests/e2e/tidbcluster/tls.go
  tests/e2e/util/proxiedpdclient/proxiedpdclient.go
Labels: status/LGT2

#3036 deprecate auto_random config
  docs/api-references/docs.md
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidb_config.go
Labels: needs-cherry-pick-1.1, status/LGT2

#3034 set TZ environment for webhook and advanced statefulset
  charts/tidb-operator/templates/admission/admission-webhook-deployment.yaml
  charts/tidb-operator/templates/advanced-statefulset-deployment.yaml
  charts/tidb-operator/values.yaml
  pkg/backup/backup/backup_cleaner.go
  pkg/backup/backup/backup_manager.go
  pkg/backup/restore/restore_manager.go
  pkg/util/util.go
  pkg/util/utils_test.go
Labels: needs-cherry-pick-1.1, status/LGT2

#3043 fix helm install question included in e2e shell under mac system
  hack/run-e2e.sh
Labels: CanMerge, contribution, needs-cherry-pick-1.1, status/LGT2
