Repository pingcap/tidb-operator, pull requests merged in 2020-09, with the labels that each got.

#3189 Support recover from failover for tiflash and tikv
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/manager/member/failover.go
  pkg/manager/member/pd_failover.go
  pkg/manager/member/tidb_failover.go
  pkg/manager/member/tiflash_failover.go
  pkg/manager/member/tiflash_member_manager.go
  pkg/manager/member/tikv_failover.go
  pkg/manager/member/tikv_member_manager.go
  pkg/manager/member/utils.go
  pkg/manager/member/utils_test.go
Labels: needs-cherry-pick-1.1, status/LGT2

#3188 support labels configuration for tidb server
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidb_config.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
Labels: status/LGT2

#3190 Fix RBAC issue for TidbMonitor
  pkg/monitor/monitor/monitor_manager.go
  pkg/monitor/monitor/util.go
Labels: needs-cherry-pick-1.1, status/LGT2

#3191 update default configuration for tiflash
  docs/api-references/config.json
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tiflash_config.go
  pkg/manager/member/tiflash_util.go
  pkg/manager/member/tiflash_util_test.go
  tests/e2e/tidbcluster/tidbcluster.go
  tests/e2e/util/image/image.go
Labels: needs-cherry-pick-1.1, status/LGT2

#3199 Added spec.tikv.config.log-format and spec.tikv.config.server.max-grpc-send-msg-len
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tikv_config.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
Labels: needs-cherry-pick-1.1, status/LGT2

#3186 dm-operator/: support scaling a dm cluster with dm-masters and dm-workers
  pkg/apis/pingcap/v1alpha1/crd_kinds.go
  pkg/apis/pingcap/v1alpha1/dmcluster.go
  pkg/controller/dmcluster/dm_cluster_control.go
  pkg/controller/dmcluster/dm_cluster_controller.go
  pkg/dmapi/dmapi.go
  pkg/dmapi/fake_dmapi.go
  pkg/dmapi/master_control.go
  pkg/manager/manager.go
  pkg/manager/member/dm_master_member_manager.go
  pkg/manager/member/dm_master_scaler.go
  pkg/manager/member/dm_worker_member_manager.go
  pkg/manager/member/dm_worker_scaler.go
  pkg/manager/member/orphan_pods_cleaner.go
  pkg/manager/member/pd_scaler.go
  pkg/manager/member/pd_scaler_test.go
  pkg/manager/member/pod_restarter.go
  pkg/manager/member/pvc_cleaner.go
  pkg/manager/member/scaler.go
  pkg/manager/member/template.go
  pkg/manager/member/tiflash_scaler.go
  pkg/manager/member/tikv_group_member_manager.go
  pkg/manager/member/tikv_member_manager.go
  pkg/manager/member/tikv_scaler.go
  pkg/manager/member/tikv_scaler_test.go
  pkg/manager/meta/reclaim_policy_manager.go
  pkg/util/http/httputil.go
Labels: status/LGT2, status/PTAL

#3193 add examples for gcp
  examples/gcp/tidb-cluster.yaml
  examples/gcp/tidb-monitor.yaml
Labels: needs-cherry-pick-1.1, status/LGT2

#3206 update labels for stale action
  .github/workflows/stale.yaml
Labels: CanMerge, needs-cherry-pick-1.1, status/LGT2

#3204 Fix all issues reported by gosimple
  .golangci.yml
  pkg/autoscaler/autoscaler/calculate/util.go
  pkg/autoscaler/autoscaler/util.go
  pkg/controller/generic_control_test.go
  pkg/manager/member/dm_master_member_manager.go
  pkg/manager/member/orphan_pods_cleaner.go
  pkg/manager/member/pd_failover.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/pvc_cleaner.go
  pkg/manager/member/tidb_failover.go
  pkg/manager/member/tiflash_failover.go
  pkg/manager/member/tikv_failover.go
  pkg/manager/member/tikv_upgrader.go
  pkg/manager/member/utils_test.go
  pkg/pdapi/pdapi.go
  pkg/tkctl/cmd/get/get.go
  pkg/util/crdutil.go
  tests/actions.go
  tests/cmd/blockwriter/main.go
  tests/crd_test_util.go
  tests/e2e/framework/framework.go
  tests/e2e/tidbcluster/stability.go
  tests/e2e/tidbcluster/tidbcluster.go
  tests/pkg/fault-trigger/manager/vm_qm.go
  tests/pkg/fault-trigger/manager/vm_virsh.go
  tests/pkg/mock/monitor.go
Labels: CanMerge, status/LGT2, status/PTAL, status/can-merge

#3195 Update auto scaling CRD
  .gitignore
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbclusterautoscaler_types.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/autoscaler/autoscaler/tidb_autoscaler.go
  pkg/autoscaler/autoscaler/tikv_autoscaler.go
  tests/e2e/tidbcluster/serial.go
Labels: CanMerge, area/auto-scaling, status/LGT2

#3196 tests: add some test cases for pkg/util
  pkg/backup/backup/backup_manager.go
  pkg/backup/restore/restore_manager.go
  pkg/util/crdutil_test.go
  pkg/util/crypto/certs_test.go
  pkg/util/discovery/discovery_test.go
  pkg/util/utils_test.go
Labels: CanMerge, status/LGT2, test/unit

#3214 Fix Pump imagePullSecrets issue
  pkg/manager/member/pump_member_manager.go
Labels: needs-cherry-pick-1.1, status/LGT2

#3208 Support PD Auto-scaling API in pdapi
  docs/api-references/docs.md
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbclusterautoscaler_types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/pdapi/fake_pdapi.go
  pkg/pdapi/pdapi.go
  pkg/util/http/httputil.go
Labels: status/LGT1

#3218 Fix wrong tag
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tikv_config.go
Labels: CanMerge, needs-cherry-pick-1.1, status/LGT2, status/PTAL

#3222 Fix the auto scaling panic problem
  docs/api-references/docs.md
  docs/design-proposals/2020-08-21-auto-scaling-with-pdapi.md
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbclusterautoscaler_types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/autoscaler/autoscaler/query/external.go
  pkg/autoscaler/autoscaler/tidb_autoscaler.go
  pkg/autoscaler/autoscaler/tikv_autoscaler.go
  pkg/autoscaler/autoscaler/util.go
Labels: area/auto-scaling, needs-cherry-pick-1.1, status/LGT2

#3223 release notes: add a note about migrating release notes to docs repo
  CHANGELOG-1.1.md
  CHANGELOG.md
Labels: CanMerge, needs-cherry-pick-1.0, needs-cherry-pick-1.1, status/LGT2

#3225 Some small optimizations
  charts/tidb-operator/values.yaml
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/crd_kinds.go
  pkg/apis/pingcap/v1alpha1/types.go
Labels: CanMerge, contribution, needs-cherry-pick-1.1, status/LGT3

#3201 dm-operator/: support auto-failover for dm-masters and dm-workers
  charts/tidb-operator/templates/controller-manager-deployment.yaml
  charts/tidb-operator/values.yaml
  cmd/controller-manager/main.go
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/defaulting/dmcluster.go
  pkg/apis/pingcap/v1alpha1/dmcluster.go
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/dmcluster/dm_cluster_controller.go
  pkg/discovery/discovery.go
  pkg/dmapi/master_control.go
  pkg/manager/member/dm_master_failover.go
  pkg/manager/member/dm_master_member_manager.go
  pkg/manager/member/dm_worker_failover.go
  pkg/manager/member/dm_worker_member_manager.go
  pkg/manager/member/failover.go
  pkg/manager/member/utils.go
Labels: CanMerge, status/LGT2, status/PTAL

#3237 Fix grafana env vars
  pkg/monitor/monitor/util.go
Labels: CanMerge, contribution, needs-cherry-pick-1.1, status/LGT3

#3240 Fix structcheck
  .golangci.yml
  pkg/controller/tidbcluster/tidb_cluster_controller_test.go
  pkg/manager/member/pump_member_manager_test.go
  pkg/webhook/pod/util_test.go
Labels: status/LGT2, status/PTAL

#3239 Fix issues of staticcheck
  .golangci.yml
  cmd/backup-manager/app/util/util_test.go
  pkg/controller/generic_control.go
  pkg/discovery/server/server_test.go
  pkg/manager/member/tidb_init_manager.go
  tests/actions.go
  tests/apiserver/example.go
  tests/config.go
  tests/e2e/tidbcluster/stability.go
  tests/e2e/tidbcluster/tls.go
  tests/e2e/util/tidb/tidb.go
  tests/failover.go
Labels: status/LGT2, status/PTAL

#3246 Add servicsAccount for pump/pd/tidb/tidbcluster
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/pump_member_manager.go
  pkg/manager/member/ticdc_member_manager.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tiflash_member_manager.go
  pkg/manager/member/tikv_member_manager.go
Labels: needs-cherry-pick-1.1, status/LGT2, status/PTAL

#3187 let tiflash/pd/tidb scaling take precedence over upgrading
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/pd_member_manager_test.go
  pkg/manager/member/pd_scaler.go
  pkg/manager/member/pd_scaler_test.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tidb_upgrader.go
  pkg/manager/member/tiflash_member_manager.go
  pkg/manager/member/tiflash_member_manager_test.go
  pkg/manager/member/tiflash_scaler.go
  tests/e2e/tidbcluster/stability.go
Labels: needs-cherry-pick-1.1, status/LGT2, status/PTAL

#3249 ci: make release version configurable via jenkins parameter
  ci/pull_e2e_kind.groovy
Labels: needs-cherry-pick-1.1, status/LGT1, test/ci, test/e2e

#3247 fix empty version issue
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
Labels: needs-cherry-pick-1.1, status/LGT2

#3248 mount cluster client certificate to pd pod
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/tikv_member_manager.go
Labels: status/LGT2

#3253 TLS support for heterogeneous components
  examples/heterogeneous-tls/README.md
  examples/heterogeneous-tls/cert-manager/basic/cluster-client-secret.yaml
  examples/heterogeneous-tls/cert-manager/basic/pd-cluster-secret.yaml
  examples/heterogeneous-tls/cert-manager/basic/tidb-client-cert.yaml
  examples/heterogeneous-tls/cert-manager/basic/tidb-cluster-issuer.yaml
  examples/heterogeneous-tls/cert-manager/basic/tidb-cluster-secret.yaml
  examples/heterogeneous-tls/cert-manager/basic/tidb-server-secret.yaml
  examples/heterogeneous-tls/cert-manager/basic/tikv-cluster-secret.yaml
  examples/heterogeneous-tls/cert-manager/heterogeneous/cluster-client-secret.yaml
  examples/heterogeneous-tls/cert-manager/heterogeneous/pd-cluster-secret.yaml
  examples/heterogeneous-tls/cert-manager/heterogeneous/tidb-client-cert.yaml
  examples/heterogeneous-tls/cert-manager/heterogeneous/tidb-cluster-secret.yaml
  examples/heterogeneous-tls/cert-manager/heterogeneous/tidb-server-secret.yaml
  examples/heterogeneous-tls/cert-manager/heterogeneous/tiflash-cluster-secret.yaml
  examples/heterogeneous-tls/cert-manager/heterogeneous/tikv-cluster-secret.yaml
  examples/heterogeneous-tls/heterogeneous-cluster.yaml
  examples/heterogeneous-tls/tidb-cluster.yaml
  examples/heterogeneous-tls/tidb-monitor.yaml
  tests/e2e/tidbcluster/tidbcluster.go
  tests/e2e/tidbcluster/tls.go
Labels: contribution, status/LGT2

#3270 apis: add gc config for TiKV
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tikv_config.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
Labels: CanMerge, contribution, needs-cherry-pick-1.1, status/LGT2

#3266 bump tidb cluster version to v4.0.6
  charts/tidb-cluster/values.yaml
  charts/tidb-drainer/values.yaml
  charts/tidb-lightning/values.yaml
  charts/tikv-importer/values.yaml
  deploy/aliyun/manifests/db-monitor.yaml.example
  deploy/aliyun/manifests/db.yaml.example
  deploy/aliyun/variables.tf
  deploy/aws/manifests/db-monitor.yaml.example
  deploy/aws/manifests/db.yaml.example
  deploy/aws/variables.tf
  deploy/gcp/manifests/db-monitor.yaml.example
  deploy/gcp/manifests/db.yaml.example
  deploy/gcp/variables.tf
  deploy/modules/aliyun/tidb-cluster/variables.tf
  deploy/modules/aws/tidb-cluster/variables.tf
  deploy/modules/gcp/tidb-cluster/variables.tf
  deploy/modules/share/tidb-cluster-release/variables.tf
  examples/advanced-statefulset/tidb-cluster-scaled.yaml
  examples/advanced-statefulset/tidb-cluster.yaml
  examples/advanced/tidb-cluster.yaml
  examples/auto-scale/tidb-cluster.yaml
  examples/auto-scale/tidb-monitor.yaml
  examples/aws/tidb-cluster.yaml
  examples/aws/tidb-monitor.yaml
  examples/basic-cn/tidb-cluster.yaml
  examples/basic-cn/tidb-monitor.yaml
  examples/basic/tidb-cluster.yaml
  examples/basic/tidb-monitor.yaml
  examples/gcp/tidb-cluster.yaml
  examples/gcp/tidb-monitor.yaml
  examples/heterogeneous/heterogeneous-cluster.yaml
  examples/heterogeneous/tidb-cluster.yaml
  examples/heterogeneous/tidb-monitor.yaml
  examples/initialize/tidb-cluster.yaml
  examples/monitor-with-externalConfigMap/tidb-monitor.yaml
  examples/selfsigned-tls/tidb-cluster.yaml
  examples/tiflash/tidb-cluster.yaml
  examples/tiflash/tidb-monitor.yaml
  images/tidb-backup-manager/Dockerfile
Labels: needs-cherry-pick-1.1, status/LGT2

#3180 adapt configurations to v4.0.6
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/pd_config.go
  pkg/apis/pingcap/v1alpha1/tidb_config.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
Labels: needs-cherry-pick-1.1, status/LGT2, status/PTAL

#3277 add omitempty for newly added tidb&pd configurations
  pkg/apis/pingcap/v1alpha1/pd_config.go
  pkg/apis/pingcap/v1alpha1/tidb_config.go
Labels: status/LGT1, status/PTAL

#3264 autoscaler: construct pd strategy request according to autoscaler spec
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbclusterautoscaler_types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/autoscaler/autoscaler/autoscaler_manager.go
  pkg/autoscaler/autoscaler/util.go
  pkg/autoscaler/autoscaler/util_test.go
Labels: status/LGT2

#3282 add switch for cluster client tls mounting
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/tikv_member_manager.go
Labels: needs-cherry-pick-1.1, status/LGT1, status/PTAL

#3284 update chart version to v1.1.5
  charts/tidb-cluster/values.yaml
  charts/tidb-operator/values.yaml
  deploy/aliyun/variables.tf
  deploy/aws/variables.tf
  deploy/gcp/variables.tf
Labels: needs-cherry-pick-1.1, status/LGT1, status/PTAL

#3285 apis: add gc config `compaction-filter-skip-version-check` for TiKV
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tikv_config.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
Labels: needs-cherry-pick-1.1, status/LGT2

#3291 Add heterogeneous cluster feature to readme.md
  README.md
Labels: contribution, status/LGT2

#3265 autoscaler: setup framework for syncing pd plans
  pkg/autoscaler/autoscaler/autoscaler_manager.go
  pkg/autoscaler/autoscaler/calculate/calculate.go
  pkg/autoscaler/autoscaler/calculate/calculate_test.go
  pkg/autoscaler/autoscaler/calculate/cpu.go
  pkg/autoscaler/autoscaler/calculate/cpu_test.go
  pkg/autoscaler/autoscaler/calculate/storage.go
  pkg/autoscaler/autoscaler/calculate/util.go
  pkg/autoscaler/autoscaler/pdplan_autoscaler.go
  pkg/autoscaler/autoscaler/tidb_autoscaler.go
  pkg/autoscaler/autoscaler/tikv_autoscaler.go
  pkg/autoscaler/autoscaler/tikv_autoscaler_test.go
  pkg/autoscaler/autoscaler/util.go
  pkg/label/label.go
  pkg/pdapi/pdapi.go
  tests/e2e/tidbcluster/serial.go
Labels: status/LGT2

#3256 Remove the TiKVGroup/TiDBGroup CRD
  cmd/controller-manager/main.go
  docs/api-references/docs.md
  hack/update-crd-groups.sh
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/crd_kinds.go
  pkg/apis/pingcap/v1alpha1/group_component.go
  pkg/apis/pingcap/v1alpha1/group_types.go
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/register.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/pingcap/v1alpha1/fake/fake_pingcap_client.go
  pkg/client/clientset/versioned/typed/pingcap/v1alpha1/fake/fake_tidbgroup.go
  pkg/client/clientset/versioned/typed/pingcap/v1alpha1/fake/fake_tikvgroup.go
  pkg/client/clientset/versioned/typed/pingcap/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/pingcap/v1alpha1/pingcap_client.go
  pkg/client/clientset/versioned/typed/pingcap/v1alpha1/tidbgroup.go
  pkg/client/clientset/versioned/typed/pingcap/v1alpha1/tikvgroup.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/pingcap/v1alpha1/interface.go
  pkg/client/informers/externalversions/pingcap/v1alpha1/tidbgroup.go
  pkg/client/informers/externalversions/pingcap/v1alpha1/tikvgroup.go
  pkg/client/listers/pingcap/v1alpha1/expansion_generated.go
  pkg/client/listers/pingcap/v1alpha1/tidbgroup.go
  pkg/client/listers/pingcap/v1alpha1/tikvgroup.go
  pkg/controller/controller_utils.go
  pkg/controller/dmcluster/dm_cluster_controller.go
  pkg/controller/tidbcluster/tidb_cluster_controller.go
  pkg/controller/tidbgroup/tidb_group_control.go
  pkg/controller/tidbgroup/tidb_group_controller.go
  pkg/controller/tidbgroup_control.go
  pkg/controller/tikvgroup/tikv_group_control.go
  pkg/controller/tikvgroup/tikv_group_controller.go
  pkg/controller/tikvgroup_control.go
  pkg/label/label.go
  pkg/manager/manager.go
  pkg/manager/member/scaler.go
  pkg/manager/member/tidbcluster_status_manager.go
  pkg/manager/member/tidbcluster_status_manager_test.go
  pkg/manager/member/tikv_group_member_manager.go
  pkg/manager/member/tikv_group_upgrader.go
  pkg/manager/member/tikv_scaler.go
  pkg/manager/member/tikv_upgrader.go
  pkg/manager/member/utils.go
  pkg/manager/meta/reclaim_policy_manager.go
  pkg/util/crdutil.go
  pkg/util/crdutil_test.go
  pkg/webhook/pod/pods.go
  pkg/webhook/pod/tikv_deleter.go
  pkg/webhook/pod/tikv_deleter_test.go
  pkg/webhook/pod/tikv_util.go
  tests/crd_test_util.go
  tests/e2e/e2e.go
  tests/e2e/tidbcluster/serial.go
  tests/pkg/fixture/fixture.go
Labels: enhancement, status/LGT2

#3296 Remove the PodRestarter controller and `tidb.pingcap.com/pod-defer-deleting` annotation
  pkg/controller/dmcluster/dm_cluster_control.go
  pkg/controller/dmcluster/dm_cluster_controller.go
  pkg/controller/tidbcluster/tidb_cluster_control.go
  pkg/controller/tidbcluster/tidb_cluster_control_test.go
  pkg/controller/tidbcluster/tidb_cluster_controller.go
  pkg/label/label.go
  pkg/manager/member/pod_restarter.go
  pkg/manager/member/pod_restarter_test.go
  pkg/webhook/pod/pd_deleter.go
  pkg/webhook/pod/tikv_deleter.go
  pkg/webhook/pod/util.go
  tests/e2e/tidbcluster/tidbcluster.go
Labels: enhancement, needs-cherry-pick-1.0, status/LGT2

#3267 autoscaler: update autoscaling clusters
  pkg/autoscaler/autoscaler/autoscaler_manager.go
  pkg/autoscaler/autoscaler/pdplan_autoscaler.go
  pkg/autoscaler/autoscaler/util.go
Labels: CanMerge, status/LGT2

#3268 autoscaler: delete autoscaling clusters
  pkg/autoscaler/autoscaler/pdplan_autoscaler.go
Labels: CanMerge, status/LGT2

#3299 Fix tidb-init job incorrect check of %% for permit_host
  charts/tidb-cluster/templates/scripts/_initialize_tidb_users.py.tpl
Labels: contribution, status/LGT2

#3278 Support pod SecurityContext for PD
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/pd_member_manager_test.go
Labels: contribution, status/LGT2

#3271 dm-operator/: support tls for dm cluster and sources
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/member/dm_master_member_manager.go
  pkg/manager/member/dm_worker_member_manager.go
  pkg/manager/member/template.go
  pkg/util/crypto/certs.go
Labels: status/LGT2, status/PTAL

#3305 add initcontainer ResourceRequirements
  pkg/manager/member/tidb_init_manager.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tidb_member_manager_test.go
  pkg/manager/member/tiflash_member_manager.go
  pkg/manager/member/tikv_member_manager.go
  pkg/manager/member/tikv_member_manager_test.go
Labels: contribution, needs-cherry-pick-1.1, status/LGT3

#3309 Remove hack/{aa-codegen, update-test-codegen}.sh and revert some changes
  charts/tidb-operator/templates/admission/admission-webhook-rbac.yaml
  hack/aa-codegen.sh
  hack/update-all.sh
  hack/update-test-codegen.sh
Labels: CanMerge, enhancement, needs-cherry-pick-1.1, status/LGT3

#3269 autoscaler: create autoscaling clusters
  pkg/autoscaler/autoscaler/pdplan_autoscaler.go
  pkg/autoscaler/autoscaler/util.go
  pkg/controller/controller_utils.go
  pkg/label/label.go
Labels: CanMerge, status/LGT2

#3312 Support pass raw toml config for pump as string
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/member/pump_member_manager.go
  pkg/manager/member/pump_member_manager_test.go
  pkg/util/config/config.go
  pkg/util/config/config_test.go
  tests/e2e/tidbcluster/tidbcluster.go
  tests/pkg/fixture/fixture.go
Labels: needs-cherry-pick-1.1, status/LGT2, status/PTAL

#3322 Fix heterogeneous code cause tidb rolling update bug
  pkg/manager/member/tidb_member_manager.go
Labels: contribution, needs-cherry-pick-1.1, status/LGT2

#3310 Add unit tests for dm cluster CRD, discovery service, dm-master/dm-worker member manager
  pkg/apis/pingcap/v1alpha1/defaulting/dmcluster_test.go
  pkg/apis/pingcap/v1alpha1/dm_config_test.go
  pkg/apis/pingcap/v1alpha1/dmcluster_test.go
  pkg/apis/pingcap/v1alpha1/validation/validation.go
  pkg/apis/pingcap/v1alpha1/validation/validation_test.go
  pkg/controller/controller_utils_test.go
  pkg/controller/dmcluster/dm_cluster_condition_updater_test.go
  pkg/controller/dmcluster/dm_cluster_control.go
  pkg/controller/dmcluster/dm_cluster_control_test.go
  pkg/controller/dmcluster/dm_cluster_controller.go
  pkg/controller/dmcluster/dm_cluster_controller_test.go
  pkg/controller/dmcluster_control.go
  pkg/controller/dmcluster_control_test.go
  pkg/controller/service_control.go
  pkg/controller/stateful_set_control.go
  pkg/controller/tidbcluster/tidb_cluster_controller.go
  pkg/controller/tidbcluster/tidb_cluster_controller_test.go
  pkg/controller/tidbcluster_control_test.go
  pkg/discovery/server/server_test.go
  pkg/dmapi/dmapi.go
  pkg/dmapi/dmapi_test.go
  pkg/label/label_test.go
  pkg/manager/member/dm_master_failover.go
  pkg/manager/member/dm_master_member_manager.go
  pkg/manager/member/dm_master_member_manager_test.go
  pkg/manager/member/dm_master_scaler.go
  pkg/manager/member/dm_worker_failover.go
  pkg/manager/member/dm_worker_member_manager.go
  pkg/manager/member/dm_worker_member_manager_test.go
  pkg/manager/member/dm_worker_scaler.go
  pkg/manager/member/pd_member_manager_test.go
  pkg/manager/member/pump_member_manager_test.go
  pkg/manager/member/tidb_member_manager_test.go
  pkg/manager/member/tiflash_member_manager_test.go
  pkg/manager/member/tikv_member_manager_test.go
  pkg/manager/meta/reclaim_policy_manager.go
Labels: status/LGT2, status/PTAL

#3326 Add unit-tests for dm-master/worker failover/scaler/upgrader and some other components
  pkg/controller/dmmaster_control.go
  pkg/dmapi/master_control.go
  pkg/manager/member/dm_master_failover.go
  pkg/manager/member/dm_master_failover_test.go
  pkg/manager/member/dm_master_scaler_test.go
  pkg/manager/member/dm_master_upgrader_test.go
  pkg/manager/member/dm_worker_failover_test.go
  pkg/manager/member/dm_worker_member_manager_test.go
  pkg/manager/member/dm_worker_scaler_test.go
  pkg/manager/member/orphan_pods_cleaner.go
  pkg/manager/member/orphan_pods_cleaner_test.go
  pkg/manager/member/pd_scaler_test.go
  pkg/manager/member/pvc_resizer.go
  pkg/manager/member/pvc_resizer_test.go
  pkg/manager/meta/reclaim_policy_manager_test.go
Labels: status/LGT2

#3328 tests: add some test cases for pkg/monitor/monitor
  .gitignore
  Makefile
  hack/version.sh
  pkg/monitor/monitor/template_test.go
  pkg/monitor/monitor/util_test.go
Labels: status/LGT2, test/unit

#3262 doc for smooth migration
  docs/design-proposals/2020-09-13-smooth-migration-to-kubernetes.md
Labels: contribution, status/LGT2

#3297 autoscaler: refactor monitor syncing logic and crd
  docs/api-references/docs.md
  examples/auto-scale/tidb-cluster-auto-scaler.yaml
  examples/auto-scale/tidb-cluster.yaml
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbclusterautoscaler_types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/autoscaler/autoscaler/autoscaler_manager.go
  pkg/autoscaler/autoscaler/pdplan_autoscaler.go
  pkg/autoscaler/autoscaler/util.go
  pkg/autoscaler/autoscaler/util_test.go
  pkg/monitor/monitor/monitor_manager.go
Labels: status/LGT2

#3311 autoscaler: create heterogeneous clusters for external query autoscaling
  pkg/apis/pingcap/v1alpha1/tidbclusterautoscaler_types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/autoscaler/autoscaler/autoscaler_manager.go
  pkg/autoscaler/autoscaler/external_autoscaler.go
  pkg/autoscaler/autoscaler/pdplan_autoscaler.go
  pkg/autoscaler/autoscaler/util.go
  pkg/autoscaler/autoscaler/util_test.go
Labels: status/LGT2

#3308 TidbMonitor monitor multiple cluster crossed multiple namespaces in non-TLS environment
  docs/api-references/docs.md
  examples/monitor-multiple-cluster-non-tls/ns1-cluster.yaml
  examples/monitor-multiple-cluster-non-tls/ns2-cluster.yaml
  examples/monitor-multiple-cluster-non-tls/tidb-monitor.yaml
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbmonitor_types.go
  pkg/monitor/monitor/monitor_manager.go
  pkg/monitor/monitor/template.go
  pkg/monitor/monitor/template_test.go
  pkg/monitor/monitor/util.go
Labels: contribution, needs-cherry-pick-1.1, status/LGT2
