Repository pingcap/tidb-operator, pull requests merged in 2020-12, with the labels that each got.

#3538 use pingcap docker mirror registry to improve CI pipeline
  ci/pull_e2e_kind.groovy
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge

#3545 fix ci
  ci/pull_e2e_kind.groovy
Labels: status/LGT1

#3513 Fix member count on multi-cluster clusters.
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/apis/pingcap/v1alpha1/tidbcluster_test.go
  pkg/manager/member/pd_failover.go
  pkg/manager/member/pd_failover_test.go
  pkg/manager/member/pd_scaler.go
  pkg/manager/member/pd_scaler_test.go
Labels: status/LGT2, status/can-merge

#3518 Fix PD failover when multi-cluster enabled
  pkg/manager/member/pd_failover.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/pd_member_manager_test.go
Labels: status/LGT2, status/can-merge

#3514 Filter out TiFlash stores when checking upStores before TiKV member scaling in
  pkg/manager/member/tikv_scaler.go
  pkg/manager/member/tikv_scaler_test.go
  pkg/util/util.go
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge

#3543 fix consistency question for tidbmonitor monitor multiple cluster
  pkg/controller/stateful_set_control.go
  pkg/monitor/monitor/monitor_manager.go
  pkg/monitor/monitor/monitor_manager_test.go
  pkg/monitor/monitor/template.go
  pkg/monitor/monitor/template_test.go
  pkg/monitor/monitor/util.go
Labels: area/monitor, needs-cherry-pick-1.1, status/LGT2, status/can-merge

#3527 Classify TiFlash and TiKV in PeerStores
  pkg/controller/pd_control.go
  pkg/manager/member/tiflash_member_manager.go
  pkg/manager/member/tiflash_member_manager_test.go
  pkg/manager/member/tikv_member_manager.go
  pkg/manager/member/tikv_member_manager_test.go
  pkg/pdapi/pd_control.go
Labels: status/LGT1

#3551 fix monitor lighting bug
  pkg/monitor/monitor/template.go
  pkg/monitor/monitor/template_test.go
Labels: needs-cherry-pick-1.1, require-LGT1, status/LGT1, status/can-merge

#3564 TidbInitializer: support skip TLS when connecting to TiDB Server
  pkg/manager/member/tidb_init_manager.go
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge

#3573 update status for tidb initializer
  pkg/manager/member/tidb_init_manager.go
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge

#3571 fix tiflash example
  examples/tiflash/tidb-cluster.yaml
Labels: status/LGT2, status/can-merge

#3569 Fix codecs error for non-ASCII char in tidbInitializer job passwordSecret
  pkg/manager/member/template.go
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge

#3559 improve github PR template
  .github/pull_request_template.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge

#3586 fix storageVolumes validate bug
  pkg/apis/pingcap/v1alpha1/validation/validation.go
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge

#3570 Fix monitor sync nil map bug
  pkg/controller/tidbmonitor/tidb_monitor_control.go
  pkg/manager/member/dm_master_member_manager.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/utils.go
  pkg/monitor/monitor/monitor_manager_test.go
  pkg/monitor/monitor/util.go
Labels: status/LGT2, status/can-merge

#3587 Fix tidbmonitor watch from deployment to statefulset
  pkg/controller/tidbmonitor/tidb_monitor_controller.go
Labels: status/LGT2, status/can-merge

#3554 supoport canary deployment
  cmd/controller-manager/main.go
  pkg/controller/dependences.go
Labels: status/LGT2, status/can-merge

#3599 Add additional port support to extend TiDB service
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/member/tidb_member_manager.go
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge

#3597 allow empty secret in gcs BR
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/backup/util/util.go
  pkg/backup/util/utils_test.go
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge

#3572 add options for local and gcs provider in backup
  cmd/backup-manager/app/clean/clean.go
  cmd/backup-manager/app/export/export.go
  cmd/backup-manager/app/import/import.go
  cmd/backup-manager/app/util/util.go
  cmd/backup-manager/app/util/util_test.go
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge

#3598 charts: add TLS support for TiDB-Lightning and TiKV-Importer
  charts/tidb-lightning/templates/_helpers.tpl
  charts/tidb-lightning/templates/job.yaml
  charts/tidb-lightning/values.yaml
  charts/tikv-importer/templates/_helpers.tpl
  charts/tikv-importer/templates/tikv-importer-statefulset.yaml
  charts/tikv-importer/values.yaml
Labels: needs-cherry-pick-1.1, needs-update-docs, status/LGT2, status/can-merge

#3530 Add retry with PD PeerMembers on cross-region clusters when all PD members broken down
  pkg/controller/pd_control.go
  pkg/controller/pd_control_test.go
  pkg/discovery/discovery.go
  pkg/discovery/discovery_test.go
  pkg/pdapi/pd_control.go
Labels: status/LGT2

#3609 TiDBMonitor add component label
  pkg/monitor/monitor/monitor_manager.go
  pkg/monitor/monitor/monitor_manager_test.go
  pkg/monitor/monitor/template.go
  pkg/monitor/monitor/template_test.go
Labels: needs-cherry-pick-1.1, status/LGT2

#3617 charts: write TiDB-Lighting logs to stdout
  charts/tidb-lightning/values.yaml
  cmd/backup-manager/app/import/import.go
Labels: needs-cherry-pick-1.1, status/LGT2

#3622 support multiple cluster
  pkg/monitor/monitor/monitor_manager.go
  pkg/monitor/monitor/template.go
  pkg/monitor/monitor/template_test.go
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge

#3550 Improve advanced example: TidbCluster
  docs/api-references/docs.md
  examples/advanced/tidb-cluster.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidb_config_wraper.go
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/discovery/discovery.go
  pkg/label/label.go
  pkg/manager/member/pd_failover.go
  pkg/manager/meta/reclaim_policy_manager.go
  pkg/util/config/config.go
  pkg/util/util.go
  pkg/webhook/pod/tikv_util.go
Labels: needs-cherry-pick-1.1, status/LGT2

#3528 Support monitor for dm cluster
  docs/api-references/docs.md
  examples/dm/dm-cluster.yaml
  examples/dm/dm-monitor.yaml
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbmonitor_types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/dmapi/master_control.go
  pkg/monitor/monitor/monitor_manager.go
  pkg/monitor/monitor/monitor_manager_test.go
  pkg/monitor/monitor/template.go
  pkg/monitor/monitor/template_test.go
  pkg/monitor/monitor/util.go
  pkg/monitor/monitor/util_test.go
  pkg/util/util.go
  pkg/util/utils_test.go
Labels: status/LGT2

#3624 Refactor pd_control.go with GetPeerPDClient
  pkg/pdapi/pd_control.go
Labels: status/LGT2

#3613 Bump operator to v1.1.8 and tidb components to v4.0.9
  charts/tidb-cluster/values.yaml
  charts/tidb-drainer/values.yaml
  charts/tidb-lightning/values.yaml
  charts/tidb-operator/values.yaml
  charts/tikv-importer/values.yaml
  deploy/aliyun/manifests/db-monitor.yaml.example
  deploy/aliyun/manifests/db.yaml.example
  deploy/aliyun/variables.tf
  deploy/aws/manifests/db-monitor.yaml.example
  deploy/aws/manifests/db.yaml.example
  deploy/aws/variables.tf
  deploy/gcp/manifests/db-monitor.yaml.example
  deploy/gcp/manifests/db.yaml.example
  deploy/gcp/variables.tf
  deploy/modules/aliyun/tidb-cluster/variables.tf
  deploy/modules/aws/tidb-cluster/variables.tf
  deploy/modules/gcp/tidb-cluster/variables.tf
  deploy/modules/share/tidb-cluster-release/variables.tf
  examples/advanced-statefulset/tidb-cluster-scaled.yaml
  examples/advanced-statefulset/tidb-cluster.yaml
  examples/advanced/tidb-cluster.yaml
  examples/auto-scale/tidb-cluster.yaml
  examples/auto-scale/tidb-monitor.yaml
  examples/aws/tidb-cluster.yaml
  examples/aws/tidb-monitor.yaml
  examples/basic-cn/tidb-cluster.yaml
  examples/basic-cn/tidb-monitor.yaml
  examples/basic/tidb-cluster.yaml
  examples/basic/tidb-monitor.yaml
  examples/gcp/tidb-cluster.yaml
  examples/gcp/tidb-monitor.yaml
  examples/heterogeneous-tls/heterogeneous-cluster.yaml
  examples/heterogeneous-tls/tidb-cluster.yaml
  examples/heterogeneous-tls/tidb-monitor.yaml
  examples/heterogeneous/heterogeneous-cluster.yaml
  examples/heterogeneous/tidb-cluster.yaml
  examples/heterogeneous/tidb-monitor.yaml
  examples/initialize/tidb-cluster.yaml
  examples/monitor-multiple-cluster-non-tls/ns1-cluster.yaml
  examples/monitor-multiple-cluster-non-tls/ns2-cluster.yaml
  examples/monitor-multiple-cluster-non-tls/tidb-monitor.yaml
  examples/monitor-with-externalConfigMap/tidb-monitor.yaml
  examples/multi-cluster/tidb-cluster-1.yaml
  examples/multi-cluster/tidb-cluster-2.yaml
  examples/multiple-pv-tikv/tidb-cluster.yaml
  examples/selfsigned-tls/tidb-cluster.yaml
  examples/tiflash/tidb-cluster.yaml
  examples/tiflash/tidb-monitor.yaml
  hack/bump-version.sh
  images/tidb-backup-manager/Dockerfile
Labels: needs-cherry-pick-1.1, status/LGT2

#3625 Refactor PD member count in failover
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/manager/member/pd_failover.go
Labels: status/LGT2, status/can-merge

#3633 update upload script
  ci/release_tidb_operator_binary_and_image.groovy
Labels: needs-cherry-pick-1.1

#3601 Optimize tidbmonitor use lister cache.
  pkg/controller/tidbcluster_control.go
  pkg/manager/member/tidbcluster_status_manager.go
  pkg/monitor/monitor/monitor_manager.go
  pkg/monitor/monitor/monitor_manager_test.go
Labels: status/LGT2, status/can-merge

#3614 Fix PD member name match for multi-cluster when dispatching join parameters in discovery
  pkg/discovery/discovery.go
Labels: status/LGT2, status/can-merge

#3631 Fix monitor for TiKV-Importer
  charts/tikv-importer/templates/tikv-importer-configmap.yaml
  charts/tikv-importer/templates/tikv-importer-service.yaml
  charts/tikv-importer/templates/tikv-importer-statefulset.yaml
  charts/tikv-importer/values.yaml
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge

#3641 support toolimage when backup/restore using dumpling/lightning
  cmd/backup-manager/app/export/export.go
  cmd/backup-manager/app/import/import.go
  cmd/backup-manager/app/import/manager.go
  docs/api-references/docs.md
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/backup/backup/backup_manager.go
  pkg/backup/restore/restore_manager.go
  pkg/util/util.go
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge

#3611 Bump helm to v2.17.0
  ci/deploy_tidb_operator_staging.groovy
  hack/lib.sh
  tests/actions.go
  tests/e2e/util/image/image.go
  tests/images/e2e/Dockerfile
  tests/images/stability-test/Dockerfile
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge

#3594 Add scripts and examples of TLS features
  docs/CONTRIBUTING.md
  docs/hack-scripts.md
  examples/basic-tls/tidb-cluster.yaml
  examples/basic-tls/tidb-monitor.yaml
  hack/gen-tls-certs.sh
  hack/lib.sh
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge

#3654 fix gcs br backup&restore path
  cmd/backup-manager/app/util/remote.go
  cmd/backup-manager/app/util/util.go
  cmd/backup-manager/app/util/util_test.go
Labels: status/LGT2, status/can-merge

#3657 Bump operator to v1.1.9 and tidb components to v4.0.9
  charts/tidb-cluster/values.yaml
  charts/tidb-operator/values.yaml
  deploy/aliyun/variables.tf
  deploy/aws/variables.tf
  deploy/gcp/variables.tf
  examples/advanced/tidb-cluster.yaml
  examples/dm/dm-monitor.yaml
  hack/bump-version.sh
Labels: status/LGT1

#3548 [WIP] Support tidb-operator to canary deploy in helm chart
  charts/tidb-operator/templates/controller-manager-deployment.yaml
  charts/tidb-operator/templates/controller-manager-rbac.yaml
  charts/tidb-operator/templates/scheduler-deployment.yaml
  charts/tidb-operator/templates/scheduler-policy-configmap.yaml
  charts/tidb-operator/templates/scheduler-rbac.yaml
  charts/tidb-operator/values.yaml
  hack/local-up-operator.sh
Labels: status/LGT2, status/can-merge

#3579 monitor support thanos sidecar feature
  docs/api-references/docs.md
  examples/thanos-sidecar/objectstorage-secret.yaml
  examples/thanos-sidecar/tidb-monitor.yaml
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbmonitor_types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/monitor/monitor/monitor_manager_test.go
  pkg/monitor/monitor/template.go
  pkg/monitor/monitor/util.go
  pkg/monitor/monitor/util_test.go
  tests/e2e/tidbcluster/tidbcluster.go
  tests/e2e/util/image/image.go
  tests/monitor.go
  tests/pkg/fixture/fixture.go
Labels: status/LGT2, status/can-merge

#3653 charts: persist checkpoint for TiDB-Lightning
  charts/tidb-lightning/templates/scripts/_start_lightning.sh.tpl
  charts/tidb-lightning/values.yaml
Labels: needs-cherry-pick-1.1, status/LGT2

#3644 charts: add local backend support for TiDB-Lightning
  charts/tidb-lightning/templates/job.yaml
  charts/tidb-lightning/templates/persistentvolumeclaim.yaml
  charts/tidb-lightning/templates/scripts/_start_lightning.sh.tpl
  charts/tidb-lightning/values.yaml
Labels: needs-cherry-pick-1.1, needs-update-docs, status/LGT2, status/can-merge

#3639 Unify e2e test logging
  hack/e2e.sh
  hack/pin-deps.sh
  hack/run-e2e.sh
  tests/actions.go
  tests/backup.go
  tests/cluster_info.go
  tests/cmd/blockwriter/main.go
  tests/cmd/fault-trigger/main.go
  tests/cmd/mock-monitor/main.go
  tests/cmd/stability/main.go
  tests/cmd/webhook/main.go
  tests/config.go
  tests/crd_test_util.go
  tests/drainer_info.go
  tests/dt.go
  tests/e2e/e2e.go
  tests/e2e/e2e_test.go
  tests/e2e/tidbcluster/ownership.go
  tests/e2e/tidbcluster/serial.go
  tests/e2e/tidbcluster/stability-asts.go
  tests/e2e/tidbcluster/stability.go
  tests/e2e/tidbcluster/tidbcluster.go
  tests/e2e/tidbcluster/tls.go
  tests/e2e/tidbcluster/util.go
  tests/e2e/util/cloud/cloud.go
  tests/e2e/util/image/image.go
  tests/e2e/util/portforward/portforward.go
  tests/e2e/util/statefulset/statefulset.go
  tests/e2e/util/storage/minio.go
  tests/failover.go
  tests/fault.go
  tests/images/e2e/entrypoint.sh
  tests/monitor.go
  tests/pkg/apimachinery/certs.go
  tests/pkg/blockwriter/blockwriter.go
  tests/pkg/client/client_test.go
  tests/pkg/fault-trigger/api/response.go
  tests/pkg/fault-trigger/api/server.go
  tests/pkg/fault-trigger/client/client.go
  tests/pkg/fault-trigger/manager/static_pod_service.go
  tests/pkg/fault-trigger/manager/systemctl_service.go
  tests/pkg/fault-trigger/manager/vm_qm.go
  tests/pkg/fault-trigger/manager/vm_virsh.go
  tests/pkg/mock/monitor.go
  tests/pkg/mock/util.go
  tests/pkg/ops/exec.go
  tests/pkg/ops/tikv.go
  tests/pkg/util/db.go
  tests/pkg/util/utils.go
  tests/pkg/webhook/pods.go
  tests/pkg/webhook/route.go
  tests/slack/slack.go
  tests/webhook.go
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge

#3663 fix all e2e failure with an explain
  tests/actions.go
  tests/e2e/e2e.go
  tests/e2e/tidbcluster/serial.go
  tests/e2e/tidbcluster/stability-asts.go
  tests/e2e/tidbcluster/stability-br.go
  tests/e2e/tidbcluster/stability.go
  tests/e2e/tidbcluster/tidbcluster.go
  tests/e2e/util/cloud/cloud.go
  tests/e2e/util/image/image.go
  tests/slack/slack.go
  tests/util.go
Labels: needs-cherry-pick-1.1, status/LGT2

#3556 Fix unavailable PD address for TiDB/TiKV restart in pdFailoverPeriod on cross-region clusters
  pkg/discovery/discovery.go
  pkg/discovery/discovery_test.go
  pkg/discovery/server/server.go
  pkg/discovery/server/server_test.go
  pkg/manager/member/template.go
  pkg/manager/member/template_test.go
Labels: status/LGT2

#3648 status missed even if backup job succeeds
  cmd/backup-manager/app/backup/manager.go
  cmd/backup-manager/app/clean/manager.go
  cmd/backup-manager/app/export/manager.go
  cmd/backup-manager/app/import/manager.go
  cmd/backup-manager/app/restore/manager.go
  pkg/backup/backup/backup_cleaner.go
  pkg/backup/backup/backup_manager.go
  pkg/backup/restore/restore_manager.go
  pkg/controller/backup_status_updater.go
  pkg/controller/backup_status_updater_test.go
  pkg/controller/restore_status_updater.go
  pkg/controller/restore_status_updater_test.go
Labels: needs-cherry-pick-1.1, status/LGT2

#3638 fix Chart resource version
  charts/tidb-cluster/templates/discovery-rbac.yaml
  charts/tidb-cluster/templates/monitor-rbac.yaml
  charts/tidb-operator/templates/controller-manager-rbac.yaml
  charts/tidb-operator/templates/scheduler-rbac.yaml
Labels: first-time-contributor, needs-cherry-pick-1.1, status/LGT2
