Repository pingcap/tidb-operator, pull requests merged in 2020-05, with the labels that each got.

#2361 update operator image to v1.1.0-rc.3
  charts/tidb-cluster/values.yaml
  charts/tidb-operator/values.yaml
  deploy/aws/variables.tf
  deploy/gcp/variables.tf
Labels: needs-cherry-pick-1.1

#2356 e2e: fix namespace creation conflict
  tests/e2e/e2e_test.go
Labels: needs-cherry-pick-1.1

#2279 Add extend ability to query external service for autoscaler
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbclusterautoscaler_types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/autoscaler/autoscaler/autoscaler_manager.go
  pkg/autoscaler/autoscaler/query/external.go
  pkg/autoscaler/autoscaler/tidb_autoscaler.go
  pkg/autoscaler/autoscaler/tikv_autoscaler.go
  pkg/autoscaler/autoscaler/util.go
  pkg/controller/autoscaler/tidbcluster_autoscaler_controller.go
  pkg/pdapi/pdapi.go
  pkg/util/crypto/certs.go
  tests/e2e/tidbcluster/serial.go
Labels: area/auto-scaling, needs-cherry-pick-1.1

#2374 Remain PVC when TidbMonitor get deleted.
  pkg/controller/generic_control.go
  pkg/controller/generic_control_test.go
  pkg/monitor/monitor/monitor_manager.go
Labels: area/monitor, enhancement, needs-cherry-pick-1.1

#2370 upgrade kind to v0.8.1
  ci/pingcap_tidb_operator_build_kind.groovy
  hack/e2e.sh
  hack/lib.sh
Labels: needs-cherry-pick-1.1

#2267 backup: support gcp backup with br
  cmd/backup-manager/app/util/remote.go
  docs/api-references/docs.md
  images/tidb-backup-manager/entrypoint.sh
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
Labels: CanMerge, needs-cherry-pick-1.1, release-note-action-required

#2284 Fix service update which would changed the nodeport
  pkg/manager/member/tidb_member_manager.go
  pkg/util/util.go
  tests/e2e/tidbcluster/tidbcluster.go
Labels: needs-cherry-pick-1.1, type/bug

#2373 upgrade aws-k8s-tester to v1.1.5
  ci/aws-clean-eks.sh
  ci/e2e_eks.groovy
  hack/e2e.sh
  hack/lib.sh
Labels: needs-cherry-pick-1.1

#1983 UCP: add Validate requests.storage field of PD/TiKV
  pkg/apis/pingcap/v1alpha1/tidbcluster_test.go
  pkg/apis/pingcap/v1alpha1/validation/validation.go
  pkg/apis/pingcap/v1alpha1/validation/validation_test.go
  pkg/controller/tidbcluster/tidb_cluster_control_test.go
  pkg/controller/tidbcluster/tidb_cluster_controller_test.go
  tests/e2e/tidbcluster/serial.go
Labels: CanMerge, contribution, needs-cherry-pick-1.1

#2396 Update TiDB/TiKV to 4.0.0-rc config (#2322)
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/pd_config.go
  pkg/apis/pingcap/v1alpha1/tidb_config.go
  pkg/apis/pingcap/v1alpha1/tikv_config.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
Labels: CanMerge

#2366 use topology to achive HA
  charts/tidb-cluster/templates/tidb-cluster.yaml
  charts/tidb-cluster/values.yaml
  pkg/label/label.go
  pkg/scheduler/predicates/ha.go
  pkg/scheduler/predicates/ha_test.go
  pkg/scheduler/predicates/predicate.go
  pkg/scheduler/predicates/predicate_test.go
  pkg/scheduler/predicates/test_helper.go
Labels: contribution

#2389 Skip the TLS of the PD dashboard when the TiDB version < v4.0.0
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/apis/pingcap/v1alpha1/tidbcluster_test.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/pd_member_manager_test.go
Labels: CanMerge, needs-cherry-pick-1.1

#2400 backup: fix gcs get commit without prefix error
  cmd/backup-manager/app/util/remote.go
Labels: CanMerge, needs-cherry-pick-1.1

#2244 dump cluster logs into artifacts directory
  ci/pingcap_tidb_operator_build_kind.groovy
  hack/e2e.sh
Labels: needs-cherry-pick-1.1

#2379 Expose PVReclaimPolicy for TidbMonitor
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbmonitor_types.go
  pkg/controller/tidbmonitor/tidb_monitor_control.go
  pkg/manager/meta/reclaim_policy_manager.go
  pkg/monitor/monitor.go
  pkg/monitor/monitor/monitor_manager.go
  tests/e2e/tidbcluster/tidbcluster.go
Labels: area/monitor, enhancement, needs-cherry-pick-1.1

#2403 Separate TiDB client certificate can be used for each component
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbinitializer_types.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/backup/backup/backup_manager.go
  pkg/backup/restore/restore_manager.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/tidb_init_manager.go
Labels: CanMerge

#2413 create node pool for tiflash and cdc
  deploy/aws/clusters.tf
  deploy/aws/variables.tf
  deploy/modules/aws/tidb-cluster/local.tf
  deploy/modules/aws/tidb-cluster/variables.tf
  deploy/modules/aws/tidb-operator/main.tf
Labels: needs-cherry-pick-1.1

#2402 Add local br e2e test
  go.mod
  go.sum
  tests/e2e/tidbcluster/tidbcluster.go
  tests/e2e/util/storage/minio.go
  tests/e2e/util/storage/s3.go
  tests/e2e/util/storage/storage.go
  tests/images/e2e/Dockerfile
  tests/images/e2e/minio/minio.yaml
  tests/pkg/fixture/fixture.go
Labels: CanMerge, area/backup, needs-cherry-pick-1.1, test/e2e

#2421 fix e2e periodical jobs
  ci/e2e_eks.groovy
  ci/e2e_gke.groovy
  ci/e2e_kind.groovy
  ci/pingcap_tidb_operator_build_kind.groovy
  hack/e2e.sh
Labels: needs-cherry-pick-1.1

#2420 support creating node pools for tiflash and cdc on ack
  deploy/aliyun/main.tf
  deploy/aliyun/variables.tf
  deploy/modules/aliyun/tidb-cluster/local.tf
  deploy/modules/aliyun/tidb-cluster/variables.tf
  deploy/modules/aliyun/tidb-operator/operator.tf
Labels: CanMerge, needs-cherry-pick-1.1

#2425 update br to v3.1.1
  images/tidb-backup-manager/Dockerfile
Labels: CanMerge, needs-cherry-pick-1.1

#2439 delete namespace on failure in jenkins e2e jobs
  ci/e2e_eks.groovy
  ci/e2e_gke.groovy
  ci/e2e_kind.groovy
  ci/pingcap_tidb_operator_build_kind.groovy
  hack/run-e2e.sh
Labels: needs-cherry-pick-1.1

#2417 add storageClassName field from documentation
  examples/basic/tidb-cluster.yaml
Labels: CanMerge, contribution

#2414 Implement Ready condition for TidbCluster
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/tidbcluster/tidb_cluster_condition_updater.go
  pkg/controller/tidbcluster/tidb_cluster_condition_updater_test.go
  pkg/controller/tidbcluster/tidb_cluster_control.go
  pkg/controller/tidbcluster/tidb_cluster_control_test.go
  pkg/controller/tidbcluster/tidb_cluster_controller.go
  pkg/util/crdutil.go
  pkg/util/tidbcluster/tidbcluster.go
  tests/examples/t.sh
Labels: CanMerge, needs-cherry-pick-1.1

#2437 bugfix: defer should be called only if err is nil
  tests/pkg/util/db.go
Labels: CanMerge, needs-cherry-pick-1.1

#2338 add cdc types
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/defaulting/tidbcluster.go
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/validation/validation.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
Labels: CanMerge, needs-cherry-pick-1.1

#2443 Support PD Etcd Client
  go.mod
  pkg/pdapi/pdetcd.go
Labels: CanMerge, needs-cherry-pick-1.1

#2415 e2e: separate client certificates support, TidbInitializer and Dashboard
  tests/e2e/tidbcluster/tidbcluster.go
  tests/e2e/tidbcluster/tls.go
  tests/pkg/fixture/fixture.go
Labels: CanMerge, needs-cherry-pick-1.1

#2416 make backup and restore pods can enter into the correct status
  cmd/backup-manager/app/backup/manager.go
  cmd/backup-manager/app/clean/manager.go
  cmd/backup-manager/app/cmd/backup.go
  cmd/backup-manager/app/cmd/clean.go
  cmd/backup-manager/app/cmd/export.go
  cmd/backup-manager/app/cmd/import.go
  cmd/backup-manager/app/cmd/restore.go
  cmd/backup-manager/app/export/manager.go
  cmd/backup-manager/app/import/manager.go
  cmd/backup-manager/app/restore/manager.go
Labels: CanMerge, needs-cherry-pick-1.1

#2424 Add MonitorRef into tidbcluster status
  cmd/controller-manager/main.go
  docs/api-references/docs.md
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/tidbcluster/tidb_cluster_control.go
  pkg/controller/tidbcluster/tidb_cluster_control_test.go
  pkg/controller/tidbcluster/tidb_cluster_controller.go
  pkg/controller/tidbmonitor/tidb_monitor_controller.go
  pkg/manager/member/tidbcluster_status_manager.go
  pkg/monitor/monitor/monitor_manager.go
  tests/e2e/tidbcluster/serial.go
  tests/e2e/tidbcluster/tidbcluster.go
  tests/monitor.go
Labels: CanMerge, area/monitor, needs-cherry-pick-1.1

#2435 support prefix for backup path
  cmd/backup-manager/app/export/export.go
  cmd/backup-manager/app/export/manager.go
  cmd/backup-manager/app/import/restore.go
  pkg/backup/util/util.go
Labels: needs-cherry-pick-1.1

#2466 Update prometheus operator tikv example
  examples/prometheus-operator/tikv-serviceMonitor.yaml
Labels: area/monitor, needs-cherry-pick-1.1

#2438 Remain healthcheckNodePort when reconciling service
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tidb_member_manager_test.go
  pkg/util/util.go
Labels: CanMerge, needs-cherry-pick-1.1

#2471 Fix the bug that service annotations exposed in tidbcluster
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/utils.go
Labels: CanMerge, needs-cherry-pick-1.1

#2382 Revise stability test
  tests/actions.go
  tests/cmd/stability/main.go
  tests/failover.go
Labels: CanMerge, needs-cherry-pick-1.1

#2432 set failurePolicy to Fail in e2e
  charts/tidb-operator/templates/admission/admission-webhook-deployment.yaml
  charts/tidb-operator/values.yaml
  ci/pingcap_tidb_operator_build_kind.groovy
  cmd/controller-manager/main.go
  go.mod
  go.sum
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/autoscaler/autoscaler/tikv_autoscaler.go
  pkg/manager/member/pd_scaler.go
  pkg/manager/member/pd_upgrader.go
  pkg/manager/member/scaler.go
  pkg/manager/member/scaler_test.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tidb_upgrader.go
  pkg/manager/member/tikv_scaler.go
  pkg/manager/member/tikv_upgrader.go
  pkg/manager/member/utils.go
  pkg/manager/member/utils_test.go
  pkg/scheme/scheme.go
  pkg/upgrader/upgrader.go
  pkg/upgrader/upgrader_test.go
  pkg/util/util.go
  pkg/webhook/admission_hooks.go
  pkg/webhook/pod/pd_deleter.go
  pkg/webhook/pod/util.go
  pkg/webhook/statefulset/statefulset.go
  tests/actions.go
  tests/e2e/config/config.go
  tests/e2e/e2e.go
  tests/e2e/tidbcluster/serial.go
  tests/e2e/tidbcluster/stability.go
  tests/e2e/tidbcluster/tidbcluster.go
  tests/e2e/util/operator/operator.go
  tests/e2e/util/statefulset/statefulset.go
  tests/e2e/util/util.go
  tests/pkg/client/client.go
Labels: CanMerge, needs-cherry-pick-1.1, test/e2e

#2481 remove one line log which is in wrong position
  tests/monitor.go
Labels: contribution

#2491 Upgrade e2e 4.0 version and fix 1.12 env error
  tests/e2e/util/image/image.go
  tests/e2e/util/util.go
Labels: needs-cherry-pick-1.1

#2495 Fix Helm install setting params
  tests/actions.go
Labels: needs-cherry-pick-1.1

#2462 e2e: separate client certificates for BR
  tests/e2e/tidbcluster/tidbcluster.go
  tests/e2e/tidbcluster/tls.go
Labels: CanMerge, needs-cherry-pick-1.1

#2489 Improve performance by removing TidbControl's lock
  pkg/controller/tidb_control.go
  pkg/controller/tidb_control_test.go
Labels: CanMerge, needs-cherry-pick-1.1

#2362 Add CDC Controller
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/apis/pingcap/v1alpha1/tidbcluster_component.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/controller_utils.go
  pkg/controller/tidbcluster/tidb_cluster_control.go
  pkg/controller/tidbcluster/tidb_cluster_control_test.go
  pkg/controller/tidbcluster/tidb_cluster_controller.go
  pkg/label/label.go
  pkg/manager/member/ticdc_member_manager.go
  tests/examples/001-basic.sh
Labels: CanMerge, needs-cherry-pick-1.1

#2488 Update TiDB and TiKV configuration to 4.0.0-rc.2
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/pd_config.go
  pkg/apis/pingcap/v1alpha1/tidb_config.go
  pkg/apis/pingcap/v1alpha1/tiflash_config.go
  pkg/apis/pingcap/v1alpha1/tikv_config.go
  pkg/apis/pingcap/v1alpha1/validation/validation.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/pd_member_manager_test.go
  pkg/manager/member/tiflash_util.go
  pkg/manager/member/tiflash_util_test.go
  pkg/manager/member/tikv_member_manager.go
  pkg/manager/member/tikv_member_manager_test.go
  tests/pkg/fixture/fixture.go
Labels: CanMerge, needs-cherry-pick-1.1

#2514 Set `reserve-space = 0MB` for TiKV 4.0+ in e2e tests
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tikv_config.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  tests/pkg/fixture/fixture.go
  tests/util.go
Labels: CanMerge, needs-cherry-pick-1.1

#2518 Fix Tiflash configuration
  pkg/apis/pingcap/v1alpha1/tiflash_config.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
Labels: CanMerge, needs-cherry-pick-1.1

#2478 recycle PVs at the end of the each test
  tests/e2e/e2e.go
  tests/e2e/framework/framework.go
  tests/e2e/tidbcluster/serial.go
  tests/e2e/tidbcluster/stability.go
  tests/e2e/tidbcluster/tidbcluster.go
Labels: needs-cherry-pick-1.1

#2515 sync pump before tidb
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/controller/tidbcluster/tidb_cluster_control.go
  pkg/manager/member/pump_member_manager.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tidb_upgrader.go
Labels: CanMerge, needs-cherry-pick-1.1

#2469 support asts for tiflash
  pkg/apis/pingcap/v1alpha1/validation/validation.go
  pkg/apis/pingcap/v1alpha1/validation/validation_test.go
  pkg/manager/member/tiflash_scaler.go
  pkg/manager/member/utils.go
  pkg/upgrader/upgrader.go
  pkg/util/util.go
  tests/actions.go
  tests/e2e/tidbcluster/serial.go
  tests/pkg/fixture/fixture.go
Labels: needs-cherry-pick-1.1

#2527 don't refresh helm repository cache
  hack/run-e2e.sh
Labels: CanMerge, needs-cherry-pick-1.1

#2526 kms: fix tikv encryption config
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tikv_config.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
Labels: CanMerge

#2535 Bump prometheus version to latest
  charts/tidb-cluster/values.yaml
  deploy/aliyun/manifests/db-monitor.yaml.example
  deploy/aws/manifests/db-monitor.yaml.example
  deploy/gcp/manifests/db-monitor.yaml.example
  examples/auto-scale/tidb-monitor.yaml
  examples/basic/tidb-monitor.yaml
  examples/prometheus-operator/prometheus.yaml
  examples/tiflash/tidb-monitor.yaml
  manifests/monitor/tidb-monitor.yaml
  tests/e2e/util/image/image.go
Labels: needs-cherry-pick-1.1

#2519 remove noisy logs
  pkg/manager/member/pd_member_manager.go
Labels: CanMerge, needs-cherry-pick-1.1

#2508 update br to v4.0.0-rc.2 to include the auto_random fix
  images/tidb-backup-manager/Dockerfile
  tests/e2e/tidbcluster/tidbcluster.go
Labels: CanMerge, needs-cherry-pick-1.1

#2546 simplify tests/cmd/stability
  tests/cmd/stability/main.go
Labels: needs-cherry-pick-1.1

#2510 tidb-scheduler: implement kube-scheduler extender preempt verb
  charts/tidb-operator/templates/config/_scheduler-policy-json.tpl
  hack/local-up-operator.sh
  pkg/scheduler/predicates/fake.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  pkg/scheduler/server/mux.go
Labels: CanMerge, needs-cherry-pick-1.1

#2507 Fix the bug in webhook with AdvancedStatefulSet
  pkg/webhook/pod/pd_deleter.go
  pkg/webhook/pod/pd_deleter_test.go
  pkg/webhook/pod/pods_test.go
  pkg/webhook/pod/tikv_deleter.go
  pkg/webhook/pod/tikv_deleter_test.go
  pkg/webhook/pod/tikv_util.go
  pkg/webhook/pod/util.go
  pkg/webhook/pod/util_test.go
Labels: CanMerge, needs-cherry-pick-1.1

#2550 e2e/bugfix: preload tidb 3 upgrade version image
  tests/e2e/util/image/image.go
Labels: needs-cherry-pick-1.1

#2544 e2e/openshift: pin the same version for docker-ce and docker-ce-cli
  hack/e2e-openshift.sh
Labels: needs-cherry-pick-1.1

#2524 Create New DB during test
  tests/actions.go
  tests/cmd/blockwriter/main.go
  tests/e2e/tidbcluster/tidbcluster.go
Labels: CanMerge, needs-cherry-pick-1.1

#2483 Support Dashboard Metrics Storage Key
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbclusterautoscaler_types.go
  pkg/controller/tidbcluster/tidb_cluster_controller.go
  pkg/manager/member/tidbcluster_status_manager.go
  pkg/monitor/monitor/monitor_manager.go
  pkg/pdapi/pdapi.go
  pkg/pdapi/pdetcd.go
Labels: CanMerge, needs-cherry-pick-1.1

#2559 Move br e2e case into periodical job
  tests/e2e/tidbcluster/stability-br.go
  tests/e2e/tidbcluster/tidbcluster.go
Labels: needs-cherry-pick-1.1, test/e2e

#2367 Backup: allow to define resources
  docs/api-references/docs.md
  manifests/backup/backup-gcs.yaml
  manifests/backup/backup-s3-br.yaml
  manifests/backup/restore-gcs.yaml
  manifests/backup/restore-s3-br.yaml
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/backup/backup/backup_cleaner.go
  pkg/backup/backup/backup_manager.go
  pkg/backup/restore/restore_manager.go
Labels: CanMerge, contribution, needs-cherry-pick-1.1

#2560 remove records of deleted pods from failure stores automatically and add an e2e test
  pkg/manager/member/tiflash_failover.go
  pkg/manager/member/tiflash_member_manager.go
  pkg/manager/member/tikv_failover.go
  pkg/manager/member/tikv_failover_test.go
  pkg/manager/member/tikv_member_manager.go
  pkg/util/tidbcluster/tidbcluster.go
  tests/e2e/tidbcluster/stability.go
  tests/e2e/util/tidbcluster/tidbcluster.go
Labels: CanMerge, needs-cherry-pick-1.1

#2562 Remove BR Test in basic context
  tests/e2e/tidbcluster/tidbcluster.go
Labels: CanMerge, needs-cherry-pick-1.1

#2525 cdc status
  docs/api-references/docs.md
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/ticdc_control.go
  pkg/controller/tidbcluster/tidb_cluster_controller.go
  pkg/manager/member/ticdc_member_manager.go
Labels: needs-cherry-pick-1.1

#2307 [UCP] Noise reduction support when cluster auto scaling
  docs/api-references/docs.md
  go.mod
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbclusterautoscaler_types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/autoscaler/autoscaler/autoscaler_manager.go
  pkg/autoscaler/autoscaler/tikv_autoscaler.go
  pkg/autoscaler/autoscaler/util.go
  pkg/autoscaler/autoscaler/util_test.go
  pkg/label/label.go
  tests/e2e/tidbcluster/serial.go
Labels: CanMerge, contribution, needs-cherry-pick-1.1

#2571 Update Configuration to 4.0.0 GA
  docs/api-references/docs.md
  pkg/apis/pingcap/v1alpha1/pd_config.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
Labels: CanMerge, needs-cherry-pick-1.1

#2570 Fix PD failover
  pkg/manager/member/pd_failover.go
Labels: CanMerge, needs-cherry-pick-1.1

#2504 e2e for cdc
  pkg/manager/member/ticdc_member_manager.go
  tests/e2e/tidbcluster/tidbcluster.go
  tests/e2e/tidbcluster/tls.go
  tests/e2e/util/image/image.go
Labels: CanMerge, needs-cherry-pick-1.1

#2574 Fix Monitor log error
  pkg/monitor/monitor/monitor_manager.go
Labels: CanMerge, needs-cherry-pick-1.1

#2575 Move AdvancedStatefulSet test case to asts context job
  tests/e2e/tidbcluster/stability-asts.go
  tests/e2e/tidbcluster/tidbcluster.go
Labels: needs-cherry-pick-1.1

#2580 update toolkit version
  images/tidb-backup-manager/Dockerfile
Labels: CanMerge, needs-cherry-pick-1.1

#2569 add v1.1.0 release notes
  CHANGELOG-1.1.md
  charts/tidb-cluster/values.yaml
  charts/tidb-operator/values.yaml
  deploy/aws/variables.tf
  deploy/gcp/variables.tf
  tests/e2e/util/image/image.go
  tests/e2e/util/image/image_test.go
Labels: needs-cherry-pick-1.1

#2445 Add e2e test for backup by dumper
  tests/e2e/tidbcluster/stability-br.go
  tests/e2e/util/storage/minio.go
  tests/e2e/util/storage/s3.go
  tests/e2e/util/storage/storage.go
  tests/images/e2e/minio/minio.yaml
  tests/pkg/fixture/fixture.go
Labels: CanMerge, area/backup, needs-cherry-pick-1.1, status/PTAL, test/e2e

#2294 UCP: support monitor mount external configuration
  docs/api-references/docs.md
  examples/monitor-with-externalConfigMap/README.md
  examples/monitor-with-externalConfigMap/external-configMap.yaml
  examples/monitor-with-externalConfigMap/tidb-monitor.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbmonitor_types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/configmap_control.go
  pkg/monitor/monitor/monitor_manager.go
  pkg/monitor/monitor/util.go
Labels: CanMerge, area/monitor, contribution, needs-cherry-pick-1.1
