Repository pingcap/tidb-operator, pull requests merged in 2020-10, with the labels that each got.

#3327 Support passing raw toml config for the tidb as a string
  cmd/controller-manager/main.go
  docs/api-references/docs.md
  go.mod
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/defaulting/tidbcluster.go
  pkg/apis/pingcap/v1alpha1/defaulting/tidbcluster_test.go
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidb_config_wraper.go
  pkg/apis/pingcap/v1alpha1/tidb_config_wraper_test.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/validation/validation_test.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/autoscaler/autoscaler/pdplan_autoscaler.go
  pkg/autoscaler/autoscaler/util.go
  pkg/controller/tidbcluster/tidb_cluster_control_test.go
  pkg/controller/tidbcluster/tidb_cluster_controller.go
  pkg/controller/tidbcluster/tidb_cluster_controller_test.go
  pkg/manager/member/config.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tidb_member_manager_test.go
  pkg/manager/member/utils.go
  pkg/util/toml/toml.go
  pkg/util/toml/toml_test.go
  tests/cmd/stability/main.go
  tests/e2e/tidbcluster/stability.go
  tests/e2e/tidbcluster/tidbcluster.go
  tests/pkg/fixture/fixture.go
Labels: status/LGT2, status/PTAL

#3340 use timestamp to update gcs prefix for scheduled backup
  pkg/backup/backupschedule/backup_schedule_manager.go
Labels: needs-cherry-pick-1.1, status/LGT2, status/PTAL

#3344 make tikv evict leader timeout configurable
  cmd/admission-webhook/main.go
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/validation/validation.go
  pkg/apis/pingcap/v1alpha1/validation/validation_test.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/member/tikv_upgrader.go
  pkg/webhook/pod/pods.go
  pkg/webhook/pod/pods_test.go
  pkg/webhook/pod/tikv_deleter.go
  pkg/webhook/pod/tikv_util.go
Labels: needs-cherry-pick-1.1, status/LGT2, status/PTAL

#3236 Proposal: Canary deployments for TiDB-Operator
  docs/design-proposals/2020-09-07-canary-deployments-for-tidb-operator.md
Labels: contribution, status/LGT2

#3342 Support passing raw toml config for tikv/pd as string type
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/pd_config.go
  pkg/apis/pingcap/v1alpha1/pd_config_wraper.go
  pkg/apis/pingcap/v1alpha1/pd_config_wraper_test.go
  pkg/apis/pingcap/v1alpha1/tidb_config_wraper.go
  pkg/apis/pingcap/v1alpha1/tikv_config.go
  pkg/apis/pingcap/v1alpha1/tikv_config_wraper.go
  pkg/apis/pingcap/v1alpha1/tikv_config_wraper_test.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/validation/validation.go
  pkg/apis/pingcap/v1alpha1/validation/validation_test.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/autoscaler/autoscaler/external_autoscaler.go
  pkg/autoscaler/autoscaler/pdplan_autoscaler.go
  pkg/autoscaler/autoscaler/util.go
  pkg/controller/tidbcluster/tidb_cluster_control_test.go
  pkg/controller/tidbcluster/tidb_cluster_controller.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/pd_member_manager_test.go
  pkg/manager/member/tikv_member_manager.go
  pkg/manager/member/tikv_member_manager_test.go
  pkg/manager/member/utils.go
  pkg/util/config/config.go
  pkg/util/config/config_test.go
  tests/cmd/stability/main.go
  tests/e2e/tidbcluster/serial.go
  tests/e2e/tidbcluster/stability.go
  tests/e2e/tidbcluster/tidbcluster.go
  tests/pkg/fixture/fixture.go
Labels: needs-cherry-pick-1.1, status/LGT2, status/WIP

#3345 tiflash: remove proxy log container and print proxy log to tiflash container
  pkg/manager/member/tiflash_util.go
  pkg/manager/member/tiflash_util_test.go
Labels: needs-cherry-pick-1.1, status/LGT2, status/PTAL

#3351 Fix pass *interface{} to json.Unmarshal
  pkg/apis/pingcap/v1alpha1/pd_config_wraper.go
  pkg/apis/pingcap/v1alpha1/pd_config_wraper_test.go
  pkg/apis/pingcap/v1alpha1/tidb_config_wraper.go
  pkg/apis/pingcap/v1alpha1/tidb_config_wraper_test.go
  pkg/apis/pingcap/v1alpha1/tikv_config_wraper.go
  pkg/apis/pingcap/v1alpha1/tikv_config_wraper_test.go
Labels: CanMerge, needs-cherry-pick-1.1, status/LGT2, status/PTAL

#3347 add sysctl init container for pd
  deploy/modules/aliyun/tidb-cluster/values/default.yaml
  deploy/modules/gcp/tidb-cluster/values/default.yaml
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/pd_member_manager_test.go
Labels: contribution, needs-cherry-pick-1.1, status/LGT2

#3363 replace Errorf with Error and Infof with Info
  cmd/backup-manager/app/backup/backup.go
  cmd/backup-manager/app/import/import.go
  cmd/backup-manager/app/restore/restore.go
  cmd/controller-manager/main.go
  pkg/backup/backupschedule/backup_schedule_manager.go
  pkg/controller/periodicity/periodicity_controller.go
  pkg/manager/member/scaler.go
  pkg/version/version.go
  pkg/webhook/statefulset/statefulset.go
  tests/failover.go
  tests/fault.go
  tests/slack/slack.go
Labels: needs-cherry-pick-1.1, status/LGT2, status/PTAL

#3348 fix tls e2e test
  tests/e2e/e2e.go
  tests/e2e/tidbcluster/stability-br.go
  tests/e2e/tidbcluster/tidbcluster.go
  tests/e2e/tidbcluster/tls.go
Labels: contribution, status/LGT2

#3355 support passing raw toml config for tiflash
  docs/api-references/docs.md
  go.mod
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tiflash_config_wraper.go
  pkg/apis/pingcap/v1alpha1/tiflash_config_wraper_test.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/validation/validation.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/pump_member_manager.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tiflash_member_manager.go
  pkg/manager/member/tiflash_util.go
  pkg/manager/member/tiflash_util_test.go
  pkg/manager/member/tikv_member_manager.go
  pkg/util/config/config.go
  pkg/util/config/config_test.go
  tests/pkg/fixture/fixture.go
Labels: needs-cherry-pick-1.1, status/LGT2, status/PTAL

#3360 support options argument, update backup type
  cmd/backup-manager/app/backup/backup.go
  cmd/backup-manager/app/restore/restore.go
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
Labels: needs-cherry-pick-1.1, status/LGT2, status/PTAL

#3365 discovery: fix problem when restart with failover pods
  pkg/discovery/discovery.go
Labels: needs-cherry-pick-1.1, status/LGT2, status/PTAL

#3372 Use correct spec
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/tiflash_member_manager.go
  pkg/manager/member/tikv_member_manager.go
Labels: needs-cherry-pick-1.1, status/LGT2, status/PTAL

#3359 Add recommended configuration to examples
  examples/advanced-statefulset/tidb-cluster-scaled.yaml
  examples/advanced-statefulset/tidb-cluster.yaml
  examples/advanced/tidb-cluster.yaml
  examples/auto-scale/tidb-cluster.yaml
  examples/aws/tidb-cluster.yaml
  examples/basic-cn/tidb-cluster.yaml
  examples/basic/tidb-cluster.yaml
  examples/dm/dm-cluster.yaml
  examples/gcp/tidb-cluster.yaml
  examples/heterogeneous-tls/heterogeneous-cluster.yaml
  examples/heterogeneous-tls/tidb-cluster.yaml
  examples/heterogeneous/heterogeneous-cluster.yaml
  examples/heterogeneous/tidb-cluster.yaml
  examples/initialize/tidb-cluster.yaml
  examples/monitor-multiple-cluster-non-tls/ns1-cluster.yaml
  examples/monitor-multiple-cluster-non-tls/ns2-cluster.yaml
  examples/prometheus-operator/tidb-cluster.yaml
  examples/selfsigned-tls/tidb-cluster.yaml
  examples/tiflash/tidb-cluster.yaml
Labels: first-time-contributor, needs-cherry-pick-1.1, status/LGT2

#3374 backup: use br metadata to get total physical bytes
  cmd/backup-manager/app/backup/backup.go
  cmd/backup-manager/app/backup/manager.go
  cmd/backup-manager/app/util/util.go
  go.mod
  go.sum
Labels: needs-cherry-pick-1.1, status/LGT2, status/PTAL

#3325 Add tidbmonitor refactor prospoal
  docs/design-proposals/2020-09-27-tidb-monitor-refactor.md
Labels: contribution, status/LGT3

#3379 bump cluster version to v4.0.7 & chart version to v1.1.6
  charts/tidb-cluster/values.yaml
  charts/tidb-drainer/values.yaml
  charts/tidb-lightning/values.yaml
  charts/tidb-operator/values.yaml
  charts/tikv-importer/values.yaml
  deploy/aliyun/manifests/db-monitor.yaml.example
  deploy/aliyun/manifests/db.yaml.example
  deploy/aliyun/variables.tf
  deploy/aws/manifests/db-monitor.yaml.example
  deploy/aws/manifests/db.yaml.example
  deploy/aws/variables.tf
  deploy/gcp/manifests/db-monitor.yaml.example
  deploy/gcp/manifests/db.yaml.example
  deploy/gcp/variables.tf
  deploy/modules/aliyun/tidb-cluster/variables.tf
  deploy/modules/aws/tidb-cluster/variables.tf
  deploy/modules/gcp/tidb-cluster/variables.tf
  deploy/modules/share/tidb-cluster-release/variables.tf
  examples/advanced-statefulset/tidb-cluster-scaled.yaml
  examples/advanced-statefulset/tidb-cluster.yaml
  examples/advanced/tidb-cluster.yaml
  examples/auto-scale/tidb-cluster.yaml
  examples/auto-scale/tidb-monitor.yaml
  examples/aws/tidb-cluster.yaml
  examples/aws/tidb-monitor.yaml
  examples/basic-cn/tidb-cluster.yaml
  examples/basic-cn/tidb-monitor.yaml
  examples/basic/tidb-cluster.yaml
  examples/basic/tidb-monitor.yaml
  examples/gcp/tidb-cluster.yaml
  examples/gcp/tidb-monitor.yaml
  examples/heterogeneous-tls/heterogeneous-cluster.yaml
  examples/heterogeneous-tls/tidb-cluster.yaml
  examples/heterogeneous-tls/tidb-monitor.yaml
  examples/heterogeneous/heterogeneous-cluster.yaml
  examples/heterogeneous/tidb-cluster.yaml
  examples/heterogeneous/tidb-monitor.yaml
  examples/initialize/tidb-cluster.yaml
  examples/monitor-multiple-cluster-non-tls/ns1-cluster.yaml
  examples/monitor-multiple-cluster-non-tls/ns2-cluster.yaml
  examples/monitor-multiple-cluster-non-tls/tidb-monitor.yaml
  examples/monitor-with-externalConfigMap/tidb-monitor.yaml
  examples/selfsigned-tls/tidb-cluster.yaml
  examples/tiflash/tidb-cluster.yaml
  examples/tiflash/tidb-monitor.yaml
  images/tidb-backup-manager/Dockerfile
Labels: CanMerge, needs-cherry-pick-1.1, status/LGT2, status/PTAL

#3226 Support smooth migration
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/validation/validation.go
  pkg/apis/pingcap/v1alpha1/validation/validation_test.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/discovery/discovery.go
  pkg/discovery/discovery_test.go
Labels: CanMerge, contribution, status/LGT3

#3378 validate additionalContainers.image to make sure it is not empty
  pkg/apis/pingcap/v1alpha1/validation/validation.go
Labels: CanMerge, contribution, needs-cherry-pick-1.1, status/LGT2

#3362 Remove deprecated autoscaler code
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbclusterautoscaler_types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/autoscaler/autoscaler/calculate/util.go
  pkg/autoscaler/autoscaler/util.go
  pkg/autoscaler/autoscaler/util_test.go
  tests/pkg/fixture/fixture.go
Labels: CanMerge, status/LGT2

#3384 cherry-pick: add sysctl init container for pd (#3347)
  deploy/modules/aliyun/tidb-cluster/values/default.yaml
  deploy/modules/gcp/tidb-cluster/values/default.yaml
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/pd_member_manager_test.go
Labels: contribution, status/LGT1

#3390 monitor: fix surprising prometheus commandOptions behavior
  pkg/monitor/monitor/util.go
  pkg/monitor/monitor/util_test.go
Labels: contribution, needs-cherry-pick-1.1, status/LGT2

#3394 Automated cherry pick of #3390: monitor: fix surprising prometheus commandOptions behavior
  pkg/monitor/monitor/util.go
  pkg/monitor/monitor/util_test.go
Labels: status/LGT1

#3396 Improve unit test for pkg/util
  pkg/util/config/config_test.go
  pkg/util/crypto/certs.go
  pkg/util/crypto/certs_test.go
  pkg/util/dmcluster/dmcluster_test.go
  pkg/util/http/httputil.go
  pkg/util/http/httputil_test.go
  pkg/util/tidbcluster/tidbcluster_test.go
  pkg/util/util.go
  pkg/util/utils_test.go
Labels: status/LGT2, status/PTAL

#3397 add phase for backup and restore status
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/backup.go
  pkg/apis/pingcap/v1alpha1/restore.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/util/crdutil.go
Labels: CanMerge, first-time-contributor, needs-cherry-pick-1.1, status/LGT2

#3393 hack: add script to seperate CRD files
  hack/split-crd.py
Labels: CanMerge, needs-cherry-pick-1.1, status/LGT2

#3367 forbid to scale in tikv when number of stores is equal to or less than 3
  pkg/manager/member/tikv_scaler.go
  pkg/manager/member/tikv_scaler_test.go
  tests/e2e/tidbcluster/tidbcluster.go
Labels: CanMerge, contribution, needs-cherry-pick-1.1, status/LGT2

#3405 Improve pkg/webhook test
  pkg/webhook/pod/pd_deleter.go
  pkg/webhook/pod/pd_deleter_test.go
  pkg/webhook/pod/pods.go
  pkg/webhook/pod/tikv_creater.go
  pkg/webhook/pod/tikv_creater_test.go
  pkg/webhook/pod/tikv_deleter.go
  pkg/webhook/pod/tikv_util.go
  pkg/webhook/pod/util_test.go
  pkg/webhook/util/util.go
  pkg/webhook/util/util_test.go
Labels: CanMerge, status/LGT2, status/PTAL

#3388 Scheduler support advanced statefulset.
  pkg/scheduler/predicates/ha.go
  pkg/scheduler/predicates/ha_test.go
Labels: contribution, needs-cherry-pick-1.1, status/LGT2

#3412 Optimize the calculation of `PDStsDesiredReplicas`
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/manager/member/pd_failover.go
  pkg/manager/member/pd_member_manager.go
Labels: CanMerge, needs-cherry-pick-1.1, status/LGT2

#3413 Add test for pkg/backup/util/util.go
  pkg/backup/util/util.go
  pkg/backup/util/utils_test.go
Labels: status/LGT2, status/PTAL

#3419 support HA scheduling when failover happen
  pkg/scheduler/predicates/ha.go
  pkg/scheduler/predicates/ha_test.go
Labels: needs-cherry-pick-1.1, status/LGT2

#3401 Add per group status for TidbClusterAutoscaler and check scale in/out interval
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbclusterautoscaler_types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/autoscaler/autoscaler/autoscaler_manager.go
  pkg/autoscaler/autoscaler/external_autoscaler.go
  pkg/autoscaler/autoscaler/pdplan_autoscaler.go
  pkg/autoscaler/autoscaler/util.go
  pkg/autoscaler/autoscaler/util_test.go
  pkg/label/label.go
Labels: status/LGT2

#3408 support ondelete
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbcluster_component.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/pump_member_manager.go
  pkg/manager/member/ticdc_member_manager.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tiflash_member_manager.go
  pkg/manager/member/tikv_member_manager.go
Labels: status/LGT2

#3395 fix: PD leader transfer does not consider the case where advanced statefulset controller enabled.
  pkg/manager/member/pd_scaler.go
  pkg/manager/member/pd_upgrader.go
Labels: needs-cherry-pick-1.1, status/LGT2

#3424 delete log, set default resyncDuration to 30s
  pkg/controller/dependences.go
  pkg/manager/member/config.go
Labels: CanMerge, needs-cherry-pick-1.1, status/LGT2, status/PTAL

#3428 heterogeneous TiKV cluster cannot be scaled in to less than 3 replicas
  pkg/manager/member/tikv_scaler.go
  pkg/manager/member/tikv_scaler_test.go
Labels: needs-cherry-pick-1.1, status/LGT2

#3431 let force upgrade happen before scale
  pkg/manager/member/dm_master_member_manager.go
  pkg/manager/member/dm_master_member_manager_test.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/pd_member_manager_test.go
Labels: status/LGT2, status/PTAL

#3425 Tikv multiple pvc feature
  docs/api-references/docs.md
  examples/multiple-pv-tikv/tidb-cluster.yaml
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/validation/validation.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/member/tikv_member_manager.go
  tests/e2e/tidbcluster/tidbcluster.go
Labels: needs-cherry-pick-1.1, status/LGT2

#3085 Multi cluster
  docs/api-references/docs.md
  examples/multi-cluster/tidb-cluster-1.yaml
  examples/multi-cluster/tidb-cluster-2.yaml
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbmonitor_types.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/controller_utils.go
  pkg/discovery/discovery.go
  pkg/discovery/discovery_test.go
  pkg/manager/member/pd_failover.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/pd_member_manager_test.go
  pkg/manager/member/pd_scaler.go
  pkg/manager/member/pd_upgrader.go
  pkg/manager/member/pd_upgrader_test.go
  pkg/manager/member/pump_member_manager.go
  pkg/manager/member/template.go
  pkg/manager/member/template_test.go
  pkg/manager/member/ticdc_member_manager.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tiflash_member_manager.go
  pkg/manager/member/tiflash_util.go
  pkg/manager/member/tiflash_util_test.go
  pkg/manager/member/tikv_member_manager.go
  pkg/manager/member/utils.go
  pkg/pdapi/pd_control.go
  pkg/webhook/pod/pd_deleter.go
  pkg/webhook/pod/pods_test.go
  pkg/webhook/pod/util.go
  pkg/webhook/pod/util_test.go
Labels: contribution, status/LGT2

#3417 Add some unit test for pkg/manager
  pkg/manager/member/config_test.go
  pkg/manager/member/pd_member_manager_test.go
  pkg/manager/member/ticdc_member_manager_test.go
  pkg/manager/member/tidb_init_manager_test.go
  pkg/manager/member/tidb_member_manager_test.go
  pkg/manager/member/tiflash_member_manager_test.go
  pkg/manager/member/tikv_member_manager_test.go
  pkg/manager/member/utils_test.go
  pkg/manager/meta/reclaim_policy_manager_test.go
Labels: status/LGT2, test/unit

#3438 Add readinessProbe config for tidb
  docs/api-references/docs.md
  go.sum
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tidb_member_manager_test.go
Labels: CanMerge, needs-cherry-pick-1.1, status/LGT2, status/PTAL

#3429 autoscaler: improve defaultTAC unit test
  pkg/autoscaler/autoscaler/util.go
  pkg/autoscaler/autoscaler/util_test.go
Labels: CanMerge, area/auto-scaling, status/LGT2
