Repository pingcap/tidb-operator, pull requests merged in 2020-02, with the labels that each got.

#1474 Make Monitor Prometheus config template as Go struct
  go.mod
  go.sum
  pkg/monitor/monitor/template.go
  pkg/monitor/monitor/template_test.go
  pkg/monitor/monitor/util.go
Labels: area/monitor, enhancement, status/PTAL

#1596 Fix upgrader error when advanced statefulset disabled
  pkg/upgrader/upgrader.go
Labels: area/controller, needs-cherry-pick-1.1, priority/critical-urgent, status/PTAL, type/bug

#1599 Sync labels for Monitor's PersistentVolume
  pkg/controller/pv_control.go
  pkg/controller/tidbmonitor/tidb_monitor_controller.go
  pkg/monitor/monitor/monitor_manager.go
  tests/e2e/tidbcluster/tidbcluster.go
  tests/pkg/fixture/fixture.go
Labels: CanMerge, area/monitor, needs-cherry-pick-1.1, status/PTAL

#1598 e2e: don't use TiDB 2 version except backward compatibility test
  tests/e2e/tidbcluster/serial.go
  tests/e2e/tidbcluster/tidbcluster.go
Labels: CanMerge

#1614 Update stability
  Makefile
  tests/actions.go
  tests/cmd/stability/main.go
  tests/images/stability-test/Dockerfile
Labels: CanMerge, needs-cherry-pick-1.1, status/LGTM1

#1608 limit nodes and reduce CI jobs
  ci/pingcap_tidb_operator_build_kind.groovy
  hack/prepare-e2e.sh
  tests/backup.go
  tests/e2e/tidbcluster/tidbcluster.go
Labels: needs-cherry-pick-1.1

#1591 make Advanced Statefulset CRD optional
  pkg/upgrader/upgrader.go
  pkg/util/discovery/discovery.go
  pkg/util/discovery/discovery_test.go
  tests/actions.go
  tests/e2e/e2e.go
  tests/e2e/tidbcluster/serial.go
  tests/e2e/util/discovery/discovery.go
Labels: needs-cherry-pick-1.1

#1621 Check store owner for tikv manager
  pkg/manager/member/tikv_member_manager.go
  pkg/manager/member/tikv_member_manager_test.go
Labels: area/controller, needs-cherry-pick-1.0, needs-cherry-pick-1.1, type/bug

#1626 fix scaling pd with Advanced StatefulSet
  pkg/manager/member/pd_scaler.go
  tests/e2e/tidbcluster/serial.go
Labels: needs-cherry-pick-1.1

#1637 WIP: don't limit nodes and reduce parallel nodes
  ci/pingcap_tidb_operator_build_kind.groovy
Labels: needs-cherry-pick-1.1

#1624 fix stability test fail issue
  tests/actions.go
  tests/cmd/stability/main.go
Labels: needs-cherry-pick-1.1

#1642 clean containers on TERM signal to avoid cgroup leaking
  ci/pingcap_tidb_operator_build_kind.groovy
Labels: needs-cherry-pick-1.1

#1632 use controller.GuaranteedUpdate to update TiDB Cluster CRD in e2e
  tests/e2e/tidbcluster/tidbcluster.go
Labels: CanMerge, needs-cherry-pick-1.1

#1625 Separate TidbMonitor's prometheus scrape job
  pkg/monitor/monitor/template.go
  pkg/monitor/monitor/template_test.go
  tests/pkg/fixture/fixture.go
Labels: area/monitor, enhancement, status/PTAL

#1648 Manually check-pick Monitor commit
  go.mod
  go.sum
  pkg/controller/pv_control.go
  pkg/controller/tidbmonitor/tidb_monitor_controller.go
  pkg/monitor/monitor/monitor_manager.go
  pkg/monitor/monitor/template.go
  pkg/monitor/monitor/template_test.go
  pkg/monitor/monitor/util.go
  tests/e2e/tidbcluster/tidbcluster.go
  tests/pkg/fixture/fixture.go
Labels: CanMerge

#1653 CI: Running on TiDB Operator Nodes.
  ci/pingcap_tidb_operator_build_kind.groovy
  hack/check-terraform.sh
  tests/e2e/tidbcluster/tidbcluster.go
Labels: needs-cherry-pick-1.1

#1652 skip restarting docker if already configured
  hack/e2e.sh
Labels: needs-cherry-pick-1.1

#1649 Create the TidbClusterAutoScaler Types
  hack/update-crd-groups.sh
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/crd_kinds.go
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbclusterautoscaler_types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/pingcap/v1alpha1/fake/fake_pingcap_client.go
  pkg/client/clientset/versioned/typed/pingcap/v1alpha1/fake/fake_tidbclusterautoscaler.go
  pkg/client/clientset/versioned/typed/pingcap/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/pingcap/v1alpha1/pingcap_client.go
  pkg/client/clientset/versioned/typed/pingcap/v1alpha1/tidbclusterautoscaler.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/pingcap/v1alpha1/interface.go
  pkg/client/informers/externalversions/pingcap/v1alpha1/tidbclusterautoscaler.go
  pkg/client/listers/pingcap/v1alpha1/expansion_generated.go
  pkg/client/listers/pingcap/v1alpha1/tidbclusterautoscaler.go
  pkg/util/crdutil.go
Labels: CanMerge, area/auto-scaling, needs-cherry-pick-1.1, status/WIP

#1602 e2e case for clear TiDB failureMembers when scale TiDB to zero
  tests/e2e/tidbcluster/tidbcluster.go
Labels: contribution, needs-cherry-pick-1.1

#1667 Automated cherry pick of #1628: upgrade cluster while pods are not consecutive
  charts/tidb-operator/templates/controller-manager-deployment.yaml
  pkg/manager/member/pd_upgrader.go
  pkg/manager/member/tidb_upgrader.go
  tests/actions.go
  tests/e2e/tidbcluster/serial.go
  tests/e2e/tidbcluster/tidbcluster.go
  tests/e2e/util/image/image.go
  tests/e2e/util/statefulset/statefulset.go
Labels: CanMerge

#1672 Add Controller for TidbClusterAutoScale
  charts/tidb-operator/values.yaml
  cmd/controller-manager/main.go
  pkg/apis/pingcap/v1alpha1/register.go
  pkg/controller/autoscaler/tidbcluster_autoscaler_control.go
  pkg/controller/autoscaler/tidbcluster_autoscaler_controller.go
  pkg/features/features.go
Labels: area/auto-scaling, needs-cherry-pick-1.1, status/PTAL

#1678 Add authorization configuration for lighting
  charts/tidb-lightning/templates/job.yaml
  charts/tidb-lightning/templates/rclone-conf.yaml
  charts/tidb-lightning/templates/scripts/_start_lightning.sh.tpl
  charts/tidb-lightning/values.yaml
Labels: needs-cherry-pick-1.1

#1682 Automated cherry pick of #1678: migrate the private changes for lightning chart in dbaas to
  charts/tidb-lightning/templates/job.yaml
  charts/tidb-lightning/templates/rclone-conf.yaml
  charts/tidb-lightning/templates/scripts/_start_lightning.sh.tpl
  charts/tidb-lightning/values.yaml
Labels: CanMerge

#1684 Sync Auto-Scaler Controller
  cmd/controller-manager/main.go
  pkg/autoscaler/autoscaler.go
  pkg/autoscaler/autoscaler/autoscaler_manager.go
  pkg/autoscaler/autoscaler/tidb_autoscaler.go
  pkg/autoscaler/autoscaler/tikv_autoscaler.go
  pkg/autoscaler/autoscaler/util.go
  pkg/controller/autoscaler/tidbcluster_autoscaler_control.go
  pkg/controller/autoscaler/tidbcluster_autoscaler_controller.go
  pkg/label/label.go
  pkg/util/util.go
  pkg/webhook/pod/pd_deleter.go
  pkg/webhook/pod/tikv_deleter.go
  pkg/webhook/pod/util.go
Labels: CanMerge, area/auto-scaling, needs-cherry-pick-1.1, status/PTAL

#1692 deploy: close connection after set privilege
  charts/tidb-cluster/templates/scripts/_initialize_tidb_users.py.tpl
Labels: CanMerge, needs-cherry-pick-1.1

#1693 fix tls client cert bug
  charts/tidb-cluster/templates/_helpers.tpl
Labels: CanMerge, needs-cherry-pick-1.1

#1704 Add secret get/list for webhook rbac
  charts/tidb-operator/templates/admission/admission-webhook-rbac.yaml
Labels: CanMerge, area/webhook, needs-cherry-pick-1.1, type/bug

#1702 add more SANs to tidb server certificate
  charts/tidb-cluster/templates/tidb-cluster.yaml
  charts/tidb-cluster/values.yaml
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/member/tidb_member_manager.go
Labels: needs-cherry-pick-1.1

#1708 tidb-backup: add restoreUsingExistingVolume option
  charts/tidb-backup/templates/backup-pvc.yaml
  charts/tidb-backup/templates/restore-job.yaml
  charts/tidb-backup/values.yaml
Labels: CanMerge, contribution, needs-cherry-pick-1.0, needs-cherry-pick-1.1

#1703 Add consecutive count check for Auto-scaling
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbclusterautoscaler_types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/autoscaler/autoscaler/autoscaler_manager.go
  pkg/autoscaler/autoscaler/tidb_autoscaler.go
  pkg/autoscaler/autoscaler/tidb_autoscaler_test.go
  pkg/autoscaler/autoscaler/tikv_autoscaler.go
  pkg/autoscaler/autoscaler/tikv_autoscaler_test.go
  pkg/autoscaler/autoscaler/util.go
  pkg/autoscaler/autoscaler/util_test.go
  pkg/label/label.go
Labels: area/auto-scaling, area/controller, needs-cherry-pick-1.1, status/PTAL

#1705 tidb-backup: restore respects resources, imagePullPolicy, nodeSelector
  charts/tidb-backup/templates/backup-job.yaml
  charts/tidb-backup/templates/restore-job.yaml
  charts/tidb-backup/values.yaml
Labels: CanMerge, contribution, needs-cherry-pick-1.1

#1710 tidb-initializer:close connection after set privilege
  pkg/manager/member/template.go
Labels: CanMerge, needs-cherry-pick-1.1

#1718 fix autoscaler api
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbclusterautoscaler_types.go
Labels: CanMerge, area/auto-scaling, needs-cherry-pick-1.1

#1716 use kubetest2 to run e2e and support GKE provider
  go.sum
  hack/e2e.sh
  hack/lib.sh
  hack/prepare-e2e.sh
  hack/run-e2e.sh
  tests/e2e/e2e.go
Labels: needs-cherry-pick-1.1

#1723 fix tidb-lightning errors
  charts/tidb-lightning/templates/rclone-conf.yaml
Labels: CanMerge, contribution, needs-cherry-pick-1.1

#1722 Add auto-scaling calculation based by CPU load
  pkg/autoscaler/autoscaler/calculate/calculate.go
  pkg/autoscaler/autoscaler/calculate/cpu.go
  pkg/autoscaler/autoscaler/calculate/util.go
  pkg/autoscaler/autoscaler/tidb_autoscaler.go
  pkg/autoscaler/autoscaler/tidb_autoscaler_test.go
  pkg/autoscaler/autoscaler/tikv_autoscaler.go
  pkg/autoscaler/autoscaler/tikv_autoscaler_test.go
  pkg/autoscaler/autoscaler/util.go
  pkg/autoscaler/autoscaler/util_test.go
Labels: area/auto-scaling, needs-cherry-pick-1.1, status/PTAL

#1732 Remove consecutive check
  pkg/autoscaler/autoscaler/autoscaler_manager.go
  pkg/autoscaler/autoscaler/tidb_autoscaler.go
  pkg/autoscaler/autoscaler/tidb_autoscaler_test.go
  pkg/autoscaler/autoscaler/tikv_autoscaler.go
  pkg/autoscaler/autoscaler/tikv_autoscaler_test.go
  pkg/autoscaler/autoscaler/util.go
  pkg/autoscaler/autoscaler/util_test.go
Labels: area/auto-scaling, needs-cherry-pick-1.1, status/PTAL

#1714 Support user-defined tidb server/client certificate
  charts/tidb-cluster/templates/_helpers.tpl
  charts/tidb-cluster/templates/tidb-cluster.yaml
  charts/tidb-cluster/values.yaml
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tidb_member_manager_test.go
Labels: CanMerge, needs-cherry-pick-1.1

#1731 Finish auto-scaler controller
  cmd/controller-manager/main.go
  pkg/autoscaler/autoscaler/autoscaler_manager.go
  pkg/autoscaler/autoscaler/tidb_autoscaler.go
  pkg/autoscaler/autoscaler/tikv_autoscaler.go
  pkg/autoscaler/autoscaler/util.go
  pkg/controller/autoscaler/tidbcluster_autoscaler_control.go
  pkg/controller/autoscaler/tidbcluster_autoscaler_controller.go
Labels: CanMerge, area/auto-scaling, needs-cherry-pick-1.1, status/PTAL

#1573 add basic yaml deployment example
  examples/basic/README.md
  examples/basic/tidb-cluster.yaml
  examples/basic/tidb-monitor.yaml
Labels: CanMerge, needs-cherry-pick-1.1

#1740 Enable Auto-scaling in IDC
  ci/deploy_tidb_operator_staging.groovy
Labels: CanMerge

#1742 cherry pick missing commits to 1.1
  .github/pull_request_template.md
  charts/tidb-cluster/templates/config/_prometheus-config.tpl
  charts/tidb-cluster/values.yaml
  charts/tidb-drainer/values.yaml
  deploy/aliyun/variables.tf
  deploy/aws/clusters.tf
  deploy/aws/variables.tf
  deploy/gcp/examples/tidb-customized.tfvars
  deploy/gcp/variables.tf
  deploy/modules/aliyun/tidb-cluster/variables.tf
  deploy/modules/aws/tidb-cluster/variables.tf
  deploy/modules/gcp/tidb-cluster/variables.tf
  deploy/modules/share/tidb-cluster-release/variables.tf
  docs/CONTRIBUTING.md
  docs/generate-changelog.md
  docs/release-note-guide.md
  hack/e2e.sh
  hack/kind-cluster-build.sh
  hack/lib.sh
  hack/run-e2e.sh
  images/tidb-operator-e2e/tidb-cluster-values.yaml
  pkg/apis/pingcap/v1alpha1/validation/validation_test.go
  pkg/controller/tidbcluster/tidb_cluster_control_test.go
  tests/config.go
  tests/e2e/config/config.go
Labels: CanMerge

#1743 add stale github action to close stale issues/prs
  .github/workflows/stale.yaml
Labels: CanMerge, needs-cherry-pick-1.1

#1745 Fix TidbMonitor template error
  pkg/monitor/monitor/template.go
  pkg/monitor/monitor/template_test.go
Labels: area/monitor, needs-cherry-pick-1.1, priority/critical-urgent, type/bug

#1750 Fix TidbMonitor template error (#1745)
  pkg/monitor/monitor/template.go
  pkg/monitor/monitor/template_test.go
Labels: CanMerge

#1640 Support AdvancedStatefulSet in admission webhook
  go.mod
  go.sum
  pkg/webhook/pod/pd_deleter.go
  pkg/webhook/pod/pods.go
  pkg/webhook/pod/tikv_deleter.go
  pkg/webhook/pod/util.go
  tests/e2e/tidbcluster/serial.go
Labels: area/webhook, status/WIP

#1747 Make TidbMonitor intergrated in AutoScaler
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbclusterautoscaler_types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/autoscaler/autoscaler/autoscaler_manager.go
  pkg/autoscaler/autoscaler/calculate/calculate.go
  pkg/autoscaler/autoscaler/tidb_autoscaler.go
  pkg/autoscaler/autoscaler/tikv_autoscaler.go
  pkg/autoscaler/autoscaler/util.go
Labels: CanMerge, area/auto-scaling, area/monitor, needs-cherry-pick-1.1, status/PTAL

#1737 Allow to configure Affinity or Tolerations for Backups and Restores
  charts/tidb-backup/templates/backup-job.yaml
  charts/tidb-backup/templates/restore-job.yaml
  charts/tidb-backup/values.yaml
  charts/tidb-cluster/templates/scheduled-backup-cronjob.yaml
  charts/tidb-cluster/values.yaml
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/backup/backup/backup_manager.go
  pkg/backup/restore/restore_manager.go
Labels: CanMerge, contribution

#1761 Support AdvancedStatefulSet in admission webhook (#1640)
  go.mod
  go.sum
  pkg/webhook/pod/pd_deleter.go
  pkg/webhook/pod/pods.go
  pkg/webhook/pod/tikv_deleter.go
  pkg/webhook/pod/util.go
  tests/e2e/tidbcluster/serial.go
Labels: CanMerge

#1758 actions: update actions/checkout to v2
  .github/workflows/ci.yaml
Labels: needs-cherry-pick-1.1

#1735 Revise controller log and fix deployment template error
  pkg/manager/member/tidb_discovery_manager.go
  pkg/monitor/monitor/monitor_manager.go
  pkg/monitor/monitor/util.go
Labels: CanMerge, area/controller, needs-cherry-pick-1.1, status/PTAL

#1749 use /hack/e2e.sh to run a single node kind cluster for develop
  hack/e2e.sh
  hack/run-e2e.sh
Labels: CanMerge, needs-cherry-pick-1.1

#1778 upgrade local volume provisioner to 2.3.4
  manifests/local-dind/local-volume-provisioner.yaml
Labels: needs-cherry-pick-1.1

#1604 make the drainer name configurable
  charts/tidb-drainer/templates/_helpers.tpl
  charts/tidb-drainer/values.yaml
Labels: CanMerge, needs-cherry-pick-1.1, status/PTAL

#1775 Added marketplace product code filter for bastion to avoid selecting AMI from wrong vendor
  deploy/modules/aws/bastion/data.tf
Labels: CanMerge, needs-cherry-pick-1.1

#1773 tls: fix cluster TLS while using CR to create cluster
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tikv_config.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/tikv_member_manager.go
Labels: CanMerge, needs-cherry-pick-1.1

#1739 binlog: add tls in pump and drainer
  charts/tidb-cluster/templates/_helpers.tpl
  charts/tidb-cluster/templates/config/_pump-config.tpl
  charts/tidb-cluster/templates/pump-statefulset.yaml
  charts/tidb-cluster/values.yaml
  charts/tidb-drainer/templates/_helpers.tpl
  charts/tidb-drainer/templates/drainer-statefulset.yaml
  charts/tidb-drainer/templates/scripts/_start_drainer.sh.tpl
  charts/tidb-drainer/values.yaml
  go.mod
  go.sum
  hack/create-cert.sh
  pkg/controller/tidbcluster/tidb_cluster_controller.go
  pkg/manager/member/pump_member_manager.go
  pkg/manager/member/pump_member_manager_test.go
Labels: CanMerge

#1786 use TidbCluster CRD to simplify the test and increase wait timeout
  .gitignore
  tests/e2e/tidbcluster/serial.go
Labels: needs-cherry-pick-1.1

#1768 release v1.1.0-beta.2
  CHANGELOG-1.1.md
  charts/tidb-cluster/values.yaml
  charts/tidb-operator/values.yaml
  docs/release-note-guide.md
  tests/manifests/stability/stability.yaml
Labels: needs-cherry-pick-1.1

#1792 terraform fmt
  deploy/gcp/examples/multi-zonal.tfvars
  deploy/gcp/examples/single-zonal.tfvars
Labels: contribution

#1791 unify tidb-backup-manager image name
  Makefile
  ci/release_tidb_operator_binary_and_image.groovy
  images/tidb-backup-manager/Dockerfile
  images/tidb-backup-manager/entrypoint.sh
Labels: needs-cherry-pick-1.1

#1799 binglog: fix tls error when create pump with TLS when use CRD
  pkg/manager/member/pump_member_manager.go
Labels: CanMerge

#1802 fix master ci
  ci/pingcap_tidb_operator_build_kind.groovy
Labels: needs-cherry-pick-1.1

#1790 add prefix for remote storage
  charts/tidb-backup/templates/scripts/_start_backup.sh.tpl
  charts/tidb-backup/templates/scripts/_start_restore.sh.tpl
  charts/tidb-backup/values.yaml
Labels: CanMerge, needs-cherry-pick-1.0, needs-cherry-pick-1.1

#1808 Fix a bug that TiKV failed to start while creating cluster using CR with cluster tls enabled
  pkg/manager/member/template.go
Labels: needs-cherry-pick-1.1

#1801 Manage hot region label for the tikv created by auto-scaler
  pkg/autoscaler/autoscaler/tidb_autoscaler.go
  pkg/autoscaler/autoscaler/tikv_autoscaler.go
  pkg/label/label.go
  pkg/manager/member/pd_scaler.go
  pkg/manager/member/scaler.go
  pkg/manager/member/tikv_scaler.go
  pkg/manager/member/utils.go
  pkg/util/util.go
Labels: CanMerge, area/auto-scaling, area/controller, needs-cherry-pick-1.1, priority/critical-urgent, status/PTAL

#1816 Enable defaulting for tidbcluster
  charts/tidb-operator/values.yaml
  ci/deploy_tidb_operator_staging.groovy
  pkg/apis/pingcap/v1alpha1/defaulting/tidbcluster.go
Labels: area/webhook, needs-cherry-pick-1.1, priority/critical-urgent

#1807 show cli flags in logs
  cmd/admission-webhook/main.go
  cmd/controller-manager/main.go
  cmd/discovery/main.go
  cmd/scheduler/main.go
Labels: CanMerge, needs-cherry-pick-1.1
