Repository pingcap/tidb-operator, pull requests merged in 2020-03, with the labels that each got.

#1824 use k8s standard tls secret format
  charts/tidb-cluster/templates/_helpers.tpl
  charts/tidb-cluster/templates/config/_prometheus-config.tpl
  charts/tidb-cluster/templates/config/_pump-config.tpl
  charts/tidb-cluster/values.yaml
  charts/tidb-drainer/templates/_helpers.tpl
  hack/create-cert.sh
  pkg/controller/secret_control.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/pump_member_manager.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tidb_member_manager_test.go
  pkg/manager/member/tikv_member_manager.go
  pkg/monitor/monitor/template.go
  pkg/pdapi/pdapi.go
Labels: CanMerge

#1832 Refactor Admission Webhook templates and values
  charts/tidb-operator/templates/admission/admission-webhook-registration.yaml
  charts/tidb-operator/templates/admission/pre-delete-job.yaml
  charts/tidb-operator/templates/controller-manager-deployment.yaml
  charts/tidb-operator/values.yaml
  ci/deploy_tidb_operator_staging.groovy
  tests/actions.go
Labels: area/webhook, enhancement, needs-cherry-pick-1.1, status/PTAL

#1831 Make evict leader scheduler compatitable
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/pd_config.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/member/pd_upgrader.go
  pkg/manager/member/tikv_upgrader.go
  pkg/webhook/pod/tikv_creater.go
Labels: CanMerge, area/webhook, needs-cherry-pick-1.1, priority/critical-urgent

#1839 support kubetest2 on non-linux platforms
  hack/lib.sh
Labels: needs-cherry-pick-1.1

#1845 Fix defaulting bug
  pkg/apis/pingcap/v1alpha1/defaulting/tidbcluster.go
Labels: needs-cherry-pick-1.1

#1834 Default TidbMonitor targetRef Namespace
  pkg/monitor/monitor/monitor_manager.go
Labels: area/monitor, needs-cherry-pick-1.1, type/bug

#1851 disable current delete slot annotations check in Advanced Statefulset upgrader
  pkg/upgrader/upgrader.go
  pkg/upgrader/upgrader_test.go
Labels: needs-cherry-pick-1.1

#1854 add hack/local-up-operator.sh to run tidb-operator locally and test examples
  .github/workflows/ci.yaml
  Makefile
  examples/basic/tidb-cluster.yaml
  hack/e2e-examples.sh
  hack/local-up-operator.sh
  tests/examples/001-basic.sh
Labels: CanMerge

#1817 Support no secret for s3/ceph
  charts/tidb-backup/templates/scripts/_start_backup.sh.tpl
  charts/tidb-backup/values.yaml
  charts/tidb-cluster/templates/scheduled-backup-cronjob.yaml
  charts/tidb-cluster/templates/scripts/_start_scheduled_backup.sh.tpl
  charts/tidb-cluster/values.yaml
Labels: contribution, needs-cherry-pick-1.1

#1835 Backup/Restore: support configuring TiKV GC life time
  cmd/backup-manager/app/backup/backup.go
  cmd/backup-manager/app/backup/manager.go
  cmd/backup-manager/app/cmd/backup.go
  cmd/backup-manager/app/cmd/export.go
  cmd/backup-manager/app/cmd/import.go
  cmd/backup-manager/app/cmd/restore.go
  cmd/backup-manager/app/export/export.go
  cmd/backup-manager/app/export/manager.go
  cmd/backup-manager/app/import/manager.go
  cmd/backup-manager/app/import/restore.go
  cmd/backup-manager/app/restore/manager.go
  cmd/backup-manager/app/restore/restore.go
  cmd/backup-manager/app/util/generic.go
  cmd/backup-manager/app/util/util.go
  images/tidb-backup-manager/Dockerfile
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/backup/backup/backup_manager.go
  pkg/backup/restore/restore_manager.go
  pkg/backup/util/util.go
Labels: CanMerge, needs-cherry-pick-1.1

#1860 Fix tidb defaulting
  pkg/apis/pingcap/v1alpha1/defaulting/tidbcluster.go
Labels: needs-cherry-pick-1.1, type/bug

#1836 Backup: support TLS for br component
  cmd/backup-manager/app/backup/backup.go
  cmd/backup-manager/app/constants/constants.go
  cmd/backup-manager/app/restore/restore.go
  cmd/backup-manager/app/util/util.go
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/backup/backup/backup_manager.go
  pkg/backup/backupschedule/backup_schedule_manager.go
  pkg/backup/constants/constants.go
  pkg/backup/restore/restore_manager.go
  pkg/backup/util/util.go
Labels: CanMerge

#1859 support starting tidb-server with `-advertise-address` parameter
  charts/tidb-cluster/templates/scripts/_start_tidb.sh.tpl
  charts/tidb-cluster/values.yaml
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/member/template.go
  pkg/manager/member/tidb_member_manager.go
Labels: needs-cherry-pick-1.1

#1833 Fix hot region label setting for tikv auto-scaling
  charts/tidb-cluster/templates/scripts/_start_tikv.sh.tpl
  charts/tidb-cluster/values.yaml
  charts/tidb-operator/templates/admission/admission-webhook-rbac.yaml
  charts/tidb-operator/templates/admission/admission-webhook-registration.yaml
  charts/tidb-operator/values.yaml
  pkg/manager/member/scaler.go
  pkg/manager/member/template.go
  pkg/manager/member/tikv_member_manager.go
  pkg/manager/member/tikv_scaler.go
  pkg/manager/member/utils.go
  pkg/webhook/admission_hooks.go
  pkg/webhook/pod/pod_mutater.go
  pkg/webhook/pod/pods.go
  pkg/webhook/pod/util.go
Labels: area/auto-scaling, area/webhook, enhancement, needs-cherry-pick-1.1, priority/important-soon, status/PTAL

#1869 Change the lightning restore image
  charts/tidb-lightning/values.yaml
Labels: CanMerge, contribution

#1872 Manually cp 1833 and 1801
  charts/tidb-cluster/templates/scripts/_start_tikv.sh.tpl
  charts/tidb-cluster/values.yaml
  charts/tidb-operator/templates/admission/admission-webhook-rbac.yaml
  charts/tidb-operator/templates/admission/admission-webhook-registration.yaml
  charts/tidb-operator/values.yaml
  pkg/autoscaler/autoscaler/tidb_autoscaler.go
  pkg/autoscaler/autoscaler/tikv_autoscaler.go
  pkg/label/label.go
  pkg/manager/member/pd_scaler.go
  pkg/manager/member/scaler.go
  pkg/manager/member/template.go
  pkg/manager/member/tikv_member_manager.go
  pkg/manager/member/tikv_scaler.go
  pkg/manager/member/utils.go
  pkg/util/util.go
  pkg/webhook/admission_hooks.go
  pkg/webhook/pod/pod_mutater.go
  pkg/webhook/pod/pods.go
  pkg/webhook/pod/util.go
Labels: CanMerge

#1871 Fix wrong method to get tikv configmap in mutation webhook
  pkg/webhook/pod/pod_mutater.go
Labels: CanMerge, area/webhook, needs-cherry-pick-1.1, type/bug

#1875 Add timestamp annotation in tidbcluster statefulset
  cmd/controller-manager/main.go
  pkg/controller/periodicity/periodicity_controller.go
  pkg/label/label.go
  pkg/manager/member/utils.go
Labels: area/webhook, needs-cherry-pick-1.1, test/e2e, type/bug

#1873 fix drainer chart: unexpected define in command
  charts/tidb-drainer/templates/_helpers.tpl
Labels: CanMerge, needs-cherry-pick-1.1

#1881 fix kubetest2 version check
  hack/lib.sh
Labels: CanMerge, needs-cherry-pick-1.1

#1880 cleanup hack/kind-cluster-build.sh
  hack/kind-cluster-build.sh
Labels: CanMerge, needs-cherry-pick-1.1

#1876 Fix defaulting webhook error
  pkg/apis/pingcap/v1alpha1/defaulting/tidbcluster.go
  pkg/apis/pingcap/v1alpha1/validation/validation.go
  tests/e2e/tidbcluster/serial.go
Labels: CanMerge, area/webhook, needs-cherry-pick-1.1, type/bug

#1823 feature:make Service port name configurable for tidb and pd service
  charts/tidb-cluster/values.yaml
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/pd_member_manager_test.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tidb_member_manager_test.go
Labels: CanMerge, contribution, needs-cherry-pick-1.1

#1887 Fix tikv configuration key in toml and add an ut case
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tikv_config.go
  pkg/apis/pingcap/v1alpha1/tikv_config_test.go
Labels: CanMerge

#1896 Fix nil error for update statefulset util
  pkg/manager/member/utils.go
Labels: CanMerge, needs-cherry-pick-1.1, type/bug

#1882 docs about manual testing in development
  docs/CONTRIBUTING.md
  hack/local-up-operator.sh
Labels: CanMerge, needs-cherry-pick-1.1

#1889 run e2e tests in gke
  ci/e2e_gke.groovy
  hack/e2e.sh
  hack/lib.sh
  hack/run-e2e.sh
  tests/e2e/e2e.go
  tests/e2e/e2e_test.go
  tests/e2e/tidbcluster/tidbcluster.go
  tests/pkg/fixture/fixture.go
Labels: CanMerge, needs-cherry-pick-1.1

#1877 fix operator failover config invalid
  charts/tidb-operator/templates/controller-manager-deployment.yaml
Labels: contribution

#1904 Improve note of failurePolicy and revise IDC configuration
  charts/tidb-operator/values.yaml
  ci/deploy_tidb_operator_staging.groovy
Labels: CanMerge, enhancement, needs-cherry-pick-1.1

#1870 tls: TLS between TiDB components
  charts/tidb-cluster/templates/_helpers.tpl
  charts/tidb-cluster/templates/config/_prometheus-config.tpl
  charts/tidb-cluster/templates/config/_pump-config.tpl
  charts/tidb-cluster/templates/monitor-deployment.yaml
  charts/tidb-cluster/templates/pump-statefulset.yaml
  charts/tidb-cluster/templates/tidb-cluster.yaml
  charts/tidb-cluster/values.yaml
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/defaulting/tidbcluster.go
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/tidb_control.go
  pkg/controller/tidbcluster/tidb_cluster_controller.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tidb_member_manager_test.go
  pkg/manager/member/tikv_member_manager.go
  pkg/manager/member/utils.go
  pkg/monitor/monitor/template.go
  pkg/monitor/monitor/util.go
  pkg/pdapi/pdapi.go
  pkg/util/crypto/certs.go
  pkg/util/util.go
  tests/actions.go
  tests/e2e/tidbcluster/tidbcluster.go
Labels: CanMerge

#1903 add aws ami version link
  deploy/modules/aws/tidb-cluster/variables.tf
Labels: needs-cherry-pick-1.1

#1910 add tikv-importer chart
  charts/tikv-importer/.helmignore
  charts/tikv-importer/Chart.yaml
  charts/tikv-importer/templates/_helpers.tpl
  charts/tikv-importer/templates/tikv-importer-configmap.yaml
  charts/tikv-importer/templates/tikv-importer-service.yaml
  charts/tikv-importer/templates/tikv-importer-statefulset.yaml
  charts/tikv-importer/values.yaml
Labels: contribution, needs-cherry-pick-1.1

#1919 fix prometheus scrape config issue while TLS is enabled
  charts/tidb-cluster/templates/config/_prometheus-config.tpl
  pkg/monitor/monitor/template.go
  pkg/monitor/monitor/template_test.go
Labels: needs-cherry-pick-1.1

#1916 Automated cherry pick of #1870: TLS between TiDB components
  charts/tidb-cluster/templates/_helpers.tpl
  charts/tidb-cluster/templates/config/_prometheus-config.tpl
  charts/tidb-cluster/templates/config/_pump-config.tpl
  charts/tidb-cluster/templates/monitor-deployment.yaml
  charts/tidb-cluster/templates/pump-statefulset.yaml
  charts/tidb-cluster/templates/tidb-cluster.yaml
  charts/tidb-cluster/values.yaml
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/defaulting/tidbcluster.go
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/tidb_control.go
  pkg/controller/tidbcluster/tidb_cluster_controller.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tidb_member_manager_test.go
  pkg/manager/member/tikv_member_manager.go
  pkg/manager/member/utils.go
  pkg/monitor/monitor/template.go
  pkg/monitor/monitor/util.go
  pkg/pdapi/pdapi.go
  pkg/util/crypto/certs.go
  pkg/util/util.go
  tests/actions.go
  tests/e2e/tidbcluster/tidbcluster.go
Labels: CanMerge

#1908 backup: support kms decryption secret
  images/tidb-backup-manager/Dockerfile
  images/tidb-backup-manager/entrypoint.sh
  manifests/backup/backup-aws-s3-br.yaml
  manifests/backup/backup-s3-br.yaml
  manifests/backup/backup-schedule-aws-s3-br.yaml
  manifests/backup/backup-schedule-s3-br.yaml
  manifests/backup/restore-aws-s3-br.yaml
  manifests/backup/restore-s3-br.yaml
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/backup/backup/backup_cleaner.go
  pkg/backup/backup/backup_manager.go
  pkg/backup/constants/constants.go
  pkg/backup/restore/restore_manager.go
  pkg/backup/util/util.go
Labels: CanMerge, needs-cherry-pick-1.1, release-note-action-required

#1925 Automated cherry pick of #1919: fix prometheus scrape config while tls is enabled
  charts/tidb-cluster/templates/config/_prometheus-config.tpl
  pkg/monitor/monitor/template.go
  pkg/monitor/monitor/template_test.go
Labels: CanMerge

#1629 Support sync bucket in lightning
  charts/tidb-lightning/templates/job.yaml
  charts/tidb-lightning/templates/scripts/_start_data_retriever.sh.tpl
  charts/tidb-lightning/templates/scripts/_start_lightning.sh.tpl
  charts/tidb-lightning/values.yaml
Labels: needs-cherry-pick-1.1

#1929 Add API document and its generating util
  .gitignore
  docs/api-references/config.json
  docs/api-references/docs.html
  docs/api-references/template/members.tpl
  docs/api-references/template/pkg.tpl
  docs/api-references/template/type.tpl
  hack/lib.sh
  hack/update-crd-groups.sh
  hack/verify-crd-groups.sh
Labels: CanMerge, enhancement, needs-cherry-pick-1.1, status/PTAL

#1933 defaulting tikv container privileged field
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/manager/member/tikv_member_manager.go
Labels: CanMerge, needs-cherry-pick-1.1

#1930 Backup: make tikv support add serviceaccount and switch rclone env_auth to true
  docs/api-references/docs.html
  images/tidb-backup-manager/entrypoint.sh
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/manager/member/tikv_member_manager.go
Labels: CanMerge, needs-cherry-pick-1.1, release-note-action-required

#1850 re comment pd service yaml value
  charts/tidb-cluster/values.yaml
Labels: CanMerge, contribution, needs-cherry-pick-1.1

#1934 check tidb clusters which own builtin StatefulSets only in upgrading
  pkg/upgrader/upgrader.go
  pkg/upgrader/upgrader_test.go
Labels: needs-cherry-pick-1.1

#1961 fix drainer installation error
  charts/tidb-drainer/templates/_helpers.tpl
Labels: needs-cherry-pick-1.0, needs-cherry-pick-1.1

#1957 fix bug in e2e-examples script
  hack/e2e-examples.sh
Labels: CanMerge, needs-cherry-pick-1.1

#1959 Adding tolerations and affinity to the discovery chart template
  charts/tidb-cluster/templates/discovery-deployment.yaml
  charts/tidb-cluster/values.yaml
Labels: CanMerge, contribution, needs-cherry-pick-1.1

#1954 update permission for tidb-controller-manager and add example for tidb-monitor
  charts/tidb-operator/templates/controller-manager-rbac.yaml
  manifests/monitor/tidb-monitor.yaml
Labels: needs-cherry-pick-1.1

#1963 Fix some webhook error
  charts/tidb-operator/templates/admission/admission-webhook-deployment.yaml
  cmd/admission-webhook/main.go
  pkg/webhook/pod/pods.go
  pkg/webhook/pod/tikv_deleter.go
  pkg/webhook/pod/tikv_deleter_test.go
Labels: CanMerge, area/webhook, needs-cherry-pick-1.1, priority/critical-urgent, type/bug

#1955 backup： fix kms bug
  pkg/backup/backup/backup_cleaner.go
  pkg/backup/backup/backup_manager.go
  pkg/backup/restore/restore_manager.go
  pkg/backup/util/util.go
Labels: CanMerge, needs-cherry-pick-1.1

#1970 backup: mask visual tables when dumper
  cmd/backup-manager/app/export/export.go
Labels: CanMerge, needs-cherry-pick-1.1

#1972 add a serial test for stable scheduling
  tests/actions.go
  tests/cmd/stability/main.go
  tests/e2e/tidbcluster/serial.go
  tests/e2e/tidbcluster/tidbcluster.go
Labels: needs-cherry-pick-1.1

#1931 make tidb-initializer support TLS
  charts/tidb-cluster/values.yaml
  docs/api-references/docs.html
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/controller/tidbinitializer/tidb_initializer_controller.go
  pkg/manager/member/template.go
  pkg/manager/member/tidb_init_manager.go
  pkg/util/util.go
Labels: CanMerge, needs-cherry-pick-1.1

#1974 some cleanups in e2e
  hack/lib.sh
  hack/run-e2e.sh
  tests/images/test-apiserver/Dockerfile
Labels: CanMerge, needs-cherry-pick-1.1, test/e2e

#1979 TLS support for Pump and Drainer
  charts/tidb-drainer/templates/_helpers.tpl
  charts/tidb-drainer/templates/drainer-statefulset.yaml
  charts/tidb-drainer/values.yaml
  pkg/manager/member/pump_member_manager.go
Labels: CanMerge, needs-cherry-pick-1.1

#1962 Fix TidbMonitor several error
  pkg/controller/generic_control.go
  pkg/monitor/monitor/monitor_manager.go
  pkg/monitor/monitor/util.go
  tests/e2e/tidbcluster/tidbcluster.go
  tests/pkg/fixture/fixture.go
Labels: CanMerge, area/monitor, needs-cherry-pick-1.1, priority/critical-urgent, status/PTAL

#1975 lightning: support lightning use IAM
  charts/tidb-lightning/templates/job.yaml
  charts/tidb-lightning/values.yaml
Labels: CanMerge

#1989 configure default parameters via envs in Jenkins job
  ci/e2e_eks.groovy
  ci/e2e_gke.groovy
Labels: needs-cherry-pick-1.1

#1991 fix clean-eks script bug
  ci/aws-clean-eks.sh
Labels: needs-cherry-pick-1.1

#1772 Add doc and examples for auto-scaler and intializer
  examples/auto-scale/README.md
  examples/auto-scale/tidb-cluster-auto-scaler.yaml
  examples/auto-scale/tidb-cluster.yaml
  examples/auto-scale/tidb-monitor.yaml
  examples/initialize/README.md
  examples/initialize/tidb-cluster.yaml
  examples/initialize/tidb-initializer.yaml
Labels: area/doc, needs-cherry-pick-1.1

#1988 backup: support br compatible with new TLS interface
  cmd/backup-manager/app/backup/backup.go
  cmd/backup-manager/app/restore/restore.go
  docs/api-references/docs.html
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/backup/backup/backup_manager.go
  pkg/backup/restore/restore_manager.go
Labels: needs-cherry-pick-1.1, release-note-action-required

#1997 Mount google-cloud-sdk into e2e image
  hack/run-e2e.sh
  tests/images/e2e/Dockerfile
  tests/images/e2e/entrypoint.sh
Labels: needs-cherry-pick-1.1

#1986 add stability e2e group and a basic case
  ci/e2e_kind.groovy
  ci/pingcap_tidb_operator_build_kind.groovy
  hack/lib.sh
  tests/e2e/e2e.go
  tests/e2e/tidbcluster/serial.go
  tests/e2e/tidbcluster/stability.go
  tests/e2e/util/pod/pod.go
  tests/e2e/util/tidb/tidb.go
Labels: needs-cherry-pick-1.1

#1938 Allocate tidb.initializer.resources to initcontainer in tidb initiali…
  charts/tidb-cluster/templates/tidb-initializer-job.yaml
  charts/tidb-cluster/values.yaml
Labels: CanMerge, contribution, needs-cherry-pick-1.1

#2006 pin alicloud version to fix ci errors
  deploy/modules/aliyun/tidb-operator/versions.tf
Labels: needs-cherry-pick-1.1

#2007 improve orphan pods clean logic
  pkg/controller/pod_control.go
  pkg/manager/member/orphan_pods_cleaner.go
  pkg/manager/member/orphan_pods_cleaner_test.go
Labels: needs-cherry-pick-1.1

#2010 fix args passing in run-e2e.sh
  hack/run-e2e.sh
  tests/e2e/e2e_test.go
Labels: needs-cherry-pick-1.1

#1906 Update TiDB Config to v3.1.0
  docs/api-references/docs.html
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidb_config.go
  pkg/apis/pingcap/v1alpha1/tidb_config_test.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
Labels: CanMerge, enhancement, needs-cherry-pick-1.1, status/PTAL

#1928 Update PD Config to v3.1.0
  docs/api-references/docs.html
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/pd_config.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
Labels: needs-cherry-pick-1.1, status/PTAL

#2004 create tidb cluster with cr on aws
  deploy/aws/clusters.tf
  deploy/aws/manifests/db-monitor.yaml.example
  deploy/aws/manifests/db.yaml.example
  deploy/aws/variables.tf
Labels: CanMerge, needs-cherry-pick-1.1

#2003 Backup: open mysql client TLS in backup
  cmd/backup-manager/app/backup/manager.go
  cmd/backup-manager/app/export/manager.go
  cmd/backup-manager/app/import/manager.go
  cmd/backup-manager/app/restore/manager.go
  cmd/backup-manager/app/util/generic.go
  docs/api-references/docs.html
  manifests/backup/backup-aws-s3-br.yaml
  manifests/backup/backup-s3-br.yaml
  manifests/backup/backup-schedule-aws-s3-br.yaml
  manifests/backup/backup-schedule-s3-br.yaml
  manifests/backup/restore-aws-s3-br.yaml
  manifests/backup/restore-s3-br.yaml
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/backup/backup/backup_cleaner.go
  pkg/backup/backup/backup_manager.go
  pkg/backup/restore/restore_manager.go
Labels: CanMerge, needs-cherry-pick-1.1, release-note-action-required

#2012 create tidb cluster on ack with cr
  deploy/aliyun/main.tf
  deploy/aliyun/manifests/db-monitor.yaml.example
  deploy/aliyun/manifests/db.yaml.example
  deploy/aliyun/variables.tf
  deploy/modules/aliyun/tidb-cluster/main.tf
  deploy/modules/aliyun/tidb-cluster/variables.tf
  deploy/modules/aliyun/tidb-operator/operator.tf
Labels: needs-cherry-pick-1.1

#1965 Add tikv store limit pattern
  pkg/manager/member/tikv_member_manager.go
Labels: needs-cherry-pick-1.1, priority/important-longterm, status/PTAL

#2023 fix default value of separateSlowLog
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
Labels: needs-cherry-pick-1.1

#1943 UCP: additionalPrinterColumns tidbautoscaler
  manifests/crd.yaml
  pkg/util/crdutil.go
Labels: CanMerge, contribution, needs-cherry-pick-1.1

#2015 Limit Autofailure condition
  docs/api-references/docs.html
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/defaulting/tidbcluster.go
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/controller/tidbcluster/tidb_cluster_control.go
  pkg/manager/member/tidb_failover.go
  pkg/manager/member/tidb_failover_test.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tidb_member_manager_test.go
  pkg/manager/member/tikv_failover.go
  pkg/manager/member/tikv_failover_test.go
  pkg/manager/member/tikv_member_manager.go
Labels: CanMerge, needs-cherry-pick-1.1, priority/important-longterm

#2032 don't run on k8s-node for PR jobs
  ci/pingcap_tidb_operator_build_kind.groovy
Labels: needs-cherry-pick-1.1

#2031 Fix the error that `kubectl get tc` cannot show correct images
  docs/api-references/docs.html
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tikv_member_manager.go
  pkg/manager/member/utils.go
  pkg/util/crdutil.go
Labels: needs-cherry-pick-1.1, type/bug

#2036 remove dependencies on k8s-node
  ci/pingcap_tidb_operator_build_kind.groovy
  ci/upload-binaries-charts.sh
Labels: needs-cherry-pick-1.1

#2039 examples for advanced statefulset
  examples/advanced-statefulset/tidb-cluster-scaled.yaml
  examples/advanced-statefulset/tidb-cluster.yaml
Labels: needs-cherry-pick-1.1

#2027 Deploy TiDB Cluster with CR via TiDB Operator v1.1 on GKE
  deploy/gcp/examples/tidb-customized.tfvars
  deploy/gcp/manifests/db-monitor.yaml.example
  deploy/gcp/manifests/db.yaml.example
  deploy/gcp/outputs.tf
  deploy/gcp/tidbclusters.tf
  deploy/gcp/variables.tf
  deploy/modules/gcp/tidb-cluster/data.tf
  deploy/modules/gcp/tidb-cluster/main.tf
  deploy/modules/gcp/tidb-cluster/variables.tf
Labels: CanMerge, needs-cherry-pick-1.1

#2029 install tidb-operator in test namespace in non-parallel test specs
  tests/e2e/tidbcluster/serial.go
  tests/e2e/tidbcluster/stability.go
Labels: needs-cherry-pick-1.1

#2052 Able to configure custom env for components
  docs/api-references/docs.html
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbcluster_component.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/validation/validation.go
  pkg/apis/pingcap/v1alpha1/validation/validation_test.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/pd_member_manager_test.go
  pkg/manager/member/pump_member_manager.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tikv_member_manager.go
  pkg/monitor/monitor/util.go
  pkg/util/util.go
  pkg/util/utils_test.go
Labels: needs-cherry-pick-1.1

#2013 add spec.paused field to pause the syncing of tidb cluster
  docs/api-references/docs.html
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/pump_member_manager.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tikv_member_manager.go
  tests/e2e/tidbcluster/tidbcluster.go
Labels: CanMerge

#2045 Default Tidb Log File Configuration
  docs/api-references/docs.html
  pkg/apis/pingcap/v1alpha1/defaulting/tidbcluster.go
  pkg/apis/pingcap/v1alpha1/defaulting/tidbcluster_test.go
  pkg/apis/pingcap/v1alpha1/pd_config.go
  pkg/apis/pingcap/v1alpha1/tidb_config.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
Labels: enhancement, needs-cherry-pick-1.1

#2051 Fix TidbMonitor Service Label
  pkg/label/label.go
  pkg/monitor/monitor/util.go
  tests/e2e/tidbcluster/tidbcluster.go
Labels: CanMerge, area/monitor, needs-cherry-pick-1.1

#2062 backup: fix issue #2028
  cmd/backup-manager/app/backup/backup.go
  cmd/backup-manager/app/backup/manager.go
  cmd/backup-manager/app/cmd/backup.go
  cmd/backup-manager/app/cmd/restore.go
  cmd/backup-manager/app/restore/manager.go
  cmd/backup-manager/app/restore/restore.go
  cmd/backup-manager/app/util/generic.go
  docs/api-references/docs.html
  manifests/backup/backup-aws-s3-br.yaml
  manifests/backup/backup-s3-br.yaml
  manifests/backup/backup-schedule-aws-s3-br.yaml
  manifests/backup/backup-schedule-s3-br.yaml
  manifests/backup/restore-aws-s3-br.yaml
  manifests/backup/restore-s3-br.yaml
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/backup/backup/backup_manager.go
  pkg/backup/restore/restore_manager.go
  pkg/controller/backup/backup_controller.go
  pkg/controller/restore/restore_controller.go
Labels: CanMerge, needs-cherry-pick-1.1

#2061 cert-allowed-cn support
  charts/tidb-drainer/templates/_helpers.tpl
  charts/tidb-drainer/values.yaml
  docs/api-references/docs.html
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/pd_config.go
  pkg/apis/pingcap/v1alpha1/tidb_config.go
  pkg/apis/pingcap/v1alpha1/tikv_config.go
  pkg/apis/pingcap/v1alpha1/validation/validation.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/tidb_control.go
  pkg/manager/member/pump_member_manager.go
Labels: CanMerge, needs-cherry-pick-1.1

#2076 remove enableAdvertiseAddress field, --advertise-address should be always configured
  charts/tidb-cluster/templates/scripts/_start_tidb.sh.tpl
  charts/tidb-cluster/values.yaml
  docs/api-references/docs.html
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/member/template.go
  pkg/manager/member/tidb_member_manager.go
Labels: needs-cherry-pick-1.1

#2071 backup: fix issue 1657
  cmd/backup-manager/app/backup/backup.go
  cmd/backup-manager/app/restore/restore.go
Labels: CanMerge, needs-cherry-pick-1.1

#2068 use tidb-lightning in restore instead of loader
  cmd/backup-manager/app/import/restore.go
  images/tidb-backup-manager/Dockerfile
Labels: CanMerge, needs-cherry-pick-1.1, status/PTAL

#2086 should not change relative order of envs
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/pd_member_manager_test.go
  pkg/manager/member/pump_member_manager.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tikv_member_manager.go
  pkg/util/util.go
  pkg/util/utils_test.go
Labels: needs-cherry-pick-1.1

#2072 release v1.1.0-rc.1
  CHANGELOG-1.1.md
  charts/tidb-cluster/values.yaml
  charts/tidb-operator/values.yaml
  deploy/gcp/variables.tf
  tests/manifests/stability/stability.yaml
Labels: needs-cherry-pick-1.1
