Repository pingcap/tidb-operator, pull requests merged in 2020-11, with the labels that each got.

#3443 Skip set gc life time
  cmd/backup-manager/app/backup/manager.go
  cmd/backup-manager/app/import/manager.go
  cmd/backup-manager/app/restore/manager.go
  cmd/backup-manager/app/util/util_test.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/backup/backup/backup_manager.go
  pkg/backup/restore/restore_manager.go
  pkg/backup/util/util.go
  pkg/backup/util/utils_test.go
  pkg/controller/backup/backup_controller_test.go
  pkg/controller/backupschedule/backup_schedule_controller_test.go
  pkg/controller/controller_utils_test.go
  pkg/controller/restore/restore_controller_test.go
  tests/pkg/fixture/fixture.go
Labels: needs-cherry-pick-1.1

#3448 Fix PD member name error for multi cluster
  pkg/controller/pd_control.go
  pkg/manager/member/pd_scaler.go
Labels: status/LGT2

#3453 Automated cherry pick of #3443: skip setting GC life time if spec.from or spec.to is not
  cmd/backup-manager/app/backup/manager.go
  cmd/backup-manager/app/import/manager.go
  cmd/backup-manager/app/restore/manager.go
  cmd/backup-manager/app/util/util_test.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/backup/backup/backup_manager.go
  pkg/backup/restore/restore_manager.go
  pkg/backup/util/util.go
  pkg/backup/util/utils_test.go
  pkg/controller/backup/backup_controller_test.go
  pkg/controller/backupschedule/backup_schedule_controller_test.go
  pkg/controller/controller_utils_test.go
  pkg/controller/restore/restore_controller_test.go
  tests/pkg/fixture/fixture.go
Labels: status/LGT1

#3444 pd and tidb nodeTypes support storageVolumes
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/pd_member_manager_test.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tidb_member_manager_test.go
  pkg/manager/member/tikv_member_manager.go
  pkg/manager/member/tikv_member_manager_test.go
  pkg/util/util.go
  pkg/util/utils_test.go
  tests/e2e/tidbcluster/tidbcluster.go
Labels: status/LGT2

#3456 Fix pd scale in to 0
  pkg/manager/member/pd_scaler.go
  pkg/manager/member/pd_scaler_test.go
Labels: first-time-contributor, needs-cherry-pick-1.1, status/LGT2

#3464 Fix invalid args in stale action
  .github/workflows/stale.yaml
Labels: status/LGT2

#3415 Add e2e test for autoscaling
  pkg/autoscaler/autoscaler/calculate/calculate.go
  tests/e2e/e2e.go
  tests/e2e/tidbcluster/serial.go
  tests/e2e/tidbcluster/tidbcluster.go
  tests/e2e/util/image/image.go
  tests/pkg/mock/monitor.go
  tests/pkg/mock/util.go
Labels: status/LGT2

#3461 Remove duplicate code in tidb_member_manager_test.go file.
  pkg/manager/member/tidb_member_manager_test.go
Labels: needs-cherry-pick-1.1, status/LGT2

#3473 update e2e for auto-scaling
  tests/e2e/tidbcluster/tidbcluster.go
Labels: status/LGT2

#3446 Imporve test of pkg/backup
  docs/api-references/docs.md
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/backup/backup/backup_cleaner.go
  pkg/backup/backup/backup_manager.go
  pkg/backup/backup/backup_test.go
  pkg/backup/backupschedule/backup_schedule_manager.go
  pkg/backup/backupschedule/backup_schedule_manager_test.go
  pkg/backup/restore/restore_manager.go
  pkg/backup/restore/restore_manager_test.go
  pkg/controller/dependences.go
  pkg/controller/dependences_test.go
Labels: CanMerge, needs-cherry-pick-1.1, status/LGT2, status/PTAL

#3475 ci: add a dedicated pipeline for nightly build
  ci/release-nightly.groovy
Labels: CanMerge, needs-cherry-pick-1.1, status/LGT2, test/ci

#3471 add init container for BR backup/restore to supply the BR bin
  cmd/backup-manager/app/backup/backup.go
  cmd/backup-manager/app/restore/restore.go
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/backup/backup/backup_manager.go
  pkg/backup/restore/restore_manager.go
  pkg/util/util.go
Labels: CanMerge, needs-cherry-pick-1.1, status/LGT2

#3465 add some unit tests for pkg/controller
  .codecov.yml
  pkg/controller/controller_utils_test.go
  pkg/controller/generic_control_test.go
  pkg/manager/member/tikv_member_manager_test.go
Labels: CanMerge, status/LGT2, test/unit

#3480 Increase timeout of lint in case timeout at ci
  hack/verify-lint.sh
  pkg/backup/backupschedule/backup_schedule_manager_test.go
Labels: needs-cherry-pick-1.1, status/LGT1, status/PTAL

#3483 Automated cherry pick of #3471: add init container for BR backup/restore to supply the BR
  cmd/backup-manager/app/backup/backup.go
  cmd/backup-manager/app/restore/restore.go
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/backup/backup/backup_manager.go
  pkg/backup/restore/restore_manager.go
  pkg/util/util.go
Labels: status/LGT1

#3486 Increase timeout of lint in case timeout at ci (#3480)
  hack/verify-lint.sh
  pkg/backup/backupschedule/backup_schedule_manager_test.go
Labels: status/PTAL

#3484 update resources config for tidb-monitor
  manifests/monitor/tidb-monitor.yaml
Labels: needs-cherry-pick-1.1, status/LGT1

#3488 remove RUNAsUser when init monitor pod
  pkg/monitor/monitor/util.go
Labels: first-time-contributor, needs-cherry-pick-1.1, status/LGT2

#3490 bump core components version to v4.0.8 & charts version to v1.1.7
  charts/tidb-cluster/values.yaml
  charts/tidb-drainer/values.yaml
  charts/tidb-lightning/values.yaml
  charts/tidb-operator/values.yaml
  charts/tikv-importer/values.yaml
  deploy/aliyun/manifests/db-monitor.yaml.example
  deploy/aliyun/manifests/db.yaml.example
  deploy/aliyun/variables.tf
  deploy/aws/manifests/db-monitor.yaml.example
  deploy/aws/manifests/db.yaml.example
  deploy/aws/variables.tf
  deploy/gcp/manifests/db-monitor.yaml.example
  deploy/gcp/manifests/db.yaml.example
  deploy/gcp/variables.tf
  deploy/modules/aliyun/tidb-cluster/variables.tf
  deploy/modules/aws/tidb-cluster/variables.tf
  deploy/modules/gcp/tidb-cluster/variables.tf
  deploy/modules/share/tidb-cluster-release/variables.tf
  examples/advanced-statefulset/tidb-cluster-scaled.yaml
  examples/advanced-statefulset/tidb-cluster.yaml
  examples/advanced/tidb-cluster.yaml
  examples/auto-scale/tidb-cluster.yaml
  examples/auto-scale/tidb-monitor.yaml
  examples/aws/tidb-cluster.yaml
  examples/aws/tidb-monitor.yaml
  examples/basic-cn/tidb-cluster.yaml
  examples/basic-cn/tidb-monitor.yaml
  examples/basic/tidb-cluster.yaml
  examples/basic/tidb-monitor.yaml
  examples/gcp/tidb-cluster.yaml
  examples/gcp/tidb-monitor.yaml
  examples/heterogeneous-tls/heterogeneous-cluster.yaml
  examples/heterogeneous-tls/tidb-cluster.yaml
  examples/heterogeneous-tls/tidb-monitor.yaml
  examples/heterogeneous/heterogeneous-cluster.yaml
  examples/heterogeneous/tidb-cluster.yaml
  examples/heterogeneous/tidb-monitor.yaml
  examples/initialize/tidb-cluster.yaml
  examples/monitor-multiple-cluster-non-tls/ns1-cluster.yaml
  examples/monitor-multiple-cluster-non-tls/ns2-cluster.yaml
  examples/monitor-multiple-cluster-non-tls/tidb-monitor.yaml
  examples/monitor-with-externalConfigMap/tidb-monitor.yaml
  examples/multi-cluster/tidb-cluster-1.yaml
  examples/multi-cluster/tidb-cluster-2.yaml
  examples/multiple-pv-tikv/tidb-cluster.yaml
  examples/selfsigned-tls/tidb-cluster.yaml
  examples/tiflash/tidb-cluster.yaml
  examples/tiflash/tidb-monitor.yaml
  images/tidb-backup-manager/Dockerfile
Labels: needs-cherry-pick-1.1, status/LGT2

#3498 update the path of filemgr
  ci/upload-binaries-charts.sh
Labels: needs-cherry-pick-1.1

#3500 fix UCLOUD_UFILE_PROXY_HOST
  ci/pull_e2e_kind.groovy
  ci/release-nightly.groovy
Labels: needs-cherry-pick-1.1

#3502 update filemgr config file
  ci/upload-binaries-charts.sh
Labels: needs-cherry-pick-1.1

#3457 parse flag of webhook
  cmd/admission-webhook/main.go
Labels: CanMerge, needs-cherry-pick-1.1, status/LGT2

#3492 add some unit tests for cmd/backup-manager/app/util
  cmd/backup-manager/app/util/util_test.go
Labels: status/LGT2, test/unit

#3505 ci: fix ngihtly build
  ci/release-nightly.groovy
Labels: needs-cherry-pick-1.1, status/LGT1, test/ci

#3507 Fix logic in UpdateMetainfo for update info to pvc when multi-clustesr enabled
  pkg/controller/pod_control.go
  pkg/controller/pod_control_test.go
Labels: status/LGT2

#3523 Refine basic examples about "max-open-files" for TiKV
  examples/basic-cn/tidb-cluster.yaml
  examples/basic/tidb-cluster.yaml
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge

#3516 Update examples for multi-cluster
  examples/multi-cluster/tidb-cluster-1.yaml
  examples/multi-cluster/tidb-cluster-2.yaml
Labels: status/LGT1

#3519 improve codegen for golang code
  docs/CONTRIBUTING.md
  hack/update-codegen.sh
Labels: needs-cherry-pick-1.1, status/LGT1

#3521 Import table filter
  cmd/backup-manager/app/import/import.go
  cmd/backup-manager/app/import/manager.go
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge

#3440 tidbmonitor deployment smooth migration to statefulset
  docs/api-references/docs.md
  pkg/apis/pingcap/v1alpha1/tidbmonitor_types.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/validation/validation.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/pv_control.go
  pkg/controller/pvc_control.go
  pkg/controller/tidbmonitor/tidb_monitor_control.go
  pkg/controller/tidbmonitor/tidb_monitor_controller.go
  pkg/manager/member/dm_master_member_manager.go
  pkg/manager/member/dm_worker_member_manager.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/pump_member_manager.go
  pkg/manager/member/ticdc_member_manager.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tiflash_member_manager.go
  pkg/manager/member/tikv_member_manager.go
  pkg/manager/member/utils.go
  pkg/manager/meta/meta_manager.go
  pkg/monitor/monitor/monitor_manager.go
  pkg/monitor/monitor/monitor_manager_test.go
  pkg/monitor/monitor/util.go
  pkg/monitor/monitor/util_test.go
  pkg/util/util.go
  tests/e2e/tidbcluster/serial.go
  tests/e2e/tidbcluster/tidbcluster.go
  tests/pkg/fixture/fixture.go
Labels: status/LGT2, status/can-merge

#3534 remove br binary in tidb-backup-manager image
  images/tidb-backup-manager/Dockerfile
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge

#3517 add local volume support for Backup/Restore using BR
  cmd/backup-manager/app/backup/backup.go
  cmd/backup-manager/app/backup/manager.go
  cmd/backup-manager/app/clean/clean.go
  cmd/backup-manager/app/export/manager.go
  cmd/backup-manager/app/restore/manager.go
  cmd/backup-manager/app/restore/restore.go
  cmd/backup-manager/app/util/remote.go
  cmd/backup-manager/app/util/util.go
  cmd/backup-manager/app/util/util_test.go
  docs/api-references/docs.md
  examples/backup/backup-nfs.yaml
  examples/backup/backup-schedule-nfs.yaml
  examples/backup/restore-nfs.yaml
  hack/update-crd-groups.sh
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/backup.go
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbcluster_component.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/backup/backup/backup_cleaner.go
  pkg/backup/backup/backup_manager.go
  pkg/backup/backup/backup_test.go
  pkg/backup/backupschedule/backup_schedule_manager.go
  pkg/backup/restore/restore_manager.go
  pkg/backup/restore/restore_manager_test.go
  pkg/backup/testutils/br.go
  pkg/backup/testutils/helpers.go
  pkg/backup/util/util.go
  pkg/controller/backup/backup_control.go
  pkg/controller/dependences.go
  pkg/manager/member/dm_master_member_manager.go
  pkg/manager/member/dm_worker_member_manager.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tiflash_member_manager.go
  pkg/manager/member/tikv_member_manager.go
  pkg/util/util.go
  pkg/util/utils_test.go
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge

#3535 fix: when tls client is enabled for tidb, br will crash the controller manager
  pkg/backup/backup/backup_manager.go
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge

#3532 Monitor: support monitoring lightning with TLS enabled
  pkg/monitor/monitor/template.go
  pkg/monitor/monitor/template_test.go
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge
