Repository pingcap/tidb-operator, pull requests merged in 2020-08, with the labels that each got.

#3045 chart/tidb-operator: add appVersion & maintainers fields
  charts/tidb-operator/Chart.yaml
  ci/release_tidb_operator_binary_and_image.groovy
Labels: needs-cherry-pick-1.1, status/LGT2

#3047 webhook: Register Strategy AdmissionHook at a separate API endpoint
  charts/tidb-operator/templates/admission/admission-webhook-registration.yaml
  cmd/admission-webhook/main.go
  pkg/webhook/admission_hooks.go
  pkg/webhook/strategy/webhook.go
  pkg/webhook/strategy/webhook_test.go
Labels: needs-cherry-pick-1.1, status/LGT2

#3054 add a chaos e2e job
  .github/workflows/chaos.yaml
Labels: needs-cherry-pick-1.1, status/LGT2

#3060 create a small cluster in github actions job
  .github/workflows/chaos.yaml
  .golangci.yml
  hack/run-e2e.sh
Labels: needs-cherry-pick-1.1, status/LGT1

#3049 support tls for tiflash
  docs/api-references/docs.md
  pkg/apis/pingcap/v1alpha1/tiflash_config.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/member/tiflash_member_manager.go
  pkg/manager/member/tiflash_util.go
  pkg/manager/member/tiflash_util_test.go
Labels: needs-cherry-pick-1.1, status/LGT2

#3064 close etcd client when tls enabled
  pkg/manager/member/tidbcluster_status_manager.go
  pkg/pdapi/pdetcd.go
Labels: needs-cherry-pick-1.1, status/LGT2

#3057 Use mysqlclient image in initcontainer (#3042)
  pkg/manager/member/tidb_init_manager.go
Labels: CanMerge, contribution, needs-cherry-pick-1.1, status/LGT2

#3067 add proposal for deploy tidb cluster across kubernetes clusters
  docs/design-proposals/2020-08-03-deploy-tidb-cluster-across-mulitple-kubernetes-clusters.md
Labels: CanMerge, status/LGT2

#3070 add advertise status address for tiflash
  pkg/apis/pingcap/v1alpha1/tiflash_config.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/member/tiflash_util.go
  pkg/manager/member/tiflash_util_test.go
Labels: needs-cherry-pick-1.1, status/LGT2

#3081 fix goroutine leak when tls enabled
  pkg/autoscaler/autoscaler/query/external.go
  pkg/controller/http_client.go
  pkg/controller/tidb_control.go
  pkg/pdapi/pdapi.go
Labels: needs-cherry-pick-1.1, status/LGT2

#3072 Simplify some code in pkg/autoscaler
  pkg/autoscaler/autoscaler/autoscaler_manager.go
  pkg/autoscaler/autoscaler/util.go
Labels: enhancement, needs-cherry-pick-1.1, status/LGT1, status/PTAL

#3076 Add support for max-index-length to TidbCluster CRD
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidb_config.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
Labels: needs-cherry-pick-1.1, status/LGT2

#3055 Register PodAdmissionHook/StatefulSetAdmissionHook at different API endpoints and remove AdmissionHook
  charts/tidb-operator/templates/admission/admission-webhook-registration.yaml
  cmd/admission-webhook/main.go
  pkg/webhook/admission_hooks.go
  pkg/webhook/pod/pods.go
  pkg/webhook/pod/pods_test.go
  pkg/webhook/statefulset/statefulset.go
  pkg/webhook/statefulset/statefulset_test.go
Labels: status/LGT1

#3074 mark deprecated configurations
  docs/api-references/docs.md
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/pd_config.go
  pkg/apis/pingcap/v1alpha1/tidb_config.go
  pkg/apis/pingcap/v1alpha1/tikv_config.go
Labels: CanMerge, needs-cherry-pick-1.1, status/LGT2, status/PTAL

#3003 TidbCluster controller update for cluster reference change
  docs/api-references/docs.md
  examples/heterogeneous/README.md
  examples/heterogeneous/heterogeneous-cluster.yaml
  examples/heterogeneous/tidb-cluster.yaml
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/pd_control.go
  pkg/controller/pod_control.go
  pkg/controller/tidbcluster/tidb_cluster_condition_updater.go
  pkg/controller/tidbcluster/tidb_cluster_condition_updater_test.go
  pkg/discovery/discovery.go
  pkg/manager/member/template.go
  pkg/manager/member/template_test.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tidbcluster_status_manager.go
  pkg/manager/member/tikv_group_member_manager.go
  pkg/manager/member/tikv_member_manager.go
  pkg/manager/member/tikv_upgrader.go
  pkg/webhook/pod/pods.go
  tests/actions.go
  tests/e2e/tidbcluster/tidbcluster.go
  tests/failover.go
  tests/pkg/webhook/pods.go
Labels: contribution, status/LGT3

#3089 Unified use of public method TidbCluster.IsTLSClusterEnabled.
  pkg/backup/backup/backup_manager.go
  pkg/backup/restore/restore_manager.go
Labels: CanMerge, contribution, needs-cherry-pick-1.1, status/LGT2

#3071 add dmclusters CRD
  docs/api-references/docs.md
  pkg/apis/pingcap/v1alpha1/crd_kinds.go
  pkg/apis/pingcap/v1alpha1/dm_config.go
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/pd_config.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/pingcap/v1alpha1/dmcluster.go
  pkg/client/clientset/versioned/typed/pingcap/v1alpha1/fake/fake_dmcluster.go
  pkg/client/clientset/versioned/typed/pingcap/v1alpha1/fake/fake_pingcap_client.go
  pkg/client/clientset/versioned/typed/pingcap/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/pingcap/v1alpha1/pingcap_client.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/pingcap/v1alpha1/dmcluster.go
  pkg/client/informers/externalversions/pingcap/v1alpha1/interface.go
  pkg/client/listers/pingcap/v1alpha1/dmcluster.go
  pkg/client/listers/pingcap/v1alpha1/expansion_generated.go
  pkg/util/crdutil.go
Labels: status/LGT2, status/PTAL

#3091 add more tests for webhook
  pkg/webhook/pod/pd_deleter_test.go
  pkg/webhook/pod/pod_mutater.go
  pkg/webhook/pod/pods.go
  pkg/webhook/pod/pods_test.go
  pkg/webhook/pod/tikv_deleter_test.go
Labels: status/LGT2

#3093 add heterogeneous design
  docs/design-proposals/2020-06-12-heterogeneous-design-for-tidb-cluster.md
  docs/design-proposals/2020-08-10-heterogeneous-design-for-tidb-cluster.md
Labels: status/LGT3

#3101 support cert-allowed-cn for tiflash
  docs/api-references/docs.md
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tiflash_config.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/member/tiflash_util.go
  pkg/manager/member/tiflash_util_test.go
Labels: needs-cherry-pick-1.1, status/LGT2

#3100 backup: TLS Support for Backup&Restore with dumpling&lightning
  cmd/backup-manager/app/cmd/export.go
  cmd/backup-manager/app/cmd/import.go
  cmd/backup-manager/app/export/export.go
  cmd/backup-manager/app/export/manager.go
  cmd/backup-manager/app/import/import.go
  cmd/backup-manager/app/import/manager.go
  pkg/backup/backup/backup_manager.go
  pkg/backup/restore/restore_manager.go
Labels: needs-cherry-pick-1.1, status/LGT2, status/PTAL

#3095 improve UT for pod_restarter and pvc_cleaner
  pkg/discovery/server/server_test.go
  pkg/manager/member/pod_restarter.go
  pkg/manager/member/pod_restarter_test.go
  pkg/manager/member/pvc_cleaner.go
  pkg/manager/member/pvc_cleaner_test.go
Labels: CanMerge, needs-cherry-pick-1.1, status/LGT2

#2998 examples for aws/eks
  examples/aws/tidb-cluster.yaml
  examples/aws/tidb-monitor.yaml
  manifests/eks/local-volume-provisioner.yaml
Labels: needs-cherry-pick-1.1, status/LGT1

#3107 update logic of orphan pod cleaner
  pkg/manager/member/orphan_pods_cleaner.go
Labels: CanMerge, needs-cherry-pick-1.1, status/LGT2

#3116 update pd import path
  go.mod
  go.sum
  pkg/pdapi/pdapi.go
Labels: needs-cherry-pick-1.1, status/LGT2

#3103 update design for across kubernetes deploy
  docs/design-proposals/2020-08-03-deploy-tidb-cluster-across-mulitple-kubernetes-clusters.md
Labels: CanMerge, status/LGT2

#3096 Patch PVCs when storage request is increased
  charts/tidb-operator/templates/controller-manager-rbac.yaml
  pkg/controller/tidbcluster/tidb_cluster_control.go
  pkg/controller/tidbcluster/tidb_cluster_control_test.go
  pkg/controller/tidbcluster/tidb_cluster_controller.go
  pkg/manager/member/pvc_resizer.go
  pkg/manager/member/pvc_resizer_test.go
  pkg/util/util.go
Labels: CanMerge, needs-cherry-pick-1.1, status/LGT2

#3124 Automated cherry pick of #3096: Patch PVC when storage request is increased
  charts/tidb-operator/templates/controller-manager-rbac.yaml
  pkg/controller/tidbcluster/tidb_cluster_control.go
  pkg/controller/tidbcluster/tidb_cluster_control_test.go
  pkg/controller/tidbcluster/tidb_cluster_controller.go
  pkg/manager/member/pvc_resizer.go
  pkg/manager/member/pvc_resizer_test.go
  pkg/util/util.go
Labels: status/LGT1

#3105 Refactor the reclaim_policy_manager and fix TiKVGroup.GetName()
  pkg/manager/meta/reclaim_policy_manager.go
Labels: needs-cherry-pick-1.1, status/LGT2, type/refactor, type/tinyfix

#3126 Revert "Refactor the reclaim_policy_manager and fix TiKVGroup.GetName()"
  pkg/manager/meta/reclaim_policy_manager.go
Labels: status/LGT2

#3129 monitoring for tiflash when tls enabled
  pkg/monitor/monitor/template.go
  pkg/monitor/monitor/template_test.go
Labels: needs-cherry-pick-1.1, status/LGT2

#3109 Added support for Environment variables in the TidbMonitor initializer container
  pkg/monitor/monitor/util.go
  pkg/util/util.go
Labels: needs-cherry-pick-1.1, status/LGT2

#3098 dm-operator: support discovery dm-master service in current discovery service
  cmd/discovery/main.go
  pkg/apis/pingcap/v1alpha1/dmcluster.go
  pkg/discovery/discovery.go
  pkg/discovery/discovery_test.go
  pkg/discovery/server/server.go
  pkg/discovery/server/server_test.go
  pkg/dmapi/dmapi.go
  pkg/dmapi/fake_dmapi.go
  pkg/dmapi/master_control.go
  pkg/manager/member/tidb_discovery_manager.go
Labels: status/LGT2, status/PTAL

#3135 Bump tidb image versions to v4.0.4
  charts/tidb-cluster/values.yaml
  charts/tidb-drainer/values.yaml
  charts/tidb-lightning/values.yaml
  charts/tikv-importer/values.yaml
  deploy/aliyun/manifests/db-monitor.yaml.example
  deploy/aliyun/manifests/db.yaml.example
  deploy/aliyun/variables.tf
  deploy/aws/manifests/db-monitor.yaml.example
  deploy/aws/manifests/db.yaml.example
  deploy/aws/variables.tf
  deploy/gcp/manifests/db-monitor.yaml.example
  deploy/gcp/manifests/db.yaml.example
  deploy/gcp/variables.tf
  deploy/modules/aliyun/tidb-cluster/variables.tf
  deploy/modules/aws/tidb-cluster/variables.tf
  deploy/modules/gcp/tidb-cluster/variables.tf
  deploy/modules/share/tidb-cluster-release/variables.tf
  examples/advanced-statefulset/tidb-cluster-scaled.yaml
  examples/advanced-statefulset/tidb-cluster.yaml
  examples/advanced/tidb-cluster.yaml
  examples/auto-scale/tidb-cluster.yaml
  examples/auto-scale/tidb-monitor.yaml
  examples/aws/tidb-cluster.yaml
  examples/aws/tidb-monitor.yaml
  examples/basic-cn/tidb-cluster.yaml
  examples/basic-cn/tidb-monitor.yaml
  examples/basic/tidb-cluster.yaml
  examples/basic/tidb-monitor.yaml
  examples/heterogeneous/heterogeneous-cluster.yaml
  examples/heterogeneous/tidb-cluster.yaml
  examples/initialize/tidb-cluster.yaml
  examples/monitor-with-externalConfigMap/tidb-monitor.yaml
  examples/selfsigned-tls/tidb-cluster.yaml
  examples/tiflash/tidb-cluster.yaml
  examples/tiflash/tidb-monitor.yaml
  images/tidb-backup-manager/Dockerfile
Labels: needs-cherry-pick-1.1, status/LGT2, status/PTAL

#3127 update instance type for tikv
  deploy/aws/demo.tfvars
  deploy/aws/manifests/db.yaml.example
  deploy/aws/prod.tfvars
Labels: needs-cherry-pick-1.1, status/LGT2

#3134 Br backup restore table filter 2
  cmd/backup-manager/app/util/util.go
  cmd/backup-manager/app/util/util_test.go
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
Labels: CanMerge, contribution, needs-cherry-pick-1.1, status/LGT2

#3128 Refactor the reclaim_policy_manager and fix TiKVGroup.GetName()
  pkg/manager/meta/reclaim_policy_manager.go
Labels: enhancement, needs-cherry-pick-1.1, status/LGT2

#3145 optimize pvc resizer logic
  pkg/manager/member/pvc_resizer.go
Labels: needs-cherry-pick-1.1, status/LGT2

#3142 add release notes for v1.1.4 and update operator versions
  CHANGELOG-1.1.md
  charts/tidb-cluster/values.yaml
  charts/tidb-operator/values.yaml
  deploy/aliyun/variables.tf
  deploy/aws/variables.tf
  deploy/gcp/variables.tf
Labels: needs-cherry-pick-1.1, status/LGT2

#3113 tiflash with tc reference
  examples/heterogeneous/heterogeneous-cluster.yaml
  pkg/manager/member/tiflash_member_manager.go
  pkg/manager/member/tiflash_util.go
  pkg/manager/member/tiflash_util_test.go
  tests/actions.go
  tests/e2e/tidbcluster/tidbcluster.go
Labels: contribution, status/LGT2

#3160 fix heterogeneous rollingupdate bug
  pkg/manager/member/tiflash_util.go
  pkg/manager/member/tikv_member_manager.go
Labels: contribution, status/LGT2

#3155 Support tidbmonitor monitor multiple cluster.
  examples/heterogeneous/tidb-monitor.yaml
  pkg/monitor/monitor/util.go
Labels: contribution, status/LGT2

#3151 refine drainer helm chart like pump
  charts/tidb-drainer/templates/scripts/_start_drainer.sh.tpl
Labels: CanMerge, needs-cherry-pick-1.1, status/LGT2, status/PTAL

#3154 fix tidb-operator helm hook-delete-policy.
  charts/tidb-operator/templates/admission/pre-delete-job.yaml
Labels: CanMerge, contribution, needs-cherry-pick-1.1, status/LGT3

#3143 ci: upload images and charts if the build is on release-* branch
  ci/pull_e2e_kind.groovy
Labels: CanMerge, needs-cherry-pick-1.1, status/LGT2, test/ci

#3153 Fix current thanos sidecar example
  examples/monitor-with-thanos/external-configMap.yaml
  examples/monitor-with-thanos/tidb-monitor.yaml
Labels: CanMerge, contribution, needs-cherry-pick-1.1, status/LGT2

#3150 add proposal for auto-scaling with pd api
  docs/design-proposals/2020-08-21-auto-scaling-with-pdapi.md
Labels: status/LGT2

#3146 dm-operator/: support start a new dm cluster with dm-masters and dm-workers
  cmd/controller-manager/main.go
  docs/api-references/docs.md
  examples/dm/README.md
  examples/dm/dm-cluster.yaml
  go.sum
  hack/update-crd-groups.sh
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/defaulting/dmcluster.go
  pkg/apis/pingcap/v1alpha1/dmcluster.go
  pkg/apis/pingcap/v1alpha1/group_component.go
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/register.go
  pkg/apis/pingcap/v1alpha1/tidbcluster_component.go
  pkg/apis/pingcap/v1alpha1/tidbcluster_test.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/validation/validation.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/controller_utils.go
  pkg/controller/dmcluster/dm_cluster_condition_updater.go
  pkg/controller/dmcluster/dm_cluster_control.go
  pkg/controller/dmcluster/dm_cluster_controller.go
  pkg/controller/dmcluster_control.go
  pkg/controller/dmmaster_control.go
  pkg/discovery/discovery.go
  pkg/discovery/discovery_test.go
  pkg/discovery/server/server.go
  pkg/dmapi/dmapi.go
  pkg/dmapi/fake_dmapi.go
  pkg/dmapi/master_control.go
  pkg/label/label.go
  pkg/manager/manager.go
  pkg/manager/member/dm_master_member_manager.go
  pkg/manager/member/dm_worker_member_manager.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/pvc_resizer.go
  pkg/manager/member/template.go
  pkg/manager/member/ticdc_member_manager.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tiflash_member_manager.go
  pkg/manager/member/tikv_member_manager.go
  pkg/manager/member/utils.go
  pkg/manager/member/utils_test.go
  pkg/util/crdutil.go
  pkg/util/dmcluster/dmcluster.go
  pkg/webhook/pod/pods.go
Labels: status/LGT2, status/PTAL

#3123 more webhook tests
  pkg/webhook/pod/pods_test.go
  pkg/webhook/statefulset/statefulset_test.go
Labels: needs-cherry-pick-1.1, status/LGT2

#3171 use the real desired replicas in HA predicate
  pkg/scheduler/predicates/ha.go
  pkg/scheduler/predicates/ha_test.go
Labels: needs-cherry-pick-1.1, status/LGT2

#3172 dm-operator/: support graceful upgrade a dm cluster with dm-masters and dm-workers
  pkg/apis/pingcap/v1alpha1/dmcluster.go
  pkg/controller/dmcluster/dm_cluster_controller.go
  pkg/controller/dmmaster_control.go
  pkg/discovery/discovery.go
  pkg/discovery/discovery_test.go
  pkg/dmapi/dmapi.go
  pkg/dmapi/fake_dmapi.go
  pkg/dmapi/master_control.go
  pkg/manager/member/dm_master_member_manager.go
  pkg/manager/member/dm_master_upgrader.go
  pkg/manager/member/upgrader.go
  pkg/manager/member/utils.go
  pkg/util/http/httputil.go
Labels: status/LGT2, status/PTAL
