Repository pingcap/tidb-operator, pull requests merged in 2020-04, with the labels that each got.

#2038 BR e2e test in AWS
  Makefile
  hack/e2e.sh
  hack/run-e2e.sh
  tests/actions.go
  tests/config.go
  tests/e2e/config/config.go
  tests/e2e/tidbcluster/tidbcluster.go
  tests/e2e/util/image/image.go
  tests/e2e/util/tidb/tidb.go
  tests/pkg/fixture/fixture.go
Labels: CanMerge, needs-cherry-pick-1.1

#2094 readme, static: update doc links and image in readme
  README.md
  static/tidb-operator-overview.png
Labels: needs-cherry-pick-1.0, needs-cherry-pick-1.1

#2098 docs: remove unnecessary duplicated docs
  docs/aliyun-tutorial.md
  docs/aws-eks-tutorial.md
  docs/backup-restore.md
  docs/cli-manual.md
  docs/google-kubernetes-tutorial.md
  docs/minikube-tutorial.md
  docs/operation-guide.md
  docs/references/tidb-backup-configuration.md
  docs/setup.md
  docs/troubleshooting.md
  docs/user-guide.md
Labels: CanMerge, needs-cherry-pick-1.0, needs-cherry-pick-1.1

#2093 UCP: add timeout config for query metrics from Prometheus
  pkg/autoscaler/autoscaler/calculate/calculate.go
Labels: contribution, needs-cherry-pick-1.1

#2108 Fix AlertManager setting error
  pkg/monitor/monitor/template.go
  pkg/monitor/monitor/template_test.go
Labels: area/monitor, needs-cherry-pick-1.1, type/bug

#2112 Find tidb cluster owner via owner references
  pkg/controller/periodicity/periodicity_controller.go
  pkg/upgrader/upgrader.go
  pkg/upgrader/upgrader_test.go
  pkg/util/util.go
Labels: needs-cherry-pick-1.1

#2115 Update Doc util
  docs/api-references/docs.md
  docs/api-references/template/pkg.tpl
  hack/update-crd-groups.sh
  hack/verify-crd-groups.sh
Labels: CanMerge, area/doc, needs-cherry-pick-1.1

#2118 upgrade cert-manager to v0.14.1 in example tests
  tests/examples/002-selfsigned-tls.sh
Labels: CanMerge, needs-cherry-pick-1.1

#2111 Add unit test for Auto-scaling Util
  pkg/autoscaler/autoscaler/calculate/calculate_test.go
  pkg/autoscaler/autoscaler/calculate/cpu_test.go
  pkg/autoscaler/autoscaler/util_test.go
Labels: CanMerge, area/auto-scaling, needs-cherry-pick-1.1, test/unit

#2119 add a recovery test on node deletion for eks/gke
  hack/e2e.sh
  hack/run-e2e.sh
  manifests/gke/local-ssd-provision/local-ssd-provision.yaml
  manifests/local-dind/local-volume-provisioner.yaml
  pkg/pdapi/pdapi.go
  tests/actions.go
  tests/e2e/e2e.go
  tests/e2e/tidbcluster/stability.go
  tests/e2e/util/node/node.go
  tests/e2e/util/tikv/tikv.go
Labels: CanMerge, needs-cherry-pick-1.1

#2085 Set PD Dashboard Config when TLS Client enabled
  docs/api-references/docs.md
  examples/selfsigned-tls/tidb-client-cert.yaml
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/pd_config.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/member/pd_member_manager.go
Labels: CanMerge, needs-cherry-pick-1.1

#2126 support v<major>.<minor> format in KUBE_VERSION and add v1.18 support
  ci/pingcap_tidb_operator_build_kind.groovy
  hack/e2e.sh
Labels: needs-cherry-pick-1.1

#2125 kill tidb-operator pods randomly in e2e
  ci/pingcap_tidb_operator_build_kind.groovy
  tests/config.go
  tests/e2e/config/config.go
  tests/e2e/e2e.go
  tests/e2e/util/operator/operator.go
Labels: needs-cherry-pick-1.1

#2122 crd for tiflash
  docs/api-references/config.json
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/defaulting/tidbcluster.go
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tiflash_config.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/validation/validation.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/controller_utils.go
Labels: needs-cherry-pick-1.1

#2135 Make webhook tls configuration easy to use
  charts/tidb-operator/templates/admission/admission-webhook-deployment.yaml
  charts/tidb-operator/templates/admission/admission-webhook-registration.yaml
  charts/tidb-operator/templates/admission/admission-webhook-secret.yaml
  charts/tidb-operator/values.yaml
  tests/webhook.go
Labels: needs-cherry-pick-1.1

#1504 Remove unnecessary informer caches
  cmd/controller-manager/main.go
  pkg/backup/backup/backup_cleaner.go
  pkg/backup/backup/backup_manager.go
  pkg/backup/restore/restore_manager.go
  pkg/backup/util/util.go
  pkg/controller/backup/backup_controller.go
  pkg/controller/configmap_control.go
  pkg/controller/configmap_control_test.go
  pkg/controller/restore/restore_controller.go
  pkg/controller/secret_control.go
  pkg/controller/tidbcluster/tidb_cluster_controller.go
  pkg/manager/member/pd_member_manager_test.go
  pkg/manager/member/pump_member_manager.go
  pkg/manager/member/pump_member_manager_test.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tidb_member_manager_test.go
Labels: CanMerge, needs-cherry-pick-1.1

#2123 Add auto-scaling e2e test
  tests/e2e/tidbcluster/serial.go
  tests/pkg/fixture/fixture.go
Labels: needs-cherry-pick-1.1

#2145 Add e2e test for upgrading from 1.0.x
  tests/e2e/tidbcluster/serial.go
  tests/util.go
Labels: CanMerge, needs-cherry-pick-1.1, test/e2e

#2148 fix terraform destroy failure on aws
  deploy/modules/aws/tidb-operator/main.tf
Labels: CanMerge, needs-cherry-pick-1.1

#2141 scripts to run e2e against OpenShift 4
  charts/tidb-cluster/templates/monitor-rbac.yaml
  charts/tidb-operator/templates/admission/admission-webhook-deployment.yaml
  charts/tidb-operator/templates/admission/admission-webhook-service.yaml
  charts/tidb-operator/templates/controller-manager-rbac.yaml
  ci/run-in-vm.sh
  ci/vm.groovy
  hack/e2e-openshift.sh
  hack/run-e2e.sh
  hack/run-in-container.sh
  pkg/monitor/monitor/monitor_manager.go
  pkg/monitor/monitor/util.go
  tests/actions.go
  tests/e2e/e2e.go
  tests/e2e/e2e_test.go
Labels: CanMerge, needs-cherry-pick-1.1

#2153 manually cp 2145
  tests/e2e/tidbcluster/serial.go
  tests/util.go
Labels: CanMerge

#2162 Remove unnecessary informer caches (#1504)
  cmd/controller-manager/main.go
  pkg/backup/backup/backup_cleaner.go
  pkg/backup/backup/backup_manager.go
  pkg/backup/restore/restore_manager.go
  pkg/backup/util/util.go
  pkg/controller/backup/backup_controller.go
  pkg/controller/configmap_control.go
  pkg/controller/configmap_control_test.go
  pkg/controller/restore/restore_controller.go
  pkg/controller/secret_control.go
  pkg/controller/tidbcluster/tidb_cluster_controller.go
  pkg/manager/member/pd_member_manager_test.go
  pkg/manager/member/pump_member_manager.go
  pkg/manager/member/pump_member_manager_test.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tidb_member_manager_test.go
Labels: CanMerge

#2152 Automated cherry pick of #2085: support pd dashboard config
  docs/api-references/docs.md
  examples/selfsigned-tls/tidb-client-cert.yaml
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/pd_config.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/member/pd_member_manager.go
Labels: CanMerge

#2151 security: tikv encryption kms config
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tikv_config.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
Labels: CanMerge

#2143 Skip TLS when connecting to TiDB Server
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/backup/backup/backup_manager.go
  pkg/backup/restore/restore_manager.go
  pkg/label/label.go
  pkg/manager/member/pd_member_manager.go
Labels: needs-cherry-pick-1.1

#2157 deploy controller for tiflash
  charts/tidb-operator/templates/controller-manager-deployment.yaml
  charts/tidb-operator/values.yaml
  cmd/controller-manager/main.go
  docs/api-references/config.json
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/apis/pingcap/v1alpha1/tidbcluster_component.go
  pkg/apis/pingcap/v1alpha1/tiflash_config.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/validation/validation.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/tidbcluster/tidb_cluster_control.go
  pkg/controller/tidbcluster/tidb_cluster_control_test.go
  pkg/controller/tidbcluster/tidb_cluster_controller.go
  pkg/controller/tidbcluster/tidb_cluster_controller_test.go
  pkg/label/label.go
  pkg/manager/member/tiflash_failover.go
  pkg/manager/member/tiflash_member_manager.go
  pkg/manager/member/tiflash_scaler.go
  pkg/manager/member/tiflash_upgrader.go
  pkg/manager/member/tiflash_util.go
  pkg/manager/member/tiflash_util_test.go
Labels: CanMerge, needs-cherry-pick-1.1

#2168 add AGE column for all CRDs
  cmd/to-crdgen/main.go
  manifests/crd.yaml
  pkg/util/crdutil.go
Labels: needs-cherry-pick-1.1

#2166 Add unit test for restore controller
  hack/check-EOF.sh
  pkg/backup/restore/restore_manager.go
  pkg/controller/backup/backup_control_test.go
  pkg/controller/backup/backup_controller_test.go
  pkg/controller/restore/restore_control.go
  pkg/controller/restore/restore_control_test.go
  pkg/controller/restore/restore_controller_test.go
Labels: needs-cherry-pick-1.1, test/unit

#2167 fix a typo
  pkg/backup/util/util.go
Labels: contribution, needs-cherry-pick-1.1

#2150 Add more events for tidbcluster and autoscaler
  pkg/autoscaler/autoscaler/autoscaler_manager.go
  pkg/controller/tidbcluster/tidb_cluster_controller.go
  pkg/manager/member/failover.go
  pkg/manager/member/pd_failover.go
  pkg/manager/member/pd_failover_test.go
  pkg/manager/member/pd_scaler_test.go
  pkg/manager/member/tidb_failover.go
  pkg/manager/member/tidb_failover_test.go
  pkg/manager/member/tikv_failover.go
  pkg/manager/member/tikv_failover_test.go
Labels: enhancement, needs-cherry-pick-1.1

#2176 Remove unused certificate control and RBAC rules
  charts/tidb-operator/templates/controller-manager-rbac.yaml
  pkg/controller/cert_control.go
  pkg/controller/secret_control.go
  pkg/controller/tidbcluster/tidb_cluster_controller.go
  pkg/discovery/discovery.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/pd_member_manager_test.go
  pkg/manager/member/pump_member_manager.go
  pkg/manager/member/pump_member_manager_test.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tidb_member_manager_test.go
  pkg/manager/member/tiflash_member_manager.go
  pkg/manager/member/tikv_member_manager.go
Labels: needs-cherry-pick-1.1

#2181 Add more events for tidbcluster and autoscaler (#2150)
  pkg/autoscaler/autoscaler/autoscaler_manager.go
  pkg/controller/tidbcluster/tidb_cluster_controller.go
  pkg/manager/member/failover.go
  pkg/manager/member/pd_failover.go
  pkg/manager/member/pd_failover_test.go
  pkg/manager/member/pd_scaler_test.go
  pkg/manager/member/tidb_failover.go
  pkg/manager/member/tidb_failover_test.go
  pkg/manager/member/tikv_failover.go
  pkg/manager/member/tikv_failover_test.go
Labels: CanMerge

#2187 fix debug docker
  .github/workflows/ci.yaml
  misc/images/tidb-control/Dockerfile
Labels: needs-cherry-pick-1.1

#2188 use fixed names for CI jobs
  .github/workflows/ci.yaml
  Makefile
Labels: needs-cherry-pick-1.1

#2184 Add spec.pd.maxFailoverCount to limit max failover replicas for PD
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/defaulting/tidbcluster.go
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/member/pd_failover.go
  pkg/manager/member/pd_failover_test.go
  pkg/manager/member/pd_member_manager.go
  tests/e2e/tidbcluster/stability.go
Labels: CanMerge, needs-cherry-pick-1.1

#2192 fix openshift job
  ci/run-in-vm.sh
Labels: needs-cherry-pick-1.1

#2182 Support Auto-scaling status
  docs/api-references/docs.md
  examples/auto-scale/tidb-cluster.yaml
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbclusterautoscaler_types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/autoscaler/autoscaler/autoscaler_manager.go
  pkg/autoscaler/autoscaler/calculate/cpu.go
  pkg/autoscaler/autoscaler/calculate/util.go
  pkg/autoscaler/autoscaler/tidb_autoscaler.go
  pkg/autoscaler/autoscaler/tikv_autoscaler.go
Labels: area/auto-scaling, needs-cherry-pick-1.1

#2194 Wait for the VM to be ready in CI
  ci/run-in-vm.sh
  hack/e2e-openshift.sh
Labels: needs-cherry-pick-1.1

#2197 release v1.1.0-rc.2
  CHANGELOG-1.1.md
Labels: needs-cherry-pick-1.1

#2204 Update version in deployment files
  charts/tidb-cluster/values.yaml
  charts/tidb-operator/values.yaml
  deploy/gcp/variables.tf
  tests/manifests/stability/stability.yaml
Labels: needs-cherry-pick-1.1

#2198 Automated cherry pick of #2151: security: tikv encryption kms config
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tikv_config.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
Labels: CanMerge

#2213 fix br log issue and include both 3.1 and 4.0 br in the tidb-backup-manager image
  cmd/backup-manager/app/backup/backup.go
  cmd/backup-manager/app/cmd/backup.go
  cmd/backup-manager/app/cmd/restore.go
  cmd/backup-manager/app/restore/restore.go
  cmd/backup-manager/app/util/generic.go
  cmd/backup-manager/app/util/util.go
  go.mod
  go.sum
  images/tidb-backup-manager/Dockerfile
  pkg/backup/backup/backup_manager.go
  pkg/backup/restore/restore_manager.go
Labels: CanMerge, needs-cherry-pick-1.1

#2206 install python for gcloud CLI in e2e image
  tests/images/e2e/Dockerfile
Labels: needs-cherry-pick-1.1

#2222 Mock TidbMonitor in Auto-scaling e2e test
  Makefile
  pkg/autoscaler/autoscaler/calculate/calculate.go
  tests/cmd/mock-monitor/main.go
  tests/e2e/tidbcluster/serial.go
  tests/images/e2e/Dockerfile
  tests/monitor.go
  tests/pkg/mock/monitor.go
  tests/pkg/mock/util.go
Labels: area/auto-scaling, needs-cherry-pick-1.1, test/e2e

#2221 make sure we don't introduce backward incompatibility changes in the same minor series
  tests/e2e/tidbcluster/serial.go
  tests/e2e/tidbcluster/stability.go
Labels: needs-cherry-pick-1.1

#2225 update the function to get the image tag
  pkg/backup/backup/backup_manager.go
  pkg/backup/restore/restore_manager.go
  pkg/backup/util/util.go
  pkg/backup/util/utils_test.go
Labels: needs-cherry-pick-1.1

#1688 Fix stability test
  tests/actions.go
  tests/cmd/stability/main.go
  tests/e2e/util/statefulset/statefulset.go
  tests/failover.go
  tests/fault.go
Labels: needs-cherry-pick-1.1, test/stability, type/bug

#2233 Upgrade AWS SDK to support OIDC IAM roles
  go.mod
  go.sum
Labels: CanMerge, contribution, needs-cherry-pick-1.1

#2227 e2e: tls for mysql client
  ci/pingcap_tidb_operator_build_kind.groovy
  tests/e2e/tidbcluster/tidbcluster.go
  tests/e2e/tidbcluster/tls.go
  tests/e2e/util/image/image.go
  tests/images/e2e/Dockerfile
  tests/pkg/util/template.go
Labels: needs-cherry-pick-1.1

#2208 build e2e images in prepare phase
  ci/pingcap_tidb_operator_build_kind.groovy
  hack/e2e.sh
  hack/prepare-e2e.sh
  hack/run-e2e.sh
Labels: needs-cherry-pick-1.1

#2246 Upgrade for TiFlash
  pkg/manager/member/tiflash_member_manager.go
  pkg/manager/member/tiflash_upgrader.go
Labels: CanMerge, needs-cherry-pick-1.1

#2245 action required for tidb pod readiness probe change
  CHANGELOG-1.1.md
Labels: needs-cherry-pick-1.1

#2265 fix the wrong script name in `CONTRIBUTING.md`
  docs/CONTRIBUTING.md
Labels: contribution, needs-cherry-pick-1.1

#2238 Update eks version in deploy scripts
  deploy/aws/manifests/db.yaml.example
  deploy/aws/variables.tf
  deploy/modules/aws/tidb-cluster/values/default.yaml
Labels: CanMerge, area/terraform, needs-cherry-pick-1.1

#2249 failover for tiflash
  pkg/apis/pingcap/v1alpha1/defaulting/tidbcluster.go
  pkg/controller/tidbcluster/tidb_cluster_controller.go
  pkg/manager/member/tiflash_failover.go
Labels: CanMerge, needs-cherry-pick-1.1

#2272 update release notes for v1.1.0-rc.1
  CHANGELOG-1.1.md
Labels: needs-cherry-pick-1.1

#2262 e2e: reduce ephemeral storage usage and request more
  ci/pingcap_tidb_operator_build_kind.groovy
  hack/run-e2e.sh
  tests/e2e/config/config.go
  tests/e2e/e2e.go
  tests/e2e/tidbcluster/serial.go
  tests/e2e/tidbcluster/tidbcluster.go
  tests/e2e/util/image/image.go
  tests/images/e2e/Dockerfile
  tests/pkg/fixture/fixture.go
Labels: needs-cherry-pick-1.1

#2242 fix typo and other issues
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tiflash_config.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/tiflash_member_manager.go
Labels: CanMerge, needs-cherry-pick-1.1

#2250 Fix the config error in restore
  cmd/backup-manager/app/import/restore.go
Labels: needs-cherry-pick-1.1, type/bug

#2283 update tidb-toolkit version
  charts/tidb-cluster/values.yaml
  charts/tidb-drainer/values.yaml
  charts/tidb-lightning/values.yaml
  charts/tikv-importer/values.yaml
  deploy/aliyun/manifests/db-monitor.yaml.example
  deploy/aliyun/manifests/db.yaml.example
  deploy/aliyun/variables.tf
  deploy/aws/manifests/db-monitor.yaml.example
  deploy/aws/manifests/db.yaml.example
  deploy/aws/variables.tf
  deploy/gcp/manifests/db-monitor.yaml.example
  deploy/gcp/manifests/db.yaml.example
  deploy/gcp/variables.tf
  deploy/modules/aliyun/tidb-cluster/variables.tf
  deploy/modules/aws/tidb-cluster/variables.tf
  deploy/modules/gcp/tidb-cluster/variables.tf
  deploy/modules/share/tidb-cluster-release/variables.tf
  examples/advanced-statefulset/tidb-cluster-scaled.yaml
  examples/advanced-statefulset/tidb-cluster.yaml
  examples/auto-scale/tidb-cluster.yaml
  examples/auto-scale/tidb-monitor.yaml
  examples/basic/tidb-cluster.yaml
  examples/basic/tidb-monitor.yaml
  examples/initialize/tidb-cluster.yaml
  examples/selfsigned-tls/tidb-cluster.yaml
  images/tidb-backup-manager/Dockerfile
  manifests/monitor/tidb-monitor.yaml
Labels: CanMerge, needs-cherry-pick-1.1

#2275 Fix pdapi cache when cluster TLS enabled
  pkg/controller/tidb_control.go
  pkg/pdapi/pdapi.go
Labels: needs-cherry-pick-1.1

#2289 Fix auto scaler status syncing error
  pkg/autoscaler/autoscaler/autoscaler_manager.go
Labels: area/auto-scaling, needs-cherry-pick-1.1, type/bug

#2259 Revise document tool
  docs/api-references/docs.md
  docs/api-references/template/pkg.tpl
  docs/api-references/template/type.tpl
  hack/lib.sh
Labels: CanMerge, needs-cherry-pick-1.1

#2163 Add prometheus operator monitor example
  examples/prometheus-operator/README.md
  examples/prometheus-operator/pd-serviceMonitor.yaml
  examples/prometheus-operator/prometheus-rules.yaml
  examples/prometheus-operator/prometheus-service.yaml
  examples/prometheus-operator/prometheus.yaml
  examples/prometheus-operator/tidb-cluster.yaml
  examples/prometheus-operator/tidb-serviceMonitor.yaml
  examples/prometheus-operator/tikv-serviceMonitor.yaml
Labels: CanMerge, contribution, needs-cherry-pick-1.1

#2297 require more ephemeral storage in periodical KIND jobs
  ci/e2e_kind.groovy
Labels: needs-cherry-pick-1.1

#2301 update filemgr tar format
  ci/upload-binaries-charts.sh
Labels: needs-cherry-pick-1.1

#2281 add some useful packages to the bastion
  deploy/modules/aws/bastion/bastion-userdata
Labels: CanMerge

#2291 Fix sts webhook error
  pkg/webhook/statefulset/statefulset.go
Labels: CanMerge, needs-cherry-pick-1.1, type/bug

#2298 Ignore NotFound error because resources may be deleted by namespace controller first
  tests/e2e/tidbcluster/tls.go
Labels: needs-cherry-pick-1.1

#2299 services are updated during every each sync
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tiflash_member_manager.go
  pkg/manager/member/tikv_member_manager.go
Labels: CanMerge, needs-cherry-pick-1.1

#2305 Add event in webhook
  pkg/webhook/admission_hooks.go
  pkg/webhook/pod/pd_deleter.go
  pkg/webhook/pod/pods.go
  pkg/webhook/pod/pods_test.go
  pkg/webhook/pod/tikv_deleter.go
  pkg/webhook/pod/util.go
Labels: CanMerge, enhancement, needs-cherry-pick-1.1

#2300 PD: auto-created failover pods should be deleted when failed members are recovered
  hack/e2e.sh
  hack/run-e2e.sh
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/label/label.go
  pkg/manager/member/pd_failover.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/pd_member_manager_test.go
  tests/e2e/tidbcluster/stability.go
  tests/e2e/util/cloud/cloud.go
Labels: CanMerge, needs-cherry-pick-1.1

#2314 Support TidbMonitor Ingress
  charts/tidb-operator/templates/controller-manager-rbac.yaml
  docs/api-references/docs.md
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbmonitor_types.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/equality.go
  pkg/controller/generic_control.go
  pkg/monitor/monitor/monitor_manager.go
  pkg/monitor/monitor/util.go
Labels: CanMerge, area/monitor, needs-cherry-pick-1.1

#2316 fix missing code in release-1.1
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tikv_config.go
Labels: CanMerge

#2317 Automated cherry pick of #2300: PD: auto-created failover pods should be deleted when
  hack/e2e.sh
  hack/run-e2e.sh
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/label/label.go
  pkg/manager/member/pd_failover.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/pd_member_manager_test.go
  tests/e2e/tidbcluster/stability.go
  tests/e2e/util/cloud/cloud.go
Labels: CanMerge

#2321 Improve operator killer and enable it in Advanced StatefulSet job
  ci/pingcap_tidb_operator_build_kind.groovy
  tests/e2e/util/operator/operator.go
Labels: needs-cherry-pick-1.1

#2308 statefulsets are updated during each sync even if no changes to the config
  pkg/manager/member/utils.go
Labels: CanMerge, needs-cherry-pick-1.1

#2318 support rclone options in backup and restore cr
  cmd/backup-manager/app/clean/clean.go
  cmd/backup-manager/app/clean/manager.go
  cmd/backup-manager/app/export/export.go
  cmd/backup-manager/app/export/manager.go
  cmd/backup-manager/app/import/manager.go
  cmd/backup-manager/app/import/restore.go
  cmd/backup-manager/app/util/util.go
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
Labels: CanMerge, needs-cherry-pick-1.1

#2327 example for tiflash
  examples/basic/README.md
  examples/tiflash/README.md
  examples/tiflash/tidb-cluster.yaml
  examples/tiflash/tidb-monitor.yaml
Labels: needs-cherry-pick-1.1

#2332 Use patch for sts in periodicity controller
  pkg/controller/periodicity/periodicity_controller.go
Labels: needs-cherry-pick-1.1

#2313 e2e: tls between tidb components
  .gitignore
  Makefile
  pkg/manager/member/pump_member_manager.go
  tests/backup.go
  tests/drainer_info.go
  tests/e2e/tidbcluster/tidbcluster.go
  tests/e2e/tidbcluster/tls.go
  tests/images/e2e/Dockerfile
  tests/util.go
Labels: needs-cherry-pick-1.1

#2328 do not enable placement rules automatically
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/tiflash_member_manager.go
  pkg/pdapi/pdapi.go
Labels: CanMerge, needs-cherry-pick-1.1

#2343 do not print rclone conf file
  images/tidb-backup-manager/entrypoint.sh
Labels: CanMerge, needs-cherry-pick-1.1

#2334 KMS: configuration is change via tikv
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tikv_config.go
Labels: CanMerge, needs-cherry-pick-1.1, release-note-action-required

#2322 Update TiDB/TiKV to 4.0.0-rc config
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/pd_config.go
  pkg/apis/pingcap/v1alpha1/tidb_config.go
  pkg/apis/pingcap/v1alpha1/tikv_config.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
Labels: CanMerge, needs-cherry-pick-1.1

#2353 configure ephemeral storage for eks/gke jobs
  ci/e2e_eks.groovy
  ci/e2e_gke.groovy
Labels: needs-cherry-pick-1.1

#2341 Add tiflash into prometheus rules in TidbMonitor
  pkg/apis/pingcap/v1alpha1/tiflash_config.go
  pkg/controller/controller_utils.go
  pkg/manager/member/tiflash_member_manager.go
  pkg/manager/member/tiflash_util.go
  pkg/manager/member/tiflash_util_test.go
  pkg/monitor/monitor/template.go
  pkg/monitor/monitor/template_test.go
Labels: CanMerge, area/monitor, needs-cherry-pick-1.1

#2350 Shorten CRD
  go.mod
  go.sum
  manifests/crd.yaml
  pkg/to-crdgen/cmd/cmd.go
  pkg/to-crdgen/cmd/generate/generate.go
  pkg/util/crdutil.go
Labels: needs-cherry-pick-1.1

#2263 don't failover if TiDB pod is not scheduled and perform recovery no matter what state failover pods are in
  pkg/controller/tidbcluster/tidb_cluster_controller.go
  pkg/manager/member/tidb_failover.go
  pkg/manager/member/tidb_failover_test.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tidb_member_manager_test.go
  tests/actions.go
  tests/e2e/tidbcluster/stability.go
  tests/e2e/tidbcluster/tidbcluster.go
Labels: CanMerge, needs-cherry-pick-1.1

#2363 update image tag in releasing
  ci/release_tidb_operator_binary_and_image.groovy
Labels: needs-cherry-pick-1.1
