Repository pingcap/tidb-operator, pull requests merged in 2020-01, with the labels that each got.

#1461 update /dev/md0 to /dev/mdx
  manifests/gke/local-ssd-provision/local-ssd-provision.yaml
Labels: needs-cherry-pick-1.0

#1462 add license header for shell scripts
  Makefile
  checkout-pr-branch.sh
  hack/check-EOF.sh
  hack/check-terraform.sh
  hack/crd-groups.sh
  hack/e2e.sh
  hack/gcp-rm-unused-disks.sh
  hack/kind-cluster-build.sh
  hack/lib.sh
  hack/pin-deps.sh
  hack/retool-install.sh
  hack/run-e2e.sh
  hack/verify-boilerplate.sh
  hack/verify-codegen.sh
  hack/version.sh
  images/backup-manager/entrypoint.sh
  manifests/local-dind/deploy-registry.sh
  misc/images/debug-launcher/entry-point.sh
  misc/images/tidb-debug/run_flamegraph.sh
  pkg/apis/pingcap/v1alpha1/tidbcluster_component.go
Labels: CanMerge

#1467 More badges in README.md
  README.md
Labels: CanMerge

#1469 retry on conflict error in e2e test
  tests/e2e/tidbcluster/tidbcluster.go
Labels: CanMerge

#1473 fix pvc name of restore job
  charts/tidb-backup/templates/restore-job.yaml
Labels: contribution

#1484 Compare k8s pod running info with pd client health info , improve inspection mechanism
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/pd_member_manager_test.go
Labels: CanMerge, contribution

#1459 release v1.1.0-beta.1
  CHANGELOG-1.1.md
  charts/tidb-cluster/values.yaml
  charts/tidb-operator/values.yaml
  tests/e2e/util/image/image.go
  tests/manifests/stability/stability.yaml
Labels: CanMerge

#1486 remove some not very useful update events
  pkg/controller/backup_schedule_status_updater.go
  pkg/controller/backup_status_updater.go
  pkg/controller/configmap_control.go
  pkg/controller/configmap_control_test.go
  pkg/controller/generic_control.go
  pkg/controller/pod_control.go
  pkg/controller/pod_control_test.go
  pkg/controller/pv_control.go
  pkg/controller/pv_control_test.go
  pkg/controller/pvc_control.go
  pkg/controller/pvc_control_test.go
  pkg/controller/restore_status_updater.go
  pkg/controller/service_control.go
  pkg/controller/service_control_test.go
  pkg/controller/stateful_set_control.go
  pkg/controller/stateful_set_control_test.go
  pkg/controller/tidbcluster_control.go
  pkg/controller/tidbcluster_control_test.go
Labels: CanMerge, needs-cherry-pick-1.1

#1466 failover: emit events when pd failover
  pkg/controller/tidbcluster/tidb_cluster_controller.go
  pkg/manager/member/pd_failover.go
  pkg/manager/member/pd_failover_test.go
Labels: CanMerge, needs-cherry-pick-1.1

#1405 test: add pd data deleting case
  tests/actions.go
  tests/cmd/stability/main.go
  tests/failover.go
Labels: CanMerge, needs-cherry-pick-1.1

#1501 fix some broken urls
  charts/tidb-cluster/values.yaml
Labels: CanMerge, needs-cherry-pick-1.1

#1514 fix upload not including backup-manager
  ci/pingcap_tidb_operator_build_kind.groovy
Labels: needs-cherry-pick-1.1

#1493 refine logs for controller watcher
  pkg/controller/controller_utils.go
Labels: CanMerge, needs-cherry-pick-1.1

#1445 Add tidbmonitor e2e test
  pkg/label/label.go
  pkg/monitor/monitor/template.go
  pkg/monitor/monitor/util.go
  tests/actions.go
  tests/e2e/tidbcluster/tidbcluster.go
  tests/monitor.go
  tests/pkg/fixture/fixture.go
Labels: CanMerge, area/monitor, needs-cherry-pick-1.1, test/e2e

#1505 add cd script to deploy to staging env
  ci/deploy_tidb_operator_staging.groovy
Labels: CanMerge, needs-cherry-pick-1.1

#1499 avoid unnecessary updates of discovery service and deployment
  pkg/controller/equality.go
  pkg/controller/generic_control.go
  pkg/controller/generic_control_test.go
Labels: needs-cherry-pick-1.1

#1430 update tidb default version to v3.0.8
  charts/tidb-cluster/values.yaml
  charts/tidb-drainer/values.yaml
  charts/tidb-lightning/values.yaml
  deploy/aliyun/variables.tf
  deploy/aws/clusters.tf
  deploy/aws/variables.tf
  deploy/gcp/examples/tidb-customized.tfvars
  deploy/gcp/variables.tf
  deploy/modules/aliyun/tidb-cluster/variables.tf
  deploy/modules/aws/tidb-cluster/variables.tf
  deploy/modules/gcp/tidb-cluster/variables.tf
  deploy/modules/share/tidb-cluster-release/variables.tf
  hack/run-e2e.sh
  images/tidb-operator-e2e/tidb-cluster-values.yaml
  pkg/apis/pingcap/v1alpha1/validation/validation_test.go
  pkg/controller/tidbcluster/tidb_cluster_control_test.go
  tests/config.go
  tests/e2e/config/config.go
  tests/e2e/util/image/image.go
Labels: CanMerge, contribution, needs-cherry-pick-1.1

#1528 configure QUAY_IO_MIRROR
  ci/pingcap_tidb_operator_build_kind.groovy
Labels: CanMerge

#1533 add readinessProbe/livenessProbe for admission webhook
  charts/tidb-operator/templates/admission/admission-webhook-deployment.yaml
Labels: needs-cherry-pick-1.1

#1530 add document about release notes
  .github/pull_request_template.md
  docs/CONTRIBUTING.md
  docs/generate-changelog.md
  docs/release-note-guide.md
Labels: CanMerge

#1542 switch to use k8s.io/component-base/cli/flag
  pkg/features/features.go
  pkg/util/flags/map_string_bool.go
Labels: needs-cherry-pick-1.1

#1541 add --preload-images switch
  ci/pingcap_tidb_operator_build_kind.groovy
  tests/config.go
  tests/e2e/config/config.go
  tests/e2e/e2e.go
Labels: needs-cherry-pick-1.1

#1550 upgrade to use kind 0.7.0
  ci/pingcap_tidb_operator_build_kind.groovy
  hack/e2e.sh
  hack/lib.sh
Labels: needs-cherry-pick-1.1

#1511 e2e: fine-grained control of waiting for apiservices/crds
  tests/actions.go
  tests/cmd/stability/main.go
  tests/e2e/e2e.go
  tests/e2e/tidbcluster/serial.go
  tests/e2e/tidbcluster/tidbcluster.go
  tests/e2e/util/util.go
  tests/failover.go
  tests/pkg/client/client.go
  tests/pkg/webhook/pods.go
Labels: CanMerge, needs-cherry-pick-1.1

#1532 Limit Restart rate for pd and tikv in admission webhook
  pkg/manager/member/utils.go
  pkg/webhook/pod/pd_deleter.go
  pkg/webhook/pod/tikv_deleter.go
  pkg/webhook/pod/util.go
Labels: area/webhook, enhancement, needs-cherry-pick-1.1

#1500 Revise TidbMonitor controller
  pkg/controller/tidbmonitor/tidb_monitor_controller.go
  pkg/monitor/monitor/monitor_manager.go
  pkg/monitor/monitor/util.go
Labels: CanMerge, area/controller, area/monitor, needs-cherry-pick-1.1

#1510 Separate prometheus scrape job
  charts/tidb-cluster/templates/config/_prometheus-config.tpl
Labels: contribution, needs-cherry-pick-1.0

#1522 e2e: use controller.GuaranteedUpdate to retry on version conflict
  tests/e2e/tidbcluster/serial.go
Labels: CanMerge, needs-cherry-pick-1.1

#1519 Automated cherry pick of #1501: fix some broken urls
  charts/tidb-cluster/values.yaml
Labels: CanMerge

#1568 Fix pd deleting admission webhook bug
  pkg/webhook/pod/pd_deleter.go
  pkg/webhook/pod/pd_deleter_test.go
  pkg/webhook/pod/pods_test.go
  pkg/webhook/pod/tikv_deleter.go
  pkg/webhook/pod/tikv_deleter_test.go
  tests/e2e/tidbcluster/serial.go
Labels: area/webhook, needs-cherry-pick-1.1, status/PTAL, type/bug

#1543 add an AdvancedStatefulSet job to verify all functions
  charts/tidb-operator/templates/admission/admission-webhook-deployment.yaml
  charts/tidb-operator/templates/admission/admission-webhook-registration.yaml
  charts/tidb-operator/values.yaml
  ci/pingcap_tidb_operator_build_kind.groovy
  go.mod
  go.sum
  pkg/features/features.go
  pkg/scheduler/scheduler.go
  pkg/webhook/admission_hooks.go
  tests/actions.go
  tests/config.go
  tests/e2e/config/config.go
  tests/e2e/tidbcluster/tidbcluster.go
Labels: CanMerge, needs-cherry-pick-1.1

#1521 Make service port-name configurable in monitor
  charts/tidb-cluster/templates/monitor-service.yaml
  charts/tidb-cluster/values.yaml
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbmonitor_component.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/monitor/monitor/util.go
Labels: area/monitor, needs-cherry-pick-1.1

#1580 Migrate Kubernetes StatefulSet to Advanced StatefulSet automatically
  charts/tidb-operator/templates/controller-manager-rbac.yaml
  cmd/controller-manager/main.go
  pkg/upgrader/upgrader.go
  pkg/upgrader/upgrader_test.go
  tests/e2e/tidbcluster/serial.go
  tests/e2e/tidbcluster/tidbcluster.go
  tests/e2e/util/pod/pod.go
Labels: needs-cherry-pick-1.1

#1520 cherry-pick #1486 to release-1.0: remove some events
  pkg/controller/pod_control.go
  pkg/controller/pod_control_test.go
  pkg/controller/pv_control.go
  pkg/controller/pv_control_test.go
  pkg/controller/pvc_control.go
  pkg/controller/pvc_control_test.go
  pkg/controller/service_control.go
  pkg/controller/service_control_test.go
  pkg/controller/stateful_set_control.go
  pkg/controller/stateful_set_control_test.go
  pkg/controller/tidbcluster_control.go
  pkg/controller/tidbcluster_control_test.go
Labels: CanMerge

#1585 remove unused e2e files
  images/tidb-operator-e2e/Dockerfile
  images/tidb-operator-e2e/tidb-cluster-values.yaml
  images/tidb-operator-e2e/tidb-operator-values.yaml
Labels: needs-cherry-pick-1.1

#1581 Able to omit storageClassName to use the default storage class of Kubernetes
  charts/tidb-operator/templates/controller-manager-deployment.yaml
  charts/tidb-operator/values.yaml
  cmd/controller-manager/main.go
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/backup/backup/backup_manager.go
  pkg/backup/backupschedule/backup_schedule_manager.go
  pkg/backup/restore/restore_manager.go
  pkg/backup/util/util.go
  pkg/controller/backup/backup_controller_test.go
  pkg/controller/controller_utils.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/tikv_member_manager.go
  tests/e2e/e2e.go
Labels: needs-cherry-pick-1.1

#1600 fix the "Release Notes Language Style Guide" url in pull request template
  .github/pull_request_template.md
Labels: CanMerge, contribution
