Repository pingcap/tidb-operator, pull requests merged in 2021-09, with the labels that each got.

#4164 upgrade tidb to v5.2.0 in e2e
  tests/e2e/br/br.go
  tests/e2e/tidbcluster/tidbcluster.go
  tests/e2e/util/image/image.go
Labels: status/can-merge, status/LGT2, needs-cherry-pick-1.2

#4158 tidbmonitor support dynamic reload configuration
  docs/api-references/docs.md
  examples/monitor-dynamic-configmap/ns1-cluster.yaml
  examples/monitor-dynamic-configmap/ns2-cluster.yaml
  examples/monitor-dynamic-configmap/tidb-monitor.yaml
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbmonitor_types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/monitor/monitor/monitor_manager_test.go
  pkg/monitor/monitor/util.go
  pkg/monitor/monitor/util_test.go
  tests/actions.go
  tests/e2e/tidbcluster/tidbcluster.go
  tests/monitor.go
Labels: status/can-merge, status/LGT2, needs-cherry-pick-1.2

#4171 Sync TiCDC after TiDB
  pkg/controller/tidbcluster/tidb_cluster_control.go
  pkg/manager/member/pd_upgrader.go
  pkg/manager/member/pd_upgrader_test.go
  pkg/manager/member/pump_member_manager.go
  pkg/manager/member/ticdc_member_manager.go
  pkg/manager/member/ticdc_upgrader.go
  pkg/manager/member/ticdc_upgrader_test.go
  pkg/manager/member/tidb_upgrader.go
  pkg/manager/member/tidb_upgrader_test.go
  pkg/manager/member/tiflash_upgrader.go
  pkg/manager/member/tiflash_upgrader_test.go
  pkg/manager/member/tikv_upgrader.go
  pkg/manager/member/tikv_upgrader_test.go
  tests/actions.go
  tests/e2e/br/br.go
Labels: status/can-merge, status/LGT2, needs-cherry-pick-1.2

#4181 Revert pr 4152 and add test case
  pkg/manager/member/tiflash_util.go
  pkg/manager/member/tiflash_util_test.go
  tests/e2e/tidbcluster/serial.go
Labels: status/LGT2, needs-cherry-pick-1.2

#4184 Bump operator to v1.2.3
  charts/tidb-cluster/values.yaml
  charts/tidb-operator/values.yaml
  deploy/aliyun/variables.tf
  deploy/aws/variables.tf
  deploy/gcp/variables.tf
  hack/bump-version.sh
Labels: status/can-merge, status/LGT2, needs-cherry-pick-1.2

#4120 Add ns
  charts/tidb-backup/templates/backup-job.yaml
  charts/tidb-backup/templates/backup-pvc.yaml
  charts/tidb-backup/templates/restore-job.yaml
  charts/tidb-cluster/templates/discovery-deployment.yaml
  charts/tidb-cluster/templates/discovery-rbac.yaml
  charts/tidb-cluster/templates/discovery-service.yaml
  charts/tidb-cluster/templates/drainer-configmap-rollout.yaml
  charts/tidb-cluster/templates/drainer-configmap.yaml
  charts/tidb-cluster/templates/drainer-service.yaml
  charts/tidb-cluster/templates/drainer-statefulset.yaml
  charts/tidb-cluster/templates/monitor-configmap.yaml
  charts/tidb-cluster/templates/monitor-deployment.yaml
  charts/tidb-cluster/templates/monitor-pvc.yaml
  charts/tidb-cluster/templates/monitor-rbac.yaml
  charts/tidb-cluster/templates/monitor-secret.yaml
  charts/tidb-cluster/templates/monitor-service.yaml
  charts/tidb-cluster/templates/pd-configmap.yaml
  charts/tidb-cluster/templates/pump-configmap-rollout.yaml
  charts/tidb-cluster/templates/pump-configmap.yaml
  charts/tidb-cluster/templates/pump-service.yaml
  charts/tidb-cluster/templates/pump-statefulset.yaml
  charts/tidb-cluster/templates/scheduled-backup-cronjob.yaml
  charts/tidb-cluster/templates/scheduled-backup-pvc.yaml
  charts/tidb-cluster/templates/tidb-cluster.yaml
  charts/tidb-cluster/templates/tidb-configmap-rollout.yaml
  charts/tidb-cluster/templates/tidb-configmap.yaml
  charts/tidb-cluster/templates/tidb-initializer-job.yaml
  charts/tidb-cluster/templates/tidb-service.yaml
  charts/tidb-cluster/templates/tikv-configmap.yaml
  charts/tidb-cluster/templates/tikv-importer-configmap.yaml
  charts/tidb-cluster/templates/tikv-importer-service.yaml
  charts/tidb-cluster/templates/tikv-importer-statefulset.yaml
  charts/tidb-drainer/templates/drainer-configmap.yaml
  charts/tidb-drainer/templates/drainer-service.yaml
  charts/tidb-drainer/templates/drainer-statefulset.yaml
  charts/tidb-lightning/secret.yaml
  charts/tidb-lightning/templates/configmap.yaml
  charts/tidb-lightning/templates/job.yaml
  charts/tidb-lightning/templates/persistentvolumeclaim.yaml
  charts/tidb-lightning/templates/rclone-conf.yaml
  charts/tidb-lightning/templates/service.yaml
  charts/tidb-operator/templates/admission/admission-webhook-deployment.yaml
  charts/tidb-operator/templates/admission/admission-webhook-rbac.yaml
  charts/tidb-operator/templates/admission/admission-webhook-registration.yaml
  charts/tidb-operator/templates/admission/admission-webhook-service.yaml
  charts/tidb-operator/templates/admission/pre-delete-job.yaml
  charts/tidb-operator/templates/advanced-statefulset-deployment.yaml
  charts/tidb-operator/templates/advanced-statefulset-rbac.yaml
  charts/tidb-operator/templates/controller-manager-deployment.yaml
  charts/tidb-operator/templates/controller-manager-rbac.yaml
  charts/tidb-operator/templates/scheduler-deployment.yaml
  charts/tidb-operator/templates/scheduler-policy-configmap.yaml
  charts/tidb-operator/templates/scheduler-rbac.yaml
  charts/tikv-importer/templates/tikv-importer-configmap.yaml
  charts/tikv-importer/templates/tikv-importer-service.yaml
  charts/tikv-importer/templates/tikv-importer-statefulset.yaml
Labels: status/can-merge, status/LGT2

#4148 add azure aks example
  examples/aks/tidb-cluster.yaml
  examples/aks/tidb-monitor.yaml
Labels: status/can-merge, status/LGT2

#4133 stop backup job before cleanup `Backup`
  pkg/backup/backup/backup_cleaner.go
  pkg/backup/backup/backup_test.go
  pkg/controller/backup/backup_controller.go
Labels: status/can-merge, status/LGT2, needs-cherry-pick-1.2

#4121 ignore the newline in secret file for initializer
  charts/tidb-cluster/templates/scripts/_initialize_tidb_users.py.tpl
  pkg/manager/member/template.go
Labels: status/can-merge, status/LGT2

#4180 TidbMonitor support dynamic prometheus rule reload and custom external rule
  docs/api-references/docs.md
  examples/monitor-with-externalRules/external-configMap.yaml
  examples/monitor-with-externalRules/tidb-monitor.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbmonitor_types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/monitor/monitor/template.go
  pkg/monitor/monitor/template_test.go
  pkg/monitor/monitor/util.go
  pkg/monitor/monitor/util_test.go
Labels: status/can-merge, status/LGT2

#4122 customize annotation for scheduler configmap
  charts/tidb-operator/templates/scheduler-policy-configmap.yaml
  charts/tidb-operator/values.yaml
Labels: status/can-merge, status/LGT2

#4123 use interanl svc name for discovery instead of external dns
  pkg/manager/member/template.go
  pkg/manager/member/template_test.go
  pkg/manager/member/ticdc_member_manager.go
  pkg/manager/member/tiflash_member_manager.go
Labels: status/can-merge, status/LGT2

#4192 remove: SyncAutoScalerAnn
  pkg/apis/label/label.go
  pkg/manager/member/dm_master_scaler.go
  pkg/manager/member/dm_worker_scaler.go
  pkg/manager/member/pd_scaler.go
  pkg/manager/member/pump_scaler.go
  pkg/manager/member/scaler.go
  pkg/manager/member/ticdc_scaler.go
  pkg/manager/member/tidb_scaler.go
  pkg/manager/member/tiflash_scaler.go
  pkg/manager/member/tikv_scaler.go
  pkg/util/util.go
  pkg/util/utils_test.go
  pkg/webhook/pod/pod_mutater.go
Labels: status/can-merge, status/LGT2

#4095 improve performance of cleanup BR
  cmd/backup-manager/app/clean/clean.go
  cmd/backup-manager/app/util/remote.go
  cmd/backup-manager/app/util/remote_test.go
  docs/api-references/docs.md
  go.mod
  go.sum
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/backup.go
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  tests/e2e/br/br.go
  tests/e2e/br/framework/br/data.go
  tests/e2e/br/utils/s3/interface.go
  tests/e2e/br/utils/s3/minio.go
Labels: status/can-merge, status/LGT2, needs-cherry-pick-1.2

#4193 Upgrade tiflash gracefully
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/controller/dependences.go
  pkg/manager/member/tiflash_upgrader.go
  pkg/manager/member/tiflash_upgrader_test.go
  pkg/tiflashapi/fake_tiflashapi.go
  pkg/tiflashapi/tiflash_control.go
  pkg/tiflashapi/tiflashapi.go
Labels: status/can-merge, status/LGT2, needs-cherry-pick-1.2

#4198 Support tidbmonitor prometheus shards feature
  docs/api-references/docs.md
  examples/monitor-shards/README.md
  examples/monitor-shards/tidb-cluster.yaml
  examples/monitor-shards/tidb-monitor.yaml
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbmonitor_types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/monitor/monitor/monitor_manager.go
  pkg/monitor/monitor/monitor_manager_test.go
  pkg/monitor/monitor/template.go
  pkg/monitor/monitor/template_test.go
  pkg/monitor/monitor/util.go
  pkg/monitor/monitor/util_test.go
  tests/actions.go
  tests/e2e/tidbcluster/tidbcluster.go
  tests/monitor.go
Labels: status/can-merge, status/LGT2

#4204 Fix tidbmonitor shard e2e test
  tests/e2e/tidbcluster/tidbcluster.go
Labels: status/can-merge, status/LGT2

#4205 Optimize tidbmonitor readme document.
  README.md
Labels: status/can-merge, status/LGT2
