Repository pingcap/tidb-operator, pull requests merged in 2021-01, with the labels that each got.

#3671 monitor: fix the commandOptions example
  examples/monitor-with-externalConfigMap/tidb-monitor.yaml
Labels: needs-cherry-pick-1.1, status/LGT1

#3670 Fix tidb config level value enclose
  examples/advanced/tidb-cluster.yaml
Labels: first-time-contributor, status/LGT2

#3678 Fix copr-cache.enable config error
  docs/api-references/docs.md
  pkg/apis/pingcap/v1alpha1/tidb_config.go
Labels: status/LGT2

#3685 fix advanced TidbCluster example
  examples/advanced/tidb-cluster.yaml
Labels: needs-cherry-pick-1.1, status/LGT1

#3684 change alertManagerRulesVersion from TiDB version to initializer image version
  pkg/monitor/monitor/monitor_manager_test.go
  pkg/monitor/monitor/util.go
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge

#3690 adjust e2e pod resources
  ci/pull_e2e_kind.groovy
Labels: needs-cherry-pick-1.1, status/LGT1

#3673 improve e2e semantics
  hack/e2e.sh
  hack/run-e2e.sh
  pkg/manager/member/pd_scaler.go
  pkg/manager/member/pd_upgrader.go
  pkg/manager/member/tidb_failover.go
  tests/actions.go
  tests/cluster_info.go
  tests/crd_test_util.go
  tests/e2e/e2e.go
  tests/e2e/tidbcluster/ownership.go
  tests/e2e/tidbcluster/serial.go
  tests/e2e/tidbcluster/stability-asts.go
  tests/e2e/tidbcluster/stability-br.go
  tests/e2e/tidbcluster/stability.go
  tests/e2e/tidbcluster/tidbcluster.go
  tests/e2e/tidbcluster/util.go
  tests/e2e/util/statefulset/statefulset.go
  tests/pkg/apimachinery/certs.go
Labels: needs-cherry-pick-1.1, status/LGT2

#3700 add customizable controller rate limiter
  go.mod
  pkg/controller/autoscaler/tidbcluster_autoscaler_controller.go
  pkg/controller/backup/backup_controller.go
  pkg/controller/backupschedule/backup_schedule_controller.go
  pkg/controller/dmcluster/dm_cluster_controller.go
  pkg/controller/rate_limiter.go
  pkg/controller/restore/restore_controller.go
  pkg/controller/tidbcluster/tidb_cluster_controller.go
  pkg/controller/tidbinitializer/tidb_initializer_controller.go
  pkg/controller/tidbmonitor/tidb_monitor_controller.go
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge

#3705 add param to set --delete-namespace-on-failure
  ci/pull_e2e_kind.groovy
Labels: status/LGT1, status/can-merge

#3706 bump chart version to v1.2.0-alpha.1
  charts/tidb-cluster/values.yaml
  charts/tidb-operator/values.yaml
  deploy/aliyun/variables.tf
  deploy/aws/variables.tf
  deploy/gcp/variables.tf
  hack/bump-version.sh
Labels: status/LGT1

#3694 Sync TiKV Statefulset even when TiKV is not bootstrapped
  docs/api-references/docs.md
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/manager/member/tikv_member_manager.go
  pkg/manager/member/tikv_member_manager_test.go
  pkg/manager/member/tikv_scaler.go
  pkg/manager/member/tikv_scaler_test.go
  pkg/manager/member/tikv_upgrader.go
  pkg/manager/member/tikv_upgrader_test.go
  pkg/pdapi/pdapi.go
  pkg/webhook/pod/tikv_creater.go
  pkg/webhook/pod/tikv_creater_test.go
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge

#3707 Fix backup & restore panic when tls enabled
  pkg/backup/backup/backup_manager.go
  pkg/backup/restore/restore_manager.go
Labels: needs-cherry-pick-1.1, status/LGT2

#3713 Support configuring init containers for components in TiDB cluster
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbcluster_component.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/pump_member_manager.go
  pkg/manager/member/ticdc_member_manager.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tiflash_member_manager.go
  pkg/manager/member/tikv_member_manager.go
Labels: needs-cherry-pick-1.1, status/LGT2

#3719 change ephemeral-storage to 150Gi
  ci/pull_e2e_kind.groovy
Labels: needs-cherry-pick-1.1, status/LGT2

#3702 The default value of statefulset partition should take `delete-slots` into consideration
  pkg/manager/member/dm_master_member_manager.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tidb_member_manager_test.go
  pkg/manager/member/tikv_member_manager.go
  pkg/util/util.go
  pkg/util/utils_test.go
Labels: status/LGT2

#3732 temporarily change to hub-dev.pingcap.net
  ci/pull_e2e_kind.groovy
Labels: status/LGT1

#3696 Support cancel backup and restore jobs via signal and update status with failed pod
  cmd/backup-manager/app/backup/backup.go
  cmd/backup-manager/app/backup/manager.go
  cmd/backup-manager/app/clean/clean.go
  cmd/backup-manager/app/clean/manager.go
  cmd/backup-manager/app/export/export.go
  cmd/backup-manager/app/export/manager.go
  cmd/backup-manager/app/import/import.go
  cmd/backup-manager/app/import/manager.go
  cmd/backup-manager/app/restore/manager.go
  cmd/backup-manager/app/restore/restore.go
  cmd/backup-manager/app/util/generic.go
  cmd/backup-manager/app/util/util.go
  pkg/apis/pingcap/v1alpha1/backup.go
  pkg/apis/pingcap/v1alpha1/restore.go
  pkg/backup/backup.go
  pkg/backup/backup/backup_manager.go
  pkg/backup/restore/restore_manager.go
  pkg/controller/backup/backup_control.go
  pkg/controller/backup/backup_controller.go
  pkg/controller/backup/backup_controller_test.go
  pkg/controller/restore/restore_control.go
  pkg/controller/restore/restore_controller.go
  pkg/controller/restore/restore_controller_test.go
Labels: needs-cherry-pick-1.1, status/LGT2

#3679 TidbMonitor add remotewrite configuration
  docs/api-references/docs.md
  examples/monitor-prom-remotewrite/tidb-monitor.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbmonitor_types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/monitor/monitor/monitor_manager_test.go
  pkg/monitor/monitor/template.go
  pkg/monitor/monitor/template_test.go
  pkg/monitor/monitor/util.go
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge

#3738 README: update links and add info
  README.md
Labels: status/LGT2, status/can-merge

#3724 EndEvictLeader after Pod is recreated in RollingUpdate
  pkg/manager/member/tikv_member_manager.go
  pkg/manager/member/tikv_scaler.go
  pkg/manager/member/tikv_upgrader.go
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge

#3731 support customizing slowlog storage
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/validation/validation.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tidb_member_manager_test.go
Labels: needs-update-docs, status/LGT2, status/can-merge

#3717 upgrade e2e tools version
  hack/e2e.sh
  hack/lib.sh
  hack/local-up-operator.sh
  hack/run-e2e.sh
  tests/actions.go
  tests/backup.go
  tests/e2e/e2e.go
  tests/examples/002-selfsigned-tls.sh
  tests/images/e2e/Dockerfile
  tests/images/stability-test/Dockerfile
Labels: status/LGT2, status/can-merge

#3747 disable running auto scaling related e2e cases
  tests/e2e/tidbcluster/stability.go
  tests/e2e/tidbcluster/tidbcluster.go
Labels: status/LGT2

#3729 split basic e2e cases into smaller chunks
  tests/crd_test_util.go
  tests/e2e/tidbcluster/tidbcluster.go
  tests/e2e/util/image/image.go
Labels: status/LGT2, status/can-merge

#3750 Tidbmonitor add `tidb_cluster `target label .
  pkg/monitor/monitor/template.go
  pkg/monitor/monitor/template_test.go
Labels: needs-cherry-pick-1.1, status/LGT2

#3757 Bump TiDB version to v4.0.10
  charts/tidb-cluster/values.yaml
  charts/tidb-drainer/values.yaml
  charts/tidb-lightning/values.yaml
  charts/tikv-importer/values.yaml
  deploy/aliyun/manifests/db-monitor.yaml.example
  deploy/aliyun/manifests/db.yaml.example
  deploy/aliyun/variables.tf
  deploy/aws/manifests/db-monitor.yaml.example
  deploy/aws/manifests/db.yaml.example
  deploy/aws/variables.tf
  deploy/gcp/manifests/db-monitor.yaml.example
  deploy/gcp/manifests/db.yaml.example
  deploy/gcp/variables.tf
  deploy/modules/aliyun/tidb-cluster/variables.tf
  deploy/modules/aws/tidb-cluster/variables.tf
  deploy/modules/gcp/tidb-cluster/variables.tf
  deploy/modules/share/tidb-cluster-release/variables.tf
  examples/advanced-statefulset/tidb-cluster-scaled.yaml
  examples/advanced-statefulset/tidb-cluster.yaml
  examples/advanced/tidb-cluster.yaml
  examples/auto-scale/tidb-cluster.yaml
  examples/auto-scale/tidb-monitor.yaml
  examples/aws/tidb-cluster.yaml
  examples/aws/tidb-monitor.yaml
  examples/basic-cn/tidb-cluster.yaml
  examples/basic-cn/tidb-monitor.yaml
  examples/basic-tls/tidb-cluster.yaml
  examples/basic-tls/tidb-monitor.yaml
  examples/basic/tidb-cluster.yaml
  examples/basic/tidb-monitor.yaml
  examples/dm/dm-monitor.yaml
  examples/gcp/tidb-cluster.yaml
  examples/gcp/tidb-monitor.yaml
  examples/heterogeneous-tls/heterogeneous-cluster.yaml
  examples/heterogeneous-tls/tidb-cluster.yaml
  examples/heterogeneous-tls/tidb-monitor.yaml
  examples/heterogeneous/heterogeneous-cluster.yaml
  examples/heterogeneous/tidb-cluster.yaml
  examples/heterogeneous/tidb-monitor.yaml
  examples/initialize/tidb-cluster.yaml
  examples/monitor-multiple-cluster-non-tls/ns1-cluster.yaml
  examples/monitor-multiple-cluster-non-tls/ns2-cluster.yaml
  examples/monitor-multiple-cluster-non-tls/tidb-monitor.yaml
  examples/monitor-prom-remotewrite/tidb-monitor.yaml
  examples/monitor-with-externalConfigMap/tidb-monitor.yaml
  examples/multi-cluster/tidb-cluster-1.yaml
  examples/multi-cluster/tidb-cluster-2.yaml
  examples/multiple-pv-tikv/tidb-cluster.yaml
  examples/selfsigned-tls/tidb-cluster.yaml
  examples/tiflash/tidb-cluster.yaml
  examples/tiflash/tidb-monitor.yaml
  hack/bump-version.sh
  images/tidb-backup-manager/Dockerfile
Labels: needs-cherry-pick-1.1, status/LGT2

#3756 Bump operator to v1.1.10
  charts/tidb-cluster/values.yaml
  charts/tidb-operator/values.yaml
  deploy/aliyun/variables.tf
  deploy/aws/variables.tf
  deploy/gcp/variables.tf
  hack/bump-version.sh
Labels: status/LGT1

#3726 Optimze thanos example
  examples/monitor-with-thanos/README.md
  examples/monitor-with-thanos/external-configMap.yaml
  examples/monitor-with-thanos/objectstorage-secret.yaml
  examples/monitor-with-thanos/thanos-query.yaml
  examples/monitor-with-thanos/tidb-monitor.yaml
  examples/thanos-sidecar/tidb-monitor.yaml
Labels: status/LGT2

#3761 wait for crd established before further operations
  tests/actions.go
  tests/e2e/tidbcluster/serial.go
  tests/util.go
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge

#3755 refactor: make monitor test template more compact
  pkg/monitor/monitor/template.go
  pkg/monitor/monitor/template_test.go
Labels: status/LGT2, status/can-merge

#3762 remove helm deployed backup/restore e2e test case from default test
  tests/e2e/tidbcluster/tidbcluster.go
Labels: status/LGT2, status/can-merge
