Repository pingcap/tidb-operator, pull requests merged in 2021-02, with the labels that each got.

#3770 e2e: refactor tidb version
  tests/e2e/tidbcluster/serial.go
  tests/e2e/tidbcluster/stability-asts.go
  tests/e2e/tidbcluster/stability-br.go
  tests/e2e/tidbcluster/stability.go
  tests/e2e/tidbcluster/tidbcluster.go
  tests/e2e/util/image/image.go
  tests/pkg/fixture/fixture.go
Labels: needs-cherry-pick-1.1, status/LGT2

#3769 e2e: upgrade cert-manager version
  hack/gen-tls-certs.sh
  hack/lib.sh
  tests/images/e2e/Dockerfile
Labels: status/LGT2, status/can-merge

#3774 check pod ready during tikv upgrade
  pkg/manager/member/tikv_upgrader.go
  pkg/manager/member/tikv_upgrader_test.go
Labels: status/LGT2, status/can-merge

#3746 e2e tikv reserve space
  tests/actions.go
  tests/images/e2e/Dockerfile
  tests/images/e2e/tikv.toml
  tests/pkg/fixture/fixture.go
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge

#3768 support print rocksdb log and raft log to stdout
  Makefile
  docs/api-references/docs.md
  examples/advanced/tidb-cluster.yaml
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/member/tikv_member_manager.go
  pkg/manager/member/tikv_member_manager_test.go
  tests/e2e/tidbcluster/tidbcluster.go
Labels: first-time-contributor, needs-cherry-pick-1.1, status/LGT2, status/can-merge

#3794 tune and suppport configuration about LeaderElection
  charts/tidb-operator/templates/controller-manager-deployment.yaml
  charts/tidb-operator/values.yaml
  cmd/controller-manager/main.go
  pkg/controller/dependences.go
Labels: needs-cherry-pick-1.1, status/LGT2, status/PTAL, status/can-merge

#3788 upgrade busybox image version to 1.33.0
  charts/tidb-cluster/values.yaml
  deploy/aliyun/manifests/db.yaml.example
  deploy/aws/manifests/db.yaml.example
  docs/api-references/docs.md
  examples/tiflash/tidb-cluster.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/manager/member/pd_member_manager_test.go
  pkg/manager/member/tidb_member_manager_test.go
  pkg/manager/member/tiflash_util_test.go
  pkg/manager/member/tikv_member_manager_test.go
Labels: status/LGT2, status/can-merge

#3801 retrieve region leader from tikv
  docs/api-references/docs.md
  go.mod
  go.sum
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/controller/dependences.go
  pkg/controller/tikv_control.go
  pkg/manager/member/tikv_upgrader.go
  pkg/manager/member/tikv_upgrader_test.go
  pkg/tikvapi/fake_tikvapi.go
  pkg/tikvapi/tikv_control.go
  pkg/tikvapi/tikvapi.go
  tests/actions.go
  tests/pkg/fixture/fixture.go
Labels: needs-cherry-pick-1.1, status/LGT2

#3789 Add TiFlash rolling upgrade logic
  pkg/manager/member/tiflash_member_manager.go
  pkg/manager/member/tiflash_upgrader.go
  pkg/manager/member/tiflash_upgrader_test.go
  pkg/manager/member/utils.go
Labels: needs-cherry-pick-1.1, status/LGT2

#3809 Fix backup manager scripts to competite with some shell
  images/tidb-backup-manager/entrypoint.sh
Labels: needs-cherry-pick-1.1, status/LGT2

#3811 Bump operator version to v1.1.11
  charts/tidb-cluster/values.yaml
  charts/tidb-operator/values.yaml
  deploy/aliyun/variables.tf
  deploy/aws/variables.tf
  deploy/gcp/variables.tf
  hack/bump-version.sh
Labels: status/LGT1, status/can-merge

#3784 add store labels
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/member/tikv_member_manager.go
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge

#3785 Fix tidbmonitor externallabels unrecognized environment variables.
  pkg/monitor/monitor/monitor_manager_test.go
  pkg/monitor/monitor/util.go
  pkg/monitor/monitor/util_test.go
  tests/e2e/util/image/image.go
Labels: status/LGT2, status/can-merge

#3793 Add delve into tidb-debug
  misc/images/tidb-debug/Dockerfile
Labels: first-time-contributor, status/LGT2, status/can-merge

#3805 Share host debugfs, kernel modules and kernel sources path to container
  pkg/tkctl/debug/launcher.go
Labels: first-time-contributor, status/LGT2, status/can-merge

#3739 Remove unnecessary LocalPV support
  tests/cmd/stability/main.go
  tests/e2e/e2e.go
  tests/e2e/tidbcluster/tidbcluster.go
  tests/pkg/fixture/fixture.go
Labels: status/LGT2, status/can-merge

#3725 e2e: add test coverage
  .codecov.yml
  .github/workflows/ci.yaml
  Makefile
  ci/pull_e2e_kind.groovy
  cmd/admission-webhook/main_test.go
  cmd/backup-manager/main_test.go
  cmd/controller-manager/main.go
  cmd/controller-manager/main_test.go
  cmd/discovery/main.go
  cmd/discovery/main_test.go
  cmd/scheduler/main.go
  cmd/scheduler/main_test.go
  hack/e2e-patch-codecov.sh
  images/tidb-backup-manager/Dockerfile.e2e
  images/tidb-backup-manager/e2e-entrypoint.sh
  images/tidb-operator/Dockerfile.e2e
  images/tidb-operator/e2e-entrypoint.sh
  tests/actions.go
  tests/e2e/e2e.go
Labels: status/LGT2, status/can-merge
