Repository pingcap/tidb-operator, pull requests merged in 2021-11, with the labels that each got.

#4227 Remove "https" head in tiflash init script
  pkg/manager/member/tiflash_member_manager.go
Labels: status/can-merge, status/LGT1, status/LGT2

#4160 Proposal: updateTidbCluster not block when error occurs
  docs/design-proposals/2021-08-27-updateTidbCluster-no-blocking.md
Labels: status/can-merge, status/LGT2

#4242 Improve advanced example: TidbMonitor
  docs/api-references/docs.md
  examples/advanced/tidb-monitor.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbmonitor_types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
Labels: status/can-merge, status/LGT2

#4166 optimize: Optimization for secret retrieving logic
  cmd/discovery/main.go
  pkg/autoscaler/autoscaler/autoscaler_manager.go
  pkg/autoscaler/autoscaler/query/external.go
  pkg/backup/backup/backup_cleaner.go
  pkg/backup/backup/backup_manager.go
  pkg/backup/restore/restore_manager.go
  pkg/backup/testutils/helpers.go
  pkg/backup/util/util.go
  pkg/backup/util/utils_test.go
  pkg/controller/dependences.go
  pkg/controller/http_client.go
  pkg/controller/pd_control_test.go
  pkg/controller/pod_control_test.go
  pkg/controller/secret_control.go
  pkg/controller/ticdc_control.go
  pkg/controller/tidb_control.go
  pkg/controller/tidb_control_test.go
  pkg/discovery/discovery_test.go
  pkg/discovery/server/server_test.go
  pkg/dmapi/master_control.go
  pkg/pdapi/pd_control.go
  pkg/pdapi/pdapi.go
  pkg/tiflashapi/tiflash_control.go
  pkg/tikvapi/tikv_control.go
  pkg/webhook/pod/pd_deleter_test.go
  pkg/webhook/pod/pods.go
  pkg/webhook/pod/pods_test.go
  pkg/webhook/pod/tikv_deleter_test.go
  pkg/webhook/pod/util_test.go
  tests/actions.go
  tests/cmd/stability/main.go
  tests/e2e/tidbcluster/stability.go
  tests/e2e/tidbcluster/tidbcluster.go
  tests/e2e/util/proxiedpdclient/proxiedpdclient.go
  tests/fault.go
  tests/pkg/webhook/pods.go
  tests/util.go
Labels: status/can-merge, status/LGT2

#4211 Feature:support configuring PodManagementPolicy in TidbCluster CR
  docs/api-references/docs.md
  examples/advanced/tidb-cluster.yaml
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbcluster_component.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/pump_member_manager.go
  pkg/manager/member/ticdc_member_manager.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tiflash_member_manager.go
  pkg/manager/member/tikv_member_manager.go
Labels: status/can-merge, status/LGT2

#4169 Optimize: support customizing the config for rocksdb and raft log of TiKV
  docs/api-references/docs.md
  examples/advanced/tidb-cluster.yaml
  examples/basic-storagevolumes/tidb-cluster.yaml
  examples/basic-storagevolumes/tidb-monitor.yaml
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/validation/validation.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tikv_member_manager.go
  pkg/manager/member/tikv_member_manager_test.go
  pkg/manager/member/utils.go
  pkg/manager/member/utils_test.go
Labels: status/can-merge, status/LGT1, status/LGT2

#4240 Fix some high security issues
  go.mod
  go.sum
Labels: status/can-merge, status/LGT2, needs-cherry-pick-1.2

#4248 Check startup script when check if configmap has beed updated
  pkg/manager/member/config.go
  pkg/manager/member/config_test.go
  tests/e2e/br/br.go
  tests/e2e/tidbcluster/tidbcluster.go
Labels: status/can-merge, status/LGT2, needs-cherry-pick-1.2

#4241 Fix `PD` scale in failed when deploying cluster across multi Kubernetes
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/manager/member/tidb_member_manager.go
Labels: status/can-merge, status/LGT2

#4265 Fix issue run unexpected e2e case
  tests/e2e/br/br.go
  tests/e2e/tidbcluster/tidbcluster.go
  tests/e2e/util/ginkgo/ginkgo_util.go
Labels: status/can-merge, status/LGT2, needs-cherry-pick-1.2

#4195 Support to use `v1 Ingress` and be compatible with `v1beta1 Ingress`
  charts/tidb-operator/templates/controller-manager-rbac.yaml
  cmd/controller-manager/main.go
  docs/api-references/docs.md
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/dependences.go
  pkg/controller/equality.go
  pkg/controller/generic_control.go
  pkg/monitor/monitor/monitor_manager.go
  pkg/monitor/monitor/util.go
  pkg/util/discovery/discovery.go
Labels: status/can-merge, status/LGT2

#4243 separate dm and tidb monitor logic
  docs/api-references/docs.md
  examples/dm/dm-monitor.yaml
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbmonitor_types.go
  pkg/controller/tidbmonitor/tidb_monitor_control.go
  pkg/monitor/monitor/monitor_manager.go
  pkg/monitor/monitor/util.go
  pkg/monitor/monitor/util_test.go
Labels: status/can-merge, status/LGT2

#4258 Upgrade kubernetes to v1.19.16 to fix security issue
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/client/go.mod
  pkg/client/go.sum
Labels: status/can-merge, status/LGT2

#4259 support PodSecurityContext for Discovery
  pkg/manager/member/tidb_discovery_manager.go
Labels: status/can-merge, status/LGT2, needs-cherry-pick-1.2

#4252 Add basic e2e about deploying cluster across kubernetes
  tests/e2e/tidbcluster/across-kubernetes.go
  tests/e2e/util/ns/ns.go
  tests/e2e/util/pd/pd.go
Labels: status/can-merge, status/LGT2

#4269 Revert "support PodSecurityContext for Discovery"
  pkg/manager/member/tidb_discovery_manager.go
Labels: status/can-merge, status/LGT2

#4270 feat(tc): support configure TiDB ssl-ca parameter via TiDBTLSClient
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tidb_member_manager_test.go
Labels: status/can-merge, status/LGT2, needs-cherry-pick-1.2
