Repository pingcap/tidb-operator, pull requests merged in 2021-12, with the labels that each got.

#4277 RFC: Add 2021-11-24-graceful-restart-tikv-pod.md
  docs/design-proposals/2021-11-24-graceful-restart-tikv-pod.md
Labels: status/can-merge, status/LGT2

#4249 Read tls client cert from local TC when TC is heterogeneous or across-kubernetes
  pkg/controller/pd_control.go
  pkg/controller/pod_control.go
  pkg/discovery/discovery.go
  pkg/dmapi/master_control.go
  pkg/manager/member/tikv_upgrader.go
  pkg/pdapi/pd_control.go
  pkg/pdapi/pdapi.go
  pkg/tiflashapi/tiflash_control.go
  pkg/tikvapi/tikv_control.go
  pkg/webhook/pod/pods.go
  tests/actions.go
  tests/e2e/util/proxiedpdclient/proxiedpdclient.go
  tests/failover.go
  tests/pkg/webhook/pods.go
Labels: status/can-merge, status/LGT2

#4283 types.go: Do not generate the UpdateStatus
  manifests/crd.yaml
  manifests/crd_v1beta1.yaml
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/client/clientset/versioned/typed/pingcap/v1alpha1/fake/fake_tidbcluster.go
  pkg/client/clientset/versioned/typed/pingcap/v1alpha1/tidbcluster.go
Labels: status/can-merge, status/LGT2

#4288 set all components minimum replicas to 0
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_dmclusters.yaml
  manifests/crd/v1/pingcap.com_tidbclusters.yaml
  manifests/crd/v1beta1/pingcap.com_dmclusters.yaml
  manifests/crd/v1beta1/pingcap.com_tidbclusters.yaml
  manifests/crd_v1beta1.yaml
  pkg/apis/pingcap/v1alpha1/types.go
Labels: status/can-merge, status/LGT2

#4273 Add `ready` field for ticdc's status
  docs/api-references/docs.md
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_tidbclusters.yaml
  manifests/crd/v1beta1/pingcap.com_tidbclusters.yaml
  manifests/crd_v1beta1.yaml
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/controller/dependences.go
  pkg/controller/ticdc_control.go
  pkg/manager/member/ticdc_member_manager.go
  pkg/manager/member/ticdc_member_manager_test.go
Labels: status/can-merge, status/LGT2, needs-cherry-pick-1.2

#4291 fix potential goroutine leak
  pkg/tikvapi/tikvapi.go
Labels: status/can-merge, needs-cherry-pick-1.1, status/LGT2, needs-cherry-pick-1.2

#4260 Update image version of busybox helper
  charts/tidb-cluster/templates/tidb-cluster.yaml
  charts/tidb-cluster/values.yaml
  deploy/aliyun/manifests/db.yaml.example
  deploy/aws/manifests/db.yaml.example
  deploy/gcp/manifests/db.yaml.example
  docs/api-references/docs.md
  examples/advanced-statefulset/tidb-cluster.yaml
  examples/advanced/tidb-cluster.yaml
  examples/aks/tidb-cluster.yaml
  examples/auto-scale/tidb-cluster.yaml
  examples/aws/tidb-cluster.yaml
  examples/basic-cn/tidb-cluster.yaml
  examples/basic-storagevolumes/tidb-cluster.yaml
  examples/basic-tls/tidb-cluster.yaml
  examples/basic/tidb-cluster.yaml
  examples/gcp/tidb-cluster.yaml
  examples/heterogeneous-tls/tidb-cluster.yaml
  examples/heterogeneous/tidb-cluster.yaml
  examples/initialize/tidb-cluster.yaml
  examples/monitor-prom-remotewrite/tidb-cluster.yaml
  examples/monitor-shards/tidb-cluster.yaml
  examples/multiple-pv-tikv/tidb-cluster.yaml
  examples/namespaced/tidb-cluster.yaml
  examples/prometheus-operator/tidb-cluster.yaml
  examples/selfsigned-tls/tidb-cluster.yaml
  examples/tiflash/tidb-cluster.yaml
  manifests/crd.yaml
  manifests/crd_v1beta1.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
Labels: status/can-merge, status/LGT2

#4272 Remove dependency with the firstTC and firstDC in the TidbMonitor controller
  docs/api-references/docs.md
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_tidbmonitors.yaml
  manifests/crd/v1beta1/pingcap.com_tidbmonitors.yaml
  manifests/crd_v1beta1.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbmonitor_types.go
  pkg/monitor/monitor/util.go
  pkg/monitor/monitor/util_test.go
Labels: status/can-merge, status/LGT2

#4299 dm: support config experimental features
  docs/api-references/docs.md
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_dmclusters.yaml
  manifests/crd/v1beta1/pingcap.com_dmclusters.yaml
  manifests/crd_v1beta1.yaml
  pkg/apis/pingcap/v1alpha1/dm_config.go
  pkg/apis/pingcap/v1alpha1/dm_config_test.go
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  tests/dm.go
  tests/e2e/dmcluster/dmcluster.go
Labels: status/can-merge, status/LGT2

#4278 fix backupschedule.status.lastBackup empty problem when it is the fir…
  pkg/backup/backupschedule/backup_schedule_manager.go
Labels: status/can-merge, status/LGT2

#4279 *: implements RFC: Add 2021-11-24-graceful-reschedule-tikv-pod.md
  cmd/controller-manager/main.go
  docs/api-references/docs.md
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_tidbclusters.yaml
  manifests/crd/v1beta1/pingcap.com_tidbclusters.yaml
  manifests/crd_v1beta1.yaml
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/tidbcluster/pod_control.go
  pkg/controller/tidbcluster/pod_control_test.go
  pkg/manager/member/tikv_upgrader.go
  pkg/manager/member/utils.go
Labels: status/can-merge, status/LGT2

#4300 add tls e2e spec of deploying tls cluster
  tests/config.go
  tests/e2e/config/config.go
  tests/e2e/e2e.go
  tests/e2e/tidbcluster/across-kubernetes.go
  tests/e2e/tidbcluster/tls.go
Labels: status/can-merge, status/LGT2

#4304 Support to configure init container resource for TiFlash
  docs/api-references/docs.md
  examples/advanced/tidb-cluster.yaml
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_tidbclusters.yaml
  manifests/crd/v1beta1/pingcap.com_tidbclusters.yaml
  manifests/crd_v1beta1.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/member/tiflash_member_manager.go
  pkg/manager/member/tiflash_member_manager_test.go
  pkg/manager/member/utils.go
Labels: status/can-merge, status/LGT2, needs-cherry-pick-1.2

#4305 Add UT for NG Monitoring
  go.mod
  go.sum
  pkg/apis/label/label_test.go
  pkg/apis/pingcap/v1alpha1/tidbngmonitoring.go
  pkg/apis/pingcap/v1alpha1/tidbngmonitoring_test.go
  pkg/controller/controller_utils_test.go
  pkg/controller/tidbngmonitoring/tidb_ng_monitoring_control.go
  pkg/controller/tidbngmonitoring/tidb_ng_monitoring_control_test.go
  pkg/controller/tidbngmonitoring/tidb_ng_monitoring_controller_test.go
  pkg/manager/meta/reclaim_policy_manager.go
  pkg/manager/tidbngmonitoring/ng_monitoring_manager_test.go
  pkg/manager/tidbngmonitoring/start_script_test.go
  pkg/manager/utils/statefulset_builder_test.go
Labels: status/can-merge, status/LGT2

#4309 Update examples
  examples/advanced-statefulset/tidb-cluster-scaled.yaml
  examples/advanced-statefulset/tidb-cluster.yaml
  examples/advanced/tidb-cluster.yaml
  examples/advanced/tidb-monitor.yaml
  examples/aks/tidb-cluster.yaml
  examples/auto-scale/tidb-cluster.yaml
  examples/aws/tidb-cluster.yaml
  examples/basic-cn/tidb-cluster.yaml
  examples/basic-storagevolumes/tidb-cluster.yaml
  examples/basic-tls/tidb-cluster.yaml
  examples/basic/tidb-cluster.yaml
  examples/dm/dm-cluster.yaml
  examples/gcp/tidb-cluster.yaml
  examples/heterogeneous-tls/heterogeneous-cluster.yaml
  examples/heterogeneous-tls/tidb-cluster.yaml
  examples/heterogeneous/heterogeneous-cluster.yaml
  examples/heterogeneous/tidb-cluster.yaml
  examples/initialize/tidb-cluster.yaml
  examples/monitor-dynamic-configmap/ns1-cluster.yaml
  examples/monitor-dynamic-configmap/ns2-cluster.yaml
  examples/monitor-multiple-cluster-non-tls/ns1-cluster.yaml
  examples/monitor-multiple-cluster-non-tls/ns2-cluster.yaml
  examples/monitor-multiple-cluster-tls/ns1-cluster.yaml
  examples/monitor-multiple-cluster-tls/ns2-cluster.yaml
  examples/monitor-prom-remotewrite/tidb-cluster.yaml
  examples/monitor-shards/tidb-cluster.yaml
  examples/multi-cluster/tidb-cluster-1.yaml
  examples/multi-cluster/tidb-cluster-2.yaml
  examples/multiple-pv-tikv/tidb-cluster.yaml
  examples/namespaced/tidb-cluster.yaml
  examples/prometheus-operator/tidb-cluster.yaml
  examples/selfsigned-tls/tidb-cluster.yaml
  examples/tiflash/tidb-cluster.yaml
Labels: status/can-merge, status/LGT2, needs-cherry-pick-1.2

#4306 Don't update config of components when tls is enable
  pkg/manager/member/dm_master_member_manager.go
  pkg/manager/member/dm_worker_member_manager.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/pump_member_manager.go
  pkg/manager/member/ticdc_member_manager.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tikv_member_manager.go
  pkg/manager/member/utils.go
  tests/e2e/tidbcluster/tidbcluster.go
Labels: status/can-merge, status/LGT2, needs-cherry-pick-1.2

#4209 Optimize: Deprecate pod validating and mutating webhook
  charts/tidb-operator/templates/admission/admission-webhook-registration.yaml
  charts/tidb-operator/templates/controller-manager-deployment.yaml
  charts/tidb-operator/values.yaml
  ci/deploy_tidb_operator_staging.groovy
  cmd/admission-webhook/main.go
  cmd/controller-manager/main.go
  go.mod
  pkg/controller/dependences.go
  pkg/controller/periodicity/periodicity_controller.go
  pkg/manager/member/dm_master_scaler.go
  pkg/manager/member/dm_master_upgrader.go
  pkg/manager/member/dm_worker_scaler.go
  pkg/manager/member/pd_scaler.go
  pkg/manager/member/pd_upgrader.go
  pkg/manager/member/tiflash_scaler.go
  pkg/manager/member/tikv_scaler.go
  pkg/manager/member/tikv_upgrader.go
  pkg/webhook/pod/pd_deleter.go
  pkg/webhook/pod/pd_deleter_test.go
  pkg/webhook/pod/pod_mutater.go
  pkg/webhook/pod/pods.go
  pkg/webhook/pod/pods_test.go
  pkg/webhook/pod/tikv_creater.go
  pkg/webhook/pod/tikv_creater_test.go
  pkg/webhook/pod/tikv_deleter.go
  pkg/webhook/pod/tikv_deleter_test.go
  pkg/webhook/pod/tikv_util.go
  pkg/webhook/pod/util.go
  pkg/webhook/pod/util_test.go
  tests/actions.go
  tests/cmd/stability/main.go
  tests/e2e/config/config.go
  tests/e2e/tidbcluster/serial.go
  tests/e2e/tidbcluster/stability-asts.go
  tests/e2e/tidbcluster/tidbcluster.go
  tests/e2e/tidbcluster/util.go
  tests/pkg/webhook/pods.go
Labels: status/can-merge, status/LGT2

#4320 add build debugger symbols back
  Makefile
Labels: status/can-merge, status/LGT2, needs-cherry-pick-1.2

#4313 Support all component spec fields for DM
  docs/api-references/docs.md
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_dmclusters.yaml
  manifests/crd/v1beta1/pingcap.com_dmclusters.yaml
  manifests/crd_v1beta1.yaml
  pkg/apis/pingcap/v1alpha1/dmcluster_test.go
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbcluster_component.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/manager/member/dm_master_member_manager.go
  pkg/manager/member/dm_master_member_manager_test.go
  pkg/manager/member/dm_worker_member_manager.go
  pkg/manager/member/dm_worker_member_manager_test.go
Labels: status/can-merge, status/LGT2, needs-cherry-pick-1.2

#4317 Remove incorrect default value
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_dmclusters.yaml
  manifests/crd/v1/pingcap.com_tidbclusters.yaml
  manifests/crd/v1beta1/pingcap.com_tidbclusters.yaml
  manifests/crd_v1beta1.yaml
  pkg/apis/pingcap/v1alpha1/types.go
Labels: status/can-merge, status/LGT2

#4312 Support to enable TLS for ng monitoring
  pkg/controller/tidbngmonitoring/tidb_ng_monitoring_control.go
  pkg/controller/tidbngmonitoring/tidb_ng_monitoring_control_test.go
  pkg/controller/tidbngmonitoring/tidb_ng_monitoring_controller.go
  pkg/manager/manager.go
  pkg/manager/tidbngmonitoring/name.go
  pkg/manager/tidbngmonitoring/ng_monitoring_manager.go
  pkg/manager/tidbngmonitoring/ng_monitoring_manager_test.go
  pkg/manager/tidbngmonitoring/tc_asset_manager.go
  pkg/manager/tidbngmonitoring/tc_asset_manager_test.go
  pkg/manager/utils/statefulset_builder_test.go
Labels: status/can-merge, status/LGT2

#4257 Proposal: Refactor admission webhook
  docs/design-proposals/2021-11-12-refactor-admission-webhook.md
Labels: status/can-merge, status/LGT2

#4323 remove default for DmClusterSpec
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_dmclusters.yaml
  manifests/crd/v1beta1/pingcap.com_dmclusters.yaml
  manifests/crd_v1beta1.yaml
  pkg/apis/pingcap/v1alpha1/types.go
Labels: status/can-merge, status/LGT2

#4324 Defaulting ns of target cluster to be same as TidbNGMonitoring
  docs/api-references/docs.md
  pkg/apis/pingcap/v1alpha1/defaulting/tidb_ng_monitoring.go
  pkg/apis/pingcap/v1alpha1/defaulting/tidb_ng_monitoring_test.go
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbmonitor_types.go
  pkg/controller/tidbngmonitoring/tidb_ng_monitoring_control.go
Labels: status/can-merge, status/LGT2

#4325 add podAntiAffinity for aws/gcp/aks examples
  examples/aks/tidb-cluster.yaml
  examples/aws/tidb-cluster.yaml
  examples/gcp/tidb-cluster.yaml
Labels: status/LGT1, needs-cherry-pick-1.2

#4314 add failover cases for x-k8s tidb cluster
  docs/api-references/docs.md
  manifests/crd.yaml
  manifests/crd_v1beta1.yaml
  pkg/apis/pingcap/v1alpha1/types.go
  tests/actions.go
  tests/e2e/tidbcluster/across-kubernetes.go
  tests/e2e/util/tidbcluster/tidbcluster.go
Labels: status/can-merge, status/LGT2

#4333 Add evictLeaderTimeout for the examples where replicas of TiKV is 1
  examples/basic-cn/tidb-cluster.yaml
  examples/basic-storagevolumes/tidb-cluster.yaml
  examples/basic-tls/tidb-cluster.yaml
  examples/basic/tidb-cluster.yaml
Labels: status/LGT2, needs-cherry-pick-1.2
