Repository pingcap/tidb-operator, pull requests merged in 2021-05, with the labels that each got.

#3956 update cn registry and remove cn example for GitHub Actions
  examples/basic-cn/tidb-cluster.yaml
  examples/basic-cn/tidb-monitor.yaml
  tests/examples/003-basic-cn.sh
Labels: status/LGT2, status/can-merge

#3965 fix no tidb
  pkg/manager/member/tidbcluster_status_manager.go
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge

#3946 e2e: add a basic test case for DM
  tests/actions.go
  tests/dm.go
  tests/e2e/dmcluster/dmcluster.go
  tests/e2e/e2e.go
  tests/e2e/e2e_test.go
  tests/e2e/util/image/image.go
  tests/pkg/fixture/fixture.go
Labels: status/LGT2, status/can-merge

#3961 Support loading kubeconfig from the 'KUBECONFIG' env
  cmd/controller-manager/main.go
Labels: status/LGT2, status/can-merge

#3959 Optimize monitor document desc
  README.md
Labels: status/LGT2, status/can-merge

#3947 get pd urls from discovery for tiflash/pump/ticdc when enable cluster domain
  pkg/apis/pingcap/v1alpha1/defaulting/tidbcluster.go
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/controller/pd_control.go
  pkg/controller/pod_control.go
  pkg/manager/member/pump_member_manager.go
  pkg/manager/member/template.go
  pkg/manager/member/template_test.go
  pkg/manager/member/ticdc_member_manager.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tidbcluster_status_manager.go
  pkg/manager/member/tiflash_member_manager.go
  pkg/manager/member/tiflash_util.go
  pkg/manager/member/tiflash_util_test.go
  pkg/manager/member/tikv_member_manager.go
  pkg/manager/member/tikv_member_manager_test.go
  pkg/manager/member/tikv_upgrader.go
  pkg/monitor/monitor/monitor_manager.go
  pkg/webhook/pod/pods.go
  tests/failover.go
  tests/pkg/webhook/pods.go
Labels: status/LGT2

#3968 fix: advanced example TiFlash conf
  examples/advanced/tidb-cluster.yaml
Labels: status/LGT2, status/can-merge

#3970 Fix the bug that rolling update may happen after changing `configUpdateStrategy` from `InPlace` to `RollingUpdate`.
  pkg/manager/member/config.go
  pkg/manager/member/config_test.go
Labels: status/LGT2, status/can-merge

#3972 Fix dm-master restarted failed; add scale E2E cases
  pkg/manager/member/template.go
  tests/dm.go
  tests/e2e/dmcluster/dmcluster.go
Labels: status/LGT2, status/can-merge

#3958 Add some useful additional printer columns for TidbMonitor
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/tidbmonitor_types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/monitor/monitor/monitor_manager.go
  pkg/util/crdutil.go
Labels: status/LGT2, status/can-merge

#3940 fix the method counting pd members when scaling out pd
  pkg/manager/member/pd_scaler.go
  pkg/manager/member/pd_scaler_test.go
Labels: status/LGT2, status/can-merge

#3934 Update the main TiDB version to v5.0 in e2e
  ci/pull_e2e_kind.groovy
  ci/pull_e2e_release.groovy
  pkg/manager/member/utils.go
  tests/actions.go
  tests/e2e/tidbcluster/serial.go
  tests/e2e/tidbcluster/stability-asts.go
  tests/e2e/tidbcluster/stability-br.go
  tests/e2e/tidbcluster/stability.go
  tests/e2e/tidbcluster/tidbcluster.go
  tests/e2e/util/image/image.go
Labels: status/LGT2, status/can-merge

#3974 examples: Update AWS ELB config
  examples/aws/tidb-cluster.yaml
  examples/aws/tidb-monitor.yaml
Labels: status/LGT2, status/can-merge

#3977 e2e: add dmctl and TLS cases for DM, some fix for previous cases
  tests/actions.go
  tests/dm.go
  tests/e2e/dmcluster/dmcluster.go
  tests/e2e/e2e.go
  tests/e2e/tidbcluster/stability-br.go
  tests/e2e/tidbcluster/tidbcluster.go
  tests/e2e/tidbcluster/tls.go
  tests/e2e/util/image/image.go
Labels: status/LGT2, status/can-merge

#3979 backup-manager: avoid logging the database password
  cmd/backup-manager/app/export/export.go
Labels: needs-cherry-pick-1.1, security, status/LGT2, status/can-merge

#3981 add custom annotations in the tidb-operator helm chart (#3957)
  charts/tidb-operator/templates/controller-manager-deployment.yaml
  charts/tidb-operator/templates/scheduler-deployment.yaml
  charts/tidb-operator/values.yaml
Labels: status/LGT2, status/can-merge

#3989 fix grammar errors in code comments
  pkg/controller/dmcluster/dm_cluster_control.go
  pkg/controller/tidbcluster/tidb_cluster_control.go
Labels: status/LGT2, status/can-merge

#3992 README: remove the TiDB Monthly link
  README.md
Labels: status/LGT2, status/can-merge

#3991 *: fix TidbMonitor for DmCluster with TLS enabled; add some e2e test cases
  pkg/monitor/monitor/template.go
  pkg/monitor/monitor/template_test.go
  pkg/util/util.go
  tests/actions.go
  tests/dm.go
  tests/e2e/dmcluster/dmcluster.go
  tests/e2e/util/image/image.go
  tests/monitor.go
  tests/pkg/fixture/fixture.go
Labels: status/LGT2, status/can-merge

#3982 e2e: add delete dc, auto failover, upgrade test cases
  tests/actions.go
  tests/e2e/dmcluster/dmcluster.go
  tests/e2e/util/image/image.go
Labels: status/LGT2, status/can-merge

#3993 e2e: fix some It args; replace local-storage sc for PD scale case
  tests/e2e/tidbcluster/stability.go
  tests/e2e/tidbcluster/tidbcluster.go
Labels: status/LGT2, status/can-merge

#3892 Enable customized labels for TidbCluster pods and "use-by=end-user" services
  .gitignore
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbcluster_component.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/backup/backup/backup_cleaner.go
  pkg/backup/backup/backup_manager.go
  pkg/backup/backupschedule/backup_schedule_manager.go
  pkg/backup/restore/restore_manager.go
  pkg/manager/member/dm_master_member_manager.go
  pkg/manager/member/dm_worker_member_manager.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/pump_member_manager.go
  pkg/manager/member/ticdc_member_manager.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tidb_member_manager_test.go
  pkg/manager/member/tiflash_member_manager.go
  pkg/manager/member/tikv_member_manager.go
  pkg/manager/member/utils.go
  pkg/manager/member/utils_test.go
  pkg/monitor/monitor/util.go
  pkg/util/object_meta.go
  pkg/util/object_meta_test.go
  tests/e2e/tidbcluster/tidbcluster.go
  tests/pkg/fixture/fixture.go
Labels: status/LGT2, status/can-merge

#3973 Support fully lifecycle management for Pump
  docs/api-references/docs.md
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/binlog/binlog.go
  pkg/controller/tidbcluster/tidb_cluster_controller.go
  pkg/manager/member/pump_member_manager.go
  pkg/manager/member/pump_member_manager_test.go
  pkg/manager/member/pump_scaler.go
  pkg/manager/member/pump_scaler_test.go
  pkg/manager/member/scaler.go
  pkg/manager/meta/meta_manager.go
  pkg/pdapi/pd_control.go
  tests/actions.go
  tests/e2e/tidbcluster/tidbcluster.go
Labels: needs-update-docs, status/LGT2, status/can-merge

#3986 add backup and restore e2e test
  cmd/backup-manager/app/export/export.go
  cmd/backup-manager/app/export/manager.go
  pkg/util/util.go
  tests/e2e/br/br.go
  tests/e2e/br/framework/br/data.go
  tests/e2e/br/framework/br/wait.go
  tests/e2e/br/framework/framework.go
  tests/e2e/br/utils/blockwriter/writer.go
  tests/e2e/br/utils/feature/feature.go
  tests/e2e/br/utils/once/once.go
  tests/e2e/br/utils/portforward/helper.go
  tests/e2e/br/utils/portforward/portforward.go
  tests/e2e/br/utils/s3/interface.go
  tests/e2e/br/utils/s3/minio.go
  tests/e2e/br/utils/tls/manager.go
  tests/e2e/br/utils/yaml/dynamic.go
  tests/e2e/e2e.go
  tests/e2e/e2e_test.go
Labels: status/LGT2, status/can-merge

#3999 Bump operator to v1.2.0-rc.1 and DM to v2.0.3
  charts/tidb-cluster/values.yaml
  charts/tidb-operator/values.yaml
  deploy/aliyun/variables.tf
  deploy/aws/variables.tf
  deploy/gcp/variables.tf
  examples/dm/dm-cluster.yaml
  hack/bump-version.sh
Labels: status/LGT2, status/can-merge

#3994 Retry checkout if checkout code failed
  ci/e2e_eks.groovy
  ci/e2e_gke.groovy
  ci/e2e_kind.groovy
  ci/pull_e2e_kind.groovy
  ci/pull_e2e_release.groovy
  ci/release-nightly.groovy
Labels: status/LGT2, status/can-merge
