Repository pingcap/tidb-operator, pull requests merged in 2021-06, with the labels that each got.

#4005 Remove some useless code
  pkg/monitor/monitor/util.go
  pkg/monitor/monitor/util_test.go
Labels: status/LGT2, status/can-merge

#3984 some tiny optimize for sts monitor
  pkg/monitor/monitor/monitor_manager.go
Labels: status/LGT2, status/can-merge

#4006 Update go version of workflow to 1.16
  .github/workflows/chaos.yaml
  .github/workflows/ci.yaml
Labels: status/LGT2, status/can-merge

#4008 fix tidb service and tc is updated continuously
  pkg/binlog/binlog.go
  pkg/controller/equality.go
  pkg/manager/member/tidb_member_manager.go
Labels: status/LGT2, status/can-merge

#4002 Operator add liveness readiness probe
  charts/tidb-operator/templates/controller-manager-deployment.yaml
Labels: status/LGT2, status/can-merge

#4011 fix chaos workflow
  .github/workflows/chaos.yaml
Labels: status/LGT2, status/can-merge

#4004 storage support for TiCDC
  docs/api-references/docs.md
  examples/advanced/tidb-cluster.yaml
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/validation/validation.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/tidbcluster/tidb_cluster_controller.go
  pkg/manager/member/pvc_resizer.go
  pkg/manager/member/pvc_resizer_test.go
  pkg/manager/member/ticdc_member_manager.go
  pkg/manager/member/ticdc_member_manager_test.go
  pkg/manager/member/ticdc_scaler.go
  pkg/manager/member/ticdc_scaler_test.go
  pkg/manager/meta/meta_manager.go
  tests/e2e/tidbcluster/tidbcluster.go
Labels: status/LGT2, status/can-merge

#4010 support config file for cdc
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/cdc_config_wraper.go
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/member/ticdc_member_manager.go
  pkg/manager/member/ticdc_member_manager_test.go
  tests/actions.go
  tests/e2e/tidbcluster/tidbcluster.go
  tests/pkg/fixture/fixture.go
Labels: status/LGT2, status/can-merge

#4016 e2e: add mirror for k8s.gcr.io
  hack/e2e.sh
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge

#4025 Update example file "tidb-cluster.yaml"
  examples/advanced/tidb-cluster.yaml
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge

#4030 Update the TiCDC capture status info in the `status.ticdc`
  docs/api-references/docs.md
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/controller/ticdc_control.go
  pkg/manager/member/ticdc_member_manager.go
Labels: status/LGT2, status/can-merge

#4033 Handle the PVC during scaling of TiDB
  pkg/controller/tidbcluster/tidb_cluster_controller.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tidb_member_manager_test.go
  pkg/manager/member/tidb_scaler.go
  pkg/manager/member/tidb_scaler_test.go
  pkg/manager/meta/meta_manager.go
  pkg/manager/meta/meta_manager_test.go
  tests/e2e/tidbcluster/tidbcluster.go
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge

#4034 optimize tikv upgrade process
  pkg/manager/member/tikv_upgrader.go
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge

#4040 Fix blocked main synchronization when TiDB don't use PVC
  pkg/manager/meta/meta_manager.go
  pkg/util/util.go
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge

#4038 Update tidb-lightning's rclone image
  charts/tidb-lightning/values.yaml
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge

#3980 e2e: add case for upgrading from TiDB V4 to V5
  tests/e2e/tidbcluster/tidbcluster.go
Labels: status/LGT2, status/can-merge

#4015 Do not generate volumeMount if not neccessary
  docs/api-references/docs.md
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/validation/validation.go
  pkg/util/util.go
  pkg/util/utils_test.go
Labels: status/LGT2, status/can-merge

#4044 Use 'centos:8' image as the base image of tidb-backup-manager
  images/tidb-backup-manager/Dockerfile
  images/tidb-backup-manager/Dockerfile.e2e
Labels: status/LGT2, status/can-merge

#4037 Handle the PVC during scaling of TiDB (#4033)
  pkg/controller/tidbcluster/tidb_cluster_controller.go
  pkg/manager/member/pd_failover.go
  pkg/manager/member/scaler.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tidb_member_manager_test.go
  pkg/manager/member/tidb_scaler.go
  pkg/manager/member/tidb_scaler_test.go
  pkg/manager/member/utils.go
  pkg/manager/meta/meta_manager.go
  pkg/manager/meta/meta_manager_test.go
  pkg/util/util.go
  tests/e2e/tidbcluster/tidbcluster.go
Labels: status/LGT1, status/can-merge

#4045 Update the 'schedulerName' field of pump to 'default-scheduler'
  examples/advanced/tidb-cluster.yaml
Labels: status/LGT2, status/can-merge

#4029 add labels and annotations support for Discovery, TidbMonitor and TidbInitializer
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbmonitor_types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/generic_control.go
  pkg/manager/member/tidb_discovery_manager.go
  pkg/manager/member/tidb_init_manager.go
  pkg/monitor/monitor/util.go
  pkg/monitor/monitor/util_test.go
  pkg/util/object_meta.go
  pkg/util/object_meta_test.go
  tests/e2e/dmcluster/dmcluster.go
  tests/e2e/tidbcluster/tidbcluster.go
  tests/pkg/fixture/fixture.go
Labels: status/LGT2, status/can-merge

#4048 Improve `toolImage` to be able to set without image tag
  docs/api-references/docs.md
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/backup/backup/backup_manager.go
  pkg/backup/restore/restore_manager.go
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge
