Repository pingcap/tidb-operator, pull requests merged in 2021-03, with the labels that each got.

#3818 fix code coverage patch script
  hack/e2e-patch-codecov.sh
Labels: status/LGT2

#3791 remove interface OperatorActions
  tests/actions.go
  tests/backup.go
  tests/dt.go
  tests/e2e/tidbcluster/serial.go
  tests/e2e/tidbcluster/stability-asts.go
  tests/e2e/tidbcluster/stability-br.go
  tests/e2e/tidbcluster/stability.go
  tests/e2e/tidbcluster/tidbcluster.go
  tests/failover.go
  tests/log_dump.go
  tests/webhook.go
Labels: status/LGT2

#3798 add test case: delete resources controlled by tc
  tests/e2e/tidbcluster/tidbcluster.go
  tests/e2e/util/tidbcluster/tidbcluster.go
Labels: status/LGT2, status/can-merge

#3819 use new serviceaccount when release suffix is appended
  charts/tidb-operator/templates/controller-manager-deployment.yaml
  charts/tidb-operator/templates/controller-manager-rbac.yaml
  charts/tidb-operator/templates/scheduler-deployment.yaml
  charts/tidb-operator/templates/scheduler-rbac.yaml
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge

#3823 Fix rolling upgrade check caused by TiDB Operator upgrade in E2E
  docs/api-references/docs.md
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/manager/member/pd_member_manager_test.go
  pkg/manager/member/tidb_member_manager_test.go
  pkg/manager/member/tiflash_util_test.go
  pkg/manager/member/tikv_member_manager_test.go
  tests/e2e/tidbcluster/serial.go
Labels: status/LGT2, status/can-merge

#3816 Fix support for multiple pvc for tikv
  pkg/manager/member/pd_scaler_test.go
  pkg/manager/member/scaler.go
  pkg/manager/member/tikv_scaler.go
  pkg/manager/member/tikv_scaler_test.go
  pkg/manager/member/utils.go
  pkg/util/util.go
  tests/e2e/tidbcluster/tidbcluster.go
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge

#3767 Remove unnecessary Helm Chart deployment
  tests/e2e/tidbcluster/serial.go
  tests/e2e/tidbcluster/stability-asts.go
  tests/e2e/tidbcluster/stability.go
  tests/e2e/tidbcluster/tidbcluster.go
Labels: status/LGT2, status/can-merge

#3820 Fix support for multiple pvc for pd
  docs/api-references/docs.md
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/tidbcluster/tidb_cluster_control.go
  pkg/manager/member/dm_master_member_manager.go
  pkg/manager/member/dm_master_scaler.go
  pkg/manager/member/dm_worker_member_manager.go
  pkg/manager/member/dm_worker_scaler.go
  pkg/manager/member/failover.go
  pkg/manager/member/pd_failover.go
  pkg/manager/member/pd_failover_test.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/pd_scaler.go
  pkg/manager/member/pd_scaler_test.go
  pkg/manager/member/scaler.go
  pkg/manager/member/scaler_test.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tiflash_member_manager.go
  pkg/manager/member/tiflash_scaler.go
  pkg/manager/member/tikv_member_manager.go
  pkg/manager/member/tikv_scaler.go
  pkg/manager/member/tikv_scaler_test.go
  pkg/manager/member/utils.go
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge

#3838 run UT and upload coverage after PR merged
  .github/workflows/ci.yaml
Labels: status/LGT2

#3836 fix UnjoinedMembers in PD and DM cluster status
  docs/api-references/docs.md
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/member/dm_master_member_manager.go
  pkg/manager/member/dm_master_member_manager_test.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/pd_member_manager_test.go
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge

#3840 revert to hub.pingcap.net
  ci/pull_e2e_kind.groovy
Labels: status/LGT1

#3815 Support tidbMonitor multiple replicas to ensure high availabilit
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbmonitor_types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/monitor/monitor/util.go
Labels: status/LGT2, status/can-merge

#3842 do not run UT in jenkins anymore
  ci/pull_e2e_kind.groovy
Labels: status/LGT2, status/can-merge

#3843 e2e: fix tiny typos
  hack/e2e.sh
  hack/lib.sh
Labels: first-time-contributor, status/LGT2, status/can-merge

#3833 Support setting customized envs for backup and restore jobs
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/backup/backup/backup_cleaner.go
  pkg/backup/backup/backup_manager.go
  pkg/backup/backup/backup_test.go
  pkg/backup/restore/restore_manager.go
  pkg/backup/restore/restore_manager_test.go
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge

#3852 fix tc.spec.tidb nil pointer dereference
  pkg/manager/member/pd_member_manager.go
Labels: status/LGT2, status/can-merge

#3847 try to fix GIT_COMMIT env after PR merged in CI
  ci/pull_e2e_kind.groovy
Labels: status/LGT2

#3855 tidbmonitor add additional volume configuration
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbmonitor_types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/monitor/monitor/util.go
Labels: status/LGT2, status/can-merge

#3858 Fix PVC resize in multiple PVC setting
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/manager/member/pvc_resizer.go
  pkg/manager/member/pvc_resizer_test.go
Labels: status/LGT2, status/can-merge

#3865 *: export prometheus metrics for tidb-operator
  cmd/controller-manager/main.go
  pkg/controller/tidbcluster/tidb_cluster_control.go
  pkg/metrics/metrics.go
  pkg/metrics/tidbcluster.go
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge

#3872 add tikv status port(20180)
  docs/api-references/docs.md
  go.sum
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/manager/member/tidb_discovery_manager.go
  pkg/manager/member/tikv_member_manager.go
Labels: first-time-contributor, needs-cherry-pick-1.1, status/LGT2, status/can-merge

#3862 Add monitor additionalVolume example
  examples/monitor-with-thanos/tidb-monitor-with-additional-volumes.yaml
Labels: status/LGT1
