Repository pingcap/tidb-operator, pull requests merged in 2021-07, with the labels that each got.

#4054 Fixed potential nil pointer issues
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/apis/pingcap/v1alpha1/tidbcluster_component.go
  pkg/apis/pingcap/v1alpha1/validation/validation.go
  pkg/backup/backup/backup_manager.go
  pkg/backup/restore/restore_manager.go
  pkg/controller/tidbcluster/tidb_cluster_condition_updater.go
  pkg/manager/member/ticdc_member_manager.go
  pkg/tkctl/cmd/info/info.go
Labels: needs-cherry-pick-1.1, status/LGT2

#4056 Bump operator to v1.1.13 and tidb components to v4.0.13
  charts/tidb-cluster/values.yaml
  charts/tidb-drainer/values.yaml
  charts/tidb-lightning/values.yaml
  charts/tidb-operator/values.yaml
  charts/tikv-importer/values.yaml
  deploy/aliyun/manifests/db-monitor.yaml.example
  deploy/aliyun/manifests/db.yaml.example
  deploy/aliyun/variables.tf
  deploy/aws/manifests/db-monitor.yaml.example
  deploy/aws/manifests/db.yaml.example
  deploy/aws/variables.tf
  deploy/gcp/manifests/db-monitor.yaml.example
  deploy/gcp/manifests/db.yaml.example
  deploy/gcp/variables.tf
  deploy/modules/aliyun/tidb-cluster/variables.tf
  deploy/modules/aws/tidb-cluster/variables.tf
  deploy/modules/gcp/tidb-cluster/variables.tf
  deploy/modules/share/tidb-cluster-release/variables.tf
  examples/advanced-statefulset/tidb-cluster-scaled.yaml
  examples/advanced-statefulset/tidb-cluster.yaml
  examples/advanced/tidb-cluster.yaml
  examples/auto-scale/tidb-cluster.yaml
  examples/auto-scale/tidb-monitor.yaml
  examples/aws/tidb-cluster.yaml
  examples/aws/tidb-monitor.yaml
  examples/basic-cn/tidb-cluster.yaml
  examples/basic-cn/tidb-monitor.yaml
  examples/basic-tls/tidb-cluster.yaml
  examples/basic-tls/tidb-monitor.yaml
  examples/basic/tidb-cluster.yaml
  examples/basic/tidb-monitor.yaml
  examples/dm/dm-cluster.yaml
  examples/dm/dm-monitor.yaml
  examples/gcp/tidb-cluster.yaml
  examples/gcp/tidb-monitor.yaml
  examples/heterogeneous-tls/heterogeneous-cluster.yaml
  examples/heterogeneous-tls/tidb-cluster.yaml
  examples/heterogeneous-tls/tidb-monitor.yaml
  examples/heterogeneous/heterogeneous-cluster.yaml
  examples/heterogeneous/tidb-cluster.yaml
  examples/heterogeneous/tidb-monitor.yaml
  examples/initialize/tidb-cluster.yaml
  examples/monitor-multiple-cluster-non-tls/ns1-cluster.yaml
  examples/monitor-multiple-cluster-non-tls/ns2-cluster.yaml
  examples/monitor-multiple-cluster-non-tls/tidb-monitor.yaml
  examples/monitor-prom-remotewrite/tidb-monitor.yaml
  examples/monitor-with-externalConfigMap/tidb-monitor.yaml
  examples/multi-cluster/tidb-cluster-1.yaml
  examples/multi-cluster/tidb-cluster-2.yaml
  examples/multiple-pv-tikv/tidb-cluster.yaml
  examples/selfsigned-tls/tidb-cluster.yaml
  examples/tiflash/tidb-cluster.yaml
  examples/tiflash/tidb-monitor.yaml
  hack/bump-version.sh
  images/tidb-backup-manager/Dockerfile
  manifests/dm/master/dm-master.yaml
  manifests/dm/worker/base/dm-worker.yaml
Labels: status/LGT1, status/can-merge

#4061 Update version of grafana to 7.5.7
  deploy/aliyun/manifests/db-monitor.yaml.example
  deploy/aws/manifests/db-monitor.yaml.example
  deploy/gcp/manifests/db-monitor.yaml.example
  examples/auto-scale/tidb-monitor.yaml
  examples/aws/tidb-monitor.yaml
  examples/basic-cn/tidb-monitor.yaml
  examples/basic-tls/tidb-monitor.yaml
  examples/basic/tidb-monitor.yaml
  examples/dm/dm-monitor.yaml
  examples/gcp/tidb-monitor.yaml
  examples/heterogeneous-tls/tidb-monitor.yaml
  examples/heterogeneous/tidb-monitor.yaml
  examples/monitor-multiple-cluster-non-tls/tidb-monitor.yaml
  examples/monitor-multiple-cluster-tls/tidb-monitor.yaml
  examples/monitor-prom-remotewrite/tidb-monitor.yaml
  examples/monitor-with-externalConfigMap/grafana/tidb-monitor.yaml
  examples/monitor-with-externalConfigMap/prometheus/tidb-monitor.yaml
  examples/monitor-with-thanos/tidb-monitor-with-additional-volumes.yaml
  examples/monitor-with-thanos/tidb-monitor.yaml
  examples/namespaced/tidb-monitor.yaml
  examples/tiflash/tidb-monitor.yaml
  manifests/monitor/tidb-monitor.yaml
Labels: needs-cherry-pick-1.2, status/LGT2

#4063 Update version of kind to v0.11.1 and version of ubuntu to 20.04
  .github/workflows/chaos.yaml
  .github/workflows/ci.yaml
  .github/workflows/stale.yaml
  hack/lib.sh
Labels: needs-cherry-pick-1.1, needs-cherry-pick-1.2, status/LGT2, status/can-merge

#4068 Open SSH when workflow failed
  .github/workflows/chaos.yaml
  .github/workflows/ci.yaml
  tests/examples/001-basic.sh
  tests/examples/002-selfsigned-tls.sh
Labels: status/LGT2, status/can-merge

#4070 correct the wrong comments of NewController functions
  pkg/controller/backupschedule/backup_schedule_controller.go
  pkg/controller/dmcluster/dm_cluster_controller.go
  pkg/controller/tidbinitializer/tidb_initializer_controller.go
  pkg/controller/tidbmonitor/tidb_monitor_controller.go
Labels: status/LGT2, status/can-merge

#4071 Set the leader eviction default timeout of TiKV to 1500 min
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/manager/member/tikv_upgrader_test.go
Labels: needs-cherry-pick-1.1, needs-cherry-pick-1.2, needs-update-docs, status/LGT2, status/can-merge

#4072 correct `imagePullSecrets` usage of example
  examples/advanced/tidb-cluster.yaml
Labels: needs-cherry-pick-1.2, status/LGT2, status/can-merge

#4078 Backup job support specify priorityClassName.
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/backup/backup/backup_cleaner.go
  pkg/backup/backup/backup_manager.go
  pkg/backup/restore/restore_manager.go
Labels: needs-cherry-pick-1.2, status/LGT2, status/can-merge

#4079 Fix publish 'nightly' charts
  ci/release_tidb_operator_binary_and_image.groovy
Labels: status/LGT2, status/can-merge

#4087 fix remoteWrite parse error
  pkg/monitor/monitor/monitor_manager_test.go
  pkg/monitor/monitor/util.go
  pkg/monitor/monitor/util_test.go
Labels: needs-cherry-pick-1.2, status/LGT2, status/can-merge

#4082 add more test case for upgrade and br
  pkg/util/config/config.go
  pkg/util/config/config_test.go
  tests/actions.go
  tests/e2e/br/br.go
  tests/e2e/br/utils/feature/feature.go
  tests/e2e/dmcluster/dmcluster.go
  tests/e2e/tidbcluster/serial.go
  tests/e2e/tidbcluster/stability-asts.go
  tests/e2e/tidbcluster/stability-br.go
  tests/e2e/tidbcluster/stability.go
  tests/e2e/tidbcluster/tidbcluster.go
  tests/e2e/util/image/image.go
Labels: needs-cherry-pick-1.2, status/LGT2, status/can-merge

#4085 add `RetentionTime` overwrite `ReserveDays`
  charts/tidb-cluster/templates/monitor-deployment.yaml
  docs/api-references/docs.md
  pkg/apis/pingcap/v1alpha1/tidbmonitor_types.go
  pkg/apis/pingcap/v1alpha1/validation/validation.go
  pkg/apis/pingcap/v1alpha1/validation/validation_test.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/monitor/monitor/util.go
  pkg/monitor/monitor/util_test.go
Labels: needs-cherry-pick-1.2, needs-update-docs, status/LGT2, status/can-merge

#4090 *: Create SECURITY.md
  SECURITY.md
Labels: status/LGT2, status/can-merge

#4053 refactor sysbench manifests
  manifests/sysbench/README.md
  manifests/sysbench/base/kustomization.yaml
  manifests/sysbench/base/options.conf
  manifests/sysbench/base/sysbench.conf
  manifests/sysbench/base/sysbench.yaml
  manifests/sysbench/bench.yaml
  manifests/sysbench/clean/clean.yaml
  manifests/sysbench/clean/kustomization.yaml
  manifests/sysbench/config.yaml
  manifests/sysbench/kustomization.yaml
  manifests/sysbench/oltp_point_select/kustomization.yaml
  manifests/sysbench/oltp_point_select/oltp-point-select.yaml
  manifests/sysbench/prepare.yaml
  manifests/sysbench/prepare/init.yaml
  manifests/sysbench/prepare/kustomization.yaml
  manifests/sysbench/prepare/prepare.yaml
  manifests/sysbench/warmup.yaml
  manifests/sysbench/warmup/kustomization.yaml
  manifests/sysbench/warmup/warmup.yaml
Labels: status/LGT2, status/can-merge

#4088 use tc.Timezone()
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/pd_member_manager_test.go
  pkg/manager/member/pump_member_manager.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tikv_member_manager.go
Labels: needs-cherry-pick-1.2, status/LGT2, status/can-merge

#4097 Revert "use tc.Timezone()"
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/pd_member_manager_test.go
  pkg/manager/member/pump_member_manager.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tikv_member_manager.go
Labels: needs-cherry-pick-1.2, status/LGT2, status/can-merge

#4098 upgrade tiflash after pd
  pkg/controller/tidbcluster/tidb_cluster_control.go
  pkg/manager/member/pd_upgrader.go
  pkg/manager/member/pd_upgrader_test.go
  pkg/manager/member/tiflash_upgrader.go
  pkg/manager/member/tiflash_upgrader_test.go
Labels: needs-cherry-pick-1.1, needs-cherry-pick-1.2, status/LGT2, status/can-merge

#4103 Add `--comments` to READMEs
  examples/basic/README.md
  examples/tiflash/README.md
  marketplace/gcp/tidb-operator/README.md
Labels: status/LGT2, status/can-merge

#4105 Bump operator to v1.2.0
  charts/tidb-cluster/values.yaml
  charts/tidb-operator/values.yaml
  deploy/aliyun/variables.tf
  deploy/aws/variables.tf
  deploy/gcp/variables.tf
  hack/bump-version.sh
Labels: needs-cherry-pick-1.2, status/LGT2, status/can-merge
