Repository pingcap/tidb-operator, pull requests merged in 2021-08, with the labels that each got.

#4113 Only open ssh session when job is 'e2e-examples'
  .github/workflows/ci.yaml
Labels: needs-cherry-pick-1.2, status/LGT2, status/can-merge

#4118 move `binlog.NodeStatus` to `apis.PumpNodestatus`
  docs/api-references/docs.md
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/binlog/binlog.go
  pkg/manager/member/pump_member_manager.go
  pkg/manager/member/pump_member_manager_test.go
Labels: status/LGT2, status/can-merge

#4111 feat: support configure tidb-controller-manager workers number
  charts/tidb-operator/templates/controller-manager-deployment.yaml
  charts/tidb-operator/values.yaml
Labels: status/LGT2, status/can-merge

#4126 move `pkg/config` package into `pkg/apis` package
  docs/api-references/docs.md
  pkg/apis/pingcap/v1alpha1/cdc_config_wraper.go
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/pd_config_wraper.go
  pkg/apis/pingcap/v1alpha1/tidb_config_wraper.go
  pkg/apis/pingcap/v1alpha1/tiflash_config_wraper.go
  pkg/apis/pingcap/v1alpha1/tikv_config_wraper.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/util/config/config.go
  pkg/apis/util/config/config_test.go
  pkg/manager/member/pump_member_manager.go
  pkg/manager/member/pump_member_manager_test.go
  tests/e2e/tidbcluster/tidbcluster.go
  tests/pkg/fixture/fixture.go
Labels: status/can-merge, status/LGT2

#4125 move `pkg/toml` package into `pkg/apis` package
  pkg/apis/pingcap/v1alpha1/pd_config_wraper_test.go
  pkg/apis/pingcap/v1alpha1/tidb_config_wraper.go
  pkg/apis/pingcap/v1alpha1/tidb_config_wraper_test.go
  pkg/apis/pingcap/v1alpha1/tiflash_config_wraper_test.go
  pkg/apis/pingcap/v1alpha1/tikv_config_wraper_test.go
  pkg/apis/util/toml/toml.go
  pkg/apis/util/toml/toml_test.go
  pkg/manager/member/config.go
  pkg/manager/member/pd_member_manager_test.go
  pkg/manager/member/tidb_member_manager_test.go
  pkg/manager/member/tiflash_util_test.go
  pkg/manager/member/tikv_member_manager_test.go
  pkg/manager/member/utils.go
Labels: status/can-merge, status/LGT2

#4115 Add enableRule switch into tidbmonitor.
  docs/api-references/docs.md
  manifests/crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbmonitor_types.go
  pkg/monitor/monitor/template.go
  pkg/monitor/monitor/template_test.go
  pkg/monitor/monitor/util.go
Labels: status/can-merge, status/LGT2

#4128 Fix issue reported by `gosec` and enable `gosec` in the CI
  .golangci.yml
  cmd/backup-manager/app/util/generic.go
  hack/tools/go.mod
  hack/tools/go.sum
  hack/verify-spelling.sh
  pkg/autoscaler/autoscaler/util.go
  pkg/backup/backupschedule/backup_schedule_manager_test.go
  pkg/controller/controller_utils_test.go
  pkg/manager/member/dm_master_failover.go
  pkg/manager/member/dm_master_upgrader_test.go
  pkg/manager/member/dm_worker_member_manager_test.go
  pkg/manager/member/pd_failover.go
  pkg/manager/member/pd_upgrader_test.go
  pkg/manager/member/pump_member_manager_test.go
  pkg/manager/member/tidb_init_manager.go
  pkg/tkctl/cmd/diagnose/diagnose.go
  pkg/tkctl/cmd/get/get.go
  pkg/tkctl/cmd/upinfo/upinfo.go
  pkg/upgrader/upgrader.go
  pkg/upgrader/upgrader_test.go
  pkg/util/util.go
  pkg/webhook/pod/pd_deleter_test.go
  pkg/webhook/pod/pod_mutater.go
  pkg/webhook/strategy/webhook_test.go
  tests/e2e/e2e.go
  tests/e2e/tidbcluster/stability.go
Labels: status/can-merge, status/LGT2, needs-cherry-pick-1.2

#4132 fix potential nil pointer issue
  pkg/controller/dmcluster/dm_cluster_controller.go
  pkg/controller/tidbcluster/tidb_cluster_controller.go
Labels: status/can-merge, status/LGT2

#4134 Separate package `pkg/apis` and `pkg/client` into submodules
  Makefile
  go.mod
  hack/lib.sh
  hack/verify-lint.sh
  hack/verify-modules.sh
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/apis/pingcap/v1alpha1/dmcluster.go
  pkg/apis/pingcap/v1alpha1/helpers.go
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/client/go.mod
  pkg/client/go.sum
Labels: status/can-merge, status/LGT2

#4108 Separate grafana configuration into new configmap from the old configuration.
  pkg/apis/label/label.go
  pkg/monitor/monitor/monitor_manager.go
  pkg/monitor/monitor/util.go
  pkg/monitor/monitor/util_test.go
Labels: status/can-merge, status/LGT2

#4141 support hostnetwork for all components
  pkg/apis/pingcap/v1alpha1/tidbcluster_component.go
  pkg/manager/member/pd_member_manager_test.go
  tests/e2e/tidbcluster/tidbcluster.go
Labels: status/can-merge, status/LGT2, needs-cherry-pick-1.2

#4146 Update download address of `helm`
  ci/release_tidb_operator_binary_and_image.groovy
Labels: status/LGT2

#4140 Build tools and output to repo's dir instead of GOBIN
  hack/tools/Makefile
  hack/tools/README.md
  hack/tools/go.mod
  hack/tools/tools.go
  hack/update-goimports.sh
  hack/verify-boilerplate.sh
  hack/verify-lint.sh
  hack/verify-spelling.sh
Labels: status/can-merge, status/LGT2

#4152 use TiDBPeerMemberName to access tidb status port
  pkg/manager/member/tiflash_util.go
  pkg/manager/member/tiflash_util_test.go
Labels: status/can-merge, status/LGT2, needs-cherry-pick-1.2

#4149 split bucket/prefix to get new bucket and prefix
  cmd/backup-manager/app/util/remote.go
Labels: status/can-merge, status/LGT2, needs-cherry-pick-1.2

#4091 Fast evict leader
  pkg/manager/member/tikv_upgrader.go
  pkg/manager/member/tikv_upgrader_test.go
  pkg/webhook/pod/tikv_deleter.go
  tests/e2e/tidbcluster/tidbcluster.go
  tests/e2e/util/tidbcluster/tidbcluster.go
Labels: status/can-merge, status/LGT2

#4107 feat: force upgrade PD when PD replicas number is less than 2
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/pd_member_manager_test.go
  pkg/webhook/pod/pods.go
  tests/e2e/tidbcluster/tidbcluster.go
Labels: status/can-merge, status/LGT2
