Repository pingcap/tidb-operator, pull requests merged in 2022-06, with the labels that each got.

#4541 ci use new cluster
  ci/e2e_eks.groovy
  ci/e2e_gke.groovy
  ci/e2e_kind.groovy
  ci/pull_e2e_kind.groovy
  ci/pull_e2e_release.groovy
  ci/release-nightly.groovy
  ci/release_cli_binary_and_debug_image.groovy
  ci/release_tidb_operator_binary_and_image.groovy
  ci/vm.groovy
  hack/e2e.sh
Labels: status/can-merge, status/LGT2, needs-cherry-pick-1.2, needs-cherry-pick-1.3

#4478 Support to deploy v1 admission webhook
  charts/tidb-operator/templates/admission/admission-webhook-registration.yaml
  charts/tidb-operator/values.yaml
  cmd/admission-webhook/main.go
  tests/e2e/tidbcluster/serial.go
  tests/e2e/util/pod/pod.go
  tests/webhook.go
Labels: status/can-merge, status/LGT2

#4293 Improve: advanced example of Backup and Restore
  docs/api-references/docs.md
  examples/advanced/backup-schedule.yaml
  examples/advanced/backup.yaml
  examples/advanced/restore.yaml
  examples/advanced/tidb-cluster.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
Labels: status/can-merge, status/LGT2

#4554 bump operator to v1.3.4
  charts/tidb-cluster/values.yaml
  charts/tidb-operator/values.yaml
  deploy/aliyun/variables.tf
  deploy/aws/variables.tf
  deploy/gcp/variables.tf
  go.mod
  hack/bump-version.sh
  pkg/client/go.mod
Labels: status/can-merge, status/LGT2, needs-cherry-pick-1.3

#4559 Fix release ci
  ci/pull_e2e_kind.groovy
  ci/pull_e2e_release.groovy
Labels: needs-cherry-pick-1.2, needs-cherry-pick-1.3

#4562 use internal fileserver to save binary and charts
  ci/deploy_tidb_operator_staging.groovy
  ci/pull_e2e_kind.groovy
  ci/pull_e2e_release.groovy
  ci/release-nightly.groovy
  ci/release_tidb_operator_binary_and_image.groovy
  ci/upload-binaries-charts.sh
Labels: status/LGT1

#4513 Add tidbmonitor remote write e2e example
  tests/e2e/remotewrite/resource.go
  tests/e2e/tidbcluster/tidbcluster.go
  tests/monitor.go
Labels: status/can-merge, status/LGT2

#4565 optimize clean pod log
  cmd/backup-manager/app/clean/clean.go
  pkg/controller/backup/backup_control.go
Labels: status/can-merge, status/LGT2, needs-cherry-pick-1.3

#4569 Bump operator to v1.3.5
  charts/tidb-cluster/values.yaml
  charts/tidb-operator/values.yaml
  deploy/aliyun/variables.tf
  deploy/aws/variables.tf
  deploy/gcp/variables.tf
  go.mod
  hack/bump-version.sh
  pkg/client/go.mod
Labels: status/can-merge, status/LGT2, needs-cherry-pick-1.3

#4604 Resize PVCs pod by pod
  pkg/manager/member/pvc_resizer.go
  pkg/manager/member/pvc_resizer_test.go
Labels: status/can-merge, status/LGT2, needs-cherry-pick-1.3
