Repository pingcap/tidb-operator, pull requests merged in 2022-10, with the labels that each got.

#4729 upgrade ubuntu to 22.04 for workflow
  .github/workflows/ci.yaml
Labels: status/LGT1, needs-cherry-pick-1.3

#4733 Fix tidb-debug image build
  misc/images/tidb-debug/Dockerfile
Labels: status/LGT1

#4736 bump operator to v1.3.9
  charts/tidb-cluster/values.yaml
  charts/tidb-operator/values.yaml
  deploy/aliyun/variables.tf
  deploy/aws/variables.tf
  deploy/gcp/variables.tf
  go.mod
  hack/bump-version.sh
  pkg/client/go.mod
Labels: status/LGT1

#4727 *: automatical align to go116
  hack/go117.patch
  hack/update-codegen.sh
Labels: status/can-merge, status/LGT2

#4740 charts: deprecate tidb-cluster and tidb-backup
  charts/tidb-backup/Chart.yaml
  charts/tidb-cluster/Chart.yaml
Labels: status/can-merge, status/LGT2

#4716 br: support track tls cluster's log backup progress
  cmd/backup-manager/app/backup/manager.go
  pkg/backup/backup/backup_manager.go
  pkg/backup/backup/backup_tracker.go
  pkg/backup/restore/restore_manager.go
  tests/e2e/br/br.go
Labels: status/can-merge, tools/br, status/LGT2

#4744 tc: wait for scaling done when upgrading to avoid restart pods twice
  pkg/manager/member/pd_scaler.go
  pkg/manager/member/pump_member_manager.go
  pkg/manager/member/ticdc_upgrader.go
  pkg/manager/member/tidb_upgrader.go
  pkg/manager/member/tiflash_upgrader.go
  pkg/manager/member/tikv_upgrader.go
  tests/e2e/tidbcluster/across-kubernetes.go
Labels: status/LGT1

#4743 br: add retry when get backup meta data
  cmd/backup-manager/app/util/util.go
Labels: status/can-merge, status/LGT2

#4746 BR: log backup checkpoint ts can be updated when operator restart
  pkg/backup/backup/backup_tracker.go
Labels: status/can-merge, status/LGT2

#4752 bump operator to 1.4.0-alpha.2
  charts/tidb-cluster/values.yaml
  charts/tidb-operator/values.yaml
  deploy/aliyun/variables.tf
  deploy/aws/variables.tf
  deploy/gcp/variables.tf
  go.mod
  hack/bump-version.sh
  pkg/client/go.mod
Labels: status/LGT1

#4756 bump operator to 1.4.0-beta.1
  charts/tidb-cluster/values.yaml
  charts/tidb-operator/values.yaml
  deploy/aliyun/variables.tf
  deploy/aws/variables.tf
  deploy/gcp/variables.tf
  go.mod
  hack/bump-version.sh
  pkg/client/go.mod
Labels: status/LGT1
