Repository pingcap/tidb-operator, pull requests merged in 2022-12, with the labels that each got.

#4785 support tidb token auth
  docs/api-references/docs.md
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_tidbclusters.yaml
  manifests/crd/v1beta1/pingcap.com_tidbclusters.yaml
  manifests/crd_v1beta1.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/member/tidb_member_manager.go
  pkg/util/util.go
Labels: status/can-merge, status/LGT2

#4793 bump operator to 1.4.0-beta.4
  charts/tidb-cluster/values.yaml
  charts/tidb-operator/values.yaml
  deploy/aliyun/variables.tf
  deploy/aws/variables.tf
  deploy/gcp/variables.tf
  go.mod
  hack/bump-version.sh
  pkg/client/go.mod
Labels: status/can-merge, status/LGT2

#4795 fix: restore the cluster to the same eks with diff namespace
  pkg/backup/snapshotter/snapshotter.go
Labels: status/can-merge, status/LGT2

#4798 feat(controller): treat "master" as latest version
  pkg/util/cmpver/cmpver.go
  pkg/util/cmpver/cmpver_test.go
Labels: status/can-merge, status/LGT2

#4788 Add a common failover handling for tikv and tiflash failover
  pkg/manager/member/common_store_failover.go
  pkg/manager/member/tiflash_failover.go
  pkg/manager/member/tikv_failover.go
  pkg/manager/member/tikv_failover_test.go
Labels: status/can-merge, status/LGT2

#4762 Fix broken links in examples docs
  examples/auto-scale/README.md
  examples/basic/README.md
  examples/dm/README.md
  examples/initialize/README.md
  examples/istio/README.md
  examples/namespaced/README.md
  examples/tiflash/README.md
Labels: status/LGT1

#4806 Fix mysql client cert parameters
  examples/basic-tls/tidb-dashboard.yaml
  pkg/manager/tidbdashboard/manager.go
Labels: status/LGT2

#4802 *: update TiProxy logic and fix goroutine leak
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/client/go.sum
  pkg/controller/tiproxy_control.go
  pkg/manager/member/tiproxy_member_manager.go
Labels: status/can-merge, status/LGT2

#4763 Add pd/tikv liveness probe
  docs/api-references/docs.md
  examples/readiness/tidb-cluster.yaml
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_dmclusters.yaml
  manifests/crd/v1/pingcap.com_tidbclusters.yaml
  manifests/crd/v1/pingcap.com_tidbdashboards.yaml
  manifests/crd/v1/pingcap.com_tidbngmonitorings.yaml
  manifests/crd/v1beta1/pingcap.com_dmclusters.yaml
  manifests/crd/v1beta1/pingcap.com_tidbclusters.yaml
  manifests/crd/v1beta1/pingcap.com_tidbdashboards.yaml
  manifests/crd/v1beta1/pingcap.com_tidbngmonitorings.yaml
  manifests/crd_v1beta1.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/pd_member_manager_test.go
  pkg/manager/member/tidb_member_manager_test.go
  pkg/manager/member/tikv_member_manager.go
  pkg/manager/member/tikv_member_manager_test.go
  pkg/manager/member/utils.go
Labels: status/LGT2

#4717 fix-rcloneImage
  charts/tidb-lightning/values.yaml
  images/tidb-backup-manager/Dockerfile
  images/tidb-backup-manager/Dockerfile.e2e
Labels: status/can-merge, status/LGT2

#4677 delete minor unreachable code caused by log.Fatal
  misc/cmd/debug-launcher/main.go
Labels: status/can-merge, status/LGT2

#4810 BR: log backup add stopped status to support truncate after stop
  manifests/crd.yaml
  manifests/crd_v1beta1.yaml
  pkg/apis/pingcap/v1alpha1/backup.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/controller/backup/backup_controller.go
  pkg/controller/backup_status_updater.go
  tests/e2e/br/br.go
Labels: status/LGT2

#4811 make tikv/tiflash compatible with IPv6
  docs/api-references/docs.md
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_tidbclusters.yaml
  manifests/crd/v1beta1/pingcap.com_tidbclusters.yaml
  manifests/crd_v1beta1.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/manager/member/startscript/v1/render_script.go
  pkg/manager/member/startscript/v1/template.go
  pkg/manager/member/startscript/v1/template_test.go
  pkg/manager/member/startscript/v2/tikv_start_script.go
  pkg/manager/member/startscript/v2/tikv_start_script_test.go
  pkg/manager/member/tiflash_util.go
  pkg/manager/member/tiflash_util_test.go
Labels: status/LGT1

#4782 Remove failed pod and pvcs of PD, TIKV and TiFlash components for auto failure recovery
  docs/api-references/docs.md
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_tidbclusters.yaml
  manifests/crd/v1beta1/pingcap.com_tidbclusters.yaml
  manifests/crd_v1beta1.yaml
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/dependences.go
  pkg/controller/pod_control.go
  pkg/manager/member/common_store_failover.go
  pkg/manager/member/failover.go
  pkg/manager/member/failure_recovery.go
  pkg/manager/member/failure_recovery_test.go
  pkg/manager/member/node.go
  pkg/manager/member/pd_failover.go
  pkg/manager/member/pd_failover_test.go
  pkg/manager/member/tiflash_failover.go
  pkg/manager/member/tiflash_failover_test.go
  pkg/manager/member/tikv_failover.go
  pkg/manager/member/tikv_failover_test.go
Labels: status/LGT2

#4700 improve-log-in-getNodeLabels
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tiflash_member_manager.go
  pkg/manager/member/tikv_member_manager.go
Labels: status/LGT2

#4737 Failed to scale down tikv instances less than 3
  pkg/manager/member/tikv_scaler.go
Labels: status/can-merge, status/LGT2

#4749 add aws-load-balancer-internal in tidb-cluster.yaml for aws
  examples/aws/tidb-cluster.yaml
Labels: status/can-merge, status/LGT2

#4796 ci(hack): add `--fail` curl cli option in `ensure_helm`
  hack/lib.sh
Labels: status/LGT2
