Repository pingcap/tidb-operator, pull requests merged in 2022-11, with the labels that each got.

#4767 BR: fix backup schedule set no Azure prefix
  pkg/backup/backupschedule/backup_schedule_manager.go
Labels: status/LGT2

#4771 upgrade aws sdk to v1.44.72 to support new region ap-southeast-3
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/client/go.sum
Labels: status/LGT2

#4776 bump operator to 1.4.0-beta.2
  charts/tidb-cluster/values.yaml
  charts/tidb-operator/values.yaml
  deploy/aliyun/variables.tf
  deploy/aws/variables.tf
  deploy/gcp/variables.tf
  go.mod
  hack/bump-version.sh
  pkg/client/go.mod
Labels: status/LGT1

#4765 *: also fix for other two codegen scripts
  hack/lib.sh
  hack/update-codegen.sh
  hack/update-goimports.sh
  hack/update-openapi-spec.sh
Labels: status/can-merge, status/LGT2

#4693 initial support for tiproxy [2/2]
  .golangci.yml
  charts/tidb-cluster/templates/config/_prometheus-config.tpl
  charts/tidb-cluster/templates/tidb-cluster.yaml
  charts/tidb-cluster/values.yaml
  docs/api-references/docs.md
  go.mod
  go.sum
  hack/localtest/cfssl/.gitignore
  hack/localtest/cfssl/ca-config.json
  hack/localtest/cfssl/ca-csr.json
  hack/localtest/cfssl/client-csr.json
  hack/localtest/cfssl/comp-csr.json
  hack/localtest/cluster.yaml
  hack/localtest/test.sh
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_tidbclusters.yaml
  manifests/crd/v1beta1/pingcap.com_tidbclusters.yaml
  manifests/crd_v1beta1.yaml
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/apis/label/label.go
  pkg/apis/label/label_test.go
  pkg/apis/pingcap/v1alpha1/component_spec.go
  pkg/apis/pingcap/v1alpha1/component_status.go
  pkg/apis/pingcap/v1alpha1/defaulting/tidbcluster.go
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/client/go.sum
  pkg/controller/controller_utils.go
  pkg/controller/controller_utils_test.go
  pkg/controller/dependences.go
  pkg/controller/tidbcluster/tidb_cluster_control.go
  pkg/controller/tidbcluster/tidb_cluster_control_test.go
  pkg/controller/tidbcluster/tidb_cluster_controller.go
  pkg/controller/tiproxy_control.go
  pkg/manager/member/constants/constants.go
  pkg/manager/member/dm_master_member_manager.go
  pkg/manager/member/dm_worker_member_manager.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/pump_member_manager.go
  pkg/manager/member/pump_scaler.go
  pkg/manager/member/startscript/render_start_script.go
  pkg/manager/member/startscript/v2/tiproxy_start_script.go
  pkg/manager/member/ticdc_member_manager.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tiflash_member_manager.go
  pkg/manager/member/tikv_member_manager.go
  pkg/manager/member/tiproxy_member_manager.go
  pkg/manager/member/tiproxy_scaler.go
  pkg/manager/member/tiproxy_upgrader.go
  pkg/manager/volumes/pod_vol_modifier.go
  pkg/manager/volumes/selector.go
Labels: status/can-merge, status/LGT2

#4773 controller: fix typo in error message
  pkg/controller/restore_status_updater.go
Labels: area/controller, status/can-merge, status/LGT2

#4784 fix backup failure on tidb cluster has massive tikv nodes (40+)
  cmd/backup-manager/app/backup/backup.go
  cmd/backup-manager/app/clean/clean.go
  cmd/backup-manager/app/clean/clean_test.go
  cmd/backup-manager/app/restore/restore.go
  cmd/backup-manager/app/util/util.go
  pkg/backup/backup/backup_manager.go
  pkg/backup/constants/constants.go
  pkg/backup/restore/restore_manager.go
  pkg/backup/restore/restore_manager_test.go
  pkg/backup/snapshotter/snapshotter.go
  pkg/backup/snapshotter/snapshotter_aws.go
  pkg/backup/snapshotter/snapshotter_gcp.go
  pkg/backup/snapshotter/snapshotter_none.go
  pkg/backup/snapshotter/snapshotter_test.go
  pkg/backup/util/remote.go
  pkg/backup/util/remote_test.go
  pkg/backup/util/util.go
Labels: status/can-merge, status/LGT2

#4783 fix: cleanup volume-snapshot backup failure
  cmd/backup-manager/app/clean/clean.go
Labels: status/can-merge, status/LGT2

#4791 bump operator to 1.4.0-beta.3
  charts/tidb-cluster/values.yaml
  charts/tidb-operator/values.yaml
  deploy/aliyun/variables.tf
  deploy/aws/variables.tf
  deploy/gcp/variables.tf
  go.mod
  hack/bump-version.sh
  pkg/client/go.mod
Labels: status/can-merge, status/LGT2
