Repository pingcap/tidb-operator, pull requests merged in 2022-09, with the labels that each got.

#4691 fix the panic on validating a nil pd spec
  pkg/apis/pingcap/v1alpha1/validation/validation.go
Labels: status/can-merge, status/LGT2

#4701 bump operator to v1.3.8
  charts/tidb-cluster/values.yaml
  charts/tidb-operator/values.yaml
  deploy/aliyun/variables.tf
  deploy/aws/variables.tf
  deploy/gcp/variables.tf
  examples/podpatch/tidb-cluster.yaml
  examples/podpatch/tidb-monitor.yaml
  go.mod
  hack/bump-version.sh
  pkg/client/go.mod
Labels: status/can-merge, status/LGT2, needs-cherry-pick-1.3

#4697 Support graceful upgrade TiCDC (>=6.3.0) pods
  docs/api-references/docs.md
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_tidbclusters.yaml
  manifests/crd/v1beta1/pingcap.com_tidbclusters.yaml
  manifests/crd_v1beta1.yaml
  pkg/apis/label/label.go
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/apis/pingcap/v1alpha1/tidbcluster_test.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/ticdc_control.go
  pkg/controller/ticdc_control_test.go
  pkg/controller/tidbcluster/tidb_cluster_condition_updater.go
  pkg/controller/tidbcluster/tidb_cluster_condition_updater_test.go
  pkg/controller/tidbcluster/tidb_cluster_control.go
  pkg/manager/member/ticdc_member_manager.go
  pkg/manager/member/ticdc_member_manager_test.go
  pkg/manager/member/ticdc_scaler.go
  pkg/manager/member/ticdc_scaler_test.go
  pkg/manager/member/ticdc_upgrader.go
  pkg/manager/member/ticdc_upgrader_test.go
  pkg/util/cmpver/cmpver_test.go
  pkg/util/tidbcluster/tidbcluster.go
Labels: status/LGT1, type/1.3-cherry-pick

#4702 bump operator to v1.3.8 for release 1.3
  charts/tidb-cluster/values.yaml
  charts/tidb-operator/values.yaml
  deploy/aliyun/variables.tf
  deploy/aws/variables.tf
  deploy/gcp/variables.tf
  go.mod
  hack/bump-version.sh
  pkg/client/go.mod
Labels: status/LGT1

#4682 br: add log backup, include start, truncate, stop
  cmd/backup-manager/app/backup/backup.go
  cmd/backup-manager/app/backup/manager.go
  cmd/backup-manager/app/cmd/backup.go
  cmd/backup-manager/app/util/generic.go
  docs/api-references/docs.md
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_backups.yaml
  manifests/crd/v1/pingcap.com_backupschedules.yaml
  manifests/crd/v1beta1/pingcap.com_backups.yaml
  manifests/crd/v1beta1/pingcap.com_backupschedules.yaml
  manifests/crd_v1beta1.yaml
  pkg/apis/pingcap/v1alpha1/backup.go
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/util/config/config.go
  pkg/backup/backup/backup_cleaner.go
  pkg/backup/backup/backup_manager.go
  pkg/backup/util/util.go
  pkg/controller/backup/backup_controller.go
  pkg/controller/backup_status_updater.go
  tests/e2e/br/br.go
  tests/e2e/br/framework/br/wait.go
Labels: status/can-merge, tools/br, status/LGT2

#4694 br: add pitr restore
  cmd/backup-manager/app/cmd/restore.go
  cmd/backup-manager/app/restore/restore.go
  cmd/backup-manager/app/util/generic.go
  cmd/backup-manager/app/util/remote.go
  cmd/backup-manager/app/util/util.go
  docs/api-references/docs.md
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_restores.yaml
  manifests/crd/v1beta1/pingcap.com_restores.yaml
  manifests/crd_v1beta1.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/backup/restore/restore_manager.go
  tests/e2e/br/br.go
  tests/e2e/br/framework/br/data.go
  tests/e2e/br/framework/br/wait.go
Labels: status/can-merge, tools/br, status/LGT2

#4688 mapping some short label names to k8s well-known labels
  pkg/manager/member/node.go
  pkg/manager/member/node_test.go
Labels: status/can-merge, status/LGT2

#4706 Upgrade go to 1.16
  ci/e2e_eks.groovy
  ci/e2e_gke.groovy
  ci/e2e_kind.groovy
  ci/pull_e2e_kind.groovy
  ci/pull_e2e_release.groovy
  ci/vm.groovy
  go.mod
  go.sum
  hack/e2e.sh
  hack/run-in-container.sh
  hack/tools/go.mod
  hack/update-api-references.sh
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/client/go.mod
  tools/tools.go
Labels: status/LGT1

#4707 Not suspend a component when the component is scaling or upgrading
  pkg/manager/suspender/suspender.go
  pkg/manager/suspender/suspender_test.go
Labels: status/LGT1

#4709 upgrade go to 1.16 for release
  ci/pull_e2e_release.groovy
  ci/release_cli_binary_and_debug_image.groovy
Labels: status/LGT1

#4683 feat(pvc): support modify ebs
  charts/tidb-operator/templates/controller-manager-deployment.yaml
  charts/tidb-operator/values.yaml
  docs/api-references/docs.md
  go.mod
  go.sum
  hack/verify-crd.sh
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_dmclusters.yaml
  manifests/crd/v1/pingcap.com_tidbclusters.yaml
  manifests/crd/v1beta1/pingcap.com_dmclusters.yaml
  manifests/crd/v1beta1/pingcap.com_tidbclusters.yaml
  manifests/crd_v1beta1.yaml
  misc/images/tidb-debug/Dockerfile
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/apis/pingcap/v1alpha1/component_status.go
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/client/go.sum
  pkg/controller/dependences.go
  pkg/controller/tidbcluster/tidb_cluster_control.go
  pkg/controller/tidbcluster/tidb_cluster_controller.go
  pkg/controller/tidbcluster_control.go
  pkg/features/features.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/pd_member_manager_test.go
  pkg/manager/member/pump_member_manager.go
  pkg/manager/member/pump_member_manager_test.go
  pkg/manager/member/ticdc_member_manager.go
  pkg/manager/member/ticdc_member_manager_test.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tidb_member_manager_test.go
  pkg/manager/member/tiflash_member_manager.go
  pkg/manager/member/tiflash_member_manager_test.go
  pkg/manager/member/tikv_member_manager.go
  pkg/manager/member/tikv_member_manager_test.go
  pkg/manager/member/tikv_upgrader.go
  pkg/manager/member/tikv_upgrader_test.go
  pkg/manager/volumes/delegation/aws/ebs_modifier.go
  pkg/manager/volumes/delegation/aws/ebs_modifier_test.go
  pkg/manager/volumes/delegation/aws/fake.go
  pkg/manager/volumes/delegation/interface.go
  pkg/manager/volumes/fake_pod_vol_modifier.go
  pkg/manager/volumes/phase.go
  pkg/manager/volumes/phase_test.go
  pkg/manager/volumes/pod_vol_modifier.go
  pkg/manager/volumes/pod_vol_modifier_test.go
  pkg/manager/volumes/pvc_modifier.go
  pkg/manager/volumes/selector.go
  pkg/manager/volumes/selector_test.go
  pkg/manager/volumes/sync_volume_status.go
  pkg/manager/volumes/sync_volume_status_test.go
Labels: status/can-merge, status/LGT2

#4715 bump operator to v1.4.0-alpha.1
  charts/tidb-cluster/values.yaml
  charts/tidb-operator/values.yaml
  deploy/aliyun/variables.tf
  deploy/aws/variables.tf
  deploy/gcp/variables.tf
  go.mod
  hack/bump-version.sh
  pkg/client/go.mod
Labels: status/LGT1

#4724 tidb: set tidb support set label min version to v6.3.0
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tidb_member_manager_test.go
Labels: status/can-merge, status/LGT2

#4711 initial support for tiproxy [1/2]
  .github/workflows/chaos.yaml
  .github/workflows/ci.yaml
  Makefile
  checkout-pr-branch.sh
  cmd/backup-manager/app/util/util.go
  docs/api-references/docs.md
  go.mod
  go.sum
  hack/boilerplate/boilerplate.py
  hack/generate-groups.sh
  hack/generate-internal-groups.sh
  hack/lib.sh
  hack/tools/.gitignore
  hack/tools/Makefile
  hack/tools/README.md
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  hack/update-EOF.sh
  hack/update-codegen.sh
  hack/update-crd.sh
  hack/update-goimports.sh
  hack/update-openapi-spec.sh
  hack/verify-EOF.sh
  hack/verify-boilerplate.sh
  hack/verify-lint.sh
  hack/verify-modules.sh
  hack/verify-spelling.sh
  manifests/crd.yaml
  manifests/crd_v1beta1.yaml
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/apis/pingcap/v1alpha1/validation/validation.go
  pkg/client/go.sum
  pkg/controller/generic_control.go
  pkg/manager/member/orphan_pods_cleaner.go
  pkg/manager/member/pd_upgrader.go
  pkg/manager/member/pump_member_manager.go
  pkg/manager/member/pvc_resizer.go
  pkg/manager/member/scaler.go
  pkg/pdapi/pd_config.go
  pkg/pdapi/pdapi.go
  pkg/registry/strategy.go
  pkg/scheduler/predicates/ha.go
  pkg/util/cmpver/cmpver.go
  pkg/util/object_meta.go
  tests/e2e/util/proxiedpdclient/proxiedpdclient.go
  tests/pkg/fault-trigger/manager/vm_qm.go
  tests/pkg/fault-trigger/manager/vm_virsh.go
  tests/pkg/metrics/annotation_util.go
  tests/pkg/metrics/annotation_util_test.go
  tools/tools.go
Labels: status/can-merge, status/LGT2

#4721 fix(pd): fix the pd name of tc with across k8s opt
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/pd_scaler.go
  pkg/manager/member/pd_upgrader.go
  pkg/manager/member/pd_upgrader_test.go
  pkg/manager/member/utils.go
Labels: status/can-merge, status/LGT2, needs-cherry-pick-1.3
