Repository pingcap/tidb-operator, pull requests merged in 2022-01, with the labels that each got.

#4289 add e2e case for deploy and delete a cluster on multi-cluster kubernetes
  tests/e2e/tidbcluster/across-kubernetes.go
Labels: status/can-merge, status/LGT2

#4337 feat(restore): retry updating restore status when restore job succeeded
  pkg/controller/backup_status_updater.go
  pkg/controller/restore_status_updater.go
Labels: status/can-merge, status/LGT2, needs-cherry-pick-1.2

#4341 Bump operator version to v1.2.6
  charts/tidb-cluster/values.yaml
  charts/tidb-operator/values.yaml
  deploy/aliyun/variables.tf
  deploy/aws/variables.tf
  deploy/gcp/variables.tf
  hack/bump-version.sh
Labels: status/can-merge, status/LGT2, needs-cherry-pick-1.2

#4349 Update version in E2E
  tests/e2e/util/image/image.go
Labels: status/can-merge, status/LGT2

#4316 add example yaml for NG Monitoring
  examples/advanced/tidb-ng-monitoring.yaml
  examples/tngm/tidb-cluster.yaml
  examples/tngm/tidb-ng-monitoring.yaml
Labels: status/can-merge, status/LGT2

#4350 Support TOML configurations for DM
  docs/api-references/docs.md
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_dmclusters.yaml
  manifests/crd/v1beta1/pingcap.com_dmclusters.yaml
  manifests/crd_v1beta1.yaml
  pkg/apis/pingcap/v1alpha1/defaulting/dmcluster_test.go
  pkg/apis/pingcap/v1alpha1/dm_config_wraper.go
  pkg/apis/pingcap/v1alpha1/dm_config_wraper_test.go
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/validation/validation_test.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/dmcluster/dm_cluster_control_test.go
  pkg/controller/dmcluster/dm_cluster_controller_test.go
  pkg/manager/member/dm_master_member_manager.go
  pkg/manager/member/dm_master_member_manager_test.go
  pkg/manager/member/dm_worker_member_manager.go
  pkg/manager/member/dm_worker_member_manager_test.go
  pkg/manager/utils/config.go
  tests/e2e/dmcluster/dmcluster.go
  tests/pkg/fixture/fixture.go
Labels: status/can-merge, status/LGT2

#4352 feat(e2e): add e2e cases for br with x-k8s tidbcluster
  tests/e2e/br/br.go
  tests/e2e/br/framework/framework.go
Labels: status/LGT2

#4354 add join cluster e2e cases for x-k8s tidbcluster
  tests/e2e/tidbcluster/across-kubernetes.go
  tests/e2e/util/pd/pd.go
Labels: status/LGT2

#4362 fix #4360
  pkg/util/util.go
Labels: status/can-merge, status/LGT2, needs-cherry-pick-1.2

#4358 Enhance the default configurations for TiFlash
  pkg/manager/member/tiflash_member_manager.go
  pkg/manager/member/tiflash_upgrader.go
  pkg/manager/member/tiflash_upgrader_test.go
  pkg/manager/member/tiflash_util.go
  pkg/manager/member/tiflash_util_test.go
  pkg/util/cmpver/cmpver.go
  pkg/util/cmpver/cmpver_test.go
Labels: status/can-merge, status/LGT2

#4367 bump operator version to v1.3.0-beta.1
  charts/tidb-cluster/values.yaml
  charts/tidb-operator/values.yaml
  deploy/aliyun/variables.tf
  deploy/aws/variables.tf
  deploy/gcp/variables.tf
  go.mod
  hack/bump-version.sh
  pkg/client/go.mod
Labels: status/LGT2

#4370 Fix version script
  hack/version.sh
Labels: status/LGT1

#4372 refine e2e check cluster domain status
  tests/e2e/br/br.go
  tests/e2e/tidbcluster/across-kubernetes.go
Labels: status/can-merge, status/LGT2

#4373 Add `failover.recoverByUID` field, support tikv/tiflash/dm-worker recover by this uid
  docs/api-references/docs.md
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_dmclusters.yaml
  manifests/crd/v1/pingcap.com_tidbclusters.yaml
  manifests/crd/v1beta1/pingcap.com_dmclusters.yaml
  manifests/crd/v1beta1/pingcap.com_tidbclusters.yaml
  manifests/crd_v1beta1.yaml
  pkg/apis/pingcap/v1alpha1/dmcluster.go
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/member/dm_worker_failover.go
  pkg/manager/member/dm_worker_failover_test.go
  pkg/manager/member/dm_worker_member_manager.go
  pkg/manager/member/tiflash_failover.go
  pkg/manager/member/tiflash_member_manager.go
  pkg/manager/member/tikv_failover.go
  pkg/manager/member/tikv_failover_test.go
  pkg/manager/member/tikv_member_manager.go
  tests/e2e/tidbcluster/tidbcluster.go
Labels: status/can-merge, status/LGT2

#4378 log optimization when deleting pvc
  pkg/manager/member/scaler.go
Labels: status/can-merge, status/LGT2

#4379 Add startUpScriptVersion for pd spec
  docs/api-references/docs.md
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_tidbclusters.yaml
  manifests/crd/v1beta1/pingcap.com_tidbclusters.yaml
  manifests/crd_v1beta1.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/template.go
Labels: status/can-merge, status/LGT2

#4377 Fixed the problem where pump would get stuck when local pds are down
  go.mod
  pkg/binlog/binlog.go
  pkg/manager/member/pump_member_manager.go
  tests/e2e/tidbcluster/across-kubernetes.go
Labels: status/can-merge, status/LGT2

#4369 Skip update tidb STS when contains not exist volumn mount
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/pump_member_manager.go
  pkg/manager/member/ticdc_member_manager.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tiflash_member_manager.go
  pkg/manager/member/tikv_member_manager.go
  pkg/manager/tidbngmonitoring/ng_monitoring_manager.go
  pkg/manager/utils/statefulset.go
  pkg/manager/utils/statefulset_test.go
Labels: status/can-merge, status/LGT2

#4382 check tikv restart status when pd failed and refactor e2e test code
  tests/e2e/tidbcluster/across-kubernetes.go
Labels: status/can-merge, status/LGT2

#4386 adjust KubeSchedulerConfiguration api changes in k8s v1.23
  charts/tidb-operator/templates/config/_scheduler-config-yaml.tpl
  charts/tidb-operator/templates/scheduler-deployment.yaml
Labels: status/can-merge, status/LGT2

#4328 Tidb support setting a random password.
  cmd/backup-manager/app/backup/manager.go
  cmd/backup-manager/app/export/manager.go
  cmd/backup-manager/app/restore/manager.go
  cmd/backup-manager/app/util/util.go
  docs/api-references/docs.md
  examples/basic-random-password/README.md
  examples/basic-random-password/tidb-cluster.yaml
  go.mod
  go.sum
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_tidbclusters.yaml
  manifests/crd/v1beta1/pingcap.com_tidbclusters.yaml
  manifests/crd_v1beta1.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/backup/constants/constants.go
  pkg/controller/controller_utils.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tidb_member_manager_test.go
  pkg/util/util.go
Labels: status/can-merge, status/LGT2

#4387 Deploy heterogeneous cluster across Kubernetes clusters and support to deploy heterogenous pump and ticdc
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/controller/controller_utils.go
  pkg/controller/pd_control.go
  pkg/discovery/discovery.go
  pkg/manager/member/pump_member_manager.go
  pkg/manager/member/template.go
  pkg/manager/member/template_test.go
  pkg/manager/member/ticdc_member_manager.go
  pkg/manager/member/tidb_discovery_manager.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tidbcluster_status_manager.go
  pkg/manager/member/tiflash_member_manager.go
  pkg/manager/member/tiflash_util.go
  pkg/manager/member/tikv_member_manager.go
  pkg/monitor/monitor/monitor_manager.go
  pkg/pdapi/pd_control.go
  tests/e2e/tidbcluster/across-kubernetes.go
  tests/e2e/tidbcluster/tidbcluster.go
Labels: status/can-merge, status/LGT2
