Repository pingcap/tidb-operator, pull requests merged in 2023-12, with the labels that each got.

#5417 br: fix pv not created due to same pvc ref name in different namespace
  pkg/backup/constants/constants.go
  pkg/backup/snapshotter/snapshotter.go
  pkg/backup/snapshotter/snapshotter_test.go
Labels: approved, size/XL, area/ebs-br

#5410 Support br-federation-manager managing resources in specific-namespace tidb clusters
  charts/br-federation/templates/controller-manager-deployment.yaml
  charts/br-federation/templates/controller-manager-rbac.yaml
  charts/br-federation/values.yaml
  cmd/br-federation-manager/main.go
  pkg/controller/br_fed_config.go
  pkg/controller/br_fed_dependences.go
Labels: contribution, first-time-contributor, size/M, lgtm, approved, area/ebs-br

#5431 Add trap to create a path when BR container exit
  images/ebs-warmup/warmup-steps.sh
  images/tidb-backup-manager/e2e-entrypoint.sh
  images/tidb-backup-manager/entrypoint.sh
Labels: contribution, lgtm, approved, size/S, area/ebs-br

#5438 [bug fix] Take into account PD peer port and PD client port when pdAddresses from TidbCluster manifest used over Discovery service in pd, tidb and tikv startup scripts
  pkg/manager/member/startscript/v2/common.go
  pkg/manager/member/startscript/v2/common_test.go
  pkg/manager/member/startscript/v2/pd_start_script.go
  pkg/manager/member/startscript/v2/pd_start_script_test.go
  pkg/manager/member/startscript/v2/tidb_start_script.go
  pkg/manager/member/startscript/v2/tidb_start_script_test.go
  pkg/manager/member/startscript/v2/tikv_start_script.go
  pkg/manager/member/startscript/v2/tikv_start_script_test.go
Labels: contribution, size/M, lgtm, approved

#5448 chart: set leader-elect-resource-lock when deploying asts controller
  charts/tidb-operator/templates/advanced-statefulset-deployment.yaml
  charts/tidb-operator/templates/advanced-statefulset-rbac.yaml
  charts/tidb-operator/values.yaml
Labels: lgtm, approved, size/S

#5450 set leader-elect-resource-lock when deploying
  charts/br-federation/templates/controller-manager-deployment.yaml
  charts/br-federation/templates/controller-manager-rbac.yaml
  charts/br-federation/values.yaml
  charts/tidb-operator/templates/controller-manager-deployment.yaml
  charts/tidb-operator/templates/controller-manager-rbac.yaml
  charts/tidb-operator/values.yaml
  cmd/br-federation-manager/main.go
  cmd/controller-manager/main.go
  pkg/controller/br_fed_config.go
  pkg/controller/dependences.go
Labels: lgtm, approved, size/L

#5458 chart: do not deploy tidb-scheduler by default
  charts/tidb-operator/values.yaml
  tests/pkg/fixture/fixture.go
Labels: lgtm, approved, size/S

#5457 br: fix backup stuck due to init pod creating stuck
  pkg/backup/backup/backup_manager.go
  pkg/backup/backup/backup_test.go
Labels: lgtm, approved, size/L, area/ebs-br

#5464 ebs br: make sure backup can be resumed even after being paused for a long time
  pkg/backup/backupschedule/backup_schedule_manager.go
  pkg/backup/backupschedule/backup_schedule_manager_test.go
  pkg/fedvolumebackup/backupschedule/backup_schedule_manager.go
  pkg/fedvolumebackup/backupschedule/backup_schedule_manager_test.go
Labels: size/M, approved, area/ebs-br

#5469 br: fix file creating error due to directory not exists
  images/tidb-backup-manager/e2e-entrypoint.sh
  images/tidb-backup-manager/entrypoint.sh
Labels: lgtm, approved, size/XS, area/ebs-br

#5452 ebs br: serial execution of volume backup gc
  pkg/backup/util/aws_ebs.go
  pkg/fedvolumebackup/backupschedule/backup_schedule_manager.go
  pkg/fedvolumebackup/backupschedule/backup_schedule_manager_test.go
Labels: size/M, approved, area/ebs-br

#5461 br: fix redundant pvc and pv in metadata
  pkg/backup/snapshotter/snapshotter.go
  pkg/backup/snapshotter/snapshotter_test.go
Labels: lgtm, approved, size/L, area/ebs-br

#5476 br: fix warmup tmp file creating error
  images/ebs-warmup/warmup-steps.sh
Labels: size/XS

#5463 bump K8s to v1.24.17
  cmd/br-federation-manager/main.go
  cmd/controller-manager/main.go
  cmd/http-service/Makefile
  cmd/http-service/go.mod
  cmd/http-service/go.sum
  cmd/http-service/main.go
  cmd/http-service/pbgen/api/service.pb.go
  cmd/http-service/pbgen/api/service_grpc.pb.go
  docs/api-references/config.json
  docs/api-references/docs.md
  docs/api-references/federation-docs.md
  go.mod
  go.sum
  hack/e2e.sh
  hack/lib.sh
  hack/local-up-operator.sh
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/autoscaler/autoscaler/external_autoscaler.go
  pkg/client/go.mod
  pkg/client/go.sum
  pkg/controller/br_fed_config.go
  pkg/controller/dependences.go
  tests/images/e2e/Dockerfile
  tests/images/stability-test/Dockerfile
Labels: lgtm, approved, size/XXL

#5471 br: support backupts param in snapshot backup
  cmd/backup-manager/app/backup/backup.go
Labels: lgtm, approved, size/XS

#5479 br: fix other backup member init job check
  pkg/backup/backup/backup_manager.go
Labels: approved, size/XS, area/ebs-br

#5481 bump operator to v1.6.0-alpha.10
  charts/br-federation/values.yaml
  charts/tidb-operator/values.yaml
  cmd/http-service/go.mod
  deploy/aliyun/variables.tf
  deploy/aws/variables.tf
  deploy/gcp/variables.tf
  go.mod
  hack/bump-version.sh
  pkg/client/go.mod
Labels: approved, size/S

#5474 deploy: add tiproxy on aws/aliyun tf example
  deploy/aliyun/main.tf
  deploy/aliyun/variables.tf
  deploy/aws/clusters.tf
  deploy/aws/variables.tf
  deploy/modules/aliyun/tidb-cluster/local.tf
  deploy/modules/aliyun/tidb-cluster/variables.tf
  deploy/modules/aws/tidb-cluster/local.tf
  deploy/modules/aws/tidb-cluster/variables.tf
Labels: size/L

#5489 fix: check `resources.request.storage` under Tiflash `storageClaims`
  pkg/apis/pingcap/v1alpha1/validation/validation.go
  pkg/apis/pingcap/v1alpha1/validation/validation_test.go
Labels: contribution, first-time-contributor, size/M

#5487 bump K8s to v1.25.16
  cmd/http-service/go.mod
  cmd/http-service/go.sum
  docs/api-references/config.json
  docs/api-references/docs.md
  docs/api-references/federation-docs.md
  go.mod
  go.sum
  hack/e2e.sh
  hack/lib.sh
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/client/go.mod
  pkg/client/go.sum
  pkg/controller/br_fed_config.go
  pkg/controller/dependences.go
  tests/e2e/br/br.go
  tests/images/e2e/Dockerfile
  tests/images/stability-test/Dockerfile
  tests/third_party/k8s/framework.go
  tests/third_party/k8s/psp.go
Labels: lgtm, approved, size/XXL
