Repository pingcap/tidb-operator, pull requests merged in 2023-07, with the labels that each got.

#5104 pkg: add 2 operator related tags to restored ebs volume
  cmd/backup-manager/app/clean/clean.go
  pkg/backup/restore/restore_manager.go
  pkg/backup/snapshotter/snapshotter.go
  pkg/backup/snapshotter/snapshotter_aws.go
  pkg/backup/snapshotter/snapshotter_gcp.go
  pkg/backup/snapshotter/snapshotter_none.go
  pkg/backup/util/aws_ebs.go
Labels: type/cherry-pick-for-release-1.5, lgtm, approved, size/L

#5119 Add TidbInitializer tolerations example
  examples/initialize/tidb-initializer.yaml
Labels: size/XS

#5148 br: GC by MaxReservedTime works on completed or failed backups
  pkg/backup/backup/backup_test.go
  pkg/backup/backupschedule/backup_schedule_manager.go
  pkg/backup/backupschedule/backup_schedule_manager_test.go
  pkg/backup/restore/restore_manager.go
  pkg/backup/restore/restore_manager_test.go
  pkg/backup/testutils/br.go
  pkg/backup/testutils/helpers.go
Labels: size/XL

#5142 br: modify fed restore status and ensure init job deleted
  pkg/apis/federation/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/backup.go
  pkg/backup/backup/backup_manager.go
  pkg/controller/backup/backup_controller.go
Labels: type/cherry-pick-for-release-1.5, size/M, lgtm, approved, area/ebs-br

#5153 br: add details of data plane to federation br status
  docs/api-references/docs.md
  docs/api-references/federation-docs.md
  manifests/crd.yaml
  manifests/crd/federation/v1/federation.pingcap.com_volumebackups.yaml
  manifests/crd/federation/v1/federation.pingcap.com_volumerestores.yaml
  manifests/crd/federation/v1beta1/federation.pingcap.com_volumebackups.yaml
  manifests/crd/federation/v1beta1/federation.pingcap.com_volumerestores.yaml
  manifests/crd/v1/pingcap.com_backups.yaml
  manifests/crd/v1/pingcap.com_restores.yaml
  manifests/crd/v1beta1/pingcap.com_backups.yaml
  manifests/crd/v1beta1/pingcap.com_restores.yaml
  manifests/crd_v1beta1.yaml
  manifests/federation-crd.yaml
  manifests/federation-crd_v1beta1.yaml
  pkg/apis/federation/pingcap/v1alpha1/types.go
  pkg/apis/federation/pingcap/v1alpha1/volume_backup.go
  pkg/apis/federation/pingcap/v1alpha1/volume_restore.go
  pkg/apis/federation/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/backup/restore/restore_manager.go
  pkg/controller/backup_status_updater.go
  pkg/controller/backup_status_updater_test.go
  pkg/controller/fedvolumebackup/fed_volume_backup_control.go
  pkg/controller/fedvolumebackup/fed_volume_backup_control_test.go
  pkg/controller/fedvolumerestore/fed_volume_restore_control.go
  pkg/controller/fedvolumerestore/fed_volume_restore_control_test.go
  pkg/controller/restore_status_updater.go
  pkg/controller/restore_status_updater_test.go
  pkg/fedvolumebackup/backup/backup_manager.go
  pkg/fedvolumebackup/backup/backup_test.go
  pkg/fedvolumebackup/restore/restore_manager.go
  pkg/fedvolumebackup/restore/restore_test.go
Labels: lgtm, approved, size/XXL

#5156 br: add permission of events to br federation manager
  charts/br-federation/templates/controller-manager-rbac.yaml
  docs/api-references/federation-docs.md
  pkg/apis/federation/pingcap/v1alpha1/types.go
Labels: size/S

#5162 br: fix missing restore volume tag
  pkg/backup/util/aws_ebs.go
Labels: lgtm, approved, size/XS

#5164 fix: add missing tiproxy label
  pkg/apis/pingcap/v1alpha1/component_spec.go
Labels: lgtm, approved, size/XS

#5169 bump operator version to 1.6.0-alpha.3
  charts/br-federation/values.yaml
  charts/tidb-cluster/values.yaml
  charts/tidb-operator/values.yaml
  deploy/aliyun/variables.tf
  deploy/aws/variables.tf
  deploy/gcp/variables.tf
  go.mod
  hack/bump-version.sh
  pkg/client/go.mod
Labels: lgtm, approved, size/S

#5167 feat: change scope of feat VolumeModifying
  pkg/controller/tidbcluster/tidb_cluster_control.go
  pkg/features/features.go
  pkg/manager/member/tikv_upgrader.go
  pkg/manager/volumes/pod_vol_modifier.go
Labels: size/M, lgtm, approved

#5177 fix jenkins groovy
  ci/pull_e2e_kind.groovy
  ci/pull_e2e_release.groovy
Labels: size/S

#5173 try to Graceful Drain TiCDC for improper constraint image tag
  pkg/controller/ticdc_control.go
  pkg/manager/member/ticdc_scaler.go
  pkg/manager/member/ticdc_scaler_test.go
Labels: size/M, lgtm, approved

#5180 bump operator to v1.4.6
  charts/tidb-cluster/values.yaml
  charts/tidb-operator/values.yaml
  deploy/aliyun/variables.tf
  deploy/aws/variables.tf
  deploy/gcp/variables.tf
  go.mod
  hack/bump-version.sh
  pkg/client/go.mod
Labels: lgtm, approved, size/S

#5170 bump K8s to v1.21.14
  go.mod
  go.sum
  hack/e2e-patch-codecov.sh
  hack/e2e.sh
  hack/lib.sh
  hack/verify-modules.sh
  manifests/crd.yaml
  manifests/crd/federation/v1/federation.pingcap.com_volumebackups.yaml
  manifests/crd/federation/v1/federation.pingcap.com_volumebackupschedules.yaml
  manifests/crd/federation/v1/federation.pingcap.com_volumerestores.yaml
  manifests/crd/federation/v1beta1/federation.pingcap.com_volumebackups.yaml
  manifests/crd/federation/v1beta1/federation.pingcap.com_volumebackupschedules.yaml
  manifests/crd/federation/v1beta1/federation.pingcap.com_volumerestores.yaml
  manifests/crd/v1/pingcap.com_backups.yaml
  manifests/crd/v1/pingcap.com_backupschedules.yaml
  manifests/crd/v1/pingcap.com_dmclusters.yaml
  manifests/crd/v1/pingcap.com_restores.yaml
  manifests/crd/v1/pingcap.com_tidbclusters.yaml
  manifests/crd/v1/pingcap.com_tidbdashboards.yaml
  manifests/crd/v1/pingcap.com_tidbinitializers.yaml
  manifests/crd/v1/pingcap.com_tidbmonitors.yaml
  manifests/crd/v1/pingcap.com_tidbngmonitorings.yaml
  manifests/crd/v1beta1/pingcap.com_backups.yaml
  manifests/crd/v1beta1/pingcap.com_backupschedules.yaml
  manifests/crd/v1beta1/pingcap.com_dmclusters.yaml
  manifests/crd/v1beta1/pingcap.com_restores.yaml
  manifests/crd/v1beta1/pingcap.com_tidbclusters.yaml
  manifests/crd/v1beta1/pingcap.com_tidbdashboards.yaml
  manifests/crd/v1beta1/pingcap.com_tidbinitializers.yaml
  manifests/crd/v1beta1/pingcap.com_tidbmonitors.yaml
  manifests/crd/v1beta1/pingcap.com_tidbngmonitorings.yaml
  manifests/crd_v1beta1.yaml
  manifests/federation-crd.yaml
  manifests/federation-crd_v1beta1.yaml
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/client/go.mod
  pkg/client/go.sum
  pkg/tkctl/debug/launcher.go
  tests/e2e/suite.go
  tests/images/e2e/Dockerfile
  tests/images/stability-test/Dockerfile
Labels: lgtm, approved, size/XXL

#5190 backup: make LogBackupTemplate optional
  docs/api-references/docs.md
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_backupschedules.yaml
  manifests/crd/v1beta1/pingcap.com_backupschedules.yaml
  manifests/crd_v1beta1.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
Labels: size/S

#5192 bump operator to v1.4.7
  charts/tidb-cluster/values.yaml
  charts/tidb-operator/values.yaml
  deploy/aliyun/variables.tf
  deploy/aws/variables.tf
  deploy/gcp/variables.tf
  go.mod
  hack/bump-version.sh
  pkg/client/go.mod
Labels: size/S

#5195 ebs br: pass region name for aws EBS volume operation
  pkg/backup/constants/constants.go
  pkg/backup/restore/restore_manager_test.go
  pkg/backup/util/aws_ebs.go
Labels: size/M, lgtm, approved

#5198 feat: use pingcap base image
  images/br-federation-manager/Dockerfile
  images/br-federation-manager/Dockerfile.e2e
  images/tidb-backup-manager/Dockerfile
  images/tidb-backup-manager/Dockerfile.e2e
  images/tidb-operator/Dockerfile
  images/tidb-operator/Dockerfile.e2e
Labels: first-time-contributor, approved, size/S

#5203 example: fix and update grafana version
  examples/advanced/tidb-monitor.yaml
  manifests/monitor/tidb-monitor.yaml
Labels: size/XS

#5186 br: modify to use one kubeconfig for multiple data planes
  charts/br-federation/templates/controller-manager-deployment.yaml
  charts/br-federation/values.yaml
  cmd/br-federation-manager/main.go
  pkg/controller/br_fed_config.go
Labels: type/cherry-pick-for-release-1.5, lgtm, approved, size/S, area/ebs-br

#5199 ebs br: fail delete cr operation if backup meta is missing
  cmd/backup-manager/app/clean/clean.go
Labels: size/XS

#5202 ebs br: make snapshot size calculation optional
  cmd/backup-manager/app/backup/manager.go
  cmd/backup-manager/app/util/backup_size.go
  docs/api-references/docs.md
  docs/api-references/federation-docs.md
  manifests/crd.yaml
  manifests/crd/federation/v1/federation.pingcap.com_volumebackups.yaml
  manifests/crd/federation/v1/federation.pingcap.com_volumebackupschedules.yaml
  manifests/crd/v1/pingcap.com_backups.yaml
  manifests/crd/v1/pingcap.com_backupschedules.yaml
  manifests/federation-crd.yaml
  pkg/apis/federation/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/federation/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/backup/snapshotter/snapshotter_test.go
Labels: type/cherry-pick-for-release-1.5, approved, size/L, area/ebs-br
