Repository pingcap/tidb-operator, pull requests merged in 2023-04, with the labels that each got.

#4953 ci: update e2e image for docker hub
  hack/run-in-container.sh
Labels: status/LGT1

#4954 Upgrade k8s libs to v1.20
  go.mod
  go.sum
  hack/lib.sh
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_backups.yaml
  manifests/crd/v1/pingcap.com_backupschedules.yaml
  manifests/crd/v1/pingcap.com_dmclusters.yaml
  manifests/crd/v1/pingcap.com_restores.yaml
  manifests/crd/v1/pingcap.com_tidbclusters.yaml
  manifests/crd/v1/pingcap.com_tidbdashboards.yaml
  manifests/crd/v1/pingcap.com_tidbmonitors.yaml
  manifests/crd/v1/pingcap.com_tidbngmonitorings.yaml
  manifests/crd/v1beta1/pingcap.com_backups.yaml
  manifests/crd/v1beta1/pingcap.com_backupschedules.yaml
  manifests/crd/v1beta1/pingcap.com_dmclusters.yaml
  manifests/crd/v1beta1/pingcap.com_restores.yaml
  manifests/crd/v1beta1/pingcap.com_tidbclusters.yaml
  manifests/crd/v1beta1/pingcap.com_tidbdashboards.yaml
  manifests/crd/v1beta1/pingcap.com_tidbmonitors.yaml
  manifests/crd/v1beta1/pingcap.com_tidbngmonitorings.yaml
  manifests/crd_v1beta1.yaml
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/client/go.mod
  pkg/client/go.sum
  tests/e2e/dmcluster/dmcluster.go
  tests/e2e/tidbcluster/stability.go
  tests/e2e/util/pod/pod.go
  tests/e2e/util/tidbcluster/wait_for_tc.go
  tests/e2e/util/util.go
Labels: status/can-merge, status/LGT2

#4964 bump go mod for CVE fix
  go.mod
  go.sum
  pkg/client/go.mod
  pkg/client/go.sum
Labels: status/LGT1

#4956 backup: make LogBackupTemplate optional
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_backupschedules.yaml
  manifests/crd/v1beta1/pingcap.com_backupschedules.yaml
  manifests/crd_v1beta1.yaml
  pkg/apis/pingcap/v1alpha1/types.go
Labels: tools/br, status/LGT1, area/CRD

#4940 [BR]supress gc when scheduled backup is newly created
  pkg/backup/backupschedule/backup_schedule_manager.go
Labels: tools/br, status/LGT1

#4963 *: remove the dep to github.com/pingcap/tidb
  go.mod
  go.sum
  pkg/controller/tidb_control.go
  pkg/controller/tidb_control_test.go
  tests/e2e/util/proxiedtidbclient/proxiedtidbclient.go
Labels: status/LGT1

#4952 Add error metrics for TidbCluster
  cmd/controller-manager/main.go
  pkg/controller/tidbcluster/tidb_cluster_control.go
  pkg/metrics/metrics.go
  pkg/metrics/tidbcluster.go
Labels: status/LGT2

#4968 *: bump some go mod for CVE fix
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/client/go.mod
  pkg/client/go.sum
Labels: status/LGT1

#4969 fix-ticdc-config-in-example
  examples/advanced/tidb-cluster.yaml
Labels: status/LGT1

#4971 Add startUpScriptVersion for dm-master spec
  docs/api-references/docs.md
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_dmclusters.yaml
  manifests/crd/v1beta1/pingcap.com_dmclusters.yaml
  manifests/crd_v1beta1.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/manager/member/dm_master_member_manager.go
  pkg/manager/member/startscript/v1/template.go
  pkg/manager/member/startscript/v1/template_test.go
Labels: status/LGT1

#4977 Add a field `preferIPv6` for DM, TD, TM, TNGM
  docs/api-references/docs.md
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_dmclusters.yaml
  manifests/crd/v1/pingcap.com_tidbdashboards.yaml
  manifests/crd/v1/pingcap.com_tidbmonitors.yaml
  manifests/crd/v1/pingcap.com_tidbngmonitorings.yaml
  manifests/crd/v1beta1/pingcap.com_dmclusters.yaml
  manifests/crd/v1beta1/pingcap.com_tidbdashboards.yaml
  manifests/crd/v1beta1/pingcap.com_tidbmonitors.yaml
  manifests/crd/v1beta1/pingcap.com_tidbngmonitorings.yaml
  manifests/crd_v1beta1.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbdashboard_types.go
  pkg/apis/pingcap/v1alpha1/tidbmonitor_types.go
  pkg/apis/pingcap/v1alpha1/tidbngmonitoring_types.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/manager/member/dm_master_member_manager.go
  pkg/manager/member/dm_worker_member_manager.go
  pkg/manager/member/tidb_discovery_manager.go
  pkg/manager/tidbdashboard/manager.go
  pkg/manager/tidbngmonitoring/ng_monitoring_manager.go
  pkg/monitor/monitor/util.go
Labels: status/LGT1

#4981 br: wait old backup job done before start
  pkg/backup/backup/backup_manager.go
  pkg/controller/backup/backup_controller.go
Labels: tools/br, status/LGT1
