Repository pingcap/tidb-operator, pull requests merged in 2023-10, with the labels that each got.

#5320 http: split gateway listen and serve
  cmd/http-service/main.go
Labels: size/XS

#5321 http-service: JSON config support for TidbCluster
  cmd/http-service/examples/create-cluster.json
  cmd/http-service/go.mod
  cmd/http-service/idl/api/service.proto
  cmd/http-service/pbgen/api/service.pb.go
  cmd/http-service/pbgen/oas/openapi-spec.swagger.json
  cmd/http-service/server/cluster.go
Labels: size/XXL

#5318 Remove k8s cluster name from restore/warmup pod names
  pkg/apis/federation/pingcap/v1alpha1/volume_restore.go
  pkg/fedvolumebackup/restore/restore_manager.go
  pkg/fedvolumebackup/restore/restore_test.go
Labels: contribution, first-time-contributor, approved, size/S, area/ebs-br

#5323 http-service: k8s deploy support
  cmd/http-service/Dockerfile
  cmd/http-service/Makefile
  cmd/http-service/README.md
  cmd/http-service/deploy.yaml
Labels: size/M

#5315 added warmup strategy
  cmd/http-service/pbgen/api/service.pb.go
  cmd/http-service/pbgen/api/service_grpc.pb.go
  docs/api-references/docs.md
  docs/api-references/federation-docs.md
  images/ebs-warmup/warmup-steps.sh
  manifests/crd.yaml
  manifests/crd/federation/v1/federation.pingcap.com_volumerestores.yaml
  manifests/crd/v1/pingcap.com_restores.yaml
  manifests/federation-crd.yaml
  pkg/apis/federation/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/federation/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/backup/restore/restore_manager.go
  pkg/backup/restore/restore_manager_test.go
  pkg/fedvolumebackup/restore/restore_manager.go
Labels: approved, size/XXL, area/ebs-br

#5333 ci: fix e2e-examples in GitHub Action
  examples/selfsigned-tls/tidb-cluster.yaml
Labels: size/XS

#5337 bump go version to 1.21.3 for security
  .github/workflows/chaos.yaml
  .github/workflows/ci.yaml
  .golangci.yml
  ci/e2e_eks.groovy
  ci/e2e_gke.groovy
  ci/e2e_kind.groovy
  ci/pull_e2e_kind.groovy
  ci/pull_e2e_release.groovy
  ci/vm.groovy
  cmd/http-service/go.mod
  cmd/http-service/go.sum
  go.mod
  hack/lib.sh
  hack/run-in-container.sh
  hack/verify-lint.sh
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/client/go.mod
  pkg/client/go.sum
  pkg/manager/member/dm_master_member_manager_test.go
  pkg/manager/member/dm_worker_member_manager_test.go
  pkg/manager/member/pd_member_manager_test.go
  pkg/manager/member/pump_member_manager_test.go
  pkg/manager/member/ticdc_member_manager_test.go
  pkg/manager/member/tidb_member_manager_test.go
  pkg/manager/member/tiflash_member_manager_test.go
  pkg/manager/member/tikv_member_manager_test.go
  pkg/manager/volumes/delegation/aws/fake.go
  pkg/manager/volumes/phase_test.go
  pkg/manager/volumes/pod_vol_modifier_test.go
  pkg/monitor/monitor/util_test.go
  pkg/upgrader/upgrader_test.go
  tests/drainer.go
  tests/images/kubekins-e2e/Dockerfile
Labels: size/L

#5342 http-service: add get cluster API
  cmd/http-service/idl/api/service.proto
  cmd/http-service/pbgen/api/service.pb.go
  cmd/http-service/pbgen/api/service.pb.gw.go
  cmd/http-service/pbgen/api/service_grpc.pb.go
  cmd/http-service/pbgen/oas/openapi-spec.swagger.json
  cmd/http-service/server/cluster.go
  cmd/http-service/server/common.go
Labels: size/XXL

#5345 Remove early return during upgrade that might block rollbacks
  pkg/manager/member/dm_master_upgrader.go
  pkg/manager/member/dm_master_upgrader_test.go
  pkg/manager/member/pd_upgrader.go
  pkg/manager/member/pd_upgrader_test.go
  pkg/manager/member/ticdc_upgrader.go
  pkg/manager/member/tidb_upgrader.go
  pkg/manager/member/tiflash_upgrader.go
  pkg/manager/member/tikv_upgrader.go
  pkg/manager/member/tiproxy_upgrader.go
Labels: contribution, size/M, lgtm, approved

#5346 http-service: flatten config map to single layer
  cmd/http-service/server/cluster.go
Labels: size/M

#5348 http-service: fix get prometheus config panic
  cmd/http-service/server/cluster.go
Labels: size/XS

#5344 bump TiDB Operator to 1.5.1
  charts/br-federation/values.yaml
  charts/tidb-cluster/values.yaml
  charts/tidb-operator/values.yaml
  deploy/aliyun/variables.tf
  deploy/aws/variables.tf
  deploy/gcp/variables.tf
  go.mod
  hack/bump-version.sh
  pkg/client/go.mod
Labels: size/S

#5349 Allow porting labels to restore pod
  pkg/fedvolumebackup/restore/restore_manager.go
Labels: contribution, lgtm, approved, size/XS, area/ebs-br

#5338 Fsr warmup support
  cmd/backup-manager/app/cmd/restore.go
  cmd/backup-manager/app/restore/restore.go
  cmd/backup-manager/app/util/util.go
  images/ebs-warmup/warmup-steps.sh
  manifests/crd.yaml
  manifests/federation-crd.yaml
  pkg/backup/restore/restore_manager.go
  pkg/backup/restore/restore_manager_test.go
Labels: approved, size/XXL, area/ebs-br

#5352 http-service: update cluster and fix scaling/upgrading status with TiFlash
  cmd/http-service/examples/update-cluster.json
  cmd/http-service/idl/api/service.proto
  cmd/http-service/pbgen/api/service.pb.go
  cmd/http-service/pbgen/api/service.pb.gw.go
  cmd/http-service/pbgen/api/service_grpc.pb.go
  cmd/http-service/pbgen/oas/openapi-spec.swagger.json
  cmd/http-service/server/cluster.go
Labels: size/XXL

#5353 http-service: add empty services
  cmd/http-service/idl/api/service.proto
  cmd/http-service/pbgen/api/service.pb.go
  cmd/http-service/pbgen/api/service.pb.gw.go
  cmd/http-service/pbgen/api/service_grpc.pb.go
  cmd/http-service/pbgen/oas/openapi-spec.swagger.json
  cmd/http-service/server/backup.go
  cmd/http-service/server/cluster.go
Labels: size/XXL

#5354 http-service: create backup for a cluster
  cmd/http-service/examples/create-backup.json
  cmd/http-service/idl/api/service.proto
  cmd/http-service/pbgen/api/service.pb.go
  cmd/http-service/pbgen/oas/openapi-spec.swagger.json
  cmd/http-service/server/backup.go
  cmd/http-service/server/cluster.go
Labels: size/XXL

#5356 http-service: create restore for a cluster
  cmd/http-service/examples/create-restore.json
  cmd/http-service/idl/api/service.proto
  cmd/http-service/pbgen/api/service.pb.go
  cmd/http-service/pbgen/oas/openapi-spec.swagger.json
  cmd/http-service/server/backup.go
Labels: size/XXL

#5359 http-service: get backup and restore info
  cmd/http-service/idl/api/service.proto
  cmd/http-service/pbgen/api/service.pb.go
  cmd/http-service/pbgen/oas/openapi-spec.swagger.json
  cmd/http-service/server/backup.go
  cmd/http-service/server/cluster.go
Labels: size/XXL

#5358 fix Golang version in CONTRIBUTING
  docs/CONTRIBUTING.md
Labels: size/XS

#5285 tiproxy: rename from TiProxy to tiproxy
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/apis/pingcap/v1alpha1/tiproxy_config_wrapper.go
  pkg/apis/pingcap/v1alpha1/tiproxy_config_wrapper_test.go
  pkg/client/go.mod
  pkg/client/go.sum
  pkg/controller/tiproxy_control.go
Labels: size/M, approved

#5357 Fsr warmup support (#5338)
  cmd/backup-manager/app/cmd/restore.go
  cmd/backup-manager/app/restore/restore.go
  cmd/backup-manager/app/util/util.go
  images/ebs-warmup/warmup-steps.sh
  manifests/crd.yaml
  manifests/crd_v1beta1.yaml
  manifests/federation-crd.yaml
  manifests/federation-crd_v1beta1.yaml
  pkg/backup/restore/restore_manager.go
  pkg/backup/restore/restore_manager_test.go
Labels: size/XXL, area/ebs-br

#5364 http-serivce: add restart tidbcluster api
  cmd/http-service/examples/restart-cluster.json
  cmd/http-service/go.mod
  cmd/http-service/go.sum
  cmd/http-service/idl/api/service.proto
  cmd/http-service/pbgen/api/service.pb.go
  cmd/http-service/pbgen/api/service.pb.gw.go
  cmd/http-service/pbgen/oas/openapi-spec.swagger.json
  cmd/http-service/server/cluster.go
Labels: first-time-contributor, lgtm, approved, size/XXL
