Repository pingcap/tidb-operator, pull requests merged in 2023-02, with the labels that each got.

#4855 fix: set LastTransitionTime for tombstoneStores status
  pkg/manager/member/tiflash_member_manager.go
  pkg/manager/member/tikv_member_manager.go
Labels: status/can-merge, status/LGT2

#4850 Fix the issue that tiflash listen on IPv4 addr when `preferIPv6` is enabled
  pkg/manager/member/tiflash_util.go
Labels: status/LGT1, type/cherry-pick-for-release-1.4

#4819 feat: calc the backup size from snapshot storage usage
  cmd/backup-manager/app/backup/backup.go
  cmd/backup-manager/app/backup/manager.go
  cmd/backup-manager/app/clean/manager.go
  cmd/backup-manager/app/util/backup_size.go
  pkg/backup/backup/backup_manager.go
  pkg/backup/restore/restore_manager.go
  pkg/backup/util/aws_ebs.go
  pkg/backup/util/worker.go
Labels: area/backup, status/can-merge, status/LGT2

#4852 bump operator version to v1.4.2
  charts/tidb-cluster/values.yaml
  charts/tidb-operator/values.yaml
  deploy/aliyun/variables.tf
  deploy/aws/variables.tf
  deploy/gcp/variables.tf
  go.mod
  hack/bump-version.sh
  pkg/client/go.mod
Labels: type/cherry-pick-for-release-1.4

#4856 *: use string for generic health info
  docs/api-references/docs.md
  go.mod
  go.sum
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_tidbclusters.yaml
  manifests/crd/v1beta1/pingcap.com_tidbclusters.yaml
  manifests/crd_v1beta1.yaml
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/client/go.sum
  pkg/controller/tiproxy_control.go
  pkg/manager/member/tiproxy_member_manager.go
Labels: status/can-merge, status/LGT2

#4846 Allow users to customize Prometheus scraping settings
  pkg/manager/member/dm_master_member_manager.go
  pkg/manager/member/dm_worker_member_manager.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/pump_member_manager.go
  pkg/manager/member/ticdc_member_manager.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tiflash_member_manager.go
  pkg/manager/member/tikv_member_manager.go
  pkg/manager/member/tiproxy_member_manager.go
Labels: status/can-merge, status/LGT2

#4864 custom e2e image
  Makefile
  ci/e2e_eks.groovy
  ci/e2e_gke.groovy
  ci/e2e_kind.groovy
  ci/pull_e2e_kind.groovy
  ci/pull_e2e_release.groovy
  ci/vm.groovy
  hack/run-in-container.sh
  tests/images/kubekins-e2e/Dockerfile
  tests/images/kubekins-e2e/runner.sh
Labels: status/LGT1

#4865 manager: better tiproxy experience
  Makefile
  images/tidb-operator/Dockerfile.new
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/manager/member/tidb_member_manager.go
  pkg/monitor/monitor/template.go
  pkg/monitor/monitor/template_test.go
Labels: status/can-merge, status/LGT2

#4866 Upgrade golang version to 1.18
  ci/e2e_eks.groovy
  ci/e2e_gke.groovy
  ci/e2e_kind.groovy
  ci/pull_e2e_kind.groovy
  ci/pull_e2e_release.groovy
  ci/vm.groovy
  go.mod
  go.sum
  hack/go117_0.patch
  hack/go117_1.patch
  hack/go117_2.patch
  hack/go117_3.patch
  hack/lib.sh
  hack/run-in-container.sh
  hack/update-codegen.sh
  hack/update-crd.sh
  hack/update-goimports.sh
  hack/update-openapi-spec.sh
  manifests/crd.yaml
  manifests/crd_v1beta1.yaml
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/client/go.mod
  pkg/client/go.sum
  tests/images/kubekins-e2e/Dockerfile
Labels: status/LGT1

#4863 wait leaders transfer back after a tikv upgrade
  docs/api-references/docs.md
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_tidbclusters.yaml
  manifests/crd/v1beta1/pingcap.com_tidbclusters.yaml
  manifests/crd_v1beta1.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/member/tikv_member_manager.go
  pkg/manager/member/tikv_upgrader.go
  pkg/manager/member/tikv_upgrader_test.go
  pkg/manager/member/utils.go
  pkg/manager/suspender/suspender.go
Labels: status/can-merge, status/LGT2

#4871 Upgrade go version to 1.19
  go.mod
  go.sum
  hack/lib.sh
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/go.mod
  pkg/client/go.sum
  tests/images/kubekins-e2e/Dockerfile
Labels: status/can-merge, status/LGT2

#4878 update go version to 1.19.5 for e2e
  ci/e2e_eks.groovy
  ci/e2e_gke.groovy
  ci/e2e_kind.groovy
  ci/pull_e2e_kind.groovy
  ci/pull_e2e_release.groovy
  ci/vm.groovy
  hack/run-in-container.sh
Labels: status/LGT1

#4874 Add http route for pprof
  cmd/controller-manager/main.go
Labels: status/can-merge, status/LGT2

#4862 Support specifying an initialize sql file on TiDB' s first bootstrap
  docs/api-references/docs.md
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_tidbclusters.yaml
  manifests/crd/v1beta1/pingcap.com_tidbclusters.yaml
  manifests/crd_v1beta1.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/validation/validation.go
  pkg/apis/pingcap/v1alpha1/validation/validation_test.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/member/startscript/v1/render_script.go
  pkg/manager/member/tidb_member_manager.go
  tests/e2e/tidbcluster/across-kubernetes.go
Labels: status/can-merge, status/LGT2

#4879 bump operator version to 1.3.10
  charts/tidb-cluster/values.yaml
  charts/tidb-operator/values.yaml
  deploy/aliyun/variables.tf
  deploy/aws/variables.tf
  deploy/gcp/variables.tf
  go.mod
  hack/bump-version.sh
  pkg/client/go.mod
Labels: status/can-merge, status/LGT1

#4880 manager: fix TLS certs for tiproxy
  Makefile
  hack/localtest/test.sh
  pkg/backup/backup/backup_manager.go
  pkg/backup/restore/restore_manager.go
  pkg/controller/tiproxy_control.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/tidb_init_manager.go
  pkg/manager/member/tiproxy_member_manager.go
  pkg/manager/tidbdashboard/tc_tls_manager.go
  pkg/monitor/monitor/template.go
  pkg/monitor/monitor/template_test.go
  pkg/util/util.go
  pkg/util/utils_test.go
  tests/e2e/br/utils/tls/manager.go
  tests/e2e/tidbcluster/tls.go
Labels: status/can-merge, status/LGT2

#4890 bump operator version to 1.4.3
  charts/tidb-cluster/values.yaml
  charts/tidb-operator/values.yaml
  deploy/aliyun/variables.tf
  deploy/aws/variables.tf
  deploy/gcp/variables.tf
  go.mod
  hack/bump-version.sh
  pkg/client/go.mod
Labels: status/LGT1

#4892 fix(ebs): fix missing param in sc when modify ebs
  pkg/manager/volumes/delegation/aws/ebs_modifier.go
Labels: status/LGT2

#4883 fix backup failed when pod was auto restarted by k8s
  cmd/backup-manager/app/backup/manager.go
  cmd/backup-manager/app/clean/clean.go
  cmd/backup-manager/app/clean/manager.go
  pkg/apis/pingcap/v1alpha1/backup.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/backup/backup/backup_test.go
  pkg/controller/backup_status_updater.go
Labels: status/LGT2

#4882 Add controller runtime related metrics
  cmd/controller-manager/main.go
  pkg/controller/autoscaler/tidbcluster_autoscaler_controller.go
  pkg/controller/backup/backup_controller.go
  pkg/controller/backupschedule/backup_schedule_controller.go
  pkg/controller/dmcluster/dm_cluster_controller.go
  pkg/controller/restore/restore_controller.go
  pkg/controller/tidbcluster/pod_control.go
  pkg/controller/tidbcluster/tidb_cluster_controller.go
  pkg/controller/tidbdashboard/tidb_dashboard_controller.go
  pkg/controller/tidbinitializer/tidb_initializer_controller.go
  pkg/controller/tidbmonitor/tidb_monitor_controller.go
  pkg/controller/tidbngmonitoring/tidb_ng_monitoring_controller.go
  pkg/metrics/metrics.go
  pkg/metrics/workerqueue.go
Labels: status/can-merge, release-note-action-required, status/LGT2

#4889 Fix the issue tiflash metric server listen on incorrect addr when ipv6 enabled
  pkg/manager/member/tiflash_util.go
Labels: status/LGT1

#4888 br: ensure pvc names sequential for ebs restore
  pkg/backup/snapshotter/snapshotter.go
  pkg/backup/snapshotter/snapshotter_test.go
  pkg/backup/testutils/br.go
Labels: area/backup, status/can-merge, status/LGT2
