Repository pingcap/tidb-operator, pull requests merged in 2023-11, with the labels that each got.

#5366 http-service: update some fields name and type for create and get cluster
  cmd/http-service/examples/create-cluster.json
  cmd/http-service/idl/api/service.proto
  cmd/http-service/pbgen/api/service.pb.go
  cmd/http-service/pbgen/oas/openapi-spec.swagger.json
  cmd/http-service/server/cluster.go
Labels: size/XXL

#5367 http-service: add pause and resume api for http-service
  cmd/http-service/idl/api/service.proto
  cmd/http-service/pbgen/api/service.pb.go
  cmd/http-service/pbgen/api/service.pb.gw.go
  cmd/http-service/pbgen/api/service_grpc.pb.go
  cmd/http-service/pbgen/oas/openapi-spec.swagger.json
  cmd/http-service/server/cluster.go
Labels: contribution, size/XXL

#5371 http-server: add deleteTidbCluster api
  cmd/http-service/idl/api/service.proto
  cmd/http-service/pbgen/api/service.pb.go
  cmd/http-service/pbgen/oas/openapi-spec.swagger.json
  cmd/http-service/server/cluster.go
Labels: contribution, first-time-contributor, size/XXL

#5373 delete all pvc in tidbcluster ns
  cmd/http-service/server/cluster.go
Labels: contribution, lgtm, approved, size/S

#5377 http-service: return deleting for get-cluster if pods/pvcs exist
  cmd/http-service/server/cluster.go
Labels: size/M

#5379 http-service: delete backup data
  cmd/http-service/idl/api/service.proto
  cmd/http-service/pbgen/api/service.pb.go
  cmd/http-service/pbgen/oas/openapi-spec.swagger.json
  cmd/http-service/server/backup.go
Labels: size/XL

#5380 http-service: delete restores when deleting the cluster
  cmd/http-service/server/cluster.go
Labels: size/S

#5378 *: fix some typos
  cmd/http-service/README.md
  cmd/http-service/server/cluster.go
  cmd/http-service/server/common.go
  docs/CONTRIBUTING.md
  examples/basic/README.md
  pkg/scheduler/scheduler.go
  pkg/scheduler/server/mux.go
Labels: first-time-contributor, approved, size/S

#5382 Fix issue in VolumeReplace feature that may block replacement when combined with an annotation change
  pkg/manager/volumes/pvc_replacer.go
Labels: contribution, lgtm, approved, size/XS

#5370 ebs br: extend throttling backoff
  cmd/backup-manager/app/util/backup_size.go
  pkg/fedvolumebackup/restore/restore_manager.go
  pkg/fedvolumebackup/restore/restore_test.go
Labels: size/M, approved, area/ebs-br

#5391 *: remove tikv-importer
  charts/tidb-cluster/templates/_helpers.tpl
  charts/tidb-cluster/templates/tikv-importer-configmap.yaml
  charts/tidb-cluster/templates/tikv-importer-service.yaml
  charts/tidb-cluster/templates/tikv-importer-statefulset.yaml
  charts/tidb-cluster/values.yaml
  charts/tidb-lightning/templates/scripts/_start_lightning.sh.tpl
  charts/tidb-lightning/values.yaml
  charts/tikv-importer/.helmignore
  charts/tikv-importer/Chart.yaml
  charts/tikv-importer/templates/_helpers.tpl
  charts/tikv-importer/templates/tikv-importer-configmap.yaml
  charts/tikv-importer/templates/tikv-importer-service.yaml
  charts/tikv-importer/templates/tikv-importer-statefulset.yaml
  charts/tikv-importer/values.yaml
  hack/gen-tls-certs.sh
  pkg/monitor/monitor/template.go
  pkg/monitor/monitor/template_test.go
Labels: size/XXL

#5374 http-service: add StopBackup&StopRestore api for http-service
  cmd/http-service/idl/api/service.proto
  cmd/http-service/pbgen/api/service.pb.go
  cmd/http-service/pbgen/oas/openapi-spec.swagger.json
  cmd/http-service/server/backup.go
  cmd/http-service/server/cluster.go
  pkg/apis/pingcap/v1alpha1/backup.go
  pkg/pdapi/pdapi.go
Labels: first-time-contributor, size/XXL

#5381 Make PD and TiKV wait until local IP address matches the one published to external DNS
  docs/api-references/docs.md
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_tidbclusters.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/member/startscript/v2/common.go
  pkg/manager/member/startscript/v2/common_test.go
  pkg/manager/member/startscript/v2/pd_start_script.go
  pkg/manager/member/startscript/v2/pd_start_script_with_wait_for_ip_match_test.go
  pkg/manager/member/startscript/v2/tikv_start_script.go
  pkg/manager/member/startscript/v2/tikv_start_script_with_wait_for_ip_match_test.go
Labels: contribution, first-time-contributor, lgtm, approved, size/XXL

#5389 tiproxy: support set require-backend-tls and use separate config for tiproxy HTTP port
  hack/localtest/cluster.yaml
  pkg/manager/member/tiproxy_member_manager.go
Labels: approved, size/S

#5393 Fix issue when using VolumeReplace feature that may mark wrong PD member ID labels.
  pkg/controller/pod_control.go
  pkg/controller/tidbcluster/pod_control.go
  pkg/controller/tidbcluster/tidb_cluster_control.go
  pkg/manager/member/tikv_scaler.go
  pkg/manager/member/tikv_scaler_test.go
Labels: contribution, size/M, lgtm, approved

#5400 Prefer PD addresses explicitly provided in TidbCluster manifest over Discovery service in pd, tidb and tikv startup scripts
  pkg/apis/pingcap/v1alpha1/validation/validation.go
  pkg/apis/pingcap/v1alpha1/validation/validation_test.go
  pkg/manager/member/startscript/v2/pd_start_script.go
  pkg/manager/member/startscript/v2/pd_start_script_test.go
  pkg/manager/member/startscript/v2/tidb_start_script.go
  pkg/manager/member/startscript/v2/tidb_start_script_test.go
  pkg/manager/member/startscript/v2/tikv_start_script.go
  pkg/manager/member/startscript/v2/tikv_start_script_test.go
Labels: contribution, size/XL

#5332 ebs br: mark backup/restore failed when job failed
  go.mod
  pkg/backup/backup/backup_manager.go
  pkg/backup/restore/restore_manager.go
  pkg/backup/util/aws_ebs.go
  pkg/controller/backup/backup_controller.go
  pkg/controller/backup/backup_controller_test.go
  pkg/controller/restore/restore_controller.go
  pkg/controller/restore/restore_controller_test.go
  tests/e2e/br/br.go
Labels: approved, size/XL, area/ebs-br

#5413 tiproxy: no need for volume
  pkg/manager/volumes/vol_compare_utils.go
Labels: lgtm, approved, size/XS

#5411 backup-manager: try to directly get the backup size from backupmeta before calculate the backup size
  cmd/backup-manager/app/util/util.go
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/client/go.mod
  pkg/client/go.sum
Labels: first-time-contributor, lgtm, approved, size/L

#5422 remove tidb-cluster and tidb-backup Helm chart
  .gitignore
  Makefile
  charts/tidb-backup/.helmignore
  charts/tidb-backup/Chart.yaml
  charts/tidb-backup/templates/NOTES.txt
  charts/tidb-backup/templates/_helpers.tpl
  charts/tidb-backup/templates/backup-job.yaml
  charts/tidb-backup/templates/backup-pvc.yaml
  charts/tidb-backup/templates/restore-job.yaml
  charts/tidb-backup/templates/scripts/_start_backup.sh.tpl
  charts/tidb-backup/templates/scripts/_start_restore.sh.tpl
  charts/tidb-backup/values.yaml
  charts/tidb-cluster/.helmignore
  charts/tidb-cluster/Chart.yaml
  charts/tidb-cluster/templates/NOTES.txt
  charts/tidb-cluster/templates/_helpers.tpl
  charts/tidb-cluster/templates/config/_drainer-config.tpl
  charts/tidb-cluster/templates/config/_grafana-dashboard.tpl
  charts/tidb-cluster/templates/config/_prometheus-config.tpl
  charts/tidb-cluster/templates/config/_pump-config.tpl
  charts/tidb-cluster/templates/discovery-deployment.yaml
  charts/tidb-cluster/templates/discovery-rbac.yaml
  charts/tidb-cluster/templates/discovery-service.yaml
  charts/tidb-cluster/templates/drainer-configmap-rollout.yaml
  charts/tidb-cluster/templates/drainer-configmap.yaml
  charts/tidb-cluster/templates/drainer-service.yaml
  charts/tidb-cluster/templates/drainer-statefulset.yaml
  charts/tidb-cluster/templates/monitor-configmap.yaml
  charts/tidb-cluster/templates/monitor-deployment.yaml
  charts/tidb-cluster/templates/monitor-pvc.yaml
  charts/tidb-cluster/templates/monitor-rbac.yaml
  charts/tidb-cluster/templates/monitor-secret.yaml
  charts/tidb-cluster/templates/monitor-service.yaml
  charts/tidb-cluster/templates/pd-configmap.yaml
  charts/tidb-cluster/templates/pump-configmap-rollout.yaml
  charts/tidb-cluster/templates/pump-configmap.yaml
  charts/tidb-cluster/templates/pump-service.yaml
  charts/tidb-cluster/templates/pump-statefulset.yaml
  charts/tidb-cluster/templates/scheduled-backup-cronjob.yaml
  charts/tidb-cluster/templates/scheduled-backup-pvc.yaml
  charts/tidb-cluster/templates/scripts/_initialize_tidb_users.py.tpl
  charts/tidb-cluster/templates/scripts/_start_drainer.sh.tpl
  charts/tidb-cluster/templates/scripts/_start_pd.sh.tpl
  charts/tidb-cluster/templates/scripts/_start_pump.sh.tpl
  charts/tidb-cluster/templates/scripts/_start_scheduled_backup.sh.tpl
  charts/tidb-cluster/templates/scripts/_start_tidb.sh.tpl
  charts/tidb-cluster/templates/scripts/_start_tikv.sh.tpl
  charts/tidb-cluster/templates/tidb-cluster.yaml
  charts/tidb-cluster/templates/tidb-configmap-rollout.yaml
  charts/tidb-cluster/templates/tidb-configmap.yaml
  charts/tidb-cluster/templates/tidb-initializer-job.yaml
  charts/tidb-cluster/templates/tidb-service.yaml
  charts/tidb-cluster/templates/tikv-configmap.yaml
  charts/tidb-cluster/values.yaml
  hack/e2e-patch-codecov.sh
  tests/actions.go
  tests/e2e/util/image/image.go
  tests/images/e2e/Dockerfile
Labels: approved, size/XXL

#5418 [BR] Remove k8s cluster name from backup/init pod names
  pkg/apis/federation/pingcap/v1alpha1/volume_backup.go
  pkg/fedvolumebackup/backup/backup_manager.go
  pkg/fedvolumebackup/backup/backup_test.go
Labels: contribution, size/M, approved, area/ebs-br

#5414 br: add additional volumes to backup/restore/warmup pods
  docs/api-references/docs.md
  docs/api-references/federation-docs.md
  manifests/crd.yaml
  manifests/crd/federation/v1/federation.pingcap.com_volumebackups.yaml
  manifests/crd/federation/v1/federation.pingcap.com_volumebackupschedules.yaml
  manifests/crd/federation/v1/federation.pingcap.com_volumerestores.yaml
  manifests/crd/v1/pingcap.com_backups.yaml
  manifests/crd/v1/pingcap.com_backupschedules.yaml
  manifests/crd/v1/pingcap.com_restores.yaml
  manifests/federation-crd.yaml
  pkg/apis/federation/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/federation/pingcap/v1alpha1/types.go
  pkg/apis/federation/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/backup/backup/backup_cleaner.go
  pkg/backup/backup/backup_manager.go
  pkg/backup/restore/restore_manager.go
  pkg/fedvolumebackup/backup/backup_manager.go
  pkg/fedvolumebackup/restore/restore_manager.go
Labels: approved, size/XXL, area/ebs-br
