Repository pingcap/tidb-operator, pull requests merged in 2023-08, with the labels that each got.

#5207 br: backup manifests related to tidb cluster in EBS backup
  pkg/backup/backup/backup_manager.go
  pkg/backup/backup/backup_manifests.go
  pkg/backup/backup/backup_manifests_test.go
  pkg/backup/constants/constants.go
  pkg/controller/controller_utils.go
Labels: type/cherry-pick-for-release-1.5, lgtm, approved, size/XXL, area/ebs-br

#5194 fix: add label overwrite for tiproxy component val compatibility and min ready sec
  docs/api-references/docs.md
  hack/lib.sh
  hack/localtest/cluster.yaml
  hack/localtest/monitor.yaml
  hack/localtest/test.sh
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_dmclusters.yaml
  manifests/crd/v1/pingcap.com_tidbclusters.yaml
  manifests/crd/v1/pingcap.com_tidbdashboards.yaml
  manifests/crd/v1/pingcap.com_tidbngmonitorings.yaml
  pkg/apis/pingcap/v1alpha1/component_spec.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/member/tiproxy_upgrader.go
Labels: lgtm, approved, size/L

#5220 br: support iam with pod authorization and fix calcSizeLevel invalid
  cmd/backup-manager/app/util/backup_size.go
  pkg/fedvolumebackup/backup/backup_manager.go
  pkg/fedvolumebackup/restore/restore_manager.go
Labels: lgtm, approved, size/S, area/ebs-br

#5221 bump to v1.6.0-alpha.4
  charts/br-federation/values.yaml
  charts/tidb-cluster/values.yaml
  charts/tidb-operator/values.yaml
  deploy/aliyun/variables.tf
  deploy/aws/variables.tf
  deploy/gcp/variables.tf
  go.mod
  hack/bump-version.sh
  pkg/client/go.mod
Labels: size/S

#5223 opt: keep ports config for TiFlash 7.1.0+ to avoid restarting
  pkg/apis/label/label.go
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/manager/member/tiflash_util.go
Labels: lgtm, approved, size/S

#5226 bump to v1.6.0-alpha.5
  charts/br-federation/values.yaml
  charts/tidb-cluster/values.yaml
  charts/tidb-operator/values.yaml
  deploy/aliyun/variables.tf
  deploy/aws/variables.tf
  deploy/gcp/variables.tf
  go.mod
  hack/bump-version.sh
  pkg/client/go.mod
Labels: size/S

#5244 fix: revert 'add missing tiproxy label'
  pkg/apis/pingcap/v1alpha1/component_spec.go
Labels: lgtm, approved, size/XS

#5241 allow porting labels when initiating backup/restore member
  pkg/fedvolumebackup/backup/backup_manager.go
  pkg/fedvolumebackup/restore/restore_manager.go
Labels: contribution, lgtm, approved, size/S, area/ebs-br

#5251 bump to v1.6.0-alpha.6
  charts/br-federation/values.yaml
  charts/tidb-cluster/values.yaml
  charts/tidb-operator/values.yaml
  deploy/aliyun/variables.tf
  deploy/aws/variables.tf
  deploy/gcp/variables.tf
  go.mod
  hack/bump-version.sh
  pkg/client/go.mod
Labels: size/S

#5229 br: add warmup process to volume snapshot restore
  docs/api-references/docs.md
  docs/api-references/federation-docs.md
  manifests/crd.yaml
  manifests/crd/federation/v1/federation.pingcap.com_volumerestores.yaml
  manifests/crd/v1/pingcap.com_restores.yaml
  manifests/federation-crd.yaml
  pkg/apis/federation/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/federation/pingcap/v1alpha1/types.go
  pkg/apis/federation/pingcap/v1alpha1/volume_restore.go
  pkg/apis/label/label.go
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/restore.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/backup/restore/restore_manager.go
  pkg/controller/restore/restore_controller.go
  pkg/fedvolumebackup/restore/restore_manager.go
  pkg/fedvolumebackup/restore/restore_test.go
Labels: lgtm, approved, size/XXL, area/ebs-br

#5238 backup: added ebs-warmup for restoring from EBS snapshots
  Makefile
  cmd/ebs-warmup/filereader/config.go
  cmd/ebs-warmup/filereader/exec.go
  cmd/ebs-warmup/main.go
  cmd/ebs-warmup/worker/tasks/task.go
  cmd/ebs-warmup/worker/worker.go
  go.mod
  go.sum
  images/ebs-warmup/Dockerfile
  images/ebs-warmup/Dockerfile.e2e
  images/ebs-warmup/warmup-steps.sh
Labels: first-time-contributor, approved, size/XXL, area/ebs-br

#5255 br: add manifests of v1beta1
  manifests/crd/federation/v1beta1/federation.pingcap.com_volumerestores.yaml
  manifests/crd/v1beta1/pingcap.com_restores.yaml
  manifests/crd_v1beta1.yaml
  manifests/federation-crd_v1beta1.yaml
Labels: size/S

#5248 br: modify time complete of restore status
  cmd/backup-manager/app/restore/manager.go
  pkg/backup/restore/restore_manager.go
Labels: lgtm, approved, size/S, area/ebs-br

#5258 ebs-warmup: added exec mode for warmup-steps.sh
  images/ebs-warmup/warmup-steps.sh
Labels: approved, size/XS, area/ebs-br

#5250 bump K8s to v1.23.17
  cmd/admission-webhook/main.go
  cmd/backup-manager/main.go
  cmd/br-federation-manager/main.go
  cmd/controller-manager/main.go
  cmd/discovery/main.go
  cmd/scheduler/main.go
  go.mod
  go.sum
  hack/e2e.sh
  hack/lib.sh
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_dmclusters.yaml
  manifests/crd/v1/pingcap.com_tidbclusters.yaml
  manifests/crd/v1/pingcap.com_tidbdashboards.yaml
  manifests/crd/v1/pingcap.com_tidbinitializers.yaml
  manifests/crd/v1/pingcap.com_tidbmonitors.yaml
  manifests/crd/v1/pingcap.com_tidbngmonitorings.yaml
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidb_config_wraper.go
  pkg/apis/util/k8s/json.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/typed/pingcap/v1alpha1/fake/fake_backup.go
  pkg/client/clientset/versioned/typed/pingcap/v1alpha1/fake/fake_backupschedule.go
  pkg/client/clientset/versioned/typed/pingcap/v1alpha1/fake/fake_dataresource.go
  pkg/client/clientset/versioned/typed/pingcap/v1alpha1/fake/fake_dmcluster.go
  pkg/client/clientset/versioned/typed/pingcap/v1alpha1/fake/fake_restore.go
  pkg/client/clientset/versioned/typed/pingcap/v1alpha1/fake/fake_tidbcluster.go
  pkg/client/clientset/versioned/typed/pingcap/v1alpha1/fake/fake_tidbclusterautoscaler.go
  pkg/client/clientset/versioned/typed/pingcap/v1alpha1/fake/fake_tidbdashboard.go
  pkg/client/clientset/versioned/typed/pingcap/v1alpha1/fake/fake_tidbinitializer.go
  pkg/client/clientset/versioned/typed/pingcap/v1alpha1/fake/fake_tidbmonitor.go
  pkg/client/clientset/versioned/typed/pingcap/v1alpha1/fake/fake_tidbngmonitoring.go
  pkg/client/clientset/versioned/typed/pingcap/v1alpha1/pingcap_client.go
  pkg/client/federation/clientset/versioned/clientset.go
  pkg/client/federation/clientset/versioned/typed/pingcap/v1alpha1/fake/fake_volumebackup.go
  pkg/client/federation/clientset/versioned/typed/pingcap/v1alpha1/fake/fake_volumebackupschedule.go
  pkg/client/federation/clientset/versioned/typed/pingcap/v1alpha1/fake/fake_volumerestore.go
  pkg/client/federation/clientset/versioned/typed/pingcap/v1alpha1/pingcap_client.go
  pkg/client/go.mod
  pkg/client/go.sum
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/pd_member_manager_test.go
  pkg/manager/member/pump_member_manager.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tidb_member_manager_test.go
  pkg/manager/member/tikv_member_manager.go
  pkg/manager/member/tikv_member_manager_test.go
  pkg/monitor/monitor/util.go
  pkg/monitor/monitor/util_test.go
  tests/e2e/br/utils/s3/minio.go
  tests/e2e/e2e_test.go
  tests/images/e2e/Dockerfile
  tests/images/stability-test/Dockerfile
Labels: size/XXL

#5150 Add Volume Replacement feature with support for pd, tidb, tikv
  charts/tidb-operator/values.yaml
  docs/api-references/docs.md
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_tidbclusters.yaml
  pkg/apis/label/label.go
  pkg/apis/pingcap/v1alpha1/component_status.go
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/controller/pod_control.go
  pkg/controller/pod_control_test.go
  pkg/controller/tidbcluster/pod_control.go
  pkg/controller/tidbcluster/pod_control_test.go
  pkg/controller/tidbcluster/tidb_cluster_control.go
  pkg/controller/tidbcluster/tidb_cluster_control_test.go
  pkg/controller/tidbcluster/tidb_cluster_controller.go
  pkg/controller/tidbcluster/tidb_cluster_controller_test.go
  pkg/features/features.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tikv_member_manager.go
  pkg/manager/member/tikv_member_manager_test.go
  pkg/manager/member/tikv_scaler.go
  pkg/manager/member/tikv_scaler_test.go
  pkg/manager/volumes/pod_vol_modifier.go
  pkg/manager/volumes/pvc_modifier.go
  pkg/manager/volumes/pvc_replacer.go
  pkg/manager/volumes/pvc_replacer_test.go
  pkg/manager/volumes/vol_compare_utils.go
Labels: contribution, first-time-contributor, lgtm, approved, size/XXL

#5273 bump asts mod and hack asts for volumeMode update
  go.mod
  go.sum
  pkg/manager/utils/statefulset.go
  pkg/util/util.go
Labels: size/M, lgtm, approved

#5275 bump to v1.6.0-alpha.7
  charts/br-federation/values.yaml
  charts/tidb-cluster/values.yaml
  charts/tidb-operator/values.yaml
  deploy/aliyun/variables.tf
  deploy/aws/variables.tf
  deploy/gcp/variables.tf
  go.mod
  hack/bump-version.sh
  pkg/client/go.mod
Labels: size/S
