Repository pingcap/tidb-operator, pull requests merged in 2023-06, with the labels that each got.

#5040 Consider cluster domain when draining capture servers across multiple kubernetes clusters
  pkg/controller/ticdc_control.go
  pkg/controller/ticdc_control_test.go
  pkg/controller/tidb_control_test.go
Labels: size/M

#5047 add tolerations support for TidbInitializer
  docs/api-references/docs.md
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_tidbinitializers.yaml
  manifests/crd/v1beta1/pingcap.com_tidbinitializers.yaml
  manifests/crd_v1beta1.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbinitializer_types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/member/tidb_init_manager.go
Labels: lgtm, approved, size/L

#5041 tiproxy: enable SSL by default
  docs/api-references/docs.md
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_tidbclusters.yaml
  manifests/crd/v1beta1/pingcap.com_tidbclusters.yaml
  manifests/crd_v1beta1.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/manager/member/tiproxy_member_manager.go
Labels: size/M, approved

#5060 fix TiCDC across K8s address
  pkg/controller/ticdc_control.go
Labels: size/XS

#5055 bump operator version to 1.6.0-alpha.1
  charts/br-federation/values.yaml
  charts/tidb-cluster/values.yaml
  charts/tidb-operator/values.yaml
  deploy/aliyun/variables.tf
  deploy/aws/variables.tf
  deploy/gcp/variables.tf
  go.mod
  hack/bump-version.sh
  pkg/client/go.mod
Labels: lgtm, approved, size/S

#5039 br: implement federation volume restore controller
  docs/api-references/federation-docs.md
  manifests/crd/federation/v1/federation.pingcap.com_volumerestores.yaml
  manifests/crd/federation/v1beta1/federation.pingcap.com_volumerestores.yaml
  manifests/federation-crd.yaml
  manifests/federation-crd_v1beta1.yaml
  pkg/apis/federation/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/federation/pingcap/v1alpha1/types.go
  pkg/apis/federation/pingcap/v1alpha1/volume_restore.go
  pkg/apis/federation/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/label/label.go
  pkg/controller/fedvolumerestore/fed_volume_restore_control.go
  pkg/controller/fedvolumerestore/fed_volume_restore_control_test.go
  pkg/controller/fedvolumerestore/fed_volume_restore_controller.go
  pkg/controller/fedvolumerestore/fed_volume_restore_controller_test.go
  pkg/fedvolumebackup/backup.go
  pkg/fedvolumebackup/backup/backup_manager.go
  pkg/fedvolumebackup/backup/backup_test.go
  pkg/fedvolumebackup/restore/restore_manager.go
  pkg/fedvolumebackup/restore/restore_test.go
Labels: lgtm, approved, size/XXL

#5075 Remove tcp and http ports for tiflash >= 7.1.0
  pkg/manager/member/tiflash_util.go
  pkg/manager/member/tiflash_util_test.go
Labels: first-time-contributor, size/M, lgtm, approved

#5070 Bump operator version to 1.4.5
  charts/tidb-cluster/values.yaml
  charts/tidb-operator/values.yaml
  deploy/aliyun/variables.tf
  deploy/aws/variables.tf
  deploy/gcp/variables.tf
  go.mod
  hack/bump-version.sh
  pkg/client/go.mod
Labels: lgtm, approved, size/S

#5058 fix(volume): fix panic bug when enable ModifyVolume feature
  pkg/manager/volumes/phase.go
  pkg/manager/volumes/phase_test.go
  pkg/manager/volumes/pod_vol_modifier.go
  pkg/manager/volumes/pod_vol_modifier_test.go
  pkg/manager/volumes/pvc_modifier.go
  pkg/manager/volumes/sync_volume_status.go
  pkg/manager/volumes/sync_volume_status_test.go
Labels: approved, size/XL

#5084 tiproxy: revert enable SSL by default
  docs/api-references/docs.md
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_tidbclusters.yaml
  manifests/crd/v1beta1/pingcap.com_tidbclusters.yaml
  manifests/crd_v1beta1.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/manager/member/tiproxy_member_manager.go
Labels: lgtm, approved, size/S

#5071 make pd start timeout configurable
  docs/api-references/docs.md
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_tidbclusters.yaml
  manifests/crd/v1beta1/pingcap.com_tidbclusters.yaml
  manifests/crd_v1beta1.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/manager/member/startscript/v1/render_script.go
  pkg/manager/member/startscript/v1/template.go
  pkg/manager/member/startscript/v1/template_test.go
  pkg/manager/member/startscript/v2/pd_start_script.go
  pkg/manager/member/startscript/v2/pd_start_script_test.go
Labels: contribution, size/M, lgtm, approved

#5096 fix PD StartTimeout if no CRD updated
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/manager/member/startscript/v1/render_script.go
  pkg/manager/member/startscript/v1/template_test.go
  pkg/manager/member/startscript/v2/pd_start_script.go
  pkg/manager/member/startscript/v2/pd_start_script_test.go
Labels: size/S

#5099 chore: add make help cmd
  Makefile
Labels: contribution, lgtm, approved, size/L

#5102 bump operator version to 1.6.0-alpha.2
  charts/br-federation/values.yaml
  charts/tidb-cluster/values.yaml
  charts/tidb-operator/values.yaml
  deploy/aliyun/variables.tf
  deploy/aws/variables.tf
  deploy/gcp/variables.tf
  go.mod
  hack/bump-version.sh
  pkg/client/go.mod
Labels: lgtm, approved, size/S

#5101 opt: do not evict leader when changing PVC size
  pkg/manager/volumes/pvc_modifier.go
Labels: size/M, lgtm, approved

#5110 Chore: update the bootstrap SQL supported version
  docs/api-references/docs.md
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
Labels: contribution, lgtm, approved, size/XS
