Repository pingcap/tidb-operator, pull requests merged in 2023-05, with the labels that each got.

#4973 Check service annotation and labels
  pkg/controller/service_control.go
  pkg/controller/service_control_test.go
  pkg/manager/member/dm_master_member_manager.go
  pkg/manager/member/dm_worker_member_manager.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/tiflash_member_manager.go
  pkg/manager/member/tikv_member_manager.go
  pkg/manager/member/tiproxy_member_manager.go
Labels: status/LGT2

#4979 check all stores are up before upgrade
  pkg/controller/tidbcluster/pod_control.go
  pkg/controller/tidbcluster/pod_control_test.go
  pkg/manager/member/tikv_upgrader.go
  pkg/manager/member/tikv_upgrader_test.go
  pkg/pdapi/pdutil.go
Labels: status/can-merge, status/LGT2

#4951 br: fix renaming pvc when there are multiple volumes in tikv pod
  pkg/backup/snapshotter/snapshotter.go
  pkg/backup/snapshotter/snapshotter_test.go
  pkg/backup/testutils/br.go
Labels: status/can-merge, tools/br, status/LGT2

#5001 Fix cluster meta data existing
  pkg/backup/backup/backup_manager.go
Labels: status/can-merge, status/LGT2

#4958 chore: migrate to new prow reviewing
  OWNERS
Labels: status/LGT1

#4999 br: refactor volume snapshot backup to support across k8s clusters
  cmd/backup-manager/app/backup/backup.go
  cmd/backup-manager/app/backup/manager.go
  cmd/backup-manager/app/cmd/backup.go
  cmd/backup-manager/app/util/generic.go
  docs/api-references/docs.md
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_backups.yaml
  manifests/crd/v1/pingcap.com_backupschedules.yaml
  manifests/crd/v1/pingcap.com_restores.yaml
  manifests/crd/v1beta1/pingcap.com_backups.yaml
  manifests/crd/v1beta1/pingcap.com_backupschedules.yaml
  manifests/crd/v1beta1/pingcap.com_restores.yaml
  manifests/crd_v1beta1.yaml
  pkg/apis/pingcap/v1alpha1/backup.go
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/backup/backup/backup_manager.go
  pkg/backup/util/util.go
  pkg/backup/util/utils_test.go
  pkg/controller/backup/backup_controller.go
Labels: status/can-merge, status/LGT2

#4997 allow leader eviction annotation to expire
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/controller/tidbcluster/pod_control.go
  pkg/controller/tidbcluster/pod_control_test.go
Labels: status/LGT2

#4995 check all PD peers are healthy before upgrade
  pkg/controller/tidbcluster/pod_control.go
  pkg/controller/tidbcluster/pod_control_test.go
  pkg/manager/member/pd_upgrader.go
  pkg/manager/member/pd_upgrader_test.go
  pkg/pdapi/pdutil.go
Labels: status/LGT2

#5015 fix PD peer svc update repeatly
  pkg/manager/member/pd_member_manager.go
Labels: status/LGT2

#5007 ebs: calc full snapshot size and report backup size for failed backup
  cmd/backup-manager/app/backup/manager.go
  cmd/backup-manager/app/clean/manager.go
  cmd/backup-manager/app/util/backup_size.go
  pkg/backup/util/remote.go
Labels: status/LGT2

#5019 Update apis/types.go printcolumn description
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_tidbclusters.yaml
  manifests/crd/v1beta1/pingcap.com_tidbclusters.yaml
  manifests/crd_v1beta1.yaml
  pkg/apis/pingcap/v1alpha1/types.go
Labels: status/LGT1

#5010 br: refactor restore controller to support across k8s
  cmd/backup-manager/app/cmd/restore.go
  cmd/backup-manager/app/restore/restore.go
  cmd/backup-manager/app/util/util.go
  docs/api-references/docs.md
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_restores.yaml
  manifests/crd/v1beta1/pingcap.com_restores.yaml
  manifests/crd_v1beta1.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/restore.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/backup/backup/backup_manager.go
  pkg/backup/backup/backup_test.go
  pkg/backup/constants/constants.go
  pkg/backup/restore/restore_manager.go
  pkg/backup/restore/restore_manager_test.go
  pkg/backup/snapshotter/snapshotter.go
  pkg/backup/snapshotter/snapshotter_aws.go
  pkg/backup/snapshotter/snapshotter_gcp.go
  pkg/backup/snapshotter/snapshotter_none.go
  pkg/backup/testutils/helpers.go
  pkg/backup/util/util.go
  pkg/backup/util/utils_test.go
  pkg/controller/restore/restore_controller.go
Labels: status/LGT1

#5014 Fix TidbDashboard baseImage parsing fault
  pkg/manager/tidbdashboard/manager.go
  pkg/manager/tidbdashboard/manager_test.go
Labels: status/LGT1

#5013 br: implement federation volume backup controller
  Makefile
  cmd/backup-manager/app/backup/backup.go
  cmd/br-federation-manager/main.go
  docs/api-references/federation-docs.md
  manifests/crd/federation/v1/federation.pingcap.com_volumebackups.yaml
  manifests/crd/federation/v1beta1/federation.pingcap.com_volumebackups.yaml
  manifests/federation-crd.yaml
  manifests/federation-crd_v1beta1.yaml
  pkg/apis/federation/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/federation/pingcap/v1alpha1/types.go
  pkg/apis/federation/pingcap/v1alpha1/volume_backup.go
  pkg/apis/federation/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/pingcap/v1alpha1/backup.go
  pkg/backup/snapshotter/snapshotter.go
  pkg/controller/backup/backup_controller.go
  pkg/controller/br_fed_dependences.go
  pkg/controller/fedvolumebackup/fed_volume_backup_control.go
  pkg/controller/fedvolumebackup/fed_volume_backup_control_test.go
  pkg/controller/fedvolumebackup/fed_volume_backup_controller.go
  pkg/controller/fedvolumebackup/fed_volume_backup_controller_test.go
  pkg/fedvolumebackup/backup.go
  pkg/fedvolumebackup/backup/backup_manager.go
  pkg/fedvolumebackup/backup/backup_test.go
Labels: status/can-merge, status/LGT2
