Repository pingcap/tidb-operator, pull requests merged in 2023-03, with the labels that each got.

#4917 manager: fix tiproxy scale & delete-slots
  hack/localtest/operator.yaml
  hack/localtest/test.sh
  pkg/apis/label/label.go
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/apis/pingcap/v1alpha1/validation/validation.go
  pkg/manager/member/tiproxy_scaler.go
  pkg/manager/member/utils.go
  pkg/upgrader/upgrader.go
  pkg/util/util.go
Labels: status/can-merge, status/LGT2

#4895 BR: Restart backup when backup job/pod unexpected failed by k8s
  cmd/backup-manager/app/backup/backup.go
  cmd/backup-manager/app/backup/manager.go
  cmd/backup-manager/app/util/util.go
  docs/api-references/docs.md
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_backups.yaml
  manifests/crd/v1/pingcap.com_backupschedules.yaml
  manifests/crd/v1beta1/pingcap.com_backups.yaml
  manifests/crd/v1beta1/pingcap.com_backupschedules.yaml
  manifests/crd_v1beta1.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/backup/backup.go
  pkg/backup/backup/backup_cleaner.go
  pkg/backup/backup/backup_manager.go
  pkg/backup/backup/backup_test.go
  pkg/controller/backup/backup_control.go
  pkg/controller/backup/backup_controller.go
  pkg/controller/backup_status_updater.go
  tests/e2e/br/br.go
  tests/e2e/br/framework/br/wait.go
Labels: tools/br, status/LGT2

#4904 BR: Auto truncate log backup in backup schedule
  docs/api-references/docs.md
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_backupschedules.yaml
  manifests/crd/v1beta1/pingcap.com_backupschedules.yaml
  manifests/crd_v1beta1.yaml
  pkg/apis/pingcap/v1alpha1/backup_schedule.go
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/util/config/config.go
  pkg/backup/backupschedule/backup_schedule_manager.go
  pkg/backup/backupschedule/backup_schedule_manager_test.go
  pkg/controller/backup_control.go
Labels: tools/br, status/LGT2

#4914 fix: add a new check for encryption during the volume snapshot restore
  pkg/backup/restore/restore_manager.go
  pkg/backup/testutils/br.go
Labels: status/can-merge, status/LGT2

#4922 br: volume-snapshot may lead to a panic when there is no block change between two snapshot
  cmd/backup-manager/app/util/backup_size.go
Labels: status/can-merge, status/LGT2

#4881 Implement the feature of pod serial number control for TiCDC using asts
  pkg/apis/label/label.go
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/apis/pingcap/v1alpha1/validation/validation.go
  pkg/apis/pingcap/v1alpha1/validation/validation_test.go
  pkg/manager/member/ticdc_member_manager.go
  pkg/manager/member/utils.go
  pkg/upgrader/upgrader.go
  pkg/util/util.go
  tests/e2e/tidbcluster/stability-asts.go
Labels: status/can-merge, status/LGT2

#4920 Skip setting store labels with invalid semver
  pkg/manager/member/tidb_member_manager.go
Labels: status/LGT2

#4925 br: refine BackoffRetryPolicy time format
  docs/api-references/docs.md
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_backups.yaml
  manifests/crd/v1/pingcap.com_backupschedules.yaml
  manifests/crd/v1beta1/pingcap.com_backups.yaml
  manifests/crd/v1beta1/pingcap.com_backupschedules.yaml
  manifests/crd_v1beta1.yaml
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/backup/util/util.go
  pkg/controller/backup/backup_controller.go
  tests/e2e/br/br.go
Labels: tools/br, status/LGT2

#4896 Add PD graceful restart
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/controller/tidbcluster/pod_control.go
  pkg/controller/tidbcluster/pod_control_test.go
Labels: status/can-merge, status/LGT2

#4847 update helm version to the 3.11.0
  charts/tidb-drainer/Chart.yaml
  charts/tidb-lightning/Chart.yaml
  charts/tikv-importer/Chart.yaml
  hack/lib.sh
  tests/images/e2e/Dockerfile
  tests/images/stability-test/Dockerfile
Labels: status/can-merge, status/LGT2

#4929 dp: cherry pick dp prs to release-1.4
  cmd/backup-manager/app/backup/backup.go
  cmd/backup-manager/app/backup/manager.go
  cmd/backup-manager/app/clean/clean.go
  cmd/backup-manager/app/clean/manager.go
  cmd/backup-manager/app/util/backup_size.go
  cmd/backup-manager/app/util/util.go
  docs/api-references/docs.md
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_backups.yaml
  manifests/crd/v1/pingcap.com_backupschedules.yaml
  manifests/crd/v1beta1/pingcap.com_backups.yaml
  manifests/crd/v1beta1/pingcap.com_backupschedules.yaml
  manifests/crd_v1beta1.yaml
  pkg/apis/pingcap/v1alpha1/backup.go
  pkg/apis/pingcap/v1alpha1/backup_schedule.go
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/util/config/config.go
  pkg/backup/backup.go
  pkg/backup/backup/backup_cleaner.go
  pkg/backup/backup/backup_manager.go
  pkg/backup/backup/backup_test.go
  pkg/backup/backupschedule/backup_schedule_manager.go
  pkg/backup/backupschedule/backup_schedule_manager_test.go
  pkg/backup/constants/constants.go
  pkg/backup/restore/restore_manager.go
  pkg/backup/restore/restore_manager_test.go
  pkg/backup/snapshotter/snapshotter.go
  pkg/backup/snapshotter/snapshotter_test.go
  pkg/backup/testutils/br.go
  pkg/backup/util/aws_ebs.go
  pkg/backup/util/util.go
  pkg/backup/util/worker.go
  pkg/controller/backup/backup_control.go
  pkg/controller/backup/backup_controller.go
  pkg/controller/backup_control.go
  pkg/controller/backup_status_updater.go
  pkg/manager/member/tiflash_member_manager.go
  pkg/pdapi/fake_pdapi.go
  pkg/pdapi/pdapi.go
  tests/e2e/br/br.go
  tests/e2e/br/framework/br/wait.go
Labels: status/LGT1

#4930 bump operator version to 1.4.4
  charts/tidb-cluster/values.yaml
  charts/tidb-operator/values.yaml
  deploy/aliyun/variables.tf
  deploy/aws/variables.tf
  deploy/gcp/variables.tf
  go.mod
  hack/bump-version.sh
  pkg/client/go.mod
Labels: status/LGT1

#4934 chore: ioutil has been deprecated in go 1.16
  cmd/backup-manager/app/backup/backup.go
  cmd/backup-manager/app/import/import.go
  cmd/backup-manager/app/restore/restore.go
  pkg/autoscaler/autoscaler/query/external.go
  pkg/binlog/binlog.go
  pkg/controller/ticdc_control.go
  pkg/controller/tidb_control.go
  pkg/controller/tidb_control_test.go
  pkg/discovery/server/proxy_test.go
  pkg/discovery/server/server_test.go
  pkg/pdapi/pdapi.go
  pkg/pdapi/pdapi_test.go
  pkg/util/http/httputil.go
  pkg/util/http/httputil_test.go
  tests/actions.go
  tests/crd_test_util.go
  tests/e2e/tidbdashboard/dashboard.go
  tests/e2e/util/pd/pd.go
  tests/e2e/util/proxiedtidbclient/proxiedtidbclient.go
  tests/e2e/util/tngm/ng_monitoring_client.go
  tests/monitor.go
  tests/pkg/fault-trigger/client/client.go
  tests/pkg/metrics/annotation_util.go
  tests/pkg/mock/monitor.go
  tests/pkg/mock/util.go
  tests/pkg/webhook/route.go
Labels: status/LGT1

#4935 br: fix dockerfile base
  images/tidb-backup-manager/Dockerfile
  images/tidb-backup-manager/Dockerfile.e2e
Labels: tools/br, status/LGT1

#4905 Update the TiDB Operator documentation to reference the correct k8s core docs
  docs/api-references/config.json
  docs/api-references/docs.md
Labels: status/LGT1

#4936 *: refine Development Guide
  README.md
  docs/CONTRIBUTING.md
  hack/lib.sh
Labels: status/LGT1

#4941 chore: update k8s.gcr.io -> registry.k8s.io
  CHANGELOG.md
  charts/tidb-operator/values.yaml
  manifests/local-dind/kubernetes-dashboard.yaml
  tests/e2e/config/config.go
  tests/e2e/tidbcluster/serial.go
  tests/e2e/tidbcluster/stability-asts.go
Labels: status/LGT1
