Repository pingcap/tidb-operator, pull requests merged in 2023-01, with the labels that each got.

#4815 Fix example tidb-dashboard image
  examples/aks/tidb-dashboard.yaml
  examples/aws/tidb-dashboard.yaml
  examples/basic-cn/tidb-dashboard.yaml
  examples/basic/tidb-dashboard.yaml
  examples/gcp/tidb-dashboard.yaml
Labels: status/can-merge, status/LGT2

#4818 Check desired volume during validation
  pkg/manager/volumes/phase.go
  pkg/manager/volumes/phase_test.go
Labels: type/bug, status/can-merge, status/LGT2

#4821 fix: adapt to new tiproxy
  docs/api-references/docs.md
  go.mod
  go.sum
  hack/lib.sh
  hack/localtest/cluster.yaml
  hack/localtest/test.sh
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_tidbclusters.yaml
  manifests/crd/v1beta1/pingcap.com_tidbclusters.yaml
  manifests/crd_v1beta1.yaml
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/apis/pingcap/v1alpha1/tiproxy_config_wrapper.go
  pkg/apis/pingcap/v1alpha1/tiproxy_config_wrapper_test.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/client/go.sum
  pkg/controller/tiproxy_control.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tiproxy_member_manager.go
  pkg/manager/volumes/phase.go
Labels: status/can-merge, status/LGT2

#4820 fix #4816 crash bug when log for buildContextForTC return error
  pkg/manager/member/pvc_resizer.go
Labels: status/LGT1

#4812 feat: support tiflash backup and restore during volume snapshot
  cmd/backup-manager/app/backup/backup.go
  cmd/backup-manager/app/clean/clean.go
  pkg/backup/constants/constants.go
  pkg/backup/restore/restore_manager.go
  pkg/backup/restore/restore_manager_test.go
  pkg/backup/snapshotter/snapshotter.go
  pkg/backup/snapshotter/snapshotter_test.go
  pkg/backup/util/aws_ebs.go
  pkg/backup/util/util.go
  pkg/manager/member/tiflash_member_manager.go
  pkg/pdapi/fake_pdapi.go
  pkg/pdapi/pdapi.go
Labels: status/can-merge, status/LGT2

#4830 Add config to increase kube-client qps limit
  charts/tidb-operator/templates/controller-manager-deployment.yaml
  charts/tidb-operator/values.yaml
  cmd/controller-manager/main.go
  pkg/controller/dependences.go
Labels: status/can-merge, status/LGT2

#4837 fix panic without PV permission
  pkg/manager/volumes/delegation/aws/ebs_modifier.go
  pkg/manager/volumes/delegation/interface.go
  pkg/manager/volumes/pod_vol_modifier.go
Labels: status/can-merge, status/LGT2

#4842 tc: delete tiflash sts before scale from 0
  pkg/manager/member/tiflash_member_manager.go
Labels: status/can-merge, status/LGT2

#4825 manager: fix dynamic config update of tiproxy
  docs/api-references/docs.md
  go.mod
  go.sum
  hack/localtest/cluster.yaml
  hack/localtest/test.sh
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_tidbclusters.yaml
  manifests/crd/v1beta1/pingcap.com_tidbclusters.yaml
  manifests/crd_v1beta1.yaml
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/apis/pingcap/v1alpha1/tiproxy_config_wrapper.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/client/go.sum
  pkg/controller/tiproxy_control.go
  pkg/manager/member/tiproxy_member_manager.go
  pkg/manager/member/tiproxy_upgrader.go
Labels: status/can-merge, status/LGT2
