Repository pingcap/tidb-operator, pull requests merged in 2024-11, with the labels that each got.

#5825 New certificate layout for tiproxy
  docs/api-references/docs.md
  manifests/crd/v1/pingcap.com_tidbclusters.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/manager/member/tiproxy_member_manager.go
Labels: contribution, lgtm, approved, size/XL

#5950 sec: bump some go mod and binaries
  go.mod
  go.sum
  images/tidb-backup-manager/Dockerfile
  images/tidb-backup-manager/Dockerfile.e2e
Labels: size/S

#5954 Regenerate CRD files
  manifests/crd.yaml
  manifests/federation-crd.yaml
Labels: contribution, lgtm, approved, size/XXL

#5956 fix(TidbMonitor): do not set OwnerReferences for ClusterRole and ClusterRoleBinding
  pkg/apis/label/label.go
  pkg/controller/generic_control.go
  pkg/monitor/monitor/monitor_manager.go
  pkg/monitor/monitor/monitor_manager_test.go
  pkg/monitor/monitor/util.go
Labels: lgtm, approved, size/L
