Repository pingcap/tidb-operator, pull requests merged in 2024-07, with the labels that each got.

#5676 bump gin for security
  cmd/http-service/go.mod
  cmd/http-service/go.sum
Labels: size/L

#5680 [tidb-dashboard] use portName for service
  pkg/manager/tidbdashboard/manager.go
  pkg/manager/tidbdashboard/manager_test.go
Labels: contribution, lgtm, approved, size/S

#5685 Add pvc volume replace for TiFlash component
  docs/CONTRIBUTING.md
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_tidbclusters.yaml
  pkg/apis/pingcap/v1alpha1/component_status.go
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/controller/tidbcluster/pod_control.go
  pkg/controller/tidbcluster/pod_control_test.go
  pkg/controller/tidbcluster/tidb_cluster_controller_test.go
  pkg/manager/member/utils.go
Labels: contribution, lgtm, approved, size/XL

#5687 sec: bump golang.org/x/net 0.27.0
  cmd/http-service/go.mod
  cmd/http-service/go.sum
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/client/go.mod
  pkg/client/go.sum
Labels: size/L

#5688 CI: bump runner Golang to v1.22.5
  ci/e2e_eks.groovy
  ci/e2e_gke.groovy
  ci/e2e_kind.groovy
  ci/pull_e2e_kind.groovy
  ci/pull_e2e_release.groovy
  ci/vm.groovy
Labels: size/S

#5691 bump controller-gen to v0.15.0
  hack/lib.sh
  hack/update-crd.sh
  manifests/crd.yaml
  manifests/crd/federation/v1/federation.pingcap.com_volumebackups.yaml
  manifests/crd/federation/v1/federation.pingcap.com_volumebackupschedules.yaml
  manifests/crd/federation/v1/federation.pingcap.com_volumerestores.yaml
  manifests/crd/v1/pingcap.com_backups.yaml
  manifests/crd/v1/pingcap.com_backupschedules.yaml
  manifests/crd/v1/pingcap.com_dmclusters.yaml
  manifests/crd/v1/pingcap.com_restores.yaml
  manifests/crd/v1/pingcap.com_tidbclusterautoscalers.yaml
  manifests/crd/v1/pingcap.com_tidbclusters.yaml
  manifests/crd/v1/pingcap.com_tidbdashboards.yaml
  manifests/crd/v1/pingcap.com_tidbinitializers.yaml
  manifests/crd/v1/pingcap.com_tidbmonitors.yaml
  manifests/crd/v1/pingcap.com_tidbngmonitorings.yaml
  manifests/federation-crd.yaml
Labels: size/XXL
