Repository pingcap/tidb-operator, pull requests merged in 2024-03, with the labels that each got.

#5552 support run tiflash pod with ConfigMap mounted in tiflash container
  pkg/apis/label/label.go
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/manager/member/startscript/v1/render_script.go
  pkg/manager/member/startscript/v1/template.go
  pkg/manager/member/startscript/v1/template_test.go
  pkg/manager/member/startscript/v2/tiflash_start_script.go
  pkg/manager/member/startscript/v2/tiflash_start_script_test.go
  pkg/manager/member/tiflash_member_manager.go
  pkg/manager/member/tiflash_util.go
  pkg/manager/member/tiflash_util_test.go
  tests/e2e/tidbcluster/tidbcluster.go
Labels: contribution, lgtm, approved, size/XXL

#5560 fix: append cluster domain for PD/TiKV/TiDB/etcd URL; prefer PD address for TiFlash/TiCDC
  pkg/apis/pingcap/v1alpha1/validation/validation.go
  pkg/apis/pingcap/v1alpha1/validation/validation_test.go
  pkg/backup/backup/backup_tracker.go
  pkg/controller/pd_control.go
  pkg/controller/tidb_control.go
  pkg/controller/tidbcluster/pod_control.go
  pkg/discovery/discovery.go
  pkg/manager/member/pump_member_manager.go
  pkg/manager/member/startscript/v2/ticdc_start_script.go
  pkg/manager/member/startscript/v2/ticdc_start_script_test.go
  pkg/manager/member/tidbcluster_status_manager.go
  pkg/manager/member/tiflash_util.go
  pkg/manager/member/tiflash_util_test.go
  pkg/manager/member/tikv_upgrader.go
  pkg/monitor/monitor/monitor_manager.go
  pkg/pdapi/pd_control.go
  pkg/tikvapi/tikv_control.go
Labels: lgtm, approved, size/L

#5559 pdms: randomly run pdms in e2e test
  examples/basic/pd-micro-service-cluster.yaml
  pkg/controller/tidbcluster/tidb_cluster_control.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/pd_ms_member_manager.go
  pkg/manager/member/startscript/v1/render_script.go
  pkg/manager/member/startscript/v2/pd_start_script.go
  pkg/manager/member/tikv_member_manager.go
  tests/actions.go
  tests/e2e/tidbcluster/tidbcluster.go
  tests/e2e/util/image/image.go
  tests/pkg/fixture/fixture.go
Labels: size/XL

#5564 pdms: PD default using start script v2 with WaitForDnsNameIpMatch when enables PDMS
  docs/api-references/docs.md
  examples/basic/pd-micro-service-cluster.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/controller/pd_control.go
  pkg/manager/member/startscript/render_start_script.go
  pkg/manager/member/startscript/v1/render_script.go
  pkg/manager/member/startscript/v1/template.go
  pkg/manager/member/startscript/v1/template_test.go
  pkg/manager/member/startscript/v2/pd_start_script.go
  pkg/manager/member/startscript/v2/pd_start_script_test.go
  pkg/manager/member/startscript/v2/pd_start_script_with_wait_for_ip_match_test.go
  pkg/manager/member/tikv_member_manager.go
  tests/pkg/fixture/fixture.go
Labels: lgtm, approved, size/XXL

#5565 feat: add readiness and liveness prob for discovery
  docs/api-references/docs.md
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_dmclusters.yaml
  manifests/crd/v1/pingcap.com_tidbclusters.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/member/tidb_discovery_manager.go
Labels: lgtm, approved, size/L

#5570 support scale TiDB simultaneously
  docs/api-references/docs.md
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_tidbclusters.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/validation/validation.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/member/tidb_scaler.go
  pkg/manager/member/tidb_scaler_test.go
  tests/e2e/e2e_test.go
  tests/e2e/tidb/tidb.go
Labels: size/XXL

#5569 Fail restore if any warmup job failed for volume-snapshot restores
  pkg/backup/restore/restore_manager.go
  pkg/backup/restore/restore_manager_test.go
Labels: contribution, type/cherry-pick-for-release-1.5, lgtm, approved, size/L, area/ebs-br

#5580 Feat: support customizing the readiness probe for tidb
  docs/api-references/docs.md
  hack/lib.sh
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_tidbclusters.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tidb_member_manager_test.go
  tests/e2e/tidbcluster/tidbcluster.go
Labels: contribution, lgtm, approved, size/XL

#5563 tiproxy: fix missing volume for http tls
  pkg/manager/member/tiproxy_member_manager.go
Labels: size/M, lgtm, approved

#5572 ebs br: add resilience to single TiKV crash
  docs/api-references/docs.md
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_restores.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/apis/pingcap/v1alpha1/tidbcluster_test.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/backup/restore/restore_manager.go
Labels: size/M, approved, area/ebs-br

#5587 ebs br: add check wal warmup option
  manifests/crd.yaml
  manifests/federation-crd.yaml
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/backup/restore/restore_manager.go
  pkg/fedvolumebackup/restore/restore_manager.go
  pkg/fedvolumebackup/restore/restore_test.go
Labels: approved, size/XXL

#5588 Feat: support customizing the startup probe for TiDB
  docs/api-references/docs.md
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_tidbclusters.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tidb_member_manager_test.go
  tests/e2e/e2e.go
  tests/e2e/tidbcluster/tidbcluster.go
  tests/third_party/k8s/test_context.go
Labels: contribution, approved, size/L

#5592 pdms: replace pd image
  examples/basic/pd-micro-service-cluster.yaml
  tests/pkg/fixture/fixture.go
Labels: size/XS

#5566 warmup-image: test WAL files while warming up
  images/ebs-warmup/Dockerfile
  images/ebs-warmup/warmup-steps.sh
Labels: lgtm, approved, size/S, area/ebs-br

#5594 add nodeSelector support for TidbInitializer Pod
  docs/api-references/docs.md
  examples/initialize/tidb-initializer.yaml
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_tidbinitializers.yaml
  manifests/federation-crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbinitializer_types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/member/tidb_init_manager.go
Labels: size/XXL

#5597 fix: avoid tidb operator panic becuase of empty backup.Status.BackoffRetryStatus
  pkg/controller/backup/backup_controller.go
Labels: contribution, first-time-contributor, lgtm, approved, size/XS
