Repository pingcap/tidb-operator, pull requests merged in 2024-12, with the labels that each got.

#5958 add azure disk modifier
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/client/go.mod
  pkg/client/go.sum
  pkg/manager/volumes/delegation/azure/disk_modifier.go
  pkg/manager/volumes/delegation/azure/disk_modifier_test.go
  pkg/manager/volumes/pod_vol_modifier.go
Labels: lgtm, approved, size/XXL

#5964 opt: add LoadBalancerClass support for TiDB service
  docs/api-references/docs.md
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_dmclusters.yaml
  manifests/crd/v1/pingcap.com_tidbclusters.yaml
  manifests/crd/v1/pingcap.com_tidbdashboards.yaml
  manifests/crd/v1/pingcap.com_tidbmonitors.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/member/dm_master_member_manager.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tidb_member_manager_test.go
Labels: size/M, lgtm, approved

#5734 fix: type mismatch in TidbMonitor remoteTimeout
  docs/api-references/docs.md
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_tidbmonitors.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbmonitor_types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/monitor/monitor/monitor_manager_test.go
  pkg/monitor/monitor/util.go
  pkg/monitor/monitor/util_test.go
Labels: contribution, first-time-contributor, size/M, lgtm, approved

#5967 The backup cleaner can't clean the CR at the `schedule` phase before task start
  pkg/backup/backup/backup_cleaner.go
  tests/e2e/br/br.go
  tests/e2e/br/framework/br/wait.go
Labels: approved, size/L

#5976 fix typo in backup manifests
  manifests/backup/backup-aws-s3-br.yaml
  manifests/backup/backup-gcs-br.yaml
  manifests/backup/backup-s3-br.yaml
  manifests/backup/backup-schedule-aws-s3-br.yaml
  manifests/backup/backup-schedule-gcs-br.yaml
  manifests/backup/backup-schedule-s3-br.yaml
  manifests/backup/restore-aws-s3-br.yaml
  manifests/backup/restore-gcs-br.yaml
  manifests/backup/restore-s3-br.yaml
Labels: contribution, lgtm, approved, size/S

#5974 bump AWS SDK for EKS Pod Identity
  go.mod
  go.sum
Labels: size/M

#5981 chore(ci): use GitHub hosted runner to run actions
  .github/workflows/ci.yaml
  .github/workflows/e2e.yaml
Labels: size/M

#5982 chore: upload coverage to codecov
  .github/workflows/ci-v2.yaml
  Makefile
Labels: size/S

#5983 feat(pd): rename underlying resource names
  apis/core/v1alpha1/cluster_types.go
  apis/core/v1alpha1/pd_types.go
  apis/core/v1alpha1/tidb_types.go
  apis/core/v1alpha1/tiflash_types.go
  apis/core/v1alpha1/tikv_types.go
  pkg/configs/pd/config.go
  pkg/configs/tidb/config.go
  pkg/configs/tiflash/config.go
  pkg/configs/tikv/config.go
  pkg/controllers/cluster/tasks/status.go
  pkg/controllers/pd/tasks/cm.go
  pkg/controllers/pd/tasks/ctx.go
  pkg/controllers/pd/tasks/finalizer.go
  pkg/controllers/pd/tasks/pod.go
  pkg/controllers/pd/tasks/pvc.go
  pkg/controllers/pd/tasks/util.go
  pkg/controllers/pdgroup/tasks/svc.go
  pkg/controllers/pdgroup/tasks/updater.go
  pkg/controllers/pdgroup/tasks/util.go
  pkg/controllers/tidb/tasks/cm.go
  pkg/controllers/tidb/tasks/cm_test.go
  pkg/controllers/tidb/tasks/ctx.go
  pkg/controllers/tidb/tasks/finalizer.go
  pkg/controllers/tidb/tasks/pod.go
  pkg/controllers/tidb/tasks/pvc.go
  pkg/controllers/tidb/tasks/server_labels.go
  pkg/controllers/tidb/tasks/util.go
  pkg/controllers/tidbgroup/tasks/svc.go
  pkg/controllers/tidbgroup/tasks/updater.go
  pkg/controllers/tidbgroup/tasks/util.go
  pkg/controllers/tiflash/tasks/cm.go
  pkg/controllers/tiflash/tasks/ctx.go
  pkg/controllers/tiflash/tasks/finalizer.go
  pkg/controllers/tiflash/tasks/pod.go
  pkg/controllers/tiflash/tasks/pvc.go
  pkg/controllers/tiflash/tasks/store_labels.go
  pkg/controllers/tiflashgroup/tasks/svc.go
  pkg/controllers/tiflashgroup/tasks/updater.go
  pkg/controllers/tiflashgroup/tasks/util.go
  pkg/controllers/tikv/tasks/cm.go
  pkg/controllers/tikv/tasks/ctx.go
  pkg/controllers/tikv/tasks/finalizer.go
  pkg/controllers/tikv/tasks/pod.go
  pkg/controllers/tikv/tasks/pvc.go
  pkg/controllers/tikv/tasks/util.go
  pkg/controllers/tikvgroup/tasks/svc.go
  pkg/controllers/tikvgroup/tasks/updater.go
  pkg/controllers/tikvgroup/tasks/util.go
  pkg/runtime/group.go
  pkg/runtime/object.go
  pkg/runtime/pd.go
  pkg/runtime/tidb.go
  pkg/runtime/tiflash.go
  pkg/runtime/tikv.go
  pkg/timanager/pd/pd.go
  pkg/updater/builder.go
  pkg/utils/k8s/deletion.go
  tests/e2e/cluster/cluster.go
  tests/e2e/cluster/tls.go
Labels: size/XXL

#5984 chore: rename the branch to feature/v2; remove the E2E GHA
  .github/workflows/ci-v2.yaml
  .github/workflows/e2e.yaml
Labels: size/M

#5986 feat(instance): remove all group dep from instance controllers
  apis/core/v1alpha1/common_types.go
  apis/core/v1alpha1/pd_types.go
  apis/core/v1alpha1/tidb_types.go
  apis/core/v1alpha1/tiflash_types.go
  apis/core/v1alpha1/tikv_types.go
  apis/core/v1alpha1/zz_generated.deepcopy.go
  examples/bootstrap-sql/03-tidb.yaml
  examples/tls/03-tidb.yaml
  manifests/crd/core.pingcap.com_pdgroups.yaml
  manifests/crd/core.pingcap.com_pds.yaml
  manifests/crd/core.pingcap.com_tidbgroups.yaml
  manifests/crd/core.pingcap.com_tidbs.yaml
  manifests/crd/core.pingcap.com_tiflashes.yaml
  manifests/crd/core.pingcap.com_tiflashgroups.yaml
  manifests/crd/core.pingcap.com_tikvgroups.yaml
  manifests/crd/core.pingcap.com_tikvs.yaml
  pkg/configs/tidb/config.go
  pkg/controllers/pd/tasks/ctx.go
  pkg/controllers/pd/tasks/pod.go
  pkg/controllers/tidb/builder.go
  pkg/controllers/tidb/tasks/cm.go
  pkg/controllers/tidb/tasks/cm_test.go
  pkg/controllers/tidb/tasks/ctx.go
  pkg/controllers/tidb/tasks/pod.go
  pkg/controllers/tiflash/builder.go
  pkg/controllers/tiflash/tasks/ctx.go
  pkg/controllers/tiflash/tasks/pod.go
  pkg/controllers/tikv/builder.go
  pkg/controllers/tikv/tasks/ctx.go
  pkg/controllers/tikv/tasks/pod.go
  tests/e2e/cluster/cluster.go
Labels: size/XXL

#5989 chore(image): add more ut cases and comments
  pkg/image/image.go
  pkg/image/image_test.go
Labels: size/L

#5992 refactor(utils): add hasher pkg and add more uts for toml
  pkg/controllers/pd/tasks/cm.go
  pkg/controllers/tidb/tasks/cm.go
  pkg/controllers/tiflash/tasks/cm.go
  pkg/controllers/tikv/tasks/cm.go
  pkg/utils/hasher/hasher.go
  pkg/utils/hasher/hasher_test.go
  pkg/utils/toml/toml.go
  pkg/utils/toml/toml_test.go
Labels: size/XXL

#5985 chore: add E2E jenkins pipeline
  .github/licenserc.yaml
  Makefile
  ci/pull_e2e_kind_v2.groovy
  hack/lib/e2e.sh
Labels: size/XL

#5987 chore: install buildx for e2e image and bump Golang version
  tests/images/kubekins-e2e/Dockerfile
Labels: size/XS

#6000 chore(pd): add UT; update data path
  apis/core/v1alpha1/common_types.go
  manifests/crd/core.pingcap.com_pdgroups.yaml
  manifests/crd/core.pingcap.com_pds.yaml
  manifests/crd/core.pingcap.com_tidbgroups.yaml
  manifests/crd/core.pingcap.com_tidbs.yaml
  manifests/crd/core.pingcap.com_tiflashes.yaml
  manifests/crd/core.pingcap.com_tiflashgroups.yaml
  manifests/crd/core.pingcap.com_tikvgroups.yaml
  manifests/crd/core.pingcap.com_tikvs.yaml
  pkg/configs/pd/config.go
  pkg/configs/pd/config_test.go
Labels: size/L

#6006 chore: add UT for config pkg; mirror fix
  .gitignore
  apis/core/v1alpha1/tidb_types.go
  apis/core/v1alpha1/tikv_types.go
  pkg/configs/pd/config.go
  pkg/configs/pd/config_test.go
  pkg/configs/tidb/config.go
  pkg/configs/tidb/config_test.go
  pkg/configs/tiflash/config.go
  pkg/configs/tiflash/config_test.go
  pkg/configs/tiflash/proxy_config_test.go
  pkg/configs/tikv/config.go
  pkg/configs/tikv/config_test.go
  pkg/controllers/tidb/tasks/pod.go
Labels: size/XXL

#6007 chore: bump some go mod and binaries for security
  cmd/http-service/go.mod
  cmd/http-service/go.sum
  go.mod
  go.sum
  images/tidb-backup-manager/Dockerfile
  images/tidb-backup-manager/Dockerfile.e2e
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/client/go.mod
  pkg/client/go.sum
Labels: size/L

#6005 Fix(e2e): run a mysql client in kind to test graceful shutdown case
  cmd/testing-workload/main.go
  hack/lib/build.sh
  hack/lib/e2e.sh
  image/Dockerfile
  pkg/configs/tidb/config.go
  pkg/controllers/tidb/tasks/cm_test.go
  tests/e2e/cluster/cluster.go
  tests/e2e/utils/tidb/tidb.go
Labels: contribution, size/XL

#6009 chore: add some UT for some pkgs
  Makefile
  pkg/action/upgrader_test.go
  pkg/overlay/overlay_test.go
  pkg/pdapi/pd/duration.go
  pkg/pdapi/pd/duration_test.go
  pkg/pdapi/pd/size_test.go
Labels: size/L

#6010 feat(common): add ut for common tasks and refactor task utils
  pkg/client/alias.go
  pkg/client/fake.go
  pkg/controllers/cluster/tasks/finalizer_test.go
  pkg/controllers/common/cond.go
  pkg/controllers/common/cond_test.go
  pkg/controllers/common/interfaces.go
  pkg/controllers/common/interfaces_test.go
  pkg/controllers/common/resource.go
  pkg/controllers/common/resource_test.go
  pkg/controllers/common/task.go
  pkg/controllers/common/task_test.go
  pkg/controllers/pd/builder.go
  pkg/controllers/pd/controller.go
  pkg/controllers/pd/tasks/cm.go
  pkg/controllers/pd/tasks/ctx.go
  pkg/controllers/pd/tasks/finalizer.go
  pkg/controllers/pd/tasks/pod.go
  pkg/controllers/pd/tasks/pvc.go
  pkg/controllers/pd/tasks/state.go
  pkg/controllers/pd/tasks/status.go
  pkg/utils/fake/fake.go
  pkg/utils/task/v3/runner.go
  pkg/utils/task/v3/runner_test.go
  pkg/utils/task/v3/task.go
  pkg/utils/task/v3/task_test.go
Labels: size/XXL

#6012 chore: add UT for PD/TiKV/TiDB/TiFlash APIs
  pkg/pdapi/v1/client_test.go
  pkg/tidbapi/v1/client_test.go
  pkg/tidbapi/v1/control.go
  pkg/tidbapi/v1/control_test.go
  pkg/tiflashapi/v1/client_test.go
  pkg/tiflashapi/v1/control.go
  pkg/tiflashapi/v1/control_test.go
  pkg/tikvapi/v1/client_test.go
  pkg/tikvapi/v1/control.go
  pkg/tikvapi/v1/control_test.go
Labels: size/XXL

#6017 chore: more UTs for some pkgs
  pkg/timanager/apis/pd/v1/types_test.go
  pkg/timanager/pd/pd.go
  pkg/timanager/pd/pd_test.go
  pkg/timanager/util_test.go
  pkg/updater/actor.go
  pkg/updater/builder_test.go
  pkg/updater/policy/topology_test.go
  pkg/utils/k8s/deletion.go
  pkg/utils/k8s/deletion_test.go
  pkg/utils/k8s/finalizer_test.go
  pkg/utils/k8s/node_test.go
  pkg/utils/k8s/pod_test.go
  pkg/utils/k8s/revision/controller_revision_test.go
  pkg/utils/kubefeat/gates.go
  pkg/utils/kubefeat/gates_test.go
  pkg/utils/map/map_test.go
  pkg/version/version_test.go
  pkg/volumes/native_modifer_test.go
  pkg/volumes/raw_modifier_test.go
  pkg/volumes/utils_test.go
Labels: size/XXL

#6019 chore: partials_as_hits for codecov
  .codecov.yml
Labels: size/S
