Repository pingcap/tidb-operator, pull requests merged in 2024-02, with the labels that each got.

#5535 pdms: support pv for log
  docs/api-references/docs.md
  examples/basic/pd-micro-service-cluster.yaml
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_tidbclusters.yaml
  pkg/apis/pingcap/v1alpha1/component_status.go
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/validation/validation.go
  pkg/apis/pingcap/v1alpha1/validation/validation_test.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/tidbcluster/tidb_cluster_controller.go
  pkg/manager/member/constants/constants.go
  pkg/manager/member/pd_ms_member_manager.go
  pkg/manager/member/pd_ms_member_manager_test.go
  pkg/manager/member/pvc_resizer.go
  pkg/manager/member/startscript/v1/render_script.go
  pkg/manager/member/startscript/v1/template.go
  pkg/manager/member/startscript/v2/pd_start_script.go
  pkg/manager/volumes/vol_compare_utils.go
  pkg/util/utils_test.go
Labels: lgtm, approved, size/XL

#5541 pdms: make pdms tls reusing pd tls
  pkg/manager/member/pd_ms_member_manager.go
  pkg/pdapi/pd_control.go
Labels: lgtm, approved, size/S

#5542 pdms: fix tls config is nil
  pkg/manager/member/pd_ms_member_manager.go
  pkg/manager/member/pd_ms_member_manager_test.go
Labels: lgtm, approved, size/L

#5534 br: add metrics for volume backup
  cmd/backup-manager/app/clean/manager.go
  pkg/apis/federation/pingcap/v1alpha1/types.go
  pkg/apis/federation/pingcap/v1alpha1/volume_backup.go
  pkg/apis/pingcap/v1alpha1/backup.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/controller/fedvolumebackup/fed_volume_backup_control.go
  pkg/fedvolumebackup/backup/backup_manager.go
  pkg/metrics/brfederation.go
Labels: approved, size/L, area/ebs-br

#5547 pdms: change get ms members return value
  pkg/pdapi/pdapi.go
Labels: lgtm, approved, size/S

#5544 fix: minreadyseconds for last TiKV
  pkg/manager/member/tikv_upgrader.go
Labels: contribution, first-time-contributor, size/M, lgtm, approved

#5536 Add capabilities: 1) bind tidb-dashboard only to localhost; 2) disable keyVisualizer
  cmd/http-service/go.sum
  docs/api-references/docs.md
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_tidbdashboards.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbdashboard_types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/tidbdashboard/manager.go
Labels: contribution, lgtm, approved, size/XXL

#5555 tiproxy: fix http tls when only tls cluster is enabled
  pkg/manager/member/tiproxy_member_manager.go
Labels: lgtm, approved, size/S

#5556 [fix] Tidb-dashboard: cmd line arg keyVisualizer renamed to keyviz
  pkg/manager/tidbdashboard/manager.go
Labels: contribution, lgtm, approved, size/XS

#5554 pdms: remove shutdown component and add test for scaler&upgrader
  pkg/manager/member/pd_ms_member_manager.go
  pkg/manager/member/pd_ms_member_manager_test.go
  pkg/manager/member/pd_ms_scaler.go
  pkg/manager/member/pd_ms_scaler_test.go
  pkg/manager/member/pd_ms_upgrader.go
  pkg/manager/member/pd_ms_upgrader_test.go
  pkg/manager/member/pd_upgrader_test.go
Labels: lgtm, approved, size/XXL

#5558 pdms: rename pdms-`service` to `service`
  pkg/apis/label/label.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/controller/controller_utils.go
  pkg/manager/member/pd_ms_member_manager_test.go
  pkg/manager/volumes/selector_test.go
  pkg/monitor/monitor/template.go
  pkg/monitor/monitor/template_test.go
  pkg/pdapi/pd_control.go
Labels: approved, size/L
