Repository pingcap/tidb-operator, pull requests merged in 2024-06, with the labels that each got.

#5659 ebs br: enhance TC validation
  pkg/backup/backup/backup_manager.go
  pkg/backup/backup/backup_test.go
  pkg/backup/testutils/helpers.go
  pkg/backup/util/util.go
  pkg/backup/util/utils_test.go
Labels: type/cherry-pick-for-release-1.5, approved, size/L, area/ebs-br, type/cherry-pick-for-release-1.6

#5667 Adding support for logRestoreStartTs option in PITR restore spec
  cmd/backup-manager/app/restore/restore.go
  docs/api-references/docs.md
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/backup/util/util.go
Labels: contribution, first-time-contributor, size/M, lgtm, approved

#5670 tc level flag to enablePVCReplace feature
  docs/api-references/docs.md
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_tidbclusters.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/tidbcluster/tidb_cluster_control.go
Labels: contribution, first-time-contributor, size/M, lgtm, approved

#5666 Add support to customize spare replicas during VolumeReplace
  docs/api-references/docs.md
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_tidbclusters.yaml
  pkg/apis/pingcap/v1alpha1/defaulting/tidbcluster.go
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/member/tikv_member_manager_test.go
Labels: contribution, lgtm, approved, size/L
