Repository pingcap/tidb-operator, pull requests merged in 2024-10, with the labels that each got.

#5755 fix: fix slice init length
  pkg/autoscaler/autoscaler/pdplan_autoscaler.go
Labels: contribution, first-time-contributor, lgtm, approved, size/XS

#5758 e2e: disable coverage upload
  ci/pull_e2e_kind.groovy
Labels: size/S

#5710 br: a more straight forward operator interface
  cmd/backup-manager/app/backup/backup.go
  cmd/backup-manager/app/backup/manager.go
  docs/api-references/docs.md
  hack/local-up-operator.sh
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_backups.yaml
  manifests/crd/v1/pingcap.com_backupschedules.yaml
  manifests/federation-crd.yaml
  pkg/apis/pingcap/v1alpha1/backup.go
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/backup/backup/backup_manager.go
  pkg/controller/backup/backup_controller.go
  pkg/controller/backup_status_updater.go
  tests/e2e/br/br.go
Labels: tools/br, first-time-contributor, needs-update-docs, lgtm, approved, size/XXL

#5735 br: modify vbk failed when all backups are complete or failed
  pkg/fedvolumebackup/backup/backup_manager.go
  pkg/fedvolumebackup/backup/backup_test.go
Labels: size/M, approved, area/ebs-br

#5763 ci: use kubetest2 hosted in pingcap/tidb-operator
  hack/lib.sh
Labels: size/XS

#5754 Stop the running log backup when deleting CR
  cmd/backup-manager/app/backup/manager.go
  hack/e2e-patch-codecov.sh
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_backups.yaml
  manifests/crd/v1/pingcap.com_backupschedules.yaml
  pkg/apis/pingcap/v1alpha1/backup.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/backup/backup/backup_cleaner.go
  pkg/controller/backup/backup_control.go
  tests/e2e/br/br.go
Labels: lgtm, approved, size/XXL

#5769 ci: update the tag used for kubetest2
  hack/lib.sh
Labels: size/XS

#5773 ci: unset GOSUMDB for "Debug Info"
  ci/pull_e2e_kind.groovy
Labels: size/XS

#5772 sec: bump Golang and some mod for security
  cmd/backup-manager/app/export/export.go
  cmd/backup-manager/app/import/import.go
  cmd/http-service/go.mod
  cmd/http-service/go.sum
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/client/go.mod
  pkg/client/go.sum
Labels: size/L

#5778 opt(ticdc): support to overwrite the default cluster TLS cert secret name
  docs/api-references/docs.md
  manifests/crd/v1/pingcap.com_tidbclusters.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/manager/member/ticdc_member_manager.go
Labels: contribution, size/M, lgtm, approved

#5823 Revert "opt(ticdc): support to overwrite the default cluster TLS cert secret name"
  docs/api-references/docs.md
  manifests/crd/v1/pingcap.com_tidbclusters.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/manager/member/ticdc_member_manager.go
Labels: contribution, size/M, lgtm, approved

#5826 TidbCluster: disable evict leader for TiKV EBS modification
  pkg/manager/volumes/vol_compare_utils.go
Labels: size/XS

#5827 feat(minReadySeconds): support minReadySeconds for PD
  pkg/manager/member/pd_upgrader.go
  pkg/manager/member/pd_upgrader_test.go
Labels: size/M
