Repository pingcap/tidb-operator, pull requests merged in 2024-01, with the labels that each got.

#5494 bump K8s to v1.26.12
  cmd/http-service/go.mod
  cmd/http-service/go.sum
  docs/api-references/config.json
  docs/api-references/docs.md
  docs/api-references/federation-docs.md
  go.mod
  go.sum
  hack/e2e.sh
  hack/lib.sh
  manifests/crd.yaml
  manifests/crd/federation/v1/federation.pingcap.com_volumebackups.yaml
  manifests/crd/federation/v1/federation.pingcap.com_volumebackupschedules.yaml
  manifests/crd/federation/v1/federation.pingcap.com_volumerestores.yaml
  manifests/crd/v1/pingcap.com_backups.yaml
  manifests/crd/v1/pingcap.com_backupschedules.yaml
  manifests/crd/v1/pingcap.com_dmclusters.yaml
  manifests/crd/v1/pingcap.com_restores.yaml
  manifests/crd/v1/pingcap.com_tidbclusters.yaml
  manifests/crd/v1/pingcap.com_tidbdashboards.yaml
  manifests/crd/v1/pingcap.com_tidbinitializers.yaml
  manifests/crd/v1/pingcap.com_tidbmonitors.yaml
  manifests/crd/v1/pingcap.com_tidbngmonitorings.yaml
  manifests/federation-crd.yaml
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/federation/clientset/versioned/clientset.go
  pkg/client/federation/informers/externalversions/factory.go
  pkg/client/go.mod
  pkg/client/go.sum
  pkg/client/informers/externalversions/factory.go
  tests/images/e2e/Dockerfile
  tests/images/stability-test/Dockerfile
Labels: size/XXL

#5259 *: add missing tiproxy label
  pkg/apis/pingcap/v1alpha1/component_spec.go
Labels: type/cherry-pick-for-release-1.5, lgtm, approved, size/XS

#5491 ebs br: resume gc and pd schedule asap if data plane backup fails
  pkg/fedvolumebackup/backup/backup_manager.go
Labels: approved, size/XS, area/ebs-br

#5490 ebs br: expose the volumebackup init pod ttl as a crd attribute
  docs/api-references/docs.md
  docs/api-references/federation-docs.md
  manifests/crd.yaml
  manifests/crd/federation/v1/federation.pingcap.com_volumebackups.yaml
  manifests/crd/federation/v1/federation.pingcap.com_volumebackupschedules.yaml
  manifests/crd/v1/pingcap.com_backups.yaml
  manifests/crd/v1/pingcap.com_backupschedules.yaml
  manifests/federation-crd.yaml
  pkg/apis/federation/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/federation/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/backup/backup/backup_manager.go
  pkg/fedvolumebackup/backup/backup_manager.go
Labels: size/M, approved, area/ebs-br

#5498 ebs br: expose the volumebackup init pod ttl as a crd attribute (#5490)
  docs/api-references/docs.md
  docs/api-references/federation-docs.md
  manifests/crd.yaml
  manifests/crd/federation/v1/federation.pingcap.com_volumebackups.yaml
  manifests/crd/federation/v1/federation.pingcap.com_volumebackupschedules.yaml
  manifests/crd/federation/v1beta1/federation.pingcap.com_volumebackups.yaml
  manifests/crd/federation/v1beta1/federation.pingcap.com_volumebackupschedules.yaml
  manifests/crd/v1/pingcap.com_backups.yaml
  manifests/crd/v1/pingcap.com_backupschedules.yaml
  manifests/crd/v1beta1/pingcap.com_backups.yaml
  manifests/crd/v1beta1/pingcap.com_backupschedules.yaml
  manifests/crd_v1beta1.yaml
  manifests/federation-crd.yaml
  manifests/federation-crd_v1beta1.yaml
  pkg/apis/federation/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/federation/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/backup/backup/backup_manager.go
  pkg/fedvolumebackup/backup/backup_manager.go
Labels: size/L, area/ebs-br

#5500 br: set volume backup failed if one data plane failed
  pkg/fedvolumebackup/backup/backup_manager.go
Labels: lgtm, approved, size/S, area/ebs-br

#5495 bump K8s to v1.28.5
  cmd/admission-webhook/main.go
  cmd/http-service/go.mod
  cmd/http-service/go.sum
  docs/api-references/config.json
  docs/api-references/docs.md
  docs/api-references/federation-docs.md
  go.mod
  go.sum
  hack/e2e.sh
  hack/lib.sh
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_dmclusters.yaml
  manifests/crd/v1/pingcap.com_tidbclusters.yaml
  manifests/crd/v1/pingcap.com_tidbdashboards.yaml
  manifests/crd/v1/pingcap.com_tidbinitializers.yaml
  manifests/crd/v1/pingcap.com_tidbmonitors.yaml
  manifests/crd/v1/pingcap.com_tidbngmonitorings.yaml
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/pingcap/v1alpha1/fake/fake_backup.go
  pkg/client/clientset/versioned/typed/pingcap/v1alpha1/fake/fake_backupschedule.go
  pkg/client/clientset/versioned/typed/pingcap/v1alpha1/fake/fake_dataresource.go
  pkg/client/clientset/versioned/typed/pingcap/v1alpha1/fake/fake_dmcluster.go
  pkg/client/clientset/versioned/typed/pingcap/v1alpha1/fake/fake_restore.go
  pkg/client/clientset/versioned/typed/pingcap/v1alpha1/fake/fake_tidbcluster.go
  pkg/client/clientset/versioned/typed/pingcap/v1alpha1/fake/fake_tidbclusterautoscaler.go
  pkg/client/clientset/versioned/typed/pingcap/v1alpha1/fake/fake_tidbdashboard.go
  pkg/client/clientset/versioned/typed/pingcap/v1alpha1/fake/fake_tidbinitializer.go
  pkg/client/clientset/versioned/typed/pingcap/v1alpha1/fake/fake_tidbmonitor.go
  pkg/client/clientset/versioned/typed/pingcap/v1alpha1/fake/fake_tidbngmonitoring.go
  pkg/client/federation/clientset/versioned/typed/pingcap/v1alpha1/fake/fake_volumebackup.go
  pkg/client/federation/clientset/versioned/typed/pingcap/v1alpha1/fake/fake_volumebackupschedule.go
  pkg/client/federation/clientset/versioned/typed/pingcap/v1alpha1/fake/fake_volumerestore.go
  pkg/client/federation/informers/externalversions/factory.go
  pkg/client/go.mod
  pkg/client/go.sum
  pkg/client/informers/externalversions/factory.go
  tests/images/e2e/Dockerfile
  tests/images/stability-test/Dockerfile
Labels: size/XXL

#5445 br: Add annotations for warmup pod
  pkg/backup/restore/restore_manager.go
Labels: contribution, approved, size/S, area/ebs-br

#5514 fips: adjust version suffix (#5512)
  pkg/fips/fips.go
  pkg/version/version.go
Labels: lgtm, approved, size/S

#5513 fips: adjust version suffix (#5512)
  pkg/fips/fips.go
  pkg/version/version.go
Labels: lgtm, approved, size/S

#5512 fips: adjust version suffix
  pkg/fips/fips.go
  pkg/version/version.go
Labels: lgtm, approved, size/S

#5492 ebs br: backoff support for snapshots deletion
  cmd/backup-manager/app/clean/clean.go
  docs/api-references/docs.md
  docs/api-references/federation-docs.md
  go.mod
  manifests/crd.yaml
  manifests/crd/federation/v1/federation.pingcap.com_volumebackups.yaml
  manifests/crd/federation/v1/federation.pingcap.com_volumebackupschedules.yaml
  manifests/crd/v1/pingcap.com_backups.yaml
  manifests/crd/v1/pingcap.com_backupschedules.yaml
  manifests/federation-crd.yaml
  pkg/apis/federation/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/federation/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/backup/util/aws_ebs.go
  pkg/fedvolumebackup/backup/backup_manager.go
  pkg/fedvolumebackup/backupschedule/backup_schedule_manager.go
Labels: approved, size/L, area/ebs-br

#5516 ebs br: backoff support for snapshots deletion (#5492)
  cmd/backup-manager/app/clean/clean.go
  docs/api-references/docs.md
  docs/api-references/federation-docs.md
  go.mod
  manifests/crd.yaml
  manifests/crd/federation/v1/federation.pingcap.com_volumebackups.yaml
  manifests/crd/federation/v1/federation.pingcap.com_volumebackupschedules.yaml
  manifests/crd/federation/v1beta1/federation.pingcap.com_volumebackups.yaml
  manifests/crd/federation/v1beta1/federation.pingcap.com_volumebackupschedules.yaml
  manifests/crd/v1/pingcap.com_backups.yaml
  manifests/crd/v1/pingcap.com_backupschedules.yaml
  manifests/crd/v1beta1/pingcap.com_backups.yaml
  manifests/crd/v1beta1/pingcap.com_backupschedules.yaml
  manifests/crd_v1beta1.yaml
  manifests/federation-crd.yaml
  manifests/federation-crd_v1beta1.yaml
  pkg/apis/federation/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/federation/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/backup/util/aws_ebs.go
  pkg/fedvolumebackup/backup/backup_manager.go
  pkg/fedvolumebackup/backupschedule/backup_schedule_manager.go
Labels: type/cherry-pick-for-release-1.5, size/L, area/ebs-br

#5519 Fixing volume tagging
  cmd/backup-manager/app/clean/clean.go
  pkg/backup/restore/restore_manager.go
  pkg/backup/snapshotter/snapshotter.go
  pkg/backup/snapshotter/snapshotter_aws.go
  pkg/backup/snapshotter/snapshotter_test.go
Labels: size/M, approved, area/ebs-br

#5518 Use CreationTimestamp of volumebackup for gc check
  pkg/fedvolumebackup/backupschedule/backup_schedule_manager.go
  pkg/fedvolumebackup/backupschedule/backup_schedule_manager_test.go
Labels: size/M, approved, area/ebs-br

#5525 ebs: adjust volume tagging
  pkg/backup/snapshotter/snapshotter_aws.go
Labels: type/bug, lgtm, approved, size/S, area/ebs-br
