Repository pingcap/tidb-operator, pull requests merged in 2025-08, with the labels that each got.

#6326 Fix ticdc's order of version upgrade
  pkg/action/upgrader.go
  pkg/action/upgrader_test.go
  pkg/client/fake.go
  pkg/controllers/ticdcgroup/tasks/updater_test.go
  pkg/runtime/group.go
  pkg/runtime/instance.go
Labels: lgtm, approved, size/XL, v2

#6363 Fix: add VolumeAttributesClass feature gate check in PVC creation
  pkg/controllers/pd/tasks/pvc.go
  pkg/controllers/pd/tasks/pvc_test.go
  pkg/controllers/scheduler/tasks/pvc.go
  pkg/controllers/ticdc/tasks/pvc.go
  pkg/controllers/ticdc/tasks/pvc_test.go
  pkg/controllers/tidb/tasks/pvc.go
  pkg/controllers/tidb/tasks/pvc_test.go
  pkg/controllers/tiflash/tasks/pvc.go
  pkg/controllers/tiflash/tasks/pvc_test.go
  pkg/controllers/tikv/tasks/pvc.go
  pkg/controllers/tikv/tasks/pvc_test.go
  pkg/controllers/tiproxy/tasks/pvc.go
  pkg/controllers/tiproxy/tasks/pvc_test.go
  pkg/controllers/tso/tasks/pvc.go
Labels: lgtm, approved, size/L, v2

#6355 Feat: support offline tikv/tiflash store
  api/core/v1alpha1/common_types.go
  api/core/v1alpha1/tiflash_types.go
  api/core/v1alpha1/tikv_types.go
  cmd/runtime-gen/generators/runtime.go
  go.mod
  go.sum
  go.work.sum
  manifests/crd/core.pingcap.com_tiflashes.yaml
  manifests/crd/core.pingcap.com_tikvs.yaml
  pkg/controllers/common/store_offline.go
  pkg/controllers/common/store_offline_mock_generated.go
  pkg/controllers/common/store_offline_test.go
  pkg/controllers/tiflash/tasks/ctx.go
  pkg/controllers/tiflash/tasks/finalizer.go
  pkg/controllers/tiflash/tasks/offline.go
  pkg/controllers/tikv/tasks/ctx.go
  pkg/controllers/tikv/tasks/finalizer.go
  pkg/controllers/tikv/tasks/offline.go
  pkg/controllers/tikv/tasks/status.go
  pkg/pdapi/v1/client.go
  pkg/pdapi/v1/client_test.go
  pkg/pdapi/v1/mock_generated.go
  pkg/runtime/instance.go
  pkg/runtime/instance_mock_generated.go
  pkg/runtime/zz_generated.runtime.pd.go
  pkg/runtime/zz_generated.runtime.scheduler.go
  pkg/runtime/zz_generated.runtime.ticdc.go
  pkg/runtime/zz_generated.runtime.tidb.go
  pkg/runtime/zz_generated.runtime.tiflash.go
  pkg/runtime/zz_generated.runtime.tikv.go
  pkg/runtime/zz_generated.runtime.tiproxy.go
  pkg/runtime/zz_generated.runtime.tso.go
  tests/e2e/data/pd.go
  tests/e2e/tikv/tikv.go
  tests/e2e/utils/waiter/tikv.go
Labels: lgtm, approved, size/XXL, v2

#6378 Chore: add a go program to verify feature gates
  Makefile
  cmd/verify-feature-gates/main.go
  pkg/features/reload.go
Labels: lgtm, approved, size/XL, v2

#6389 fix(security): update go.mod
  api/go.mod
  api/go.sum
  cmd/tidb-backup-manager/app/clean/clean.go
  go.mod
  go.sum
  go.work.sum
  tests/validation/go.mod
  tests/validation/go.sum
Labels: lgtm, approved, size/L, v2

#6392 fix(security): update go.mod
  api/go.mod
  api/go.sum
  cmd/tidb-backup-manager/app/clean/clean.go
  go.mod
  go.sum
  go.work.sum
  tests/validation/go.mod
  tests/validation/go.sum
Labels: lgtm, approved, size/XXL

#6393 fix(ci): also run ci in release-2.0 branch
  .github/workflows/ci-v2.yaml
Labels: lgtm, approved, size/S, v2

#6386 feat(tidb): support sem config
  api/core/v1alpha1/names.go
  api/core/v1alpha1/tidb_types.go
  api/core/v1alpha1/zz_generated.deepcopy.go
  manifests/crd/core.pingcap.com_tidbgroups.yaml
  manifests/crd/core.pingcap.com_tidbs.yaml
  pkg/apiutil/core/v1alpha1/tidb.go
  pkg/configs/tidb/config.go
  pkg/configs/tidb/config_test.go
  pkg/controllers/tidb/tasks/pod.go
Labels: lgtm, approved, size/L, v2

#6395 fix(group): ensure feature gates should sync before reconciling
  pkg/controllers/common/task.go
  pkg/controllers/pdgroup/builder.go
  pkg/controllers/replicationworkergroup/builder.go
  pkg/controllers/schedulergroup/builder.go
  pkg/controllers/ticdcgroup/builder.go
  pkg/controllers/tidbgroup/builder.go
  pkg/controllers/tiflashgroup/builder.go
  pkg/controllers/tikvgroup/builder.go
  pkg/controllers/tiproxygroup/builder.go
  pkg/controllers/tsogroup/builder.go
Labels: size/M, lgtm, approved, v2

#6396 fix(updater): defer delete instance should not be counted as update
  pkg/updater/builder.go
Labels: lgtm, approved, size/XS, v2

#6402 fix(instance): fix unexpected unready condition
  pkg/apiutil/core/v1alpha1/group.go
  pkg/controllers/pd/tasks/status.go
  pkg/controllers/scheduler/tasks/status.go
  pkg/controllers/ticdc/tasks/status.go
  pkg/controllers/tidb/tasks/status.go
  pkg/controllers/tiflash/builder.go
  pkg/controllers/tiflash/tasks/state.go
  pkg/controllers/tiflash/tasks/status.go
  pkg/controllers/tikv/builder.go
  pkg/controllers/tikv/tasks/ctx.go
  pkg/controllers/tikv/tasks/state.go
  pkg/controllers/tikv/tasks/status.go
  pkg/controllers/tikv/tasks/status_test.go
  pkg/controllers/tiproxy/tasks/status.go
  pkg/controllers/tso/tasks/status.go
  pkg/updater/builder.go
  pkg/updater/executor.go
  pkg/updater/executor_test.go
  pkg/utils/compare/compare.go
  pkg/utils/compare/compare_test.go
Labels: lgtm, approved, size/XL, v2

#6408 Fix CI in the release branch
  go.work.sum
Labels: lgtm, approved, size/L

#6390 Feat: add VolumeAttributesClassName validation rule
  api/core/v1alpha1/common_types.go
  go.work.sum
  manifests/crd/br.pingcap.com_tibrgcs.yaml
  manifests/crd/br.pingcap.com_tibrs.yaml
  manifests/crd/core.pingcap.com_pdgroups.yaml
  manifests/crd/core.pingcap.com_pds.yaml
  manifests/crd/core.pingcap.com_replicationworkergroups.yaml
  manifests/crd/core.pingcap.com_replicationworkers.yaml
  manifests/crd/core.pingcap.com_schedulergroups.yaml
  manifests/crd/core.pingcap.com_schedulers.yaml
  manifests/crd/core.pingcap.com_ticdcgroups.yaml
  manifests/crd/core.pingcap.com_ticdcs.yaml
  manifests/crd/core.pingcap.com_tidbgroups.yaml
  manifests/crd/core.pingcap.com_tidbs.yaml
  manifests/crd/core.pingcap.com_tiflashes.yaml
  manifests/crd/core.pingcap.com_tiflashgroups.yaml
  manifests/crd/core.pingcap.com_tikvgroups.yaml
  manifests/crd/core.pingcap.com_tikvs.yaml
  manifests/crd/core.pingcap.com_tiproxies.yaml
  manifests/crd/core.pingcap.com_tiproxygroups.yaml
  manifests/crd/core.pingcap.com_tsogroups.yaml
  manifests/crd/core.pingcap.com_tsos.yaml
  tests/validation/common_test.go
  tests/validation/pd_test.go
  tests/validation/replication_worker_test.go
  tests/validation/scheduler_test.go
  tests/validation/tiflash_test.go
  tests/validation/tikv_test.go
  tests/validation/tso_test.go
Labels: lgtm, approved, size/XL, v2

#6410 Feat: add VolumeAttributesClassName validation rule
  api/core/v1alpha1/common_types.go
  go.work.sum
  manifests/crd/br.pingcap.com_tibrs.yaml
  manifests/crd/core.pingcap.com_pdgroups.yaml
  manifests/crd/core.pingcap.com_pds.yaml
  manifests/crd/core.pingcap.com_schedulergroups.yaml
  manifests/crd/core.pingcap.com_schedulers.yaml
  manifests/crd/core.pingcap.com_ticdcgroups.yaml
  manifests/crd/core.pingcap.com_ticdcs.yaml
  manifests/crd/core.pingcap.com_tidbgroups.yaml
  manifests/crd/core.pingcap.com_tidbs.yaml
  manifests/crd/core.pingcap.com_tiflashes.yaml
  manifests/crd/core.pingcap.com_tiflashgroups.yaml
  manifests/crd/core.pingcap.com_tikvgroups.yaml
  manifests/crd/core.pingcap.com_tikvs.yaml
  manifests/crd/core.pingcap.com_tiproxies.yaml
  manifests/crd/core.pingcap.com_tiproxygroups.yaml
  manifests/crd/core.pingcap.com_tsogroups.yaml
  manifests/crd/core.pingcap.com_tsos.yaml
  tests/validation/common_test.go
  tests/validation/pd_test.go
  tests/validation/scheduler_test.go
  tests/validation/tiflash_test.go
  tests/validation/tikv_test.go
  tests/validation/tso_test.go
  tests/validation/validation.go
Labels: lgtm, approved, size/XL

#6413 Fix(image): use fixed user id instead of username
  charts/tidb-operator/values.yaml
  image/Dockerfile
Labels: lgtm, approved, size/S, v2
