Repository pingcap/tidb-operator, pull requests merged in 2025-03, with the labels that each got.

#6087 ebs br: fail the ebs volume backup when some backup member tc is invalid
  pkg/backup/backup/backup_manager.go
  pkg/backup/backupschedule/backup_schedule_manager.go
  pkg/backup/backupschedule/backup_schedule_manager_test.go
  pkg/controller/backup/backup_controller.go
  pkg/fedvolumebackup/backup/backup_manager.go
  pkg/fedvolumebackup/backup/backup_test.go
  pkg/fedvolumebackup/backupschedule/backup_schedule_manager_test.go
Labels: tools/br, lgtm, approved, size/L, area/ebs-br

#6106 feat(crd): remove unused required constraints of overlay from crd
  Makefile
  api/core/v1alpha1/pd_types.go
  api/core/v1alpha1/ticdc_types.go
  api/core/v1alpha1/tidb_types.go
  api/core/v1alpha1/tiflash_types.go
  api/core/v1alpha1/tikv_types.go
  cmd/crd-modifier/main.go
  go.mod
  manifests/crd/core.pingcap.com_pdgroups.yaml
  manifests/crd/core.pingcap.com_pds.yaml
  manifests/crd/core.pingcap.com_ticdcgroups.yaml
  manifests/crd/core.pingcap.com_ticdcs.yaml
  manifests/crd/core.pingcap.com_tidbgroups.yaml
  manifests/crd/core.pingcap.com_tidbs.yaml
  manifests/crd/core.pingcap.com_tiflashes.yaml
  manifests/crd/core.pingcap.com_tiflashgroups.yaml
  manifests/crd/core.pingcap.com_tikvgroups.yaml
  manifests/crd/core.pingcap.com_tikvs.yaml
  tests/validation/crd/core.pingcap.com_pdgroups.yaml
  tests/validation/crd/core.pingcap.com_pds.yaml
  tests/validation/crd/core.pingcap.com_ticdcgroups.yaml
  tests/validation/crd/core.pingcap.com_ticdcs.yaml
  tests/validation/crd/core.pingcap.com_tidbgroups.yaml
  tests/validation/crd/core.pingcap.com_tidbs.yaml
  tests/validation/crd/core.pingcap.com_tiflashes.yaml
  tests/validation/crd/core.pingcap.com_tiflashgroups.yaml
  tests/validation/crd/core.pingcap.com_tikvgroups.yaml
  tests/validation/crd/core.pingcap.com_tikvs.yaml
Labels: lgtm, approved, size/XXL, v2

#6110 fix(overlay): add test for example and fix overlay issue
  .github/licenserc.yaml
  Makefile
  api/core/v1alpha1/pd_types.go
  api/core/v1alpha1/ticdc_types.go
  api/core/v1alpha1/tidb_types.go
  api/core/v1alpha1/tiflash_types.go
  api/core/v1alpha1/tikv_types.go
  examples/basic/03-tidb.yaml
  examples/basic/04-tiflash.yaml
  go.mod
  go.sum
  manifests/crd/core.pingcap.com_pdgroups.yaml
  manifests/crd/core.pingcap.com_pds.yaml
  manifests/crd/core.pingcap.com_ticdcgroups.yaml
  manifests/crd/core.pingcap.com_ticdcs.yaml
  manifests/crd/core.pingcap.com_tidbgroups.yaml
  manifests/crd/core.pingcap.com_tidbs.yaml
  manifests/crd/core.pingcap.com_tiflashes.yaml
  manifests/crd/core.pingcap.com_tiflashgroups.yaml
  manifests/crd/core.pingcap.com_tikvgroups.yaml
  manifests/crd/core.pingcap.com_tikvs.yaml
  pkg/client/client.go
  pkg/controllers/common/revision_test.go
  pkg/controllers/tidbgroup/tasks/state_test.go
  pkg/controllers/tiflashgroup/tasks/state_test.go
  tests/e2e/e2e_test.go
  tests/e2e/example/data
  tests/e2e/example/example.go
  tests/e2e/framework/cluster.go
  tests/e2e/framework/framework.go
  tests/e2e/framework/tiflash.go
  tests/e2e/label/well_known.go
  tests/e2e/tidb/tidb.go
  tests/e2e/utils/cert/cert.go
  tests/e2e/utils/waiter/tiflash.go
  tests/e2e/utils/yaml/yaml.go
  tests/validation/crd
  tests/validation/crd/br.pingcap.com_backups.yaml
  tests/validation/crd/br.pingcap.com_backupschedules.yaml
  tests/validation/crd/br.pingcap.com_compactbackups.yaml
  tests/validation/crd/br.pingcap.com_restores.yaml
  tests/validation/crd/core.pingcap.com_clusters.yaml
  tests/validation/crd/core.pingcap.com_pdgroups.yaml
  tests/validation/crd/core.pingcap.com_pds.yaml
  tests/validation/crd/core.pingcap.com_ticdcgroups.yaml
  tests/validation/crd/core.pingcap.com_ticdcs.yaml
  tests/validation/crd/core.pingcap.com_tidbgroups.yaml
  tests/validation/crd/core.pingcap.com_tidbs.yaml
  tests/validation/crd/core.pingcap.com_tiflashes.yaml
  tests/validation/crd/core.pingcap.com_tiflashgroups.yaml
  tests/validation/crd/core.pingcap.com_tikvgroups.yaml
  tests/validation/crd/core.pingcap.com_tikvs.yaml
Labels: lgtm, approved, size/XXL, v2

#6112 Fix: do not set defaultGracefulWaitBeforeShutdownInSeconds && fix TerminationGracePeriodSeconds
  pkg/configs/tidb/config.go
  pkg/configs/tidb/config_test.go
  pkg/controllers/tidb/tasks/pod.go
  pkg/controllers/tidb/tasks/pod_test.go
  tests/e2e/cluster/cluster.go
Labels: size/M, lgtm, approved, v2

#6113 fix(client): use same field manager and force apply unmanaged fields
  cmd/operator/main.go
  pkg/client/client.go
Labels: lgtm, approved, size/XS, v2

#6114 fix(cdc): retry when waiting for capture to be drained
  pkg/controllers/ticdc/tasks/pod.go
Labels: lgtm, approved, size/XS, v2

#6115 feat(tidb): support scale out extra tidb when rolling update
  pkg/apiutil/core/v1alpha1/instance.go
  pkg/checker/checker.go
  pkg/checker/checker_test.go
  pkg/controllers/tidbgroup/tasks/updater.go
  pkg/overlay/overlay.go
  tests/e2e/cluster/cluster.go
  tests/e2e/data/tidb.go
  tests/e2e/label/well_known.go
  tests/e2e/pd/pd.go
  tests/e2e/tidb/tidb.go
  tests/e2e/tikv/topology.go
  tests/e2e/utils/waiter/pod.go
Labels: lgtm, approved, size/XXL, v2

#6124 fix(cluster): fix hash collision of cm and pod
  Makefile
  api/core/v1alpha1/common_types.go
  pkg/checker/checker.go
  pkg/controllers/pd/tasks/cm.go
  pkg/controllers/pd/tasks/cm_test.go
  pkg/controllers/pd/tasks/ctx.go
  pkg/controllers/pd/tasks/pod.go
  pkg/controllers/pd/tasks/pod_test.go
  pkg/controllers/ticdc/tasks/cm.go
  pkg/controllers/ticdc/tasks/cm_test.go
  pkg/controllers/ticdc/tasks/ctx.go
  pkg/controllers/ticdc/tasks/pod.go
  pkg/controllers/ticdc/tasks/pod_test.go
  pkg/controllers/tidb/tasks/cm.go
  pkg/controllers/tidb/tasks/cm_test.go
  pkg/controllers/tidb/tasks/ctx.go
  pkg/controllers/tidb/tasks/pod.go
  pkg/controllers/tidb/tasks/pod_test.go
  pkg/controllers/tidbgroup/tasks/updater.go
  pkg/controllers/tiflash/tasks/cm.go
  pkg/controllers/tiflash/tasks/cm_test.go
  pkg/controllers/tiflash/tasks/ctx.go
  pkg/controllers/tiflash/tasks/pod.go
  pkg/controllers/tiflash/tasks/pod_test.go
  pkg/controllers/tikv/tasks/cm.go
  pkg/controllers/tikv/tasks/cm_test.go
  pkg/controllers/tikv/tasks/ctx.go
  pkg/controllers/tikv/tasks/pod.go
  pkg/controllers/tikv/tasks/pod_test.go
  pkg/reloadable/common.go
  pkg/reloadable/pd.go
  pkg/reloadable/ticdc.go
  pkg/reloadable/tidb.go
  pkg/reloadable/tidb_test.go
  pkg/reloadable/tiflash.go
  pkg/reloadable/tikv.go
  tests/e2e/br/utils/s3/minio.go
  tests/e2e/framework/framework.go
Labels: lgtm, approved, size/XXL, v2

#6125 feat(pvc): support overlay pvc labels and annotations
  pkg/controllers/pd/tasks/pvc.go
  pkg/controllers/pd/tasks/pvc_test.go
  pkg/controllers/ticdc/tasks/pvc.go
  pkg/controllers/ticdc/tasks/pvc_test.go
  pkg/controllers/tidb/tasks/pvc.go
  pkg/controllers/tidb/tasks/pvc_test.go
  pkg/controllers/tiflash/tasks/pvc.go
  pkg/controllers/tiflash/tasks/pvc_test.go
  pkg/controllers/tikv/tasks/pvc.go
  pkg/controllers/tikv/tasks/pvc_test.go
  pkg/overlay/overlay.go
  pkg/reloadable/common.go
Labels: lgtm, approved, size/L, v2

#6118 Feat: add an annotation for restart operation
  api/meta/v1alpha1/annotations.go
  go.work.sum
  pkg/reloadable/common.go
  pkg/reloadable/common_test.go
  pkg/reloadable/pd.go
  pkg/reloadable/ticdc.go
  pkg/reloadable/tidb.go
  pkg/reloadable/tidb_test.go
  pkg/reloadable/tiflash.go
  pkg/reloadable/tikv.go
  pkg/utils/k8s/pod.go
  pkg/utils/k8s/pod_test.go
  tests/e2e/cluster/cluster.go
  tests/e2e/utils/k8s/k8s.go
Labels: lgtm, approved, size/XXL, v2

#6126 fix(*): inherit specific labels and annotations from instance
  api/meta/v1alpha1/annotations.go
  pkg/apiutil/core/v1alpha1/group.go
  pkg/apiutil/core/v1alpha1/instance.go
  pkg/controllers/pd/tasks/cm.go
  pkg/controllers/pd/tasks/pod.go
  pkg/controllers/pd/tasks/pvc.go
  pkg/controllers/pdgroup/tasks/updater.go
  pkg/controllers/ticdc/tasks/cm.go
  pkg/controllers/ticdc/tasks/pod.go
  pkg/controllers/ticdc/tasks/pvc.go
  pkg/controllers/ticdcgroup/tasks/updater.go
  pkg/controllers/tidb/tasks/cm.go
  pkg/controllers/tidb/tasks/pod.go
  pkg/controllers/tidb/tasks/pvc.go
  pkg/controllers/tidbgroup/tasks/updater.go
  pkg/controllers/tiflash/tasks/cm.go
  pkg/controllers/tiflash/tasks/pod.go
  pkg/controllers/tiflash/tasks/pvc.go
  pkg/controllers/tiflashgroup/tasks/updater.go
  pkg/controllers/tikv/tasks/cm.go
  pkg/controllers/tikv/tasks/pod.go
  pkg/controllers/tikv/tasks/pvc.go
  pkg/controllers/tikvgroup/tasks/updater.go
  pkg/reloadable/common.go
  pkg/reloadable/common_test.go
  pkg/reloadable/pd.go
  pkg/reloadable/ticdc.go
  pkg/reloadable/tidb.go
  pkg/reloadable/tidb_test.go
  pkg/reloadable/tiflash.go
  pkg/reloadable/tikv.go
  pkg/runtime/group.go
  pkg/runtime/instance.go
  pkg/runtime/pd.go
  pkg/runtime/ticdc.go
  pkg/runtime/tidb.go
  pkg/runtime/tiflash.go
  pkg/runtime/tikv.go
  pkg/utils/map/map.go
  pkg/utils/map/map_test.go
  tests/e2e/br/framework/data.go
  tests/e2e/cluster/cluster.go
  tests/e2e/pd/pd.go
Labels: lgtm, approved, size/XXL, v2

#6128 Opt: no need to check if StorageClass is changed when use VAC
  pkg/volumes/native_modifer.go
Labels: lgtm, approved, size/S, v2

#6122 Feat: add a field to set prestop hook sleep time
  Makefile
  api/core/v1alpha1/tidb_types.go
  api/core/v1alpha1/zz_generated.deepcopy.go
  cmd/testing-workload/main.go
  cmd/testing-workload/workload.go
  hack/lib/e2e.sh
  manifests/crd/core.pingcap.com_tidbgroups.yaml
  manifests/crd/core.pingcap.com_tidbs.yaml
  pkg/controllers/tidb/tasks/cm.go
  pkg/controllers/tidb/tasks/ctx.go
  pkg/controllers/tidb/tasks/pod.go
  pkg/controllers/tidb/tasks/pod_test.go
  tests/e2e/cluster/cluster.go
Labels: lgtm, approved, size/L, v2

#6129 feat(tidb): disable slowlog by default
  api/core/v1alpha1/tidb_types.go
  manifests/crd/core.pingcap.com_tidbgroups.yaml
  manifests/crd/core.pingcap.com_tidbs.yaml
  pkg/apiutil/core/v1alpha1/tidb.go
  pkg/configs/tidb/config_test.go
Labels: lgtm, approved, size/S, v2

#6132 fix(status): check generation when call IsReady
  pkg/controllers/tidb/tasks/pod.go
  pkg/runtime/pd.go
  pkg/runtime/ticdc.go
  pkg/runtime/tidb.go
  pkg/runtime/tiflash.go
  pkg/runtime/tikv.go
Labels: size/M, lgtm, approved, v2

#6130 fix(client): fix unexpected null creationTimestamp
  pkg/client/client.go
  pkg/client/converter.go
  tests/e2e/cluster/cluster.go
  tests/e2e/data/tidb.go
  tests/e2e/label/well_known.go
  tests/e2e/tidb/tidb.go
  third_party/kube-openapi/pkg/util/proto/document_v3.go
Labels: lgtm, approved, size/L, v2
