Repository pingcap/tidb-operator, pull requests merged in 2025-07, with the labels that each got.

#6279 feat(semver): add compatibility pkg to check component semver
  cmd/runtime-gen/generators/runtime.go
  go.mod
  go.sum
  go.work.sum
  pkg/apicall/doc.go
  pkg/apiutil/core/v1alpha1/doc.go
  pkg/apiutil/core/v1alpha1/group.go
  pkg/apiutil/core/v1alpha1/instance.go
  pkg/apiutil/core/v1alpha1/object.go
  pkg/compatibility/feat.go
  pkg/compatibility/semver.go
  pkg/compatibility/semver_test.go
  pkg/runtime/br.go
  pkg/runtime/group.go
  pkg/runtime/object.go
  pkg/runtime/zz_generated.runtime.pd.go
  pkg/runtime/zz_generated.runtime.scheduler.go
  pkg/runtime/zz_generated.runtime.ticdc.go
  pkg/runtime/zz_generated.runtime.tidb.go
  pkg/runtime/zz_generated.runtime.tiflash.go
  pkg/runtime/zz_generated.runtime.tikv.go
  pkg/runtime/zz_generated.runtime.tiproxy.go
  pkg/runtime/zz_generated.runtime.tso.go
  pkg/utils/datacontainer/slice_test.go
Labels: lgtm, approved, size/XL, v2

#6280 chore(group): refactor and remove unused code
  pkg/controllers/common/interfaces_test.go
  pkg/controllers/common/task.go
  pkg/controllers/common/task_test.go
  pkg/controllers/pdgroup/builder.go
  pkg/controllers/pdgroup/tasks/state.go
  pkg/controllers/pdgroup/tasks/state_test.go
  pkg/controllers/pdgroup/tasks/util.go
  pkg/controllers/ticdcgroup/builder.go
  pkg/controllers/ticdcgroup/tasks/state.go
  pkg/controllers/ticdcgroup/tasks/state_test.go
  pkg/controllers/tidbgroup/builder.go
  pkg/controllers/tidbgroup/tasks/state.go
  pkg/controllers/tidbgroup/tasks/state_test.go
  pkg/controllers/tiflashgroup/builder.go
  pkg/controllers/tiflashgroup/tasks/state.go
  pkg/controllers/tiflashgroup/tasks/state_test.go
  pkg/controllers/tikvgroup/builder.go
  pkg/controllers/tikvgroup/tasks/state.go
  pkg/controllers/tikvgroup/tasks/state_test.go
  pkg/controllers/tikvgroup/tasks/svc.go
  pkg/controllers/tiproxygroup/builder.go
  pkg/controllers/tiproxygroup/tasks/state.go
  pkg/controllers/tiproxygroup/tasks/state_test.go
Labels: lgtm, approved, size/XL, v2

#6267 set `gc.ratio-threshold` to `-1` when performing pitr restore
  pkg/apis/util/config/config.go
  pkg/backup/restore/restore_manager.go
  pkg/backup/restore/restore_manager_test.go
  pkg/backup/testutils/helpers.go
  pkg/controller/dependences.go
  pkg/manager/member/tikv_member_manager.go
  pkg/manager/member/tikv_member_manager_test.go
  pkg/manager/utils/config.go
  pkg/manager/utils/config_test.go
  tests/e2e/br/br.go
Labels: lgtm, approved, size/XXL

#6284 feat(kube): upgrade kubernetes api to v1.32
  api/br/v1alpha1/zz_generated.register.go
  api/core/v1alpha1/zz_generated.register.go
  api/go.mod
  api/go.sum
  cmd/runtime-gen/generators/runtime.go
  go.mod
  go.sum
  go.work.sum
  manifests/crd/br.pingcap.com_backups.yaml
  manifests/crd/br.pingcap.com_backupschedules.yaml
  manifests/crd/br.pingcap.com_compactbackups.yaml
  manifests/crd/br.pingcap.com_restores.yaml
  manifests/crd/br.pingcap.com_tibrgcs.yaml
  manifests/crd/br.pingcap.com_tibrs.yaml
  manifests/crd/core.pingcap.com_pdgroups.yaml
  manifests/crd/core.pingcap.com_pds.yaml
  manifests/crd/core.pingcap.com_schedulergroups.yaml
  manifests/crd/core.pingcap.com_schedulers.yaml
  manifests/crd/core.pingcap.com_ticdcgroups.yaml
  manifests/crd/core.pingcap.com_ticdcs.yaml
  manifests/crd/core.pingcap.com_tidbgroups.yaml
  manifests/crd/core.pingcap.com_tidbs.yaml
  manifests/crd/core.pingcap.com_tiflashes.yaml
  manifests/crd/core.pingcap.com_tiflashgroups.yaml
  manifests/crd/core.pingcap.com_tikvgroups.yaml
  manifests/crd/core.pingcap.com_tikvs.yaml
  manifests/crd/core.pingcap.com_tiproxies.yaml
  manifests/crd/core.pingcap.com_tiproxygroups.yaml
  manifests/crd/core.pingcap.com_tsogroups.yaml
  manifests/crd/core.pingcap.com_tsos.yaml
  pkg/overlay/zz_generated.overlay.go
  pkg/overlay/zz_generated.overlay_test.go
  pkg/timanager/apis/pd/v1/zz_generated.register.go
Labels: lgtm, approved, size/XXL, v2

#6286 fix(tidb): remove unused service field in tidbgroup
  api/core/v1alpha1/tidb_types.go
  api/core/v1alpha1/zz_generated.deepcopy.go
  examples/basic/03-tidb.yaml
  manifests/crd/core.pingcap.com_tidbgroups.yaml
Labels: size/M, lgtm, approved, v2

#6289 fix(image): change default prestop hook image
  hack/lib/e2e.sh
  hack/lib/image.sh
  hack/lib/vars.sh
  pkg/image/image.go
  pkg/image/image_test.go
Labels: size/M, lgtm, approved, v2

#6288 br: prune failed tasks for restore
  cmd/backup-manager/app/cmd/restore.go
  cmd/backup-manager/app/restore/manager.go
  cmd/backup-manager/app/restore/restore.go
  docs/api-references/docs.md
  docs/design-proposals/2025-7-11-restore-prune-task.md
  examples/Runbooks/AKS/md-sc.yaml
  examples/Runbooks/AKS/md-tidb-cluster.yaml
  examples/Runbooks/AKS/tidb-dashboard.yaml
  examples/Runbooks/EKS/tidb-monitor.yaml
  examples/Runbooks/GKE/local-ssd-provisioner.yaml
  examples/Runbooks/GKE/pd-sc.yaml
  examples/Runbooks/GKE/pd-tidb-cluster.yaml
  examples/Runbooks/GKE/tidb-dashboard.yaml
  examples/Runbooks/GKE/tidb-monitor.yaml
  examples/Runbooks/K8s/ssd-cluster.yaml
  examples/Runbooks/K8s/tidb-monitor.yaml
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_restores.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/restore.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/backup/restore/restore_manager.go
  pkg/controller/restore/restore_controller.go
Labels: lgtm, approved, size/XL

#6298 Fix cannot del tiflash/tikv instance if pod is deleted
  cmd/testing-workload/import_data.go
  pkg/controllers/common/cond.go
  pkg/controllers/common/cond_test.go
  pkg/controllers/ticdc/builder.go
  pkg/controllers/tidb/builder.go
  pkg/controllers/tiflash/builder.go
  pkg/controllers/tiflash/tasks/finalizer.go
  pkg/controllers/tiflash/tasks/finalizer_test.go
  pkg/controllers/tiflash/tasks/offline.go
  pkg/controllers/tikv/builder.go
  pkg/controllers/tikv/tasks/finalizer.go
  pkg/controllers/tikv/tasks/finalizer_test.go
  pkg/controllers/tikv/tasks/offline.go
  pkg/controllers/tikv/tasks/pod.go
  pkg/controllers/tiproxy/builder.go
  tests/e2e/framework/workload.go
  tests/e2e/tikv/tikv.go
Labels: lgtm, approved, size/XXL, v2

#6275 fix(store): fail if pd is not ready
  pkg/controllers/common/cond.go
  pkg/controllers/tiflash/builder.go
  pkg/controllers/tiflash/tasks/ctx.go
  pkg/controllers/tiflash/tasks/offline.go
  pkg/controllers/tiflash/tasks/pod.go
  pkg/controllers/tiflash/tasks/pod_test.go
  pkg/controllers/tiflash/tasks/pvc.go
  pkg/controllers/tiflash/tasks/pvc_test.go
  pkg/controllers/tiflash/tasks/status.go
  pkg/controllers/tiflash/tasks/status_test.go
  pkg/controllers/tiflash/tasks/store_labels.go
  pkg/controllers/tikv/builder.go
  pkg/controllers/tikv/tasks/ctx.go
  pkg/controllers/tikv/tasks/evict_leader.go
  pkg/controllers/tikv/tasks/offline.go
  pkg/controllers/tikv/tasks/pod.go
  pkg/controllers/tikv/tasks/pod_test.go
  pkg/controllers/tikv/tasks/pvc.go
  pkg/controllers/tikv/tasks/pvc_test.go
  pkg/controllers/tikv/tasks/status.go
  pkg/controllers/tikv/tasks/status_test.go
  pkg/controllers/tikv/tasks/store_labels.go
Labels: lgtm, approved, size/XL, v2

#6307 CI: update debian image in for E2E
  tests/images/e2e/Dockerfile
  tests/images/kubekins-e2e/Dockerfile
Labels: size/XS

#6303 bump TiDB Operator to 1.6.3
  charts/br-federation/values.yaml
  charts/tidb-operator/values.yaml
  cmd/http-service/go.mod
  deploy/aliyun/variables.tf
  deploy/aws/variables.tf
  deploy/gcp/variables.tf
  examples/Runbooks/AKS/md-tidb-cluster.yaml
  examples/Runbooks/AKS/readme.md
  examples/Runbooks/EKS/readme.md
  examples/Runbooks/EKS/ssd-tidb-cluster.yaml
  examples/Runbooks/EKS/tidb-cluster.yaml
  examples/Runbooks/EKS/tidb-monitor.yaml
  examples/Runbooks/GKE/localdisk-tidb-cluster.yaml
  examples/Runbooks/GKE/pd-tidb-cluster.yaml
  examples/Runbooks/GKE/readme.md
  examples/Runbooks/GKE/tidb-monitor.yaml
  examples/Runbooks/K8s/readme.md
  examples/Runbooks/K8s/ssd-tidb-cluster.yaml
  examples/Runbooks/K8s/tidb-cluster.yaml
  examples/Runbooks/K8s/tidb-monitor.yaml
  go.mod
  hack/bump-version.sh
  pkg/client/go.mod
Labels: size/M, lgtm, approved

#6325 feat(log): support use sidecar to tail log
  docs/api-references/docs.md
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_tidbclusters.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tiflash_member_manager.go
  pkg/manager/member/tiflash_util.go
  pkg/manager/member/tikv_member_manager.go
Labels: lgtm, approved, size/XL

#6330 Fix(pd): add feature gate check before calling GetMemberReady
  pkg/controllers/pd/tasks/ctx.go
Labels: lgtm, approved, size/S, v2

#6334 Fix tiproxy e2e cases
  go.work.sum
  pkg/controllers/tiproxy/tasks/ctx.go
  pkg/controllers/tiproxy/tasks/pod.go
  pkg/controllers/tiproxy/tasks/state.go
  pkg/controllers/tiproxy/tasks/state_test.go
  tests/e2e/data/data.go
  tests/e2e/data/tiproxy.go
  tests/e2e/e2e_test.go
  tests/e2e/tiproxy/tiproxy.go
Labels: lgtm, approved, size/L, v2

#6342 Chore: adjust name length limit
  api/core/v1alpha1/pd_types.go
  api/core/v1alpha1/scheduler_types.go
  api/core/v1alpha1/ticdc_types.go
  api/core/v1alpha1/tidb_types.go
  api/core/v1alpha1/tiflash_types.go
  api/core/v1alpha1/tikv_types.go
  api/core/v1alpha1/tiproxy_types.go
  api/core/v1alpha1/tso_types.go
  manifests/crd/core.pingcap.com_pdgroups.yaml
  manifests/crd/core.pingcap.com_pds.yaml
  manifests/crd/core.pingcap.com_schedulergroups.yaml
  manifests/crd/core.pingcap.com_schedulers.yaml
  manifests/crd/core.pingcap.com_ticdcgroups.yaml
  manifests/crd/core.pingcap.com_ticdcs.yaml
  manifests/crd/core.pingcap.com_tidbgroups.yaml
  manifests/crd/core.pingcap.com_tidbs.yaml
  manifests/crd/core.pingcap.com_tiflashes.yaml
  manifests/crd/core.pingcap.com_tiflashgroups.yaml
  manifests/crd/core.pingcap.com_tikvgroups.yaml
  manifests/crd/core.pingcap.com_tikvs.yaml
  manifests/crd/core.pingcap.com_tiproxies.yaml
  manifests/crd/core.pingcap.com_tiproxygroups.yaml
  manifests/crd/core.pingcap.com_tsogroups.yaml
  manifests/crd/core.pingcap.com_tsos.yaml
  tests/validation/cluster_test.go
  tests/validation/common_test.go
Labels: lgtm, approved, size/L, v2

#6333 Fix(tikv): end evict leader may not be called
  pkg/controllers/tikv/tasks/evict_leader.go
Labels: lgtm, approved, size/S, v2

#6341 Add tls e2e case for tiproxy
  cmd/testing-workload/main.go
  pkg/controllers/tiproxy/tasks/pod.go
  tests/e2e/data/data.go
  tests/e2e/data/tiproxy.go
  tests/e2e/framework/workload.go
  tests/e2e/pd/pd.go
  tests/e2e/ticdc/ticdc.go
  tests/e2e/tidb/tidb.go
  tests/e2e/tikv/tikv.go
  tests/e2e/tiproxy/tiproxy.go
  tests/e2e/utils/cert/cert.go
Labels: lgtm, approved, size/L, v2
