Repository pingcap/tidb-operator, pull requests merged in 2025-09, with the labels that each got.

#6420 br: add new field `MinCompactStartTs` in `backupSchedule`, enable users customize compact start ts
  docs/api-references/docs.md
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_backupschedules.yaml
  manifests/federation-crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/backup/backupschedule/backup_schedule_manager.go
  pkg/backup/backupschedule/backup_schedule_manager_test.go
  pkg/controller/generic_control_test.go
  pkg/monitor/monitor/util_test.go
  tests/e2e/br/br.go
Labels: lgtm, approved, size/XXL

#6400 br: cp bugfix from operator v1
  api/br/v1alpha1/restore_types.go
  manifests/crd/br.pingcap.com_restores.yaml
  pkg/controllers/br/manager/restore/restore_manager.go
Labels: lgtm, approved, size/S, v2

#6424 fix(updater): fix executor if outdated is unavailable
  pkg/updater/executor.go
  pkg/updater/executor_test.go
Labels: size/M, lgtm, approved, v2

#6437 fix(group): break if feature gates field is not synced
  pkg/controllers/common/cond.go
  pkg/controllers/common/cond_test.go
  pkg/controllers/common/interfaces_test.go
  pkg/controllers/common/task.go
  pkg/controllers/pdgroup/builder.go
  pkg/controllers/replicationworkergroup/builder.go
  pkg/controllers/schedulergroup/builder.go
  pkg/controllers/ticdcgroup/builder.go
  pkg/controllers/tidbgroup/builder.go
  pkg/controllers/tiflashgroup/builder.go
  pkg/controllers/tikvgroup/builder.go
  pkg/controllers/tiproxygroup/builder.go
  pkg/controllers/tsogroup/builder.go
Labels: lgtm, approved, size/L, v2

#6426 feat(runtime): add GVK function for runtime scope
  cmd/runtime-gen/generators/scope.go
  pkg/apiutil/core/v1alpha1/instance.go
  pkg/runtime/scope/br.go
  pkg/runtime/scope/scope.go
  pkg/runtime/scope/zz_generated.scope.pd.go
  pkg/runtime/scope/zz_generated.scope.replicationworker.go
  pkg/runtime/scope/zz_generated.scope.scheduler.go
  pkg/runtime/scope/zz_generated.scope.ticdc.go
  pkg/runtime/scope/zz_generated.scope.tidb.go
  pkg/runtime/scope/zz_generated.scope.tiflash.go
  pkg/runtime/scope/zz_generated.scope.tikv.go
  pkg/runtime/scope/zz_generated.scope.tiproxy.go
  pkg/runtime/scope/zz_generated.scope.tso.go
Labels: lgtm, approved, size/L, v2

#6414 feat(tidb): support activate tidb from standby mode
  api/core/v1alpha1/tidb_types.go
  manifests/crd/core.pingcap.com_tidbgroups.yaml
  manifests/crd/core.pingcap.com_tidbs.yaml
  pkg/configs/tidb/config.go
  pkg/controllers/tidb/builder.go
  pkg/controllers/tidb/tasks/activate.go
  pkg/reloadable/tidb.go
  pkg/reloadable/tidb_test.go
  pkg/tidbapi/v1/client.go
  pkg/tidbapi/v1/client_test.go
  pkg/tidbapi/v1/types.go
  pkg/utils/http/error.go
  pkg/utils/http/error_test.go
  pkg/utils/http/http.go
  tests/validation/tidb_test.go
Labels: lgtm, approved, size/XXL, v2

#6451 fix(tidb): support keyspace in config file if spec.keyspace is unset
  api/core/v1alpha1/tidb_types.go
  manifests/crd/core.pingcap.com_tidbs.yaml
  pkg/configs/tidb/config.go
  pkg/configs/tidb/config_test.go
  tests/validation/tidb_test.go
Labels: size/M, lgtm, approved, v2

#6453 test(e2e): add more error infos if e2e failed
  tests/e2e/utils/waiter/common.go
  tests/e2e/utils/waiter/pd.go
  tests/e2e/utils/waiter/scheduler.go
  tests/e2e/utils/waiter/ticdc.go
  tests/e2e/utils/waiter/tidb.go
  tests/e2e/utils/waiter/tiflash.go
  tests/e2e/utils/waiter/tikv.go
  tests/e2e/utils/waiter/tiproxy.go
  tests/e2e/utils/waiter/tso.go
Labels: lgtm, approved, size/L, v2

#6455 fix(cert): only mount ca.crt in ca secret
  pkg/apiutil/core/v1alpha1/instance.go
  pkg/apiutil/core/v1alpha1/tidb.go
  pkg/apiutil/core/v1alpha1/tiproxy.go
  tests/e2e/framework/workload/options.go
  tests/e2e/suite/cluster/tls.go
Labels: size/M, lgtm, approved, v2

#6456 fix(store): cannot trigger reconciliation if store has been removed
  pkg/controllers/tiflash/tasks/ctx.go
  pkg/controllers/tikv/tasks/ctx.go
Labels: lgtm, approved, size/S, v2

#6450 fix(tiflash): fix rolling update issue for tiflash
  api/meta/v1alpha1/feature.go
  cmd/testing-workload/import_data.go
  cmd/testing-workload/main.go
  cmd/testing-workload/pd_region.go
  cmd/testing-workload/ping.go
  cmd/testing-workload/workload.go
  cmd/tidb-operator/main.go
  manifests/crd/core.pingcap.com_clusters.yaml
  manifests/crd/core.pingcap.com_pdgroups.yaml
  manifests/crd/core.pingcap.com_pds.yaml
  manifests/crd/core.pingcap.com_replicationworkergroups.yaml
  manifests/crd/core.pingcap.com_replicationworkers.yaml
  manifests/crd/core.pingcap.com_schedulergroups.yaml
  manifests/crd/core.pingcap.com_schedulers.yaml
  manifests/crd/core.pingcap.com_ticdcgroups.yaml
  manifests/crd/core.pingcap.com_ticdcs.yaml
  manifests/crd/core.pingcap.com_tidbgroups.yaml
  manifests/crd/core.pingcap.com_tidbs.yaml
  manifests/crd/core.pingcap.com_tiflashes.yaml
  manifests/crd/core.pingcap.com_tiflashgroups.yaml
  manifests/crd/core.pingcap.com_tikvgroups.yaml
  manifests/crd/core.pingcap.com_tikvs.yaml
  manifests/crd/core.pingcap.com_tiproxies.yaml
  manifests/crd/core.pingcap.com_tiproxygroups.yaml
  manifests/crd/core.pingcap.com_tsogroups.yaml
  manifests/crd/core.pingcap.com_tsos.yaml
  pkg/apiutil/core/v1alpha1/tiflash.go
  pkg/controllers/tidb/tasks/pod.go
  pkg/controllers/tiflash/builder.go
  pkg/controllers/tiflash/controller.go
  pkg/controllers/tiflash/tasks/ctx.go
  pkg/controllers/tiflash/tasks/finalizer.go
  pkg/controllers/tiflash/tasks/finalizer_test.go
  pkg/controllers/tiflash/tasks/pod.go
  pkg/controllers/tiflash/tasks/pod_test.go
  pkg/controllers/tiflash/tasks/state.go
  pkg/controllers/tiflash/tasks/status.go
  pkg/controllers/tiflash/tasks/status_test.go
  pkg/controllers/tikv/tasks/offline.go
  pkg/features/reload.go
  pkg/tiflashapi/v1/client.go
  pkg/tiflashapi/v1/client_test.go
  pkg/timanager/manager.go
  pkg/timanager/tiflash/tiflash.go
  pkg/timanager/util.go
  tests/e2e/data/pd.go
  tests/e2e/data/tidb.go
  tests/e2e/data/tiflash.go
  tests/e2e/data/tikv.go
  tests/e2e/framework/framework.go
  tests/e2e/framework/util.go
  tests/e2e/framework/workload.go
  tests/e2e/framework/workload/options.go
  tests/e2e/label/well_known.go
  tests/e2e/suite/availability/pd.go
  tests/e2e/suite/availability/tiflash.go
  tests/e2e/suite/availability/tikv.go
  tests/e2e/tidb/standby.go
  tests/e2e/utils/waiter/common.go
  tests/e2e/utils/waiter/job.go
Labels: lgtm, approved, size/XXL, v2

#6421 Add comment for passwordSecret
  docs/api-references/docs.md
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbinitializer_types.go
Labels: lgtm, approved, size/XS

#6468 fix(e2e): adjust default leader transfer time to 200ms
  cmd/testing-workload/pd_region.go
Labels: lgtm, approved, size/XS, v2

#6147 br: Log backup sync state with kernel br periodically
  docs/api-references/docs.md
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_backups.yaml
  pkg/apis/pingcap/v1alpha1/backup.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/backup/backup/backup_manager.go
  pkg/backup/backup/backup_test.go
  pkg/backup/backup/backup_tracker.go
  pkg/backup/backup/backup_tracker_test.go
  pkg/backup/backup/pause_info.go
  pkg/backup/testutils/helpers.go
  pkg/controller/backup/backup_controller.go
  pkg/controller/backup_status_updater.go
Labels: lgtm, approved, size/XXL

#6473 fix(tiflash): retry if tiflash is not running
  pkg/controllers/tiflash/tasks/status.go
  pkg/controllers/tiflash/tasks/status_test.go
Labels: size/M, lgtm, approved, v2

#6479 dep(ginkgo): update ginkgo to v2.23.3
  go.mod
  go.sum
  go.work.sum
Labels: lgtm, approved, size/S, v2

#6476 fix(e2e): enable some disabled cases
  tests/e2e/framework/tikv.go
  tests/e2e/framework/util.go
  tests/e2e/ticdc/ticdc.go
  tests/e2e/tikv/tikv.go
  tests/e2e/tiproxy/tiproxy.go
Labels: lgtm, approved, size/S, v2
