Repository pingcap/tidb-operator, pull requests merged in 2025-06, with the labels that each got.

#6227 add-tikv-config
  examples/advanced-statefulset/tidb-cluster.yaml
  examples/advanced/tidb-cluster.yaml
  examples/aks/tidb-cluster.yaml
  examples/aws/tidb-cluster.yaml
  examples/gcp/tidb-cluster.yaml
  examples/heterogeneous-tls/tidb-cluster.yaml
  examples/heterogeneous/tidb-cluster.yaml
  examples/tiflash/tidb-cluster.yaml
Labels: size/M, lgtm, approved

#6210 feat: support `--retention-period` arg for NGMonitoring
  docs/api-references/docs.md
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_tidbngmonitorings.yaml
  manifests/federation-crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbngmonitoring_types.go
  pkg/manager/tidbngmonitoring/ng_monitoring_manager.go
  pkg/manager/tidbngmonitoring/start_script.go
  pkg/manager/tidbngmonitoring/start_script_test.go
Labels: contribution, size/XXL

#6229 Fix(tikv): wait for leaders to transfer back during rolling restart
  Makefile
  cmd/testing-workload/import_data.go
  cmd/testing-workload/main.go
  hack/lib/e2e.sh
  pkg/controllers/common/interfaces.go
  pkg/controllers/tiflash/tasks/state.go
  pkg/controllers/tikv/tasks/ctx.go
  pkg/controllers/tikv/tasks/state.go
  tests/e2e/br/framework/framework.go
  tests/e2e/cluster/cluster.go
  tests/e2e/framework/framework.go
  tests/e2e/tikv/tikv.go
  tests/e2e/tikv/topology.go
Labels: lgtm, approved, size/L, v2

#6235 fix(tikv): check the leader count based on the total region count
  pkg/controllers/common/interfaces.go
  pkg/controllers/tiflash/tasks/ctx.go
  pkg/controllers/tiflash/tasks/state.go
  pkg/controllers/tikv/tasks/ctx.go
  pkg/controllers/tikv/tasks/state.go
  pkg/pdapi/v1/client.go
  pkg/timanager/apis/pd/v1/types.go
  pkg/timanager/pd/store.go
  tests/e2e/tikv/topology.go
Labels: size/M, lgtm, approved, v2

#6237 Support setting Server Labels for tidb and tiproxy via spec
  docs/api-references/docs.md
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_tidbclusters.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/member/node.go
  pkg/manager/member/tidb_member_manager.go
  pkg/manager/member/tiproxy_member_manager.go
  pkg/util/map/map.go
  pkg/util/map/map_test.go
Labels: contribution, lgtm, approved, size/XL, needs-ok-to-test

#6236 feat(charts): support release charts to ghcr.io
  .github/workflows/release-v2.yaml
  charts/tidb-operator/templates/_helpers.tpl
  charts/tidb-operator/templates/deployment.yaml
  charts/tidb-operator/values.yaml
  hack/release.sh
Labels: size/M, lgtm, approved, v2

#6239 feat(tikv): try to evict leaders before deleting stores
  pkg/apis/label/label.go
  pkg/manager/member/tikv_scaler.go
  pkg/manager/member/tikv_scaler_test.go
  pkg/manager/member/utils.go
Labels: lgtm, approved, size/L

#6243 opt: check PD member ready when upgrading
  pkg/controller/pd_control.go
  pkg/controller/pd_control_test.go
  pkg/manager/member/pd_upgrader.go
  pkg/manager/member/pd_upgrader_test.go
  pkg/pdapi/fake_pdapi.go
  pkg/pdapi/pd_control.go
  pkg/pdapi/pd_control_test.go
  pkg/pdapi/pdapi.go
Labels: approved, size/L

#6250 s3: add forth path style parameter for fips backup
  docs/api-references/docs.md
  manifests/crd.yaml
  manifests/crd/federation/v1/federation.pingcap.com_volumebackups.yaml
  manifests/crd/federation/v1/federation.pingcap.com_volumebackupschedules.yaml
  manifests/crd/federation/v1/federation.pingcap.com_volumerestores.yaml
  manifests/crd/v1/pingcap.com_backups.yaml
  manifests/crd/v1/pingcap.com_backupschedules.yaml
  manifests/crd/v1/pingcap.com_compactbackups.yaml
  manifests/crd/v1/pingcap.com_restores.yaml
  manifests/federation-crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/backup/util/remote.go
  pkg/backup/util/remote_test.go
Labels: first-time-contributor, lgtm, approved, size/XXL

#6253 Chore: Rename `VolumeAttributeClass` to `VolumeAttributesClass`
  api/meta/v1alpha1/feature.go
  manifests/crd/core.pingcap.com_clusters.yaml
  manifests/crd/core.pingcap.com_pdgroups.yaml
  manifests/crd/core.pingcap.com_pds.yaml
  manifests/crd/core.pingcap.com_schedulergroups.yaml
  manifests/crd/core.pingcap.com_schedulers.yaml
  manifests/crd/core.pingcap.com_ticdcgroups.yaml
  manifests/crd/core.pingcap.com_ticdcs.yaml
  manifests/crd/core.pingcap.com_tidbgroups.yaml
  manifests/crd/core.pingcap.com_tidbs.yaml
  manifests/crd/core.pingcap.com_tiflashes.yaml
  manifests/crd/core.pingcap.com_tiflashgroups.yaml
  manifests/crd/core.pingcap.com_tikvgroups.yaml
  manifests/crd/core.pingcap.com_tikvs.yaml
  manifests/crd/core.pingcap.com_tiproxies.yaml
  manifests/crd/core.pingcap.com_tiproxygroups.yaml
  manifests/crd/core.pingcap.com_tsogroups.yaml
  manifests/crd/core.pingcap.com_tsos.yaml
  pkg/features/reload.go
  pkg/volumes/utils.go
  tests/validation/common_test.go
Labels: lgtm, approved, size/L, v2

#6255 Revert "Volume Replacement causes excessive CPU and IO usage on the p…
  pkg/manager/volumes/pvc_replacer.go
  pkg/manager/volumes/pvc_replacer_test.go
Labels: contribution, size/M, lgtm, approved, needs-ok-to-test

#6257 feat(tiproxy): support readiness probe
  pkg/manager/member/tiproxy_member_manager.go
  pkg/manager/member/tiproxy_member_manager_test.go
Labels: contribution, lgtm, approved, size/L, needs-ok-to-test

#6268 br: support custom s3 endpoint for backup manager
  pkg/backup/util/remote.go
Labels: size/M, lgtm, approved

#6266 Opt: Add a ValidatingAdmissionPolicy for volume storage
  charts/tidb-operator/templates/webhook.yaml
  tests/e2e/data/data.go
  tests/e2e/data/tiproxy.go
  tests/e2e/e2e_test.go
  tests/e2e/webhook/webhook.go
Labels: lgtm, approved, size/XL, v2

#6265 Chore: fix `lll` and `unparam` linters
  .golangci.yml
  cmd/tidb-backup-manager/app/backup/backup.go
  cmd/tidb-backup-manager/app/backup/manager.go
  cmd/tidb-backup-manager/app/clean/clean.go
  cmd/tidb-backup-manager/app/restore/restore.go
  cmd/tidb-backup-manager/app/util/util.go
  pkg/apiutil/core/v1alpha1/tiproxy.go
  pkg/client/client.go
  pkg/configs/tiproxy/config.go
  pkg/controllers/br/manager/backup/backup_cleaner.go
  pkg/controllers/br/manager/backup/backup_manager.go
  pkg/controllers/br/manager/backup/backup_status_updater.go
  pkg/controllers/br/manager/backup/backup_tracker.go
  pkg/controllers/br/manager/restore/restore_manager.go
  pkg/controllers/br/manager/restore/restore_status_updater.go
  pkg/controllers/br/manager/util/remote.go
  pkg/controllers/br/manager/util/util.go
  pkg/controllers/br/restore/controller.go
  pkg/controllers/br/tibr/tasks/sts.go
  pkg/controllers/common/job.go
  pkg/controllers/tikv/tasks/finalizer.go
  pkg/controllers/tiproxy/tasks/pod.go
  pkg/tiproxyapi/v1/control.go
Labels: lgtm, approved, size/XL, v2

#6273 fix(store): fix deletion bug when del tikv or tiflash
  pkg/controllers/tiflash/tasks/ctx.go
  pkg/controllers/tiflash/tasks/finalizer.go
  pkg/controllers/tiflash/tasks/finalizer_test.go
  pkg/controllers/tikv/tasks/ctx.go
  pkg/controllers/tikv/tasks/finalizer.go
  pkg/controllers/tikv/tasks/finalizer_test.go
Labels: lgtm, approved, size/S, v2

#6276 feat(log): add id for report and use logger from ctx
  go.mod
  pkg/controllers/br/backup/controller.go
  pkg/controllers/br/restore/controller.go
  pkg/controllers/br/tibr/controller.go
  pkg/controllers/cluster/controller.go
  pkg/controllers/pd/controller.go
  pkg/controllers/pdgroup/controller.go
  pkg/controllers/scheduler/controller.go
  pkg/controllers/schedulergroup/controller.go
  pkg/controllers/ticdc/controller.go
  pkg/controllers/ticdcgroup/controller.go
  pkg/controllers/tidb/controller.go
  pkg/controllers/tidbgroup/controller.go
  pkg/controllers/tiflash/controller.go
  pkg/controllers/tiflashgroup/controller.go
  pkg/controllers/tikv/controller.go
  pkg/controllers/tikvgroup/controller.go
  pkg/controllers/tiproxy/controller.go
  pkg/controllers/tiproxygroup/controller.go
  pkg/controllers/tso/controller.go
  pkg/controllers/tsogroup/controller.go
  pkg/utils/task/v3/runner.go
  pkg/utils/task/v3/runner_test.go
Labels: lgtm, approved, size/L, v2
