Repository pingcap/tidb-operator, pull requests merged in 2025-05, with the labels that each got.

#6186 refactor(scope): refactor and generate scope
  cmd/runtime-gen/generators/namer.go
  cmd/runtime-gen/generators/runtime.go
  cmd/runtime-gen/generators/scope.go
  cmd/runtime-gen/main.go
  pkg/action/upgrader.go
  pkg/apicall/cluster.go
  pkg/apicall/group.go
  pkg/apiutil/core/v1alpha1/instance.go
  pkg/apiutil/core/v1alpha1/object.go
  pkg/controllers/common/mock_generated.go
  pkg/controllers/common/task.go
  pkg/controllers/common/task_status.go
  pkg/controllers/common/task_status_test.go
  pkg/controllers/pdgroup/tasks/state.go
  pkg/runtime/scope/scope.go
  pkg/runtime/scope/zz_generated.scope.pd.go
  pkg/runtime/scope/zz_generated.scope.scheduler.go
  pkg/runtime/scope/zz_generated.scope.ticdc.go
  pkg/runtime/scope/zz_generated.scope.tidb.go
  pkg/runtime/scope/zz_generated.scope.tiflash.go
  pkg/runtime/scope/zz_generated.scope.tikv.go
  pkg/runtime/scope/zz_generated.scope.tso.go
Labels: lgtm, approved, size/XXL, v2

#6187 refactor(common): use ContextObject task
  pkg/controllers/common/interfaces.go
  pkg/controllers/common/interfaces_test.go
  pkg/controllers/common/task.go
  pkg/controllers/common/task_test.go
  pkg/controllers/pd/builder.go
  pkg/controllers/pd/tasks/state.go
  pkg/controllers/pd/tasks/state_test.go
  pkg/controllers/pdgroup/builder.go
  pkg/controllers/pdgroup/tasks/state.go
  pkg/controllers/pdgroup/tasks/state_test.go
  pkg/controllers/ticdc/builder.go
  pkg/controllers/ticdc/tasks/state.go
  pkg/controllers/ticdc/tasks/state_test.go
  pkg/controllers/ticdcgroup/builder.go
  pkg/controllers/ticdcgroup/tasks/state.go
  pkg/controllers/ticdcgroup/tasks/state_test.go
  pkg/controllers/tidb/builder.go
  pkg/controllers/tidb/tasks/state.go
  pkg/controllers/tidb/tasks/state_test.go
  pkg/controllers/tidbgroup/builder.go
  pkg/controllers/tidbgroup/tasks/state.go
  pkg/controllers/tidbgroup/tasks/state_test.go
  pkg/controllers/tiflash/builder.go
  pkg/controllers/tiflash/tasks/state.go
  pkg/controllers/tiflash/tasks/state_test.go
  pkg/controllers/tiflashgroup/builder.go
  pkg/controllers/tiflashgroup/tasks/state.go
  pkg/controllers/tiflashgroup/tasks/state_test.go
  pkg/controllers/tikv/builder.go
  pkg/controllers/tikv/tasks/state.go
  pkg/controllers/tikv/tasks/state_test.go
  pkg/controllers/tikvgroup/builder.go
  pkg/controllers/tikvgroup/tasks/state.go
  pkg/controllers/tikvgroup/tasks/state_test.go
Labels: lgtm, approved, size/XL, v2

#6191 feat(instance): add synced condition for instance
  api/core/v1alpha1/common_types.go
  pkg/apiutil/core/v1alpha1/condition.go
  pkg/controllers/common/mock_generated.go
  pkg/controllers/common/task_status.go
  pkg/controllers/common/task_status_test.go
  pkg/controllers/pd/builder.go
  pkg/controllers/ticdc/builder.go
  pkg/controllers/tidb/builder.go
  pkg/controllers/tiflash/builder.go
  pkg/controllers/tikv/builder.go
  pkg/controllers/tso/builder.go
Labels: lgtm, approved, size/XL, v2

#6192 feat(pd): add feature to disable pd's default readiness probe
  api/meta/v1alpha1/feature.go
  pkg/controllers/pd/tasks/pod.go
  pkg/controllers/pd/tasks/pod_test.go
  tests/e2e/data/cluster.go
Labels: lgtm, approved, size/S, v2

#6197 chore(release): support release crds and deploy files
  .github/workflows/release-v2.yaml
  Makefile
  charts/tidb-operator/Chart.yaml
  charts/tidb-operator/templates/deployment.yaml
  charts/tidb-operator/templates/rbac.yaml
  charts/tidb-operator/templates/webhook.yaml
  cmd/operator/main.go
  cmd/tidb-operator/main.go
  hack/boilerplate/boilerplate.yaml.txt
  hack/lib/build.sh
  hack/lib/e2e.sh
  hack/lib/vars.sh
  hack/release.sh
  hack/yaml.sh
  image/Dockerfile
  manifests/deploy/00-ns.yaml
  manifests/deploy/01-sa.yaml
  manifests/deploy/02-role.yaml
  manifests/deploy/03-role_binding.yaml
  manifests/deploy/04-webhook.yaml
  manifests/deploy/05-deploy.yaml
Labels: lgtm, approved, size/XXL, v2

#6200 fix(br): rename backup-manager to tidb-backup-manager
  Makefile
  charts/tidb-operator/values.yaml
  cmd/tidb-backup-manager/app/backup/backup.go
  cmd/tidb-backup-manager/app/backup/manager.go
  cmd/tidb-backup-manager/app/backup_manager.go
  cmd/tidb-backup-manager/app/clean/clean.go
  cmd/tidb-backup-manager/app/clean/manager.go
  cmd/tidb-backup-manager/app/cmd/backup.go
  cmd/tidb-backup-manager/app/cmd/clean.go
  cmd/tidb-backup-manager/app/cmd/cmd.go
  cmd/tidb-backup-manager/app/cmd/restore.go
  cmd/tidb-backup-manager/app/constants/constants.go
  cmd/tidb-backup-manager/app/restore/manager.go
  cmd/tidb-backup-manager/app/restore/restore.go
  cmd/tidb-backup-manager/app/util/generic.go
  cmd/tidb-backup-manager/app/util/util.go
  cmd/tidb-backup-manager/app/util/util_test.go
  cmd/tidb-backup-manager/main.go
  hack/lib/build.sh
  hack/lib/e2e.sh
  hack/release.sh
  image/Dockerfile
  pkg/controllers/br/manager/backup/backup_manager.go
  pkg/controllers/br/manager/restore/restore_manager.go
Labels: lgtm, approved, size/L, v2

#6198 Doc: add a design doc about tiproxy
  docs/rfcs/250515-tiproxy.md
Labels: lgtm, approved, size/L, v2, rfc

#6201 fix(instance): wait until pd addr is registered into cluster status
  pkg/controllers/common/cond.go
  pkg/controllers/common/cond_test.go
  pkg/controllers/scheduler/builder.go
  pkg/controllers/ticdc/builder.go
  pkg/controllers/tidb/builder.go
  pkg/controllers/tiflash/builder.go
  pkg/controllers/tikv/builder.go
  pkg/controllers/tso/builder.go
Labels: size/M, lgtm, approved, v2

#6196 Feat: add tiproxy CRD
  api/core/v1alpha1/common_types.go
  api/core/v1alpha1/tiproxy_types.go
  api/core/v1alpha1/zz_generated.deepcopy.go
  api/core/v1alpha1/zz_generated.register.go
  cmd/runtime-gen/main.go
  manifests/crd/core.pingcap.com_tiproxies.yaml
  manifests/crd/core.pingcap.com_tiproxygroups.yaml
  pkg/runtime/scope/zz_generated.scope.tiproxy.go
  pkg/runtime/zz_generated.runtime.tiproxy.go
Labels: lgtm, approved, size/XXL, v2

#6203 fix(updater): support scale in/out to replace update
  pkg/controllers/tidbgroup/tasks/updater.go
  pkg/updater/actor.go
  pkg/updater/builder.go
  pkg/utils/topology/scheduler_test.go
  tests/e2e/framework/framework.go
  tests/e2e/framework/tidb.go
  tests/e2e/tidb/topology.go
  tests/e2e/utils/waiter/pod.go
Labels: lgtm, approved, size/L, v2

#6211 fix(br): mount gcp credentials directly into br jobs
  pkg/controllers/br/manager/backup/backup_cleaner.go
  pkg/controllers/br/manager/backup/backup_manager.go
  pkg/controllers/br/manager/constants/constants.go
  pkg/controllers/br/manager/restore/restore_manager.go
  pkg/controllers/br/manager/util/util.go
Labels: lgtm, approved, size/L, v2

#6213 feat(group): support scale subresource
  .golangci.yml
  api/core/v1alpha1/common_types.go
  api/core/v1alpha1/pd_types.go
  api/core/v1alpha1/scheduler_types.go
  api/core/v1alpha1/ticdc_types.go
  api/core/v1alpha1/tidb_types.go
  api/core/v1alpha1/tiflash_types.go
  api/core/v1alpha1/tikv_types.go
  api/core/v1alpha1/tiproxy_types.go
  api/core/v1alpha1/tso_types.go
  cmd/runtime-gen/generators/runtime.go
  manifests/crd/core.pingcap.com_pdgroups.yaml
  manifests/crd/core.pingcap.com_schedulergroups.yaml
  manifests/crd/core.pingcap.com_ticdcgroups.yaml
  manifests/crd/core.pingcap.com_tidbgroups.yaml
  manifests/crd/core.pingcap.com_tiflashgroups.yaml
  manifests/crd/core.pingcap.com_tikvgroups.yaml
  manifests/crd/core.pingcap.com_tiproxygroups.yaml
  manifests/crd/core.pingcap.com_tsogroups.yaml
  pkg/apiutil/core/v1alpha1/group.go
  pkg/controllers/common/mock_generated.go
  pkg/controllers/common/task_status.go
  pkg/controllers/common/task_status_test.go
  pkg/controllers/pdgroup/builder.go
  pkg/controllers/schedulergroup/builder.go
  pkg/controllers/ticdcgroup/builder.go
  pkg/controllers/tidbgroup/builder.go
  pkg/controllers/tiflashgroup/builder.go
  pkg/controllers/tikvgroup/builder.go
  pkg/controllers/tsogroup/builder.go
  pkg/runtime/group.go
  pkg/runtime/zz_generated.runtime.pd.go
  pkg/runtime/zz_generated.runtime.scheduler.go
  pkg/runtime/zz_generated.runtime.ticdc.go
  pkg/runtime/zz_generated.runtime.tidb.go
  pkg/runtime/zz_generated.runtime.tiflash.go
  pkg/runtime/zz_generated.runtime.tikv.go
  pkg/runtime/zz_generated.runtime.tiproxy.go
  pkg/runtime/zz_generated.runtime.tso.go
Labels: lgtm, approved, size/XL, v2

#6202 feat(tidb): support setting server labels dynamically
  .github/licenserc.yaml
  api/core/v1alpha1/tidb_types.go
  api/core/v1alpha1/zz_generated.deepcopy.go
  manifests/crd/core.pingcap.com_tidbgroups.yaml
  manifests/crd/core.pingcap.com_tidbs.yaml
  pkg/configs/tidb/config.go
  pkg/configs/tidb/config_test.go
  pkg/controllers/tidb/tasks/server_labels.go
  pkg/reloadable/tidb.go
  pkg/reloadable/tidb_test.go
  pkg/utils/k8s/node.go
  tests/validation/tidb_test.go
Labels: lgtm, approved, size/L, v2

#6215 Chore: bump golangci-lint to v2
  .golangci.yml
  Makefile
  cmd/tidb-backup-manager/app/backup/backup.go
  cmd/tidb-backup-manager/app/restore/restore.go
  cmd/tidb-backup-manager/app/util/util.go
  pkg/controllers/br/manager/backup/backup_tracker.go
  pkg/controllers/br/manager/util/remote.go
  pkg/controllers/common/job.go
  pkg/overlay/overlay_test.go
  pkg/pdapi/v1/client_test.go
  pkg/runtime/br.go
  pkg/ticdcapi/v1/client_test.go
  third_party/kubernetes/pkg/controller/history/controller_history.go
Labels: lgtm, approved, size/L, v2

#6216 feat(validation): cannot overlay pod labels starting with pingcap.com/
  api/core/v1alpha1/common_types.go
  manifests/crd/core.pingcap.com_pdgroups.yaml
  manifests/crd/core.pingcap.com_pds.yaml
  manifests/crd/core.pingcap.com_schedulergroups.yaml
  manifests/crd/core.pingcap.com_schedulers.yaml
  manifests/crd/core.pingcap.com_ticdcgroups.yaml
  manifests/crd/core.pingcap.com_ticdcs.yaml
  manifests/crd/core.pingcap.com_tidbgroups.yaml
  manifests/crd/core.pingcap.com_tidbs.yaml
  manifests/crd/core.pingcap.com_tiflashes.yaml
  manifests/crd/core.pingcap.com_tiflashgroups.yaml
  manifests/crd/core.pingcap.com_tikvgroups.yaml
  manifests/crd/core.pingcap.com_tikvs.yaml
  manifests/crd/core.pingcap.com_tiproxies.yaml
  manifests/crd/core.pingcap.com_tiproxygroups.yaml
  manifests/crd/core.pingcap.com_tsogroups.yaml
  manifests/crd/core.pingcap.com_tsos.yaml
  tests/validation/common_test.go
  tests/validation/pd_test.go
  tests/validation/scheduler_test.go
  tests/validation/tidb_test.go
  tests/validation/tso_test.go
Labels: lgtm, approved, size/L, v2

#6218 feat(pd): add log for pd
  pkg/controllers/pd/handler.go
  pkg/controllers/pd/tasks/ctx.go
Labels: lgtm, approved, size/S, v2

#6221 Fix: register TiProxy and TiProxyGroup controllers
  cmd/tidb-operator/main.go
Labels: lgtm, approved, size/S, v2
