Repository pingcap/tidb-operator, pull requests merged in 2025-01, with the labels that each got.

#6024 *: fix typo
  docs/api-references/docs.md
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/tidbcluster.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/manager/member/pd_member_manager.go
  pkg/manager/member/pd_ms_member_manager.go
  pkg/manager/member/pd_ms_scaler.go
  pkg/manager/member/pd_ms_upgrader.go
  pkg/manager/member/pvc_resizer.go
  pkg/manager/member/startscript/v2/common.go
  pkg/manager/member/startscript/v2/pd_start_script.go
  pkg/manager/member/startscript/v2/pd_start_script_test.go
  pkg/manager/member/tikv_member_manager.go
  pkg/pdapi/pdapi.go
Labels: lgtm, approved, size/L

#6026 chore(pd): add uts for pd
  .github/licenserc.yaml
  Makefile
  hack/boilerplate/boilerplate.txt
  pkg/controllers/pd/builder.go
  pkg/controllers/pd/tasks/cm.go
  pkg/controllers/pd/tasks/cm_test.go
  pkg/controllers/pd/tasks/finalizer.go
  pkg/controllers/pd/tasks/finalizer_test.go
  pkg/controllers/pd/tasks/pod.go
  pkg/controllers/pd/tasks/pod_test.go
  pkg/controllers/pd/tasks/pvc.go
  pkg/controllers/pd/tasks/pvc_test.go
  pkg/controllers/pd/tasks/state_test.go
  pkg/controllers/pd/tasks/status.go
  pkg/controllers/pd/tasks/status_test.go
  pkg/controllers/tidb/tasks/state_test.go
  pkg/controllers/tiflash/tasks/state_test.go
  pkg/controllers/tiflash/tasks/status.go
  pkg/controllers/tikv/tasks/state_test.go
  pkg/controllers/tikv/tasks/status.go
  pkg/pdapi/v1/client.go
  pkg/pdapi/v1/mock_generated.go
  pkg/timanager/pd/mock_generated.go
  pkg/timanager/pd/pd.go
  pkg/utils/k8s/pod.go
  pkg/volumes/mock_generated.go
  pkg/volumes/types.go
  pkg/volumes/utils.go
  pkg/volumes/utils_test.go
Labels: lgtm, approved, size/XXL, v2

#6027 Fix: generate tiflash config hash by combining tiflash config and proxy config
  pkg/controllers/tiflash/tasks/cm.go
  pkg/controllers/tiflash/tasks/util.go
  pkg/utils/hasher/hasher.go
  pkg/utils/hasher/hasher_test.go
Labels: contribution, approved, size/L, v2

#5822 br: add a new CRD for compact backup
  cmd/backup-manager/app/backup/manager.go
  cmd/backup-manager/app/clean/clean_test.go
  cmd/backup-manager/app/cmd/cmd.go
  cmd/backup-manager/app/cmd/compact.go
  cmd/backup-manager/app/compact/manager.go
  cmd/backup-manager/app/compact/options/options.go
  cmd/backup-manager/app/util/util.go
  cmd/backup-manager/app/util/util_test.go
  cmd/backup-manager/main.go
  cmd/controller-manager/main.go
  docs/api-references/docs.md
  go.mod
  go.sum
  images/tidb-backup-manager/e2e-entrypoint.sh
  images/tidb-backup-manager/entrypoint.sh
  manifests/backup/backup-rbac.yaml
  manifests/crd.yaml
  manifests/crd/v1/pingcap.com_compactbackups.yaml
  manifests/federation-crd.yaml
  pkg/apis/pingcap/v1alpha1/openapi_generated.go
  pkg/apis/pingcap/v1alpha1/register.go
  pkg/apis/pingcap/v1alpha1/types.go
  pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/pingcap/v1alpha1/compactbackup.go
  pkg/client/clientset/versioned/typed/pingcap/v1alpha1/fake/fake_compactbackup.go
  pkg/client/clientset/versioned/typed/pingcap/v1alpha1/fake/fake_pingcap_client.go
  pkg/client/clientset/versioned/typed/pingcap/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/pingcap/v1alpha1/pingcap_client.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/pingcap/v1alpha1/compactbackup.go
  pkg/client/informers/externalversions/pingcap/v1alpha1/interface.go
  pkg/client/listers/pingcap/v1alpha1/compactbackup.go
  pkg/client/listers/pingcap/v1alpha1/expansion_generated.go
  pkg/controller/compact_backup_control.go
  pkg/controller/compact_status_updater.go
  pkg/controller/compactbackup/compact_backup_controller.go
  pkg/controller/controller_utils.go
  pkg/controller/dependences.go
  pkg/util/util.go
  tests/e2e/br/br.go
  tests/e2e/br/framework/br/data.go
  tests/e2e/br/framework/br/wait.go
Labels: tools/br, approved, size/XXL

#6034 Opt(tidb): do not use sleep action for better compatibility
  Makefile
  pkg/controllers/tidb/tasks/pod.go
  pkg/controllers/tidb/tasks/pod_test.go
Labels: contribution, lgtm, approved, size/S

#6036 fix(instances): fix vol name prefix and refactor volume for to mount
  apis/core/v1alpha1/common_types.go
  apis/core/v1alpha1/pd_types.go
  apis/core/v1alpha1/tidb_types.go
  apis/core/v1alpha1/tiflash_types.go
  apis/core/v1alpha1/tikv_types.go
  apis/core/v1alpha1/zz_generated.deepcopy.go
  examples/basic/01-pd.yaml
  examples/basic/02-tikv.yaml
  examples/basic/04-tiflash.yaml
  examples/bootstrap-sql/01-pd.yaml
  examples/bootstrap-sql/02-tikv.yaml
  examples/overlay/01-pd.yaml
  examples/overlay/02-tikv.yaml
  examples/schedule-policy/01-pd.yaml
  examples/schedule-policy/02-tikv.yaml
  examples/tls/01-pd.yaml
  examples/tls/02-tikv.yaml
  examples/tls/04-tiflash.yaml
  manifests/crd/core.pingcap.com_pdgroups.yaml
  manifests/crd/core.pingcap.com_pds.yaml
  manifests/crd/core.pingcap.com_tidbgroups.yaml
  manifests/crd/core.pingcap.com_tidbs.yaml
  manifests/crd/core.pingcap.com_tiflashes.yaml
  manifests/crd/core.pingcap.com_tiflashgroups.yaml
  manifests/crd/core.pingcap.com_tikvgroups.yaml
  manifests/crd/core.pingcap.com_tikvs.yaml
  pkg/configs/pd/config.go
  pkg/configs/pd/config_test.go
  pkg/configs/tidb/config.go
  pkg/configs/tidb/config_test.go
  pkg/configs/tiflash/config.go
  pkg/configs/tiflash/config_test.go
  pkg/configs/tikv/config.go
  pkg/configs/tikv/config_test.go
  pkg/controllers/pd/tasks/pod.go
  pkg/controllers/pd/tasks/util.go
  pkg/controllers/tidb/tasks/ctx.go
  pkg/controllers/tidb/tasks/pod.go
  pkg/controllers/tidb/tasks/util.go
  pkg/controllers/tiflash/tasks/pod.go
  pkg/controllers/tiflash/tasks/pod_test.go
  pkg/controllers/tiflash/tasks/util.go
  pkg/controllers/tikv/tasks/pod.go
  pkg/controllers/tikv/tasks/util.go
  tests/e2e/data/pd.go
  tests/e2e/utils/data/cluster.go
Labels: lgtm, approved, size/XXL, v2

#6037 feat: add annotations for Prometheus
  pkg/controllers/pd/tasks/pod.go
  pkg/controllers/tidb/tasks/pod.go
  pkg/controllers/tiflash/tasks/pod.go
  pkg/controllers/tikv/tasks/pod.go
  pkg/utils/k8s/annotation.go
  pkg/utils/k8s/annotation_test.go
Labels: size/L

#6039 Fix: use task.Retry() instead of task.Wait() in some cases
  pkg/controllers/common/task.go
  pkg/controllers/common/task_finalizer.go
  pkg/controllers/common/task_finalizer_test.go
  pkg/controllers/common/task_test.go
  pkg/controllers/pd/tasks/finalizer.go
  pkg/controllers/pd/tasks/finalizer_test.go
  pkg/controllers/pdgroup/tasks/finalizer.go
  pkg/controllers/pdgroup/tasks/finalizer_test.go
  pkg/controllers/tidb/tasks/finalizer.go
  pkg/controllers/tidb/tasks/finalizer_test.go
  pkg/controllers/tiflash/tasks/finalizer.go
  pkg/controllers/tiflash/tasks/finalizer_test.go
  pkg/controllers/tikv/tasks/finalizer.go
  pkg/controllers/tikv/tasks/finalizer_test.go
  pkg/utils/task/v3/result.go
Labels: size/M, lgtm, approved

#6030 Fix that pod spec's hash may be changed when new fields are added to the `PodSpec`
  .gitignore
  Makefile
  pkg/controllers/pd/tasks/pod_test.go
  pkg/controllers/tidb/tasks/pod_test.go
  pkg/controllers/tiflash/tasks/pod_test.go
  pkg/controllers/tikv/tasks/pod_test.go
  pkg/utils/k8s/pod.go
  pkg/utils/k8s/revision/controller_revision.go
Labels: contribution, size/M, approved

#6041 opt(tiflash): only report error if there are not equal to the managed fields for some dir config items
  pkg/configs/tiflash/config.go
  pkg/configs/tiflash/config_test.go
Labels: size/M, lgtm, approved, v2

#6043 fix: remove namespace in PD MS example
  examples/basic/pd-micro-service-cluster.yaml
Labels: size/XS

#6047 opt: add some app.kubernetes.io/* labels back
  pkg/controllers/pd/tasks/pod.go
  pkg/controllers/tidb/tasks/pod.go
  pkg/controllers/tiflash/tasks/pod.go
  pkg/controllers/tikv/tasks/pod.go
  pkg/utils/k8s/annotation.go
  pkg/utils/k8s/annotation_test.go
  pkg/utils/k8s/pod.go
  pkg/utils/k8s/pod_test.go
Labels: size/L

#6045 fix(controllerrevision): add component into revision name
  pkg/controllers/common/interfaces.go
  pkg/controllers/common/resource.go
  pkg/controllers/common/revision.go
  pkg/controllers/common/revision_test.go
  pkg/controllers/pdgroup/builder.go
  pkg/controllers/pdgroup/tasks/state.go
  pkg/controllers/tidbgroup/builder.go
  pkg/controllers/tidbgroup/tasks/state.go
  pkg/controllers/tidbgroup/tasks/state_test.go
  pkg/controllers/tiflashgroup/builder.go
  pkg/controllers/tiflashgroup/tasks/state.go
  pkg/controllers/tiflashgroup/tasks/state_test.go
  pkg/controllers/tikvgroup/builder.go
  pkg/controllers/tikvgroup/tasks/state.go
  pkg/utils/k8s/revision/controller_revision.go
  pkg/utils/k8s/revision/controller_revision_test.go
  third_party/kubernetes/pkg/controller/history/controller_history.go
Labels: size/L, v2

#6049 feat: add cluster/member/store ID for Pod and PVC
  apis/core/v1alpha1/cluster_types.go
  apis/core/v1alpha1/common_types.go
  cmd/operator/main.go
  manifests/crd/core.pingcap.com_clusters.yaml
  pkg/controllers/cluster/controller.go
  pkg/controllers/cluster/tasks/status.go
  pkg/controllers/cluster/tasks/status_test.go
  pkg/controllers/pd/tasks/ctx.go
  pkg/controllers/pd/tasks/pod.go
  pkg/controllers/pd/tasks/pod_test.go
  pkg/controllers/pd/tasks/pvc.go
  pkg/controllers/pd/tasks/pvc_test.go
  pkg/controllers/pd/tasks/status.go
  pkg/controllers/tidb/handler.go
  pkg/controllers/tidb/tasks/pod.go
  pkg/controllers/tidb/tasks/pod_test.go
  pkg/controllers/tidb/tasks/pvc.go
  pkg/controllers/tidb/tasks/pvc_test.go
  pkg/controllers/tiflash/handler.go
  pkg/controllers/tiflash/tasks/pod.go
  pkg/controllers/tiflash/tasks/pod_test.go
  pkg/controllers/tiflash/tasks/pvc.go
  pkg/controllers/tiflash/tasks/pvc_test.go
  pkg/controllers/tikv/handler.go
  pkg/controllers/tikv/tasks/pod.go
  pkg/controllers/tikv/tasks/pod_test.go
  pkg/controllers/tikv/tasks/pvc.go
  pkg/controllers/tikv/tasks/pvc_test.go
  pkg/timanager/apis/pd/v1/types.go
  pkg/timanager/pd/member.go
Labels: size/XXL, v2

#6050 opt: skip transfer leader if only one PD; update some CRD comments
  apis/core/v1alpha1/cluster_types.go
  apis/core/v1alpha1/pd_types.go
  manifests/crd/core.pingcap.com_clusters.yaml
  manifests/crd/core.pingcap.com_pdgroups.yaml
  pkg/controllers/pd/tasks/pod.go
  pkg/controllers/pd/tasks/pod_test.go
  tests/e2e/pd/pd.go
Labels: size/L, v2

#6053 fix(group): fix unexpected rolling update when scale out/in
  apis/core/v1alpha1/pd_types.go
  apis/core/v1alpha1/tidb_types.go
  apis/core/v1alpha1/tiflash_types.go
  apis/core/v1alpha1/tikv_types.go
  manifests/crd/core.pingcap.com_pdgroups.yaml
  manifests/crd/core.pingcap.com_pds.yaml
  manifests/crd/core.pingcap.com_tidbgroups.yaml
  manifests/crd/core.pingcap.com_tidbs.yaml
  manifests/crd/core.pingcap.com_tiflashes.yaml
  manifests/crd/core.pingcap.com_tiflashgroups.yaml
  manifests/crd/core.pingcap.com_tikvgroups.yaml
  manifests/crd/core.pingcap.com_tikvs.yaml
  pkg/action/upgrader_test.go
  pkg/controllers/common/revision_test.go
  pkg/controllers/pdgroup/tasks/updater.go
  pkg/controllers/pdgroup/tasks/updater_test.go
  pkg/controllers/tidbgroup/tasks/state_test.go
  pkg/controllers/tidbgroup/tasks/updater.go
  pkg/controllers/tidbgroup/tasks/updater_test.go
  pkg/controllers/tiflashgroup/tasks/state_test.go
  pkg/controllers/tiflashgroup/tasks/updater.go
  pkg/controllers/tiflashgroup/tasks/updater_test.go
  pkg/controllers/tikvgroup/tasks/updater.go
  pkg/controllers/tikvgroup/tasks/updater_test.go
  pkg/runtime/pd.go
  pkg/runtime/tidb.go
  pkg/runtime/tiflash.go
  pkg/runtime/tikv.go
  pkg/utils/k8s/revision/controller_revision.go
  pkg/utils/k8s/revision/controller_revision_test.go
  tests/e2e/cluster/cluster.go
  tests/e2e/data/pd.go
  tests/e2e/data/tidb.go
  tests/e2e/data/tikv.go
  tests/e2e/utils/data/cluster.go
Labels: approved, size/L, v2
